# =============================================================================
# 📋 MANIFEST MODULE - MAIN FACADE
# =============================================================================
# Path: .tilt/topologies/tilt/manifest/__init__.star
# Purpose: Clean API surface for the manifest system
# Status: Phase 4 Complete - All modules integrated
# 
# Usage:
#   load("../manifest/__init__.star", "Manifest")
#   result = Manifest.load_from_file("path/to/manifest.json")
#   if result.error:
#       print(result.error)
#   else:
#       manifest = result.manifest
# =============================================================================

# Import submodules
load("./constants.star", "ManifestConstants")
load("./errors.star", "ManifestErrors")
load("./schema.star", "ManifestSchema")
load("./loader.star", "ManifestLoader")
load("./parser.star", "ManifestParser")
load("./validator.star", "ManifestValidator")
load("./integration.star", "ManifestIntegration")
load("./mapper.star", "ManifestMapper")

# =============================================================================
# PUBLIC API - Manifest System
# =============================================================================

Manifest = struct(
    # =========================================================================
    # Constants and Configuration
    # =========================================================================
    
    # Manifest filename
    filename=ManifestConstants.MANIFEST_FILENAME,
    
    # Default values
    defaults=ManifestConstants.MANIFEST_DEFAULTS,
    
    # Valid options
    app_types=ManifestConstants.VALID_APP_TYPES,
    stacks=ManifestConstants.VALID_STACKS,
    features=ManifestConstants.VALID_FEATURES,
    
    # Port ranges
    port_ranges=ManifestConstants.PORT_RANGES,
    
    # File paths
    autogenerated_paths=ManifestConstants.AUTOGENERATED_CONFIG_PATHS,
    
    # =========================================================================
    # Schema Access
    # =========================================================================
    
    # Full schema definition
    schema=ManifestSchema.MANIFEST_SCHEMA,
    
    # Schema utilities
    get_field=ManifestSchema.get_field,
    get_required_fields=ManifestSchema.get_required_fields,
    get_default=ManifestSchema.get_default,
    get_valid_values=ManifestSchema.get_valid_values,
    is_required=ManifestSchema.is_required,
    is_deprecated=ManifestSchema.is_deprecated,
    get_all_fields=ManifestSchema.get_all_fields,
    
    # =========================================================================
    # Error Handling
    # =========================================================================
    
    # Error severity levels
    severity=ManifestErrors.SEVERITY,
    
    # Error categories
    category=ManifestErrors.CATEGORY,
    
    # Error messages
    error_messages=ManifestErrors.ERROR_MESSAGES,
    
    # Error utilities
    format_error=ManifestErrors.format,
    group_errors=ManifestErrors.group,
    has_critical_errors=ManifestErrors.has_critical,
    get_error_summary=ManifestErrors.get_summary,
    
    # =========================================================================
    # Data Loading
    # =========================================================================
    
    # File loading functions
    load_from_file=ManifestLoader.load_from_file,
    load_from_path=ManifestLoader.load_from_path,
    load_all=ManifestLoader.load_all,
    
    # Cache management
    clear_cache=ManifestLoader.clear_cache,
    get_cache_stats=ManifestLoader.get_cache_stats,
    is_cached=ManifestLoader.is_cached,
    
    # Path utilities
    get_manifest_path=ManifestLoader.get_manifest_path,
    
    # =========================================================================
    # Parsing and Normalization
    # =========================================================================
    
    # Parsing functions
    parse=ManifestParser.parse,
    normalize=ManifestParser.normalize,
    get_normalized=ManifestParser.get_normalized,
    
    # Path extraction
    extract_resource_path=ManifestParser.extract_resource_path,
    extract_stack=ManifestParser.extract_stack,
    
    # Config parsing
    parse_traefik=ManifestParser.parse_traefik,
    
    # Manifest utilities
    merge_manifests=ManifestParser.merge,
    get_description=ManifestParser.get_description,
    
    # =========================================================================
    # Validation ⭐ NEW (Phase 3)
    # =========================================================================
    
    # Main validation
    validate=ManifestValidator.validate,
    is_valid=ManifestValidator.is_valid,
    get_validation_report=ManifestValidator.get_report,
    
    # Specific validation levels
    validate_schema=ManifestValidator.validate_schema,
    validate_values=ManifestValidator.validate_values,
    validate_dependencies=ManifestValidator.validate_dependencies,
    
    # =========================================================================
    # Discovery Integration ⭐ NEW (Phase 4)
    # =========================================================================
    
    # Integration with discovery system
    load_and_validate_integration=ManifestIntegration.load_and_validate,
    load_all_integration=ManifestIntegration.load_all,
    convert_to_resource=ManifestIntegration.convert_to_resource,
    get_validation_summary=ManifestIntegration.get_validation_summary,
    check_port_conflicts=ManifestIntegration.check_port_conflicts,
    check_dependencies_valid=ManifestIntegration.check_dependencies_valid,
    
    # =========================================================================
    # Field Mapper ⭐ NEW (Field Name Abstraction)
    # =========================================================================
    
    # Field name mapping - THE MAGIC LAYER!
    # Change field names in manifests without changing code
    # Example: YAML has 'portNewNameOfAttr', code uses get('port')
    map_field=ManifestMapper.get,
    set_mapped_field=ManifestMapper.set,
    get_all_mapped_fields=ManifestMapper.get_all,
    map_manifest=ManifestMapper.map,
    field_mappings=ManifestMapper.mappings,
)

# =============================================================================
# Convenience Functions
# =============================================================================

def _is_valid_manifest(manifest):
    """
    Quick check if manifest has required fields.
    
    Args:
        manifest: Dict to check
    
    Returns:
        True if manifest appears valid
    """
    if not manifest:
        return False
    
    required = ['appName', 'appType', 'stack']
    for field in required:
        if not manifest.get(field):
            return False
    
    return True

def _get_resource_type(manifest):
    """
    Get human-readable resource type description.
    
    Args:
        manifest: Manifest dict
    
    Returns:
        String description
    """
    app_type = manifest.get('appType', 'unknown')
    stack = manifest.get('stack', 'unknown')
    name = manifest.get('appName', 'unknown')
    
    return "{stack}/{app_type}/{name}".format(
        stack=stack,
        app_type=app_type,
        name=name,
    )

# Add convenience functions to Manifest struct
Manifest = struct(
    **{k: getattr(Manifest, k) for k in dir(Manifest) if not k.startswith('_')},
    is_valid_manifest=_is_valid_manifest,
    get_resource_type=_get_resource_type,
)


# Inlined constant
DEFAULTS = {}
