#!/usr/bin/env starlark
# =============================================================================
# 📋 MANIFEST MODULE - CONSTANTS (Self-Contained for Extension Loading)
# =============================================================================
# Path: topologies/tilt/manifest/constants.star
# Purpose: Shared constants, defaults, and validation lists for manifest system
# Status: MIGRATED - Self-contained for pure extension loading (ext://)
#
# NOTE: This file is now self-contained and does NOT import from external paths
# All constants are inlined below to support pure extension loading from GitHub.
# =============================================================================

# =============================================================================
# INLINED CONSTANTS (formerly loaded from external files)
# =============================================================================

# From TILT_RESOURCE_DEFAULTS.star
BASE_PORT_FRONTEND = 3000
BASE_PORT_BACKEND = 4000
HEALTH_CHECK_PATH = "/health"

NAMING_PATTERNS = {
    "backend_suffix": "-backend",
    "frontend_suffix": "-frontend",
    "migrator_suffix": "-migrator",
    "library_suffix": "-lib",
    "sdk_suffix": "-sdk",
    "worker_suffix": "-worker",
    "valid_separators": ["-", "_"],
    "max_length": 63,
    "min_length": 3,
}

TRAEFIK_CONFIG = {
    "entrypoint": "web",
    "network": "traefik-public",
    "default_host": "localhost",
    "default_port": 8080,
    "tls_enabled": False,
    "entrypoints": ["web"],
    "middlewares": [],
    "tls": {"enabled": False},
    "healthcheck_path": "/health",
    "healthcheck_interval": "10s",
    "healthcheck_timeout": "5s",
    "frontend_priority_base": 100,
}

# From TILT_TECH_STACK.star
RUNTIME = "bun"

# From TILT_DISCOVERY.star
# Stacks are project-specific and discovered dynamically from filesystem
VALID_STACKS = []

VALID_RESOURCE_TYPES = [
    "frontend",
    "backend",
    "library",
    "migrator",
    "sdk",
    "worker",
    "infra",
]

VALID_FEATURES = [
    # Resource-level features (code generators)
    "api-client",
    "env-config",
    "api-index",
    "prisma",
    # Infrastructure features
    "nats",
    "redis",
    "infisical",
    "vitest",
    "traefik",
    "websocket",
    "graphql",
    "grpc",
    "vite-node",
    "maintenance",
]

PORT_RANGES = {
    "frontend": {"min": 3000, "max": 5999},
    "backend": {"min": 4000, "max": 5999},
    "worker": {"min": 6000, "max": 6999},
    "migrator": {"min": 7000, "max": 7999},
    "sdk": {"min": 3000, "max": 9999},
    "library": {"min": 3000, "max": 9999},
}

MAX_DEPENDENCIES = 10

# From spec.master (OUTPUT section)
AUTOGENERATED_FOLDER = ".autogenerated"

# =============================================================================
# MANIFEST FILE NAMING
# =============================================================================

MANIFEST_FILENAME = 'service.json'
MANIFEST_FILENAME_YAML = 'service.yaml'
MANIFEST_PATTERN = 'service.json'

# =============================================================================
# PACKAGE & GENERATED CONFIGURATION
# =============================================================================

PACKAGE_CONFIG_FILENAMES = {
    'npmrc': '.npmrc.autogenerated',
    'npmrc_docker_autogenerated': '.npmrc.docker.autogenerated',
    'bunfig': 'bunfig.autogenerated.toml',
    'bunfig_docker_autogenerated': 'bunfig.docker.autogenerated.toml',
}

GENERATED_CONFIG_FILENAMES = {
    'vite_frontend': 'vite.config.frontend.autogenerated.ts',
    'vite_backend': 'vite.config.backend.autogenerated.ts',
    'vite_library': 'vite.config.lib.autogenerated.ts',
    'vite_sdk': 'vite.config.sdk.autogenerated.ts',
    'vite_build': 'vite.config.build.autogenerated.ts',
    'tsconfig_docker': 'tsconfig.docker.autogenerated.json',
    'tsconfig_local': 'tsconfig.autogenerated.json',
    'playwright': 'playwright.config.autogenerated.ts',
    'prisma': 'prisma.config.autogenerated.ts',
    'dockerfile_app': 'Dockerfile.app.autogenerated',
    'dockerfile_migrator': 'Dockerfile.migrator.autogenerated',
    'nginx': 'nginx.autogenerated.conf',
    'env_frontend': '.env.frontend.autogenerated',
    'env_backend': '.env.backend.autogenerated',
    'npmrc': PACKAGE_CONFIG_FILENAMES['npmrc'],
    'npmrc_docker': PACKAGE_CONFIG_FILENAMES['npmrc_docker_autogenerated'],
    'bunfig': PACKAGE_CONFIG_FILENAMES['bunfig'],
    'bunfig_docker': PACKAGE_CONFIG_FILENAMES['bunfig_docker_autogenerated'],
    'agents_md': 'AGENTS.md',
}

AUTOGENERATED_CONFIG_PATHS = {
    'npmrc': AUTOGENERATED_FOLDER + '/' + PACKAGE_CONFIG_FILENAMES['npmrc'],
    'npmrc_docker': AUTOGENERATED_FOLDER + '/' + PACKAGE_CONFIG_FILENAMES['npmrc_docker_autogenerated'],
    'bunfig': AUTOGENERATED_FOLDER + '/' + PACKAGE_CONFIG_FILENAMES['bunfig'],
    'bunfig_docker': AUTOGENERATED_FOLDER + '/' + PACKAGE_CONFIG_FILENAMES['bunfig_docker_autogenerated'],
    'prisma': AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['prisma'],
}

# =============================================================================
# MANIFEST DEFAULTS
# =============================================================================

MANIFEST_DEFAULTS = {
    'port': BASE_PORT_BACKEND,
    'appType': 'backend',
    'healthCheckPath': HEALTH_CHECK_PATH,
    'internalPort': BASE_PORT_FRONTEND,
    'replicas': 1,
    'featuresEnabled': [],
    'envVars': {},
    'syncs': None,
    'dependsOn': [],
    'runtime': RUNTIME,
    'traefik': {
        'pathPrefix': '',
        'priority': 100,
    },
}

VALID_APP_TYPES = VALID_RESOURCE_TYPES

DEFAULT_SYNCS = {
    'frontend': [
        'src',
        'public',
        'index.html',
        AUTOGENERATED_CONFIG_PATHS['npmrc_docker'],
        AUTOGENERATED_CONFIG_PATHS['bunfig_docker']
    ],
    'backend': [
        'src',
        AUTOGENERATED_CONFIG_PATHS['npmrc_docker'],
        AUTOGENERATED_CONFIG_PATHS['bunfig_docker']
    ],
    'migrator': ['prisma'],
    'library': ['src', 'package.json'],
    'sdk': ['src', 'package.json'],
}

RUNTIME_CONFIGS = {
    'bun': {
        'image_base': 'oven/bun:latest',
        'package_manager': 'bun',
        'lockfile': 'bun.lock',
    },
    'node': {
        'image_base': 'node:20-alpine',
        'package_manager': 'npm',
        'lockfile': 'package-lock.json',
    },
}

TRAEFIK_DEFAULTS = {
    'entrypoints': TRAEFIK_CONFIG['entrypoints'],
    'middlewares': TRAEFIK_CONFIG['middlewares'],
    'tls': TRAEFIK_CONFIG['tls'],
    'healthcheck': {
        'path': TRAEFIK_CONFIG['healthcheck_path'],
        'interval': TRAEFIK_CONFIG['healthcheck_interval'],
        'timeout': TRAEFIK_CONFIG['healthcheck_timeout'],
    },
}

RESOURCE_NAME_PATTERNS = NAMING_PATTERNS

VALIDATION_THRESHOLDS = {
    'max_replicas': 5,
    'max_dependencies': MAX_DEPENDENCIES,
    'max_features': 10,
    'max_env_vars': 50,
}

# =============================================================================
# STRUCT EXPORT (for easy importing)
# =============================================================================

ManifestConstants = struct(
    MANIFEST_FILENAME=MANIFEST_FILENAME,
    MANIFEST_FILENAME_YAML=MANIFEST_FILENAME_YAML,
    MANIFEST_PATTERN=MANIFEST_PATTERN,
    PACKAGE_CONFIG_FILENAMES=PACKAGE_CONFIG_FILENAMES,
    GENERATED_CONFIG_FILENAMES=GENERATED_CONFIG_FILENAMES,
    AUTOGENERATED_CONFIG_PATHS=AUTOGENERATED_CONFIG_PATHS,
    MANIFEST_DEFAULTS=MANIFEST_DEFAULTS,
    VALID_APP_TYPES=VALID_APP_TYPES,
    VALID_STACKS=VALID_STACKS,
    BASE_PORT_FRONTEND=BASE_PORT_FRONTEND,
    BASE_PORT_BACKEND=BASE_PORT_BACKEND,
    DEFAULT_SYNCS=DEFAULT_SYNCS,
    RUNTIME_CONFIGS=RUNTIME_CONFIGS,
    TRAEFIK_DEFAULTS=TRAEFIK_DEFAULTS,
    RESOURCE_NAME_PATTERNS=RESOURCE_NAME_PATTERNS,
    VALIDATION_THRESHOLDS=VALIDATION_THRESHOLDS,
)



CONSTANTS = {}

VALIDATION = {}

# Inlined OUTPUT constant
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
