# =============================================================================
# 🤖 TILT SDK - AGENTS.MD GENERATOR (free-tier stub)
# =============================================================================
# Path: .tilt/providers/generators/agents_md.star
# =============================================================================
# The full AI-agent guard rails (the multi-section AGENTS.md explaining the
# manifest-driven architecture, the do/don't table, and the emergency
# override procedure) are a paid TDK feature. When a valid license grants
# the "agents-md" resource, cli/src/generator/template-engine.ts
# (vendorTdkExtension) overwrites this file with the licensed version
# fetched via extension-fetch.ts before Tilt loads it. Same function
# signature either way, so nothing else in the generator pipeline changes.
# =============================================================================


# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load('../../../topologies/tilt/common/utils.star', 'Utils')

_STUB_NOTICE = """# ⚠️ AUTOGENERATED FILES - DO NOT MODIFY

**This folder (`.autogenerated/`) contains MACHINE-GENERATED files.** Any changes you make here will be overwritten the next time Tilt runs the configuration generators.

Full AI-agent guard rails (architecture explanation, do/don't table, emergency override procedure) are a paid TDK feature. Run `tdk upgrade` to enable the complete generated AGENTS.md for this service.
"""


def generate_agents_md(manifest, write_fn=None):
    """
    Free-tier stub - see module header. Signature matches the licensed
    implementation so callers never need to know which one is active.
    """
    resource_path = manifest.get('_resource_path', '')
    app_name = manifest.get('appName', 'unknown-service')
    app_type = manifest.get('appType', 'backend')

    header = Utils.get_template_header(
        'agents_md',
        'AgentsMd.generate() [unlicensed stub]',
        app_name,
        'Output: .autogenerated/AGENTS.md',
    )

    content = header + _STUB_NOTICE

    if write_fn:
        output_path = resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/AGENTS.md'
        write_fn(output_path, content)

    return content


# =============================================================================
# 🎯 PUBLIC API
# =============================================================================

AgentsMd = struct(
    generate = generate_agents_md,
)
