# =============================================================================
# 🎯 GENERATORS - Master Index
# =============================================================================
# All generators for Tilt topology configuration
# =============================================================================

# =============================================================================
# Legacy Generators (existing)
# =============================================================================

# Load individual generator functions (they export functions, not structs)
load("./typescript/backend_tsconfig.star", "generate_backend_tsconfig")
load("./typescript/frontend_tsconfig.star", "generate_frontend_tsconfig")
load("./typescript/frontend_library_tsconfig.star", "generate_frontend_library_tsconfig")
load("./typescript/backend_library_tsconfig.star", "generate_backend_library_tsconfig")
load("./typescript/prisma_config.star", "generate_prisma_config")
load("./typescript/playwright_config.star", "generate_playwright_config")

load("./vite/generators.star", "generate_for_manifest")
load("./npmrc.star", "PackageConfig")
load("./agents_md.star", "AgentsMd")
# NOTE: nginx_conf.star and api_gateway.star loaded from manifest_resource.star
# to avoid circular imports with discovery/registry

# =============================================================================
# NEW: Pre-Flight Validation Generators (v2.0)
# =============================================================================
# These generators prevent vibe-coding failures by validating before build

load("./validators.star", "Validators")
load("./typescript/fixed_frontend_tsconfig.star", "FixedTSConfig")
load("./dependency_manifest.star", "DependencyManifest")
load("./database_provisioner.star", "DatabaseProvisioner")

# =============================================================================
# 🔐 INFISICAL Secrets Management Generators
# =============================================================================
# Provides complete Infisical integration for secret management

load("./infisical/index.star", "Infisical")

# =============================================================================
# Legacy Exports (for backward compatibility)
# =============================================================================

# Functions are already loaded directly
# Vite generator
Vite = struct(
    for_manifest = generate_for_manifest,
)

# =============================================================================
# NEW: Pre-Flight Validation Exports
# =============================================================================

# Validators - Pre-flight checks
Validate = Validators

# Fixed TSConfig - Docker-safe path handling
FixedTSConfig = FixedTSConfig

# Dependency Resolution
Dependency = DependencyManifest

# Database Provisioning
Database = DatabaseProvisioner

# =============================================================================
# 🔐 INFISICAL Secrets Management Exports
# =============================================================================

# Complete Infisical integration
SecretsManagement = Infisical

# =============================================================================
# Master Generation Orchestrator
# =============================================================================

def run_pre_flight_validations(resource_path, manifest, all_services, global_config):
    """
    Runs all pre-flight validations for a service.
    
    This is the main entry point for validation. Call this during config-gen
    to catch issues before they cause build failures.
    
    Args:
        resource_path: Path to service directory
        manifest: Service manifest dict
        all_services: List of all services for dependency checking
        global_config: Global topology config
    
    Returns:
        Validation report dict
    """
    return Validators.run_all_validations(
        resource_path,
        manifest,
        all_services,
        global_config,
        None,  # write_fn - will write to .autogenerated/
    )

def generate_fixed_frontend_tsconfig(resource_path, internal_deps, is_docker, write_fn):
    """
    Generates Docker-safe frontend tsconfig.
    
    This version excludes path aliases in Docker builds to prevent
    "Module not found" errors.
    
    Args:
        resource_path: Path to service
        internal_deps: Dict of {package_name: source_path}
        is_docker: If True, excludes path aliases (safer for Docker)
        write_fn: Function to write files
    
    Returns:
        Path to generated config
    """
    return FixedTSConfig.generate_frontend_tsconfig(
        resource_path,
        write_fn,
        internal_deps,
        is_docker,
    )

def resolve_missing_dependencies(all_services, library_roots):
    """
    Discovers and generates manifests for missing dependencies.
    
    Call this at topology load time to identify missing libraries
    and generate stubs or manifests for them.
    
    Args:
        all_services: List of all services
        library_roots: Dict of {type: root_path}
    
    Returns:
        Resolution report dict
    """
    return DependencyManifest.generate_dependency_resolution_report(
        all_services,
        library_roots,
        None,
    )

def provision_resource_database(resource_name, db_name, db_config, write_fn):
    """
    Generates all files needed to provision a database for a service.
    
    Creates:
      - Docker Compose entry
      - Provisioning SQL
      - Connection strings
      - Provisioning script
    
    Args:
        resource_name: Name of service
        db_name: Database name
        db_config: Database configuration dict
        write_fn: Function to write files
    
    Returns:
        Provisioning config struct
    """
    return DatabaseProvisioner.generate_database_provisioning_resource(
        resource_name,
        db_name,
        db_config,
        write_fn,
    )

# =============================================================================
# Exports
# =============================================================================

Generators = struct(
    # Legacy
    generate_backend_tsconfig=generate_backend_tsconfig,
    generate_frontend_tsconfig=generate_frontend_tsconfig,
    generate_frontend_library_tsconfig=generate_frontend_library_tsconfig,
    generate_backend_library_tsconfig=generate_backend_library_tsconfig,
    generate_prisma_config=generate_prisma_config,
    generate_playwright_config=generate_playwright_config,
    Vite=Vite,

    # NEW: Pre-flight validation
    Validate=Validate,
    FixedTSConfig=FixedTSConfig,
    Dependency=Dependency,
    Database=Database,

    # NEW: Orchestrators
    run_pre_flight_validations=run_pre_flight_validations,
    generate_fixed_frontend_tsconfig=generate_fixed_frontend_tsconfig,
    resolve_missing_dependencies=resolve_missing_dependencies,
    provision_resource_database=provision_resource_database,

    # NEW: Infisical Secrets Management
    SecretsManagement=SecretsManagement,

    # NEW: AGENTS.md Generator for .autogenerated/ folder
    AgentsMd=AgentsMd,
)
