# =============================================================================
# 🎯 GENERATORS - Master Index
# =============================================================================
# All generators for Tilt topology configuration
# =============================================================================

# =============================================================================
# Legacy Generators (existing)
# =============================================================================

# Load individual generator functions (they export functions, not structs)
load("./typescript/backend_tsconfig.star", "generate_backend_tsconfig")
load("./typescript/frontend_tsconfig.star", "generate_frontend_tsconfig")
load("./typescript/frontend_library_tsconfig.star", "generate_frontend_library_tsconfig")
load("./typescript/backend_library_tsconfig.star", "generate_backend_library_tsconfig")
load("./typescript/prisma_config.star", "generate_prisma_config")
load("./typescript/playwright_config.star", "generate_playwright_config")

load("./vite/generators.star", "generate_for_manifest")
load("./npmrc.star", "PackageConfig")
load("./agents_md.star", "AgentsMd")
# NOTE: nginx_conf.star and api_gateway.star loaded from manifest_resource.star
# to avoid circular imports with discovery/registry

# =============================================================================
# NEW: Pre-Flight Validation Generators (v2.0)
# =============================================================================
# These generators prevent vibe-coding failures by validating before build

load("./validators.star", "Validators")
# fixed_frontend_tsconfig.star, dependency_manifest.star, and
# database_provisioner.star moved to premium/ - none had any call sites
# outside this file, so they were dead code in the free engine.

# =============================================================================
# 🔐 INFISICAL Secrets Management Generators
# =============================================================================
# Provides complete Infisical integration for secret management

load("./infisical/index.star", "Infisical")

# =============================================================================
# Legacy Exports (for backward compatibility)
# =============================================================================

# Functions are already loaded directly
# Vite generator
Vite = struct(
    for_manifest = generate_for_manifest,
)

# =============================================================================
# NEW: Pre-Flight Validation Exports
# =============================================================================

# Validators - Pre-flight checks
Validate = Validators

# =============================================================================
# 🔐 INFISICAL Secrets Management Exports
# =============================================================================

# Complete Infisical integration
SecretsManagement = Infisical

# =============================================================================
# Master Generation Orchestrator
# =============================================================================

def run_pre_flight_validations(resource_path, manifest, all_services, global_config):
    """
    Runs all pre-flight validations for a service.
    
    This is the main entry point for validation. Call this during config-gen
    to catch issues before they cause build failures.
    
    Args:
        resource_path: Path to service directory
        manifest: Service manifest dict
        all_services: List of all services for dependency checking
        global_config: Global topology config
    
    Returns:
        Validation report dict
    """
    return Validators.run_all_validations(
        resource_path,
        manifest,
        all_services,
        global_config,
        None,  # write_fn - will write to .autogenerated/
    )

# generate_fixed_frontend_tsconfig, resolve_missing_dependencies, and
# provision_resource_database moved to premium/ along with the modules
# they wrapped (fixed_frontend_tsconfig.star, dependency_manifest.star,
# database_provisioner.star) - none had call sites outside this file.

# =============================================================================
# Exports
# =============================================================================

Generators = struct(
    # Legacy
    generate_backend_tsconfig=generate_backend_tsconfig,
    generate_frontend_tsconfig=generate_frontend_tsconfig,
    generate_frontend_library_tsconfig=generate_frontend_library_tsconfig,
    generate_backend_library_tsconfig=generate_backend_library_tsconfig,
    generate_prisma_config=generate_prisma_config,
    generate_playwright_config=generate_playwright_config,
    Vite=Vite,

    # NEW: Pre-flight validation
    Validate=Validate,

    # NEW: Orchestrators
    run_pre_flight_validations=run_pre_flight_validations,

    # NEW: Infisical Secrets Management
    SecretsManagement=SecretsManagement,

    # NEW: AGENTS.md Generator for .autogenerated/ folder
    AgentsMd=AgentsMd,
)
