# =============================================================================
# 🌐 TILT SDK - NGINX PROVIDER
# =============================================================================
# Path: .tilt/providers/nginx.star
# Purpose: Generate nginx configs for frontend services
# =============================================================================


# === INLINED CONSTANTS for pure extension loading ===
BASE_PORT_FRONTEND = 3000
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load('../../../topologies/tilt/common/utils.star', 'Utils')
load('../../../topologies/tilt/manifest/constants.star', 'GENERATED_CONFIG_FILENAMES')

# NOTE: api_gateway.star loaded by caller to avoid circular imports


def api_proxy_location(backend_name, port=BASE_PORT_FRONTEND, base_path='', stack=''):
    """Return nginx location /api block that proxy_passes to the given backend (Vite-proxy style in prod)."""
    return """
    location /api {{
        proxy_pass http://{backend}:{port};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }}""".format(backend=backend_name, port=port)


def generate_frontend_nginx(manifest, write_fn=None, referer_map_block=''):
    """
    Generate nginx config for frontend services.
    
    Args:
        manifest: Service manifest dict
        write_fn: Function to write files
        referer_map_block: Generated referer map block (from ApiGateway)

    Output:
      {resource_path}/.autogenerated/nginx.autogenerated.conf
    """
    if manifest.get('appType') != 'frontend':
        return ''

    resource_path = manifest.get('_resource_path', '')
    app_name = manifest.get('appName', 'unknown-frontend')
    backend_name = manifest.get('backendName', 'backend')
    header = Utils.get_template_header(
        'nginx',
        'Nginx.frontend()',
        app_name,
        'Output: .autogenerated/' + GENERATED_CONFIG_FILENAMES['nginx'],
    )

    base_path = manifest.get('basePath', '')
    stack = manifest.get('stack', '')
    port = manifest.get('port', BASE_PORT_FRONTEND)
    # NOTE: referer_map_block now passed as parameter to avoid circular import

    conf = """{header}
    # Docker DNS resolver
    resolver 127.0.0.11 valid=30s ipv6=off;

{referer_map_block}

    server {{
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/json
            application/javascript
            application/xml+rss
            application/atom+xml
            image/svg+xml;

        location / {{
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-cache, no-store, must-revalidate" always;
            add_header Pragma "no-cache" always;
            add_header Expires "0" always;
        }}

        location ~* \\.(js|css)$ {{
            expires 2m;
            add_header Cache-Control "public, max-age=120, must-revalidate";
            add_header Last-Modified $date_gmt;
            add_header ETag off;
            if_modified_since off;
        }}

        location ~* \\.(png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {{
            expires 1y;
            add_header Cache-Control "public, immutable";
        }}

        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;

        location /api {{
            proxy_pass $api_backend;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Referer $http_referer;
        }}

        location /health {{
            access_log off;
            return 200 "healthy\\n";
            add_header Content-Type text/plain;
        }}
    }}""".format(header=header, referer_map_block=referer_map_block)

    if write_fn:
        write_fn(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['nginx'], conf)

    return conf


Nginx = struct(
    api_proxy_location = api_proxy_location,
    frontend = generate_frontend_nginx,
)
