import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  checkHostPorts,
  checkIngressPorts,
  checkPrivateNpmRegistry,
  checkTiltResourceHealth,
  findForeignIngressHolders,
  HOST_PORT_FIXES,
  orderTiltFailures,
  parsePublishedPortHolders,
  parseTiltResourceFailures,
  probeContainerRuntimeError,
  summarizeTiltBuildError,
} from "../../utils/doctor-runtime.js";
import {
  checkDockerVersions,
  checkFrontendDockerPreflight,
  checkGeneratedProjectRuntimeAssets,
  checkResourceDiscovery,
  checkStarlarkLoadExports,
  checkTypeScriptTypeDependencies,
  DOCTOR_FIXES,
  getDoctorOutcomeMessage,
  WSL2_DOCTOR_MESSAGE,
} from "../doctor.js";

describe("doctor exact guidance", () => {
  it("keeps prerequisite fixes as the specified copy-paste text", () => {
    expect(DOCTOR_FIXES).toEqual({
      dockerMissing: "See https://docs.docker.com/get-docker/",
      dockerDaemonDown: "Start Docker Desktop, OrbStack, or Colima, then retry: tdk doctor",
      tiltMissing:
        "curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash",
      bunMissing: "curl -fsSL https://bun.sh/install | bash",
      port80: "Stop the process bound to port 80, or stop local nginx/caddy. Then: tdk doctor",
      port5432: "Stop local Postgres or change the host port. Then: tdk doctor",
      notProject: "tdk project --yes",
    });
    expect(WSL2_DOCTOR_MESSAGE).toBe(
      "WSL2 detected. Use Docker Desktop WSL integration. Guide: docs/wsl2.md",
    );
  });

  it("prints exact project-aware final outcomes", () => {
    expect(getDoctorOutcomeMessage(false, true)).toBe("Doctor passed. Next: tdk project example");
    expect(getDoctorOutcomeMessage(true, true)).toBe("Doctor passed. Next: tdk up");
    expect(getDoctorOutcomeMessage(true, false)).toBe(
      "Doctor failed. Fix the items above, then run: tdk doctor",
    );
  });

  it("uses exact remediation copy for ports 80 and 5432", async () => {
    const port80 = await checkHostPorts((() => "") as never, "tdk-project", async (port) =>
      port === 80 ? "in-use" : "free",
    );
    const port5432 = await checkHostPorts((() => "") as never, "tdk-project", async (port) =>
      port === 5432 ? "in-use" : "free",
    );

    expect(port80.fix).toBe(HOST_PORT_FIXES.port80);
    expect(port5432.fix).toBe(HOST_PORT_FIXES.port5432);
  });
});

describe("doctor frontend Docker preflight", () => {
  let testDir: string;
  let originalCwd: string;

  beforeEach(() => {
    originalCwd = process.cwd();
    testDir = join(
      tmpdir(),
      `tdk-doctor-frontend-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    );
    mkdirSync(testDir, { recursive: true });
    process.chdir(testDir);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    if (testDir && existsSync(testDir)) {
      rmSync(testDir, { recursive: true, force: true });
    }
  });

  function writeFrontendProject(options: {
    composePort: number;
    dockerTsconfig: Record<string, unknown>;
    mainTsx: string;
  }) {
    const appDir = join(testDir, "services", "app", "dashboard-app");
    const generatedDir = join(appDir, ".autogenerated");
    const stackGeneratedDir = join(testDir, "services", "app", ".autogenerated");

    mkdirSync(generatedDir, { recursive: true });
    mkdirSync(stackGeneratedDir, { recursive: true });
    mkdirSync(join(appDir, "src"), { recursive: true });
    mkdirSync(join(appDir, "public"), { recursive: true });

    writeFileSync(
      join(appDir, "service.json"),
      JSON.stringify(
        {
          appName: "dashboard-app",
          appType: "frontend",
          stack: "app",
          port: 3200,
          basePath: "/dashboard-app",
        },
        null,
        2,
      ),
    );
    writeFileSync(
      join(generatedDir, "Dockerfile.app.autogenerated"),
      "FROM nginx:alpine\nCOPY dist /usr/share/nginx/html\nEXPOSE 80\n",
    );
    writeFileSync(
      join(stackGeneratedDir, "docker-compose.app.autogenerated.yml"),
      [
        "services:",
        "  dashboard-app:",
        "    labels:",
        `      - "traefik.http.services.dashboard-app.loadbalancer.server.port=${options.composePort}"`,
      ].join("\n"),
    );
    writeFileSync(
      join(generatedDir, "tsconfig.docker.autogenerated.json"),
      JSON.stringify(options.dockerTsconfig, null, 2),
    );
    writeFileSync(join(appDir, "src", "main.tsx"), options.mainTsx);
  }

  it("fails when generated Traefik routes an nginx frontend to the Vite dev port", () => {
    writeFrontendProject({
      composePort: 3200,
      dockerTsconfig: { compilerOptions: { allowSyntheticDefaultImports: true } },
      mainTsx: 'import { StrictMode } from "react";\n',
    });

    const result = checkFrontendDockerPreflight();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("nginx runtime exposes 80");
    expect(result.message).toContain("routes to 3200");
  });

  it("fails when Docker tsconfig rejects default React imports used by the entrypoint", () => {
    writeFrontendProject({
      composePort: 80,
      dockerTsconfig: { compilerOptions: { strict: true } },
      mainTsx: ['import React from "react";', 'import ReactDOM from "react-dom/client";', ""].join(
        "\n",
      ),
    });

    const result = checkFrontendDockerPreflight();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("does not allow synthetic default imports");
    expect(result.message).toContain("react-dom/client");
  });

  it("fails when a frontend has no public/ folder for the Docker build to copy", () => {
    writeFrontendProject({
      composePort: 80,
      dockerTsconfig: { compilerOptions: { strict: true } },
      mainTsx: "",
    });
    rmSync(join(testDir, "services", "app", "dashboard-app", "public"), { recursive: true });

    const result = checkFrontendDockerPreflight();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("dashboard-app: no public/ folder");
    expect(result.message).toContain("mkdir -p services/app/dashboard-app/public");
  });

  it("passes when generated frontend Docker metadata is internally consistent", () => {
    writeFrontendProject({
      composePort: 80,
      dockerTsconfig: { compilerOptions: { strict: true } },
      mainTsx: [
        'import { StrictMode } from "react";',
        'import { createRoot } from "react-dom/client";',
        "",
      ].join("\n"),
    });

    const result = checkFrontendDockerPreflight();

    expect(result.didPass).toBe(true);
  });

  it("fails when generated Starlark loads a private exported symbol", () => {
    const outDir = join(testDir, ".tdk", ".tdk-out");
    const extDir = join(outDir, "tdk-cli-ext", "engine");
    mkdirSync(extDir, { recursive: true });
    writeFileSync(join(outDir, "Tiltfile"), 'load("./tdk-cli-ext/engine/bad.star", "Bad")\n');
    writeFileSync(
      join(extDir, "sablier_container_cycle.star"),
      "_sablier_middleware_suffix = 'x'\n",
    );
    writeFileSync(join(extDir, "public.star"), "Docker = struct()\n");
    writeFileSync(
      join(extDir, "bad.star"),
      [
        "Bad = struct()",
        'load("./sablier_container_cycle.star", "_sablier_middleware_suffix")',
        'load("./public.star", _Docker = "Docker")',
        "",
      ].join("\n"),
    );

    const result = checkStarlarkLoadExports();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("_sablier_middleware_suffix");
    expect(result.message).not.toContain("_Docker");
  });

  it("fails when generated Starlark loads a missing relative file", () => {
    const outDir = join(testDir, ".tdk", ".tdk-out");
    const extDir = join(outDir, "tdk-cli-ext", "discovery");
    mkdirSync(extDir, { recursive: true });
    writeFileSync(
      join(outDir, "Tiltfile"),
      'load("./tdk-cli-ext/discovery/daemon.star", "Daemon")\n',
    );
    writeFileSync(join(extDir, "daemon.star"), 'load("./resource_registry.star", "CacheOps")\n');

    const result = checkStarlarkLoadExports();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("Missing relative load targets");
    expect(result.message).toContain("resource_registry.star");
  });

  it("passes when generated Starlark only uses private local aliases", () => {
    const extDir = join(testDir, ".tdk", ".tdk-out", "tdk-cli-ext", "engine");
    mkdirSync(extDir, { recursive: true });
    writeFileSync(join(extDir, "public.star"), "Docker = struct()\n");
    writeFileSync(join(extDir, "good.star"), 'load("./public.star", _Docker = "Docker")\n');

    const result = checkStarlarkLoadExports();

    expect(result.didPass).toBe(true);
  });
});

describe("doctor generated runtime asset preflight", () => {
  let testDir: string;
  let originalCwd: string;

  beforeEach(() => {
    originalCwd = process.cwd();
    testDir = join(
      tmpdir(),
      `tdk-doctor-runtime-assets-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    );
    mkdirSync(join(testDir, ".tdk"), { recursive: true });
    writeFileSync(
      join(testDir, ".tdk", "project.json"),
      JSON.stringify({
        version: "1.0",
        project: { name: "asset-check", version: "1.0.0" },
        phases: {
          pre_alpha: { name: "Pre-Alpha", description: "", enabledStacks: [] },
          alpha: { name: "Alpha", description: "", enabledStacks: [] },
          beta: { name: "Beta", description: "", enabledStacks: [] },
          out_of_scope: { name: "Out of Scope", description: "", enabledStacks: [] },
        },
        optional_infra: {
          monitoring: false,
          elk: false,
          debezium: false,
          golden_image: true,
          verdaccio: false,
        },
        discovery: { paths: ["services/*/*"] },
        overrides: {},
      }),
    );
    process.chdir(testDir);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    if (testDir && existsSync(testDir)) {
      rmSync(testDir, { recursive: true, force: true });
    }
  });

  function writeRequiredRuntimeAssets() {
    const templateDir = join(testDir, "shared-platform-engineering", "docker-templates");
    mkdirSync(templateDir, { recursive: true });
    for (const file of [
      "install-deps.sh",
      "bun-hoisted-symlink-fix.sh",
      "prisma-bun-client-link-fix.sh",
      "prisma-normalize-client.sh",
      "infisical-entrypoint.sh",
    ]) {
      writeFileSync(join(templateDir, file), "#!/bin/sh\n");
    }
  }

  it("fails when the root workspace package.json and Docker template scripts are missing", () => {
    const result = checkGeneratedProjectRuntimeAssets();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("package.json");
    expect(result.message).toContain("install-deps.sh");
    expect(result.fix).toContain("tdk project");
  });

  it("passes when generated Docker runtime assets are present", () => {
    writeFileSync(
      join(testDir, "package.json"),
      JSON.stringify({ name: "asset-check", private: true, workspaces: ["services/*/*"] }),
    );
    writeRequiredRuntimeAssets();

    const result = checkGeneratedProjectRuntimeAssets();

    expect(result.didPass).toBe(true);
    expect(result.message).toContain("runtime assets are present");
  });

  it("flags a script a generated Dockerfile copies but the project lacks", () => {
    writeFileSync(
      join(testDir, "package.json"),
      JSON.stringify({ name: "asset-check", private: true, workspaces: ["services/*/*"] }),
    );
    writeRequiredRuntimeAssets();
    const serviceDir = join(testDir, "services", "shop", "orders-api");
    mkdirSync(join(serviceDir, ".autogenerated"), { recursive: true });
    writeFileSync(
      join(serviceDir, "service.json"),
      JSON.stringify({ appName: "orders-api", appType: "backend", stack: "shop", port: 4000 }),
    );
    writeFileSync(
      join(serviceDir, ".autogenerated", "Dockerfile.app.autogenerated"),
      "COPY shared-platform-engineering/docker-templates/migrate.sh /usr/local/bin/migrate.sh\n",
    );

    const result = checkGeneratedProjectRuntimeAssets();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("migrate.sh");
  });
});

describe("doctor TypeScript type dependency check", () => {
  let testDir: string;
  let originalCwd: string;

  beforeEach(() => {
    originalCwd = process.cwd();
    testDir = join(
      tmpdir(),
      `tdk-doctor-types-bun-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    );
    mkdirSync(testDir, { recursive: true });
    process.chdir(testDir);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    if (testDir && existsSync(testDir)) {
      rmSync(testDir, { recursive: true, force: true });
    }
  });

  function writeBackendResource(
    devDependencies: Record<string, string>,
    types: string[] = ["bun"],
    dependencies: Record<string, string> = {},
    scripts: Record<string, string> = { build: "tsc" },
  ) {
    const appDir = join(testDir, "services", "finance", "cash-management-api");
    const generatedDir = join(appDir, ".autogenerated");
    mkdirSync(generatedDir, { recursive: true });

    writeFileSync(
      join(appDir, "service.json"),
      JSON.stringify(
        {
          appName: "cash-management-api",
          appType: "backend",
          stack: "finance",
          port: 4000,
        },
        null,
        2,
      ),
    );
    writeFileSync(
      join(appDir, "package.json"),
      JSON.stringify(
        { name: "cash-management-api", scripts, dependencies, devDependencies },
        null,
        2,
      ),
    );
    writeFileSync(
      join(generatedDir, "tsconfig.docker.autogenerated.json"),
      JSON.stringify({ compilerOptions: { types } }, null, 2),
    );
  }

  it('fails when a service\'s tsconfig sets "types": ["bun"] but @types/bun is not a devDependency', () => {
    writeBackendResource({ typescript: "^5.0.0" });

    const result = checkTypeScriptTypeDependencies();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("cash-management-api");
    expect(result.message).toContain("@types/bun");
    expect(result.fix).toContain('"@types/bun"');
  });

  it('passes when @types/bun and @types/node are devDependencies alongside "types": ["bun"]', () => {
    writeBackendResource({
      typescript: "^5.0.0",
      "@types/bun": "^1.4.2",
      "@types/node": "^20.0.0",
    });

    const result = checkTypeScriptTypeDependencies();

    expect(result.didPass).toBe(true);
  });

  it('fails when "types": ["node"] has no @types/node (the case a fresh scaffold hit)', () => {
    // The engine's Docker tsconfig lists "node"; a scaffold without @types/node failed the
    // image build with TS2688, and this check only looked at "bun", so doctor said all clear.
    writeBackendResource({ typescript: "^7.0.0", "@types/bun": "^1.4.2" }, ["node"]);

    const result = checkTypeScriptTypeDependencies();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain(
      'cash-management-api: "types" lists "node" (needs @types/node)',
    );
    expect(result.message).toContain("TS2688");
    expect(result.fix).toContain('"@types/node": "^20.0.0"');
  });

  it('passes when @types/node is present for "types": ["node"]', () => {
    writeBackendResource({ "@types/node": "^20.0.0" }, ["node"]);
    expect(checkTypeScriptTypeDependencies().didPass).toBe(true);
  });

  it("reports only the entries that are missing when several are listed", () => {
    writeBackendResource({ "@types/bun": "^1.4.2" }, ["bun", "node"]);

    const result = checkTypeScriptTypeDependencies();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain('"node"');
    expect(result.message).not.toContain('"bun"');
  });

  it("accepts a type package listed under dependencies, not just devDependencies", () => {
    writeBackendResource({}, ["node"], { "@types/node": "^20.0.0" });
    expect(checkTypeScriptTypeDependencies().didPass).toBe(true);
  });

  it("does not flag a service whose build is vite build, which never reads tsconfig types", () => {
    // The ERP frontends: types ["node"] in the Docker tsconfig, no @types/node, and they build
    // fine because `vite build` only transpiles. Flagging them told a working project it was broken.
    writeBackendResource({}, ["node"], {}, { build: "vite build", typecheck: "tsc --noEmit" });
    expect(checkTypeScriptTypeDependencies().didPass).toBe(true);
  });

  it("flags a frontend whose build runs tsc before vite", () => {
    writeBackendResource({}, ["node"], {}, { build: "tsc && vite build" });
    expect(checkTypeScriptTypeDependencies().didPass).toBe(false);
  });

  it("follows a build script that runs another script which runs tsc", () => {
    writeBackendResource({}, ["node"], {}, { build: "bun run compile", compile: "bunx tsc -p ." });
    expect(checkTypeScriptTypeDependencies().didPass).toBe(false);
  });

  it("skips a service with no build script", () => {
    writeBackendResource({}, ["node"], {}, {});
    expect(checkTypeScriptTypeDependencies().didPass).toBe(true);
  });

  it("does not loop forever on scripts that run each other", () => {
    writeBackendResource({}, ["node"], {}, { build: "bun run a", a: "bun run build" });
    expect(checkTypeScriptTypeDependencies().didPass).toBe(true);
  });

  it("fails when @types/bun is used but @types/node is not a direct dependency (bun-types' hidden reference)", () => {
    // bun-types hardcodes `/// <reference types="node" />` in its own index.d.ts.
    // TypeScript honors that regardless of the tsconfig's "types" restriction, so
    // "types": ["bun"] alone is not enough -- @types/node must resolve too. It can
    // resolve transitively via bun-types' own dependency, but that hoisting is not
    // guaranteed in Docker's isolated per-service install, unlike a full workspace
    // install, so the same service can build locally and fail with TS2688 in Docker.
    writeBackendResource({ typescript: "^5.0.0", "@types/bun": "^1.4.2" });

    const result = checkTypeScriptTypeDependencies();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("cash-management-api");
    expect(result.message).toContain("@types/bun");
    expect(result.message).toContain("node types internally");
    expect(result.fix).toContain('"@types/node"');
  });

  it("passes when @types/bun and @types/node are both direct dependencies", () => {
    writeBackendResource({
      typescript: "^5.0.0",
      "@types/bun": "^1.4.2",
      "@types/node": "^20.0.0",
    });
    expect(checkTypeScriptTypeDependencies().didPass).toBe(true);
  });

  it("does not require @types/node when @types/bun is unused", () => {
    writeBackendResource({ "@types/node": "^20.0.0" }, ["node"]);
    expect(checkTypeScriptTypeDependencies().didPass).toBe(true);
  });

  it("catches the hidden @types/node requirement even when @types/bun is a dependency without being in the types array", () => {
    // "types" only lists what the tsconfig explicitly restricts resolution to; a
    // service can still have @types/bun installed (and hit its reference) without
    // "bun" appearing there.
    writeBackendResource({ "@types/bun": "^1.4.2" }, []);

    const result = checkTypeScriptTypeDependencies();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("node types internally");
  });

  it("resolves subpath and scoped entries to the package that provides them", () => {
    writeBackendResource({ vitest: "^5.0.0", "@cloudflare/workers-types": "^4.0.0" }, [
      "vitest/globals",
      "@cloudflare/workers-types/2023-07-01",
    ]);
    expect(checkTypeScriptTypeDependencies().didPass).toBe(true);

    const missing = (() => {
      writeBackendResource({}, ["vitest/globals"]);
      return checkTypeScriptTypeDependencies();
    })();
    expect(missing.didPass).toBe(false);
    expect(missing.message).toContain('"vitest/globals" (needs vitest)');
  });
});

describe("doctor ingress + tilt runtime checks", () => {
  it("detects a foreign Traefik holding host port 80", () => {
    const dockerPs = [
      "tdk_saas_starter_traefik\t0.0.0.0:80->80/tcp,:::80->80/tcp,0.0.0.0:8080->8080/tcp",
      "tdk_project_postgres\t0.0.0.0:5432->5432/tcp",
    ].join("\n");

    const holders = parsePublishedPortHolders(dockerPs, [80, 443]);
    expect(holders).toHaveLength(1);
    expect(holders[0]?.name).toBe("tdk_saas_starter_traefik");
    expect(holders[0]?.publishedPorts).toContain(80);

    const foreign = findForeignIngressHolders(holders, "tdk_project");
    expect(foreign).toHaveLength(1);

    const result = checkIngressPorts((() => dockerPs) as never, "tdk-project");
    expect(result.didPass).toBe(false);
    expect(result.message).toContain("tdk_saas_starter_traefik");
    expect(result.fix).toContain("docker stop");
  });

  it("passes when this project's Traefik owns the ingress ports", () => {
    const dockerPs = "tdk_project_traefik\t0.0.0.0:80->80/tcp,:::80->80/tcp,0.0.0.0:443->443/tcp";
    const result = checkIngressPorts((() => dockerPs) as never, "tdk-project");
    expect(result.didPass).toBe(true);
    expect(result.message).toContain("tdk_project_traefik");
  });

  it("fails doctor when Tilt reports Traefik update errors that block apps", () => {
    const payload = {
      items: [
        {
          metadata: { name: "traefik" },
          status: {
            updateStatus: "error",
            runtimeStatus: "unknown",
            buildHistory: [
              {
                error:
                  "Bind for 0.0.0.0:80 failed: port is already allocated\nerror: exit status 1",
              },
            ],
          },
        },
        {
          metadata: { name: "salon-management-frontend" },
          status: { updateStatus: "pending", runtimeStatus: "pending" },
        },
        {
          metadata: { name: "postgres" },
          status: { updateStatus: "ok", runtimeStatus: "ok" },
        },
      ],
    };

    const parsed = parseTiltResourceFailures(JSON.stringify(payload));
    expect(parsed.failures).toHaveLength(1);
    expect(parsed.failures[0]?.name).toBe("traefik");
    expect(parsed.pendingCount).toBe(1);

    const result = checkTiltResourceHealth((() => JSON.stringify(payload)) as never);
    expect(result.didPass).toBe(false);
    expect(result.message).toContain("traefik");
    expect(result.message).toContain("port 80");
    expect(result.message).toContain("pending");
    expect(result.fix).toMatch(/docker ps --filter publish=80|Free the conflicting/);
  });

  it("separates sablier.deferStart resources from genuinely pending ones", () => {
    const payload = {
      items: [
        {
          metadata: { name: "data-governance-api" },
          status: { updateStatus: "none", runtimeStatus: "none" },
        },
        {
          metadata: { name: "some-other-stuck-resource" },
          status: { updateStatus: "pending", runtimeStatus: "pending" },
        },
        {
          metadata: { name: "postgres" },
          status: { updateStatus: "ok", runtimeStatus: "ok" },
        },
      ],
    };

    const parsed = parseTiltResourceFailures(
      JSON.stringify(payload),
      new Set(["data-governance-api"]),
    );
    expect(parsed.failures).toHaveLength(0);
    expect(parsed.deferredCount).toBe(1);
    expect(parsed.pendingCount).toBe(1);

    const result = checkTiltResourceHealth((() => JSON.stringify(payload)) as never);
    expect(result.didPass).toBe(true);
    // Without an injected deferredNames set (checkTiltResourceHealth computes
    // its own via discoverResources(), best-effort empty outside a project),
    // this specific resource isn't classified as deferred here -- covered by
    // the direct parseTiltResourceFailures assertions above instead.
  });

  it("does not describe deferred resources as blocked by unrelated failures", () => {
    const payload = {
      items: [
        {
          metadata: { name: "traefik" },
          status: {
            updateStatus: "error",
            runtimeStatus: "unknown",
            buildHistory: [{ error: "Bind for 0.0.0.0:80 failed: port is already allocated" }],
          },
        },
        {
          metadata: { name: "data-governance-api" },
          status: { updateStatus: "none", runtimeStatus: "none" },
        },
      ],
    };

    const parsed = parseTiltResourceFailures(
      JSON.stringify(payload),
      new Set(["data-governance-api"]),
    );
    expect(parsed.deferredCount).toBe(1);
    expect(parsed.pendingCount).toBe(0);
  });

  it("skips tilt resource check when tilt is not running", () => {
    const result = checkTiltResourceHealth((() => {
      throw new Error("tilt not running");
    }) as never);
    expect(result.isSkipped).toBe(true);
    expect(result.didPass).toBe(true);
  });

  it("summarizes ConnectionRefused package manifest errors from build logs", () => {
    const raw = [
      "error: ConnectionRefused downloading package manifest @tdk-landscape/eventing",
      "error: ConnectionRefused downloading package manifest @tdk-landscape/identity-js-sdk",
      "error: ConnectionRefused downloading package manifest @tdk-landscape/observability",
      'ImageBuild: process "/bin/sh -c bun install --production --cache-dir=/cache/bun" did not complete successfully: exit code: 1',
    ].join("\n");

    const summary = summarizeTiltBuildError(raw);
    expect(summary).toContain("ConnectionRefused");
    expect(summary).toContain("@tdk-landscape/eventing");
    expect(summary).toContain("Verdaccio");
  });

  it("summarizes truncated bun install ImageBuild exits as registry failures", () => {
    const summary = summarizeTiltBuildError(
      'ImageBuild: process "/bin/sh -c bun install --production --cache-dir=/cache/bun" did not complete successfully: exit code: 1',
    );
    expect(summary).toMatch(/dependency install failed|Verdaccio|ConnectionRefused/i);
  });

  it("summarizes missing compose images for run-only resources", () => {
    const summary = summarizeTiltBuildError(
      'Command "docker compose -p appointment-planner-autogenerated -f .../docker-compose.app.autogenerated.yml up -d --no-build appointment-planner-builder-backend" failed: exit status 1',
    );
    expect(summary).toContain("appointment-planner-builder-backend");
    expect(summary).toMatch(/image is missing|ImageBuild|run-only/i);
  });

  it("lists every failed resource even when an infra resource also failed", () => {
    const payload = {
      items: [
        {
          metadata: { name: "nats-http-bridge" },
          status: { updateStatus: "ok", runtimeStatus: "error" },
        },
        {
          metadata: { name: "appointment-management-backend" },
          status: {
            updateStatus: "error",
            runtimeStatus: "unknown",
            buildHistory: [
              {
                error:
                  'ImageBuild: process "/bin/sh -c bun run build" did not complete successfully: exit code: 1',
              },
            ],
          },
        },
        {
          metadata: { name: "appointment-management-backend-run-only" },
          status: {
            updateStatus: "error",
            runtimeStatus: "not_applicable",
            buildHistory: [
              {
                error:
                  'Command "docker compose -p appointment-autogenerated -f x.yml up -d --no-build appointment-management-backend" failed: exit status 1',
              },
            ],
          },
        },
      ],
    };

    const result = checkTiltResourceHealth(((command: string) => {
      if (command.includes("tilt get uiresources")) {
        return JSON.stringify(payload);
      }
      if (command.startsWith("docker ps")) {
        return "platform-autogenerated-nats-http-bridge-1\n";
      }
      if (command.includes("docker logs")) {
        return 'error: Failed to start NATS HTTP Bridge {"error":"Connection error: getaddrinfo ENOTFOUND"}\nInitializing Kafka consumer... {"brokers":["kafka:9092"]}';
      }
      throw new Error(`unexpected exec: ${command}`);
    }) as typeof import("node:child_process").execSync);

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("3 failed resources");
    expect(result.message).toContain("nats-http-bridge");
    expect(result.message).toContain("appointment-management-backend");
    expect(result.message).toContain("appointment-management-backend-run-only");
    expect(result.message).toMatch(/Kafka broker unreachable|kafka:9092/i);
    expect(result.message).toMatch(/bun run build/i);
    expect(result.fix).toMatch(/Kafka/i);
    expect(
      orderTiltFailures(parseTiltResourceFailures(JSON.stringify(payload)).failures)[0]?.name,
    ).toBe("nats-http-bridge");
  });

  it("probes docker logs for Kafka ENOTFOUND runtime crashes", () => {
    const exec = ((command: string) => {
      if (command.startsWith("docker ps")) {
        return "platform-autogenerated-nats-http-bridge-1\n";
      }
      if (command.includes("docker logs")) {
        return "getaddrinfo ENOTFOUND\nbroker kafka:9092\nFailed to start NATS HTTP Bridge";
      }
      return "";
    }) as typeof import("node:child_process").execSync;

    const summary = probeContainerRuntimeError("nats-http-bridge", exec);
    expect(summary).toMatch(/Kafka broker unreachable/);
  });

  it("summarizes bun run build ImageBuild failures", () => {
    const summary = summarizeTiltBuildError(
      'ImageBuild: process "/bin/sh -c bun run build" did not complete successfully: exit code: 1',
    );
    expect(summary).toMatch(/bun run build|TypeScript|Tilt/i);
  });

  it("surfaces registry-oriented fix when ImageBuild dependency installs fail", () => {
    const payload = {
      items: [
        {
          metadata: { name: "appointment-management-backend" },
          status: {
            updateStatus: "error",
            runtimeStatus: "unknown",
            buildHistory: [
              {
                error:
                  'ImageBuild: process "/bin/sh -c bun install --production --cache-dir=/cache/bun" did not complete successfully: exit code: 1',
              },
            ],
          },
        },
        {
          metadata: { name: "salon-management-frontend" },
          status: { updateStatus: "pending", runtimeStatus: "pending" },
        },
      ],
    };

    const result = checkTiltResourceHealth((() => JSON.stringify(payload)) as never);
    expect(result.didPass).toBe(false);
    expect(result.message).toContain("appointment-management-backend");
    expect(result.message).toMatch(/dependency install failed|Verdaccio|ConnectionRefused/i);
    expect(result.fix).toMatch(/verdaccio:start|publish/i);
  });

  it("fails private registry check when Verdaccio is enabled but unreachable", () => {
    const projectRoot = join(
      tmpdir(),
      `tdk-doctor-registry-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    );
    mkdirSync(join(projectRoot, ".tdk"), { recursive: true });
    writeFileSync(
      join(projectRoot, ".tdk", "project.json"),
      JSON.stringify({
        project: { name: "demo" },
        optional_infra: { verdaccio: true },
        phases: {},
      }),
    );

    const execDown = ((command: string) => {
      if (command.startsWith("docker ps")) {
        return "";
      }
      if (command.includes("curl")) {
        throw new Error("Failed to connect to localhost port 4873");
      }
      return "";
    }) as typeof import("node:child_process").execSync;

    const result = checkPrivateNpmRegistry(execDown, projectRoot, "http://localhost:4873");

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("ConnectionRefused");
    expect(result.fix).toMatch(/verdaccio:start/);

    rmSync(projectRoot, { recursive: true, force: true });
  });

  it("passes private registry check when Verdaccio responds", () => {
    const projectRoot = join(
      tmpdir(),
      `tdk-doctor-registry-ok-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    );
    mkdirSync(join(projectRoot, ".tdk"), { recursive: true });
    writeFileSync(
      join(projectRoot, ".tdk", "project.json"),
      JSON.stringify({
        project: { name: "demo" },
        optional_infra: { verdaccio: true },
        phases: {},
      }),
    );

    const execUp = ((command: string) => {
      if (command.startsWith("docker ps")) {
        return "tdk-project-verdaccio\n";
      }
      if (command.includes("curl")) {
        return "200";
      }
      return "";
    }) as typeof import("node:child_process").execSync;

    const result = checkPrivateNpmRegistry(execUp, projectRoot, "http://localhost:4873");

    expect(result.didPass).toBe(true);
    expect(result.message).toContain("reachable");

    rmSync(projectRoot, { recursive: true, force: true });
  });
});

describe("doctor private registry check without a Verdaccio license", () => {
  function projectWithVerdaccioEnabled(npmrc?: string): string {
    const projectRoot = join(
      tmpdir(),
      `tdk-doctor-registry-unlicensed-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    );
    mkdirSync(join(projectRoot, ".tdk"), { recursive: true });
    writeFileSync(
      join(projectRoot, ".tdk", "project.json"),
      JSON.stringify({
        project: { name: "demo" },
        optional_infra: { verdaccio: true },
        phases: {},
      }),
    );
    if (npmrc) writeFileSync(join(projectRoot, ".npmrc"), npmrc);
    return projectRoot;
  }

  const unreachable = (() => {
    throw new Error("Failed to connect to localhost port 4873");
  }) as unknown as typeof import("node:child_process").execSync;

  it("skips when the config enables Verdaccio but TDK will not start it", () => {
    const projectRoot = projectWithVerdaccioEnabled();
    const result = checkPrivateNpmRegistry(
      unreachable,
      projectRoot,
      "http://localhost:4873",
      false,
    );
    expect(result.didPass).toBe(true);
    expect(result.isSkipped).toBe(true);
    expect(result.message).toContain("Premium license");
    rmSync(projectRoot, { recursive: true, force: true });
  });

  it("still checks a registry the project's own .npmrc points at", () => {
    const projectRoot = projectWithVerdaccioEnabled("@acme:registry=http://localhost:4873\n");
    const result = checkPrivateNpmRegistry(
      unreachable,
      projectRoot,
      "http://localhost:4873",
      false,
    );
    expect(result.didPass).toBe(false);
    rmSync(projectRoot, { recursive: true, force: true });
  });
});

describe("doctor Docker version check", () => {
  function fakeExec(engine: string, compose: string) {
    return (async (command: string) =>
      command.startsWith("docker compose") ? `${compose}\n` : `${engine}\n`) as never;
  }

  it("passes on Docker Engine 25+ and Compose 2.20.2+", async () => {
    const result = await checkDockerVersions(fakeExec("29.8.0", "2.39.1"));

    expect(result.didPass).toBe(true);
    expect(result.isSkipped).toBeFalsy();
    expect(result.message).toContain("29.8.0");
  });

  it("fails with an upgrade hint when the engine is older than 25", async () => {
    const result = await checkDockerVersions(fakeExec("24.0.7", "2.39.1"));

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("Docker Engine 24.0.7");
    expect(result.message).toContain("start_interval");
    expect(result.fix).toContain("Update Docker");
  });

  it("fails when Compose is older than 2.20.2", async () => {
    const result = await checkDockerVersions(fakeExec("27.1.1", "v2.20.1"));

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("Docker Compose v2.20.1");
  });

  it("skips instead of failing when versions cannot be read", async () => {
    const result = await checkDockerVersions((() => {
      throw new Error("docker not found");
    }) as never);

    expect(result.didPass).toBe(true);
    expect(result.isSkipped).toBe(true);
  });
});

describe("doctor resource discovery", () => {
  let testDir: string;
  let originalCwd: string;

  beforeEach(() => {
    originalCwd = process.cwd();
    testDir = join(
      tmpdir(),
      `tdk-doctor-discovery-${Date.now()}-${Math.random().toString(16).slice(2)}`,
    );
    mkdirSync(join(testDir, ".tdk"), { recursive: true });
    writeFileSync(join(testDir, "Tiltfile"), "");
    writeFileSync(
      join(testDir, ".tdk", "project.json"),
      JSON.stringify({ discovery: { paths: ["services/*/*"] } }),
    );
    process.chdir(testDir);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    rmSync(testDir, { recursive: true, force: true });
  });

  function writeResource(dir: string, appName: string) {
    mkdirSync(join(testDir, dir), { recursive: true });
    writeFileSync(
      join(testDir, dir, "service.json"),
      JSON.stringify({ appName, appType: "frontend", stack: "shop" }),
    );
  }

  it("passes when every resource is under a discovery path", () => {
    writeResource("services/shop/storefront", "storefront");
    expect(checkResourceDiscovery().didPass).toBe(true);
  });

  it("fails and names resources that Tilt would never start", () => {
    writeResource("services/shop/orders-api", "orders-api");
    writeResource("apps/storefront", "storefront");

    const result = checkResourceDiscovery();

    expect(result.didPass).toBe(false);
    expect(result.message).toContain("apps/storefront");
    expect(result.message).not.toContain("orders-api");
    expect(result.fix).toContain("discovery.paths");
  });
});
