import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, it } from "vitest";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../../..");
const registration = readFileSync(
  join(
    repoRoot,
    "engine",
    "topologies",
    "tilt",
    "resources",
    "orchestrator",
    "apply_compose_resource_registration.star",
  ),
  "utf-8",
);

// Tilt resolves sync() local paths against the Tiltfile directory (.tdk/.tdk-out), not the
// docker_build context. A project-relative path never matches the changed files, so every
// edit fell back to a full rebuild ("Found file(s) not matching any sync").
it("anchors live-update sync sources at the project root", () => {
  expect(registration).toContain(
    "def _live_update_sync_source(project_root, full_res_path, sync_path)",
  );
  expect(registration).toContain("return project_root.rstrip('/') + '/' + relative_path");
  expect(registration).toContain(
    "full_sync_path = _live_update_sync_source(project_root, full_res_path, sync_path)",
  );
});

it("passes the project root and language to the live-update rules by keyword", () => {
  expect(registration).toContain(
    "def _build_live_update_rules(res_path, full_res_path, syncs, project_root='', language='bun')",
  );
  expect(registration).toContain("project_root=config.get('project_root', ''),");
  expect(registration).toContain("language=config.get('manifest', {}).get('language', 'bun'),");
});

it("gives Go and Rust backends no live-update rules, so Tilt rebuilds the image on change", () => {
  expect(registration).toContain("if language in ['go', 'rust']:\n        return []");
  // The early return must come before any sync() step is built: Tilt rejects sync steps that are created but unused.
  expect(registration.indexOf("if language in ['go', 'rust']:")).toBeLessThan(
    registration.indexOf("live_update_rules.append(sync(full_sync_path, dest))"),
  );
});

it("keeps the container destination under /app, independent of the host project root", () => {
  expect(registration).toContain("dest = '/app/' + full_res_path + '/' + sync_path");
});

it("does not sync the Bun/npm registry config for Python backends", () => {
  expect(registration).toContain("if language == 'python' and (");
  expect(registration).toContain("sync_path.endswith('.npmrc.docker.autogenerated')");
  expect(registration).toContain("sync_path.endswith('bunfig.docker.autogenerated.toml')");
});
