import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolve(__dirname, "../../../..");
const cliBin = join(repoRoot, "cli", "bin", "tdk.js");

function runTdk(args: string[], cwd: string, input?: string): string {
  return execFileSync(process.execPath, [cliBin, ...args], {
    cwd,
    encoding: "utf-8",
    input,
    env: {
      ...process.env,
      TDK_EXTENSION_SOURCE: repoRoot,
    },
  });
}

describe("frontend resource framework selection", () => {
  let projectRoot = "";

  beforeAll(() => {
    projectRoot = mkdtempSync(join(tmpdir(), "tdk-resource-framework-"));
    runTdk(["project", "--yes"], projectRoot);
  });

  afterAll(() => {
    if (projectRoot.startsWith(tmpdir())) {
      rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  it("scaffolds the default React provider and persists its id", () => {
    const resourcePath = join(projectRoot, "apps", "storefront");
    runTdk(
      [
        "resource",
        "storefront",
        "--type",
        "frontend",
        "--stack",
        "shop",
        "--path",
        "apps/storefront",
      ],
      projectRoot,
      "y\n",
    );

    const service = JSON.parse(readFileSync(join(resourcePath, "service.json"), "utf-8"));
    const pkg = JSON.parse(readFileSync(join(resourcePath, "package.json"), "utf-8"));
    const tsconfig = JSON.parse(readFileSync(join(resourcePath, "tsconfig.json"), "utf-8"));
    const engineConstants = readFileSync(
      join(repoRoot, "engine", "topologies", "tilt", "manifest", "constants.star"),
      "utf-8",
    );
    const generatedViteConfig = engineConstants.match(/'vite_frontend': '([^']+)'/)?.[1];
    const generatedBuildConfig = engineConstants.match(/'vite_build': '([^']+)'/)?.[1];

    expect(service.framework).toBe("react");
    expect(pkg.dependencies).toMatchObject({ react: "^19.0.0", "react-dom": "^19.0.0" });
    expect(pkg.devDependencies).toHaveProperty("@vitejs/plugin-react");
    expect(generatedViteConfig).toBe("vite.config.frontend.autogenerated.ts");
    expect(generatedBuildConfig).toBe("vite.config.build.autogenerated.ts");
    expect(pkg.scripts.dev).toBe(`vite --config .autogenerated/${generatedViteConfig}`);
    expect(pkg.scripts.build).toBe(
      `tsc && vite build --config .autogenerated/${generatedBuildConfig}`,
    );
    expect(tsconfig.compilerOptions.jsx).toBe("react-jsx");
    expect(readdirSync(resourcePath).sort()).toEqual([
      "Dockerfile",
      "index.html",
      "package.json",
      "service.json",
      "src",
      "tests",
      "tsconfig.json",
    ]);
    expect(existsSync(join(resourcePath, "vite.config.ts"))).toBe(false);
    const vendoredViteRoot = join(
      projectRoot,
      ".tdk",
      ".tdk-out",
      "tdk-cli-ext",
      "engine",
      "topologies",
      "tilt",
      "generators",
      "vite",
    );
    expect(existsSync(join(vendoredViteRoot, "frameworks", "react.star"))).toBe(true);
    expect(readFileSync(join(vendoredViteRoot, "frontend.star"), "utf-8")).toContain(
      "load('./frameworks/react.star'",
    );
    expect(readFileSync(join(vendoredViteRoot, "templates.star"), "utf-8")).not.toContain(
      "TEMPLATE_VITE_FRONTEND",
    );
    expect(readFileSync(join(resourcePath, "index.html"), "utf-8")).toContain("/src/main.tsx");
    expect(readFileSync(join(resourcePath, "src", "main.tsx"), "utf-8")).toContain(
      "ReactDOM.createRoot",
    );
    expect(readFileSync(join(resourcePath, "src", "App.tsx"), "utf-8")).toContain(
      "Frontend resource created with TDK",
    );
  }, 15000);

  it("scaffolds Vue without a second Vite config owner or runtime fork", () => {
    const vuePath = join(projectRoot, "apps", "vue-web");
    const reactPath = join(projectRoot, "apps", "react-web");
    runTdk(
      [
        "resource",
        "vue-web",
        "--type",
        "frontend",
        "--framework",
        "vue",
        "--stack",
        "shop",
        "--path",
        "apps/vue-web",
      ],
      projectRoot,
      "y\n",
    );
    runTdk(
      [
        "resource",
        "react-web",
        "--type",
        "frontend",
        "--stack",
        "shop",
        "--path",
        "apps/react-web",
      ],
      projectRoot,
      "y\n",
    );

    const vueService = JSON.parse(readFileSync(join(vuePath, "service.json"), "utf-8"));
    const reactService = JSON.parse(readFileSync(join(reactPath, "service.json"), "utf-8"));
    const vuePackage = JSON.parse(readFileSync(join(vuePath, "package.json"), "utf-8"));
    const reactPackage = JSON.parse(readFileSync(join(reactPath, "package.json"), "utf-8"));
    const vueTsconfig = JSON.parse(readFileSync(join(vuePath, "tsconfig.json"), "utf-8"));
    const cliPackage = JSON.parse(readFileSync(join(repoRoot, "cli", "package.json"), "utf-8"));

    expect(vueService.framework).toBe("vue");
    expect(vueService.appType).toBe("frontend");
    expect(vueService.stack).toBe(reactService.stack);
    expect(vueService.dev).toEqual(reactService.dev);
    expect(vueService.build).toEqual(reactService.build);
    expect(vueService.port).toBeGreaterThanOrEqual(3000);
    expect(vueService.port).toBeLessThan(4000);
    expect(vuePackage.scripts).toEqual(reactPackage.scripts);
    expect(vuePackage.dependencies).toHaveProperty("vue");
    expect(vuePackage.dependencies).not.toHaveProperty("react");
    expect(vuePackage.devDependencies).toHaveProperty("@vitejs/plugin-vue");
    expect(vuePackage.devDependencies).not.toHaveProperty("@vitejs/plugin-react");
    expect(cliPackage.dependencies).not.toHaveProperty("vue");
    expect(cliPackage.dependencies).not.toHaveProperty("@vitejs/plugin-vue");
    expect(vueTsconfig.compilerOptions).not.toHaveProperty("jsx");
    expect(readFileSync(join(vuePath, "Dockerfile"), "utf-8")).toBe(
      readFileSync(join(reactPath, "Dockerfile"), "utf-8"),
    );
    expect(readdirSync(vuePath).sort()).toEqual([
      "Dockerfile",
      "index.html",
      "package.json",
      "service.json",
      "src",
      "tests",
      "tsconfig.json",
    ]);
    expect(readdirSync(join(vuePath, "src")).sort()).toEqual([
      "App.vue",
      "main.ts",
      "vite-env.d.ts",
    ]);
    expect(existsSync(join(vuePath, "vite.config.ts"))).toBe(false);
    expect(readFileSync(join(vuePath, "index.html"), "utf-8")).toContain("/src/main.ts");
    expect(readFileSync(join(vuePath, "src", "main.ts"), "utf-8")).toContain(
      "createApp(App).mount('#app')",
    );
    expect(readFileSync(join(vuePath, "src", "App.vue"), "utf-8")).toContain(
      '<script setup lang="ts">',
    );
    expect(
      existsSync(
        join(
          projectRoot,
          ".tdk/.tdk-out/tdk-cli-ext/engine/topologies/tilt/generators/vite/frameworks/vue.star",
        ),
      ),
    ).toBe(true);
  }, 15000);

  it("fails for an unknown framework before creating a resource directory", () => {
    const resourcePath = join(projectRoot, "apps", "invalid-web");

    expect(() =>
      runTdk(
        [
          "resource",
          "invalid-web",
          "--type",
          "frontend",
          "--framework",
          "svelte",
          "--stack",
          "shop",
          "--path",
          "apps/invalid-web",
        ],
        projectRoot,
      ),
    ).toThrow(/Unknown frontend framework "svelte"/);
    expect(existsSync(resourcePath)).toBe(false);
  }, 15000);

  it("rejects framework selection for backend resources before creating their directory", () => {
    const resourcePath = join(projectRoot, "services", "shop", "orders-api");

    expect(() =>
      runTdk(
        [
          "resource",
          "orders-api",
          "--type",
          "backend",
          "--framework",
          "react",
          "--stack",
          "shop",
          "--path",
          "services/shop/orders-api",
        ],
        projectRoot,
      ),
    ).toThrow(/only be used with --type frontend/);
    expect(existsSync(resourcePath)).toBe(false);
  }, 15000);
});
