import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolve(__dirname, "../../../..");
const cliBin = join(repoRoot, "cli", "bin", "tdk.js");

function runTdk(args: string[], cwd: string, input?: string): string {
  return execFileSync(process.execPath, [cliBin, ...args], {
    cwd,
    encoding: "utf-8",
    input,
    env: {
      ...process.env,
      TDK_EXTENSION_SOURCE: repoRoot,
    },
  });
}

describe("frontend resource framework selection", () => {
  let projectRoot = "";

  beforeAll(() => {
    projectRoot = mkdtempSync(join(tmpdir(), "tdk-resource-framework-"));
    runTdk(["project", "--yes"], projectRoot);
  });

  afterAll(() => {
    if (projectRoot.startsWith(tmpdir())) {
      rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  it("scaffolds the default React provider and persists its id", () => {
    const resourcePath = join(projectRoot, "apps", "storefront");
    runTdk(
      [
        "resource",
        "storefront",
        "--type",
        "frontend",
        "--stack",
        "shop",
        "--path",
        "apps/storefront",
      ],
      projectRoot,
      "y\n",
    );

    const service = JSON.parse(readFileSync(join(resourcePath, "service.json"), "utf-8"));
    const pkg = JSON.parse(readFileSync(join(resourcePath, "package.json"), "utf-8"));
    const tsconfig = JSON.parse(readFileSync(join(resourcePath, "tsconfig.json"), "utf-8"));
    const engineConstants = readFileSync(
      join(repoRoot, "engine", "topologies", "tilt", "manifest", "constants.star"),
      "utf-8",
    );
    const generatedViteConfig = engineConstants.match(/'vite_frontend': '([^']+)'/)?.[1];
    const generatedBuildConfig = engineConstants.match(/'vite_build': '([^']+)'/)?.[1];

    expect(service.framework).toBe("react");
    expect(pkg.dependencies).toMatchObject({ react: "^19.0.0", "react-dom": "^19.0.0" });
    expect(pkg.devDependencies).toHaveProperty("@vitejs/plugin-react");
    expect(generatedViteConfig).toBe("vite.config.frontend.autogenerated.ts");
    expect(generatedBuildConfig).toBe("vite.config.build.autogenerated.ts");
    expect(pkg.scripts.dev).toBe(`vite --config .autogenerated/${generatedViteConfig}`);
    expect(pkg.scripts.build).toBe(
      `tsc && vite build --config .autogenerated/${generatedBuildConfig}`,
    );
    expect(tsconfig.compilerOptions.jsx).toBe("react-jsx");
    expect(readdirSync(resourcePath).sort()).toEqual([
      "Dockerfile",
      "index.html",
      "package.json",
      "public",
      "service.json",
      "src",
      "tests",
      "tsconfig.json",
    ]);
    expect(existsSync(join(resourcePath, "vite.config.ts"))).toBe(false);
    const vendoredViteRoot = join(
      projectRoot,
      ".tdk",
      ".tdk-out",
      "tdk-cli-ext",
      "engine",
      "topologies",
      "tilt",
      "generators",
      "vite",
    );
    expect(existsSync(join(vendoredViteRoot, "frameworks", "react.star"))).toBe(true);
    expect(readFileSync(join(vendoredViteRoot, "frontend.star"), "utf-8")).toContain(
      "load('./frameworks/react.star'",
    );
    expect(readFileSync(join(vendoredViteRoot, "templates.star"), "utf-8")).not.toContain(
      "TEMPLATE_VITE_FRONTEND",
    );
    expect(readFileSync(join(resourcePath, "index.html"), "utf-8")).toContain("/src/main.tsx");
    expect(readFileSync(join(resourcePath, "src", "main.tsx"), "utf-8")).toContain(
      "ReactDOM.createRoot",
    );
    expect(readFileSync(join(resourcePath, "src", "App.tsx"), "utf-8")).toContain(
      "Frontend resource created with TDK",
    );
  }, 15000);

  it("scaffolds Vue without a second Vite config owner or runtime fork", () => {
    const vuePath = join(projectRoot, "apps", "vue-web");
    const reactPath = join(projectRoot, "apps", "react-web");
    runTdk(
      [
        "resource",
        "vue-web",
        "--type",
        "frontend",
        "--framework",
        "vue",
        "--stack",
        "shop",
        "--path",
        "apps/vue-web",
      ],
      projectRoot,
      "y\n",
    );
    runTdk(
      [
        "resource",
        "react-web",
        "--type",
        "frontend",
        "--stack",
        "shop",
        "--path",
        "apps/react-web",
      ],
      projectRoot,
      "y\n",
    );

    const vueService = JSON.parse(readFileSync(join(vuePath, "service.json"), "utf-8"));
    const reactService = JSON.parse(readFileSync(join(reactPath, "service.json"), "utf-8"));
    const vuePackage = JSON.parse(readFileSync(join(vuePath, "package.json"), "utf-8"));
    const reactPackage = JSON.parse(readFileSync(join(reactPath, "package.json"), "utf-8"));
    const vueTsconfig = JSON.parse(readFileSync(join(vuePath, "tsconfig.json"), "utf-8"));
    const cliPackage = JSON.parse(readFileSync(join(repoRoot, "cli", "package.json"), "utf-8"));

    expect(vueService.framework).toBe("vue");
    expect(vueService.appType).toBe("frontend");
    expect(vueService.stack).toBe(reactService.stack);
    expect(vueService.dev).toEqual(reactService.dev);
    expect(vueService.build).toEqual(reactService.build);
    expect(vueService.port).toBeGreaterThanOrEqual(3000);
    expect(vueService.port).toBeLessThan(4000);
    expect(vuePackage.scripts).toEqual(reactPackage.scripts);
    expect(vuePackage.dependencies).toHaveProperty("vue");
    expect(vuePackage.dependencies).not.toHaveProperty("react");
    expect(vuePackage.devDependencies).toHaveProperty("@vitejs/plugin-vue");
    expect(vuePackage.devDependencies).not.toHaveProperty("@vitejs/plugin-react");
    expect(cliPackage.dependencies).not.toHaveProperty("vue");
    expect(cliPackage.dependencies).not.toHaveProperty("@vitejs/plugin-vue");
    expect(vueTsconfig.compilerOptions).not.toHaveProperty("jsx");
    expect(readFileSync(join(vuePath, "Dockerfile"), "utf-8")).toBe(
      readFileSync(join(reactPath, "Dockerfile"), "utf-8"),
    );
    expect(readdirSync(vuePath).sort()).toEqual([
      "Dockerfile",
      "index.html",
      "package.json",
      "public",
      "service.json",
      "src",
      "tests",
      "tsconfig.json",
    ]);
    expect(readdirSync(join(vuePath, "src")).sort()).toEqual([
      "App.vue",
      "main.ts",
      "vite-env.d.ts",
    ]);
    expect(existsSync(join(vuePath, "vite.config.ts"))).toBe(false);
    expect(readFileSync(join(vuePath, "index.html"), "utf-8")).toContain("/src/main.ts");
    expect(readFileSync(join(vuePath, "src", "main.ts"), "utf-8")).toContain(
      "createApp(App).mount('#app')",
    );
    expect(readFileSync(join(vuePath, "src", "App.vue"), "utf-8")).toContain(
      '<script setup lang="ts">',
    );
    expect(
      existsSync(
        join(
          projectRoot,
          ".tdk/.tdk-out/tdk-cli-ext/engine/topologies/tilt/generators/vite/frameworks/vue.star",
        ),
      ),
    ).toBe(true);
  }, 15000);

  it("scaffolds Svelte without a second Vite config owner or runtime fork", () => {
    const sveltePath = join(projectRoot, "apps", "svelte-web");
    runTdk(
      [
        "resource",
        "svelte-web",
        "--type",
        "frontend",
        "--framework",
        "svelte",
        "--stack",
        "shop",
        "--path",
        "apps/svelte-web",
      ],
      projectRoot,
      "y\n",
    );

    const service = JSON.parse(readFileSync(join(sveltePath, "service.json"), "utf-8"));
    const pkg = JSON.parse(readFileSync(join(sveltePath, "package.json"), "utf-8"));
    const tsconfig = JSON.parse(readFileSync(join(sveltePath, "tsconfig.json"), "utf-8"));
    const cliPackage = JSON.parse(readFileSync(join(repoRoot, "cli", "package.json"), "utf-8"));

    expect(service.framework).toBe("svelte");
    expect(service.appType).toBe("frontend");
    expect(service.port).toBeGreaterThanOrEqual(3000);
    expect(service.port).toBeLessThan(4000);
    expect(pkg.dependencies).toHaveProperty("svelte");
    expect(pkg.dependencies).not.toHaveProperty("react");
    expect(pkg.devDependencies).toHaveProperty("@sveltejs/vite-plugin-svelte");
    expect(pkg.devDependencies).not.toHaveProperty("@vitejs/plugin-react");
    expect(cliPackage.dependencies).not.toHaveProperty("svelte");
    expect(cliPackage.dependencies).not.toHaveProperty("@sveltejs/vite-plugin-svelte");
    expect(tsconfig.compilerOptions).not.toHaveProperty("jsx");
    expect(readdirSync(join(sveltePath, "src")).sort()).toEqual([
      "App.svelte",
      "main.ts",
      "vite-env.d.ts",
    ]);
    expect(existsSync(join(sveltePath, "vite.config.ts"))).toBe(false);
    expect(readFileSync(join(sveltePath, "index.html"), "utf-8")).toContain("/src/main.ts");
    expect(readFileSync(join(sveltePath, "src", "App.svelte"), "utf-8")).toContain(
      '<script lang="ts">',
    );
    expect(
      existsSync(
        join(
          projectRoot,
          ".tdk/.tdk-out/tdk-cli-ext/engine/topologies/tilt/generators/vite/frameworks/svelte.star",
        ),
      ),
    ).toBe(true);
  }, 15000);

  it("scaffolds Preact without a second Vite config owner or runtime fork", () => {
    const preactPath = join(projectRoot, "apps", "preact-web");
    runTdk(
      [
        "resource",
        "preact-web",
        "--type",
        "frontend",
        "--framework",
        "preact",
        "--stack",
        "shop",
        "--path",
        "apps/preact-web",
      ],
      projectRoot,
      "y\n",
    );

    const service = JSON.parse(readFileSync(join(preactPath, "service.json"), "utf-8"));
    const pkg = JSON.parse(readFileSync(join(preactPath, "package.json"), "utf-8"));
    const tsconfig = JSON.parse(readFileSync(join(preactPath, "tsconfig.json"), "utf-8"));
    const cliPackage = JSON.parse(readFileSync(join(repoRoot, "cli", "package.json"), "utf-8"));

    expect(service.framework).toBe("preact");
    expect(service.appType).toBe("frontend");
    expect(pkg.dependencies).toHaveProperty("preact");
    expect(pkg.dependencies).not.toHaveProperty("react");
    expect(pkg.devDependencies).toHaveProperty("@preact/preset-vite");
    expect(pkg.devDependencies).not.toHaveProperty("@vitejs/plugin-react");
    expect(cliPackage.dependencies).not.toHaveProperty("preact");
    expect(tsconfig.compilerOptions.jsxImportSource).toBe("preact");
    expect(readdirSync(join(preactPath, "src")).sort()).toEqual(["App.tsx", "main.tsx"]);
    expect(existsSync(join(preactPath, "vite.config.ts"))).toBe(false);
    expect(readFileSync(join(preactPath, "src", "main.tsx"), "utf-8")).toContain("from 'preact'");
    expect(
      existsSync(
        join(
          projectRoot,
          ".tdk/.tdk-out/tdk-cli-ext/engine/topologies/tilt/generators/vite/frameworks/preact.star",
        ),
      ),
    ).toBe(true);
  }, 15000);

  it("scaffolds Lit without a second Vite config owner or runtime fork", () => {
    const litPath = join(projectRoot, "apps", "lit-web");
    runTdk(
      [
        "resource",
        "lit-web",
        "--type",
        "frontend",
        "--framework",
        "lit",
        "--stack",
        "shop",
        "--path",
        "apps/lit-web",
      ],
      projectRoot,
      "y\n",
    );

    const service = JSON.parse(readFileSync(join(litPath, "service.json"), "utf-8"));
    const pkg = JSON.parse(readFileSync(join(litPath, "package.json"), "utf-8"));
    const cliPackage = JSON.parse(readFileSync(join(repoRoot, "cli", "package.json"), "utf-8"));

    expect(service.framework).toBe("lit");
    expect(service.appType).toBe("frontend");
    expect(pkg.dependencies).toHaveProperty("lit");
    expect(pkg.dependencies).not.toHaveProperty("react");
    expect(pkg.devDependencies).not.toHaveProperty("@vitejs/plugin-react");
    expect(cliPackage.dependencies).not.toHaveProperty("lit");
    expect(readdirSync(join(litPath, "src")).sort()).toEqual(["app-root.ts", "main.ts"]);
    expect(existsSync(join(litPath, "vite.config.ts"))).toBe(false);
    expect(
      existsSync(
        join(
          projectRoot,
          ".tdk/.tdk-out/tdk-cli-ext/engine/topologies/tilt/generators/vite/frameworks/lit.star",
        ),
      ),
    ).toBe(true);
  }, 15000);

  it("scaffolds Vanilla without a second Vite config owner or runtime fork", () => {
    const vanillaPath = join(projectRoot, "apps", "vanilla-web");
    runTdk(
      [
        "resource",
        "vanilla-web",
        "--type",
        "frontend",
        "--framework",
        "vanilla",
        "--stack",
        "shop",
        "--path",
        "apps/vanilla-web",
      ],
      projectRoot,
      "y\n",
    );

    const service = JSON.parse(readFileSync(join(vanillaPath, "service.json"), "utf-8"));
    const pkg = JSON.parse(readFileSync(join(vanillaPath, "package.json"), "utf-8"));

    expect(service.framework).toBe("vanilla");
    expect(service.appType).toBe("frontend");
    expect(pkg.dependencies ?? {}).toEqual({});
    expect(pkg.dependencies).not.toHaveProperty("react");
    expect(pkg.devDependencies).not.toHaveProperty("@vitejs/plugin-react");
    expect(readdirSync(join(vanillaPath, "src")).sort()).toEqual(["app.ts", "main.ts"]);
    expect(existsSync(join(vanillaPath, "vite.config.ts"))).toBe(false);
    expect(
      existsSync(
        join(
          projectRoot,
          ".tdk/.tdk-out/tdk-cli-ext/engine/topologies/tilt/generators/vite/frameworks/vanilla.star",
        ),
      ),
    ).toBe(true);
  }, 15000);

  it("scaffolds Solid without a second Vite config owner or runtime fork", () => {
    const solidPath = join(projectRoot, "apps", "solid-web");
    runTdk(
      [
        "resource",
        "solid-web",
        "--type",
        "frontend",
        "--framework",
        "solid",
        "--stack",
        "shop",
        "--path",
        "apps/solid-web",
      ],
      projectRoot,
      "y\n",
    );

    const service = JSON.parse(readFileSync(join(solidPath, "service.json"), "utf-8"));
    const pkg = JSON.parse(readFileSync(join(solidPath, "package.json"), "utf-8"));
    const tsconfig = JSON.parse(readFileSync(join(solidPath, "tsconfig.json"), "utf-8"));
    const cliPackage = JSON.parse(readFileSync(join(repoRoot, "cli", "package.json"), "utf-8"));

    expect(service.framework).toBe("solid");
    expect(service.appType).toBe("frontend");
    expect(pkg.dependencies).toHaveProperty("solid-js");
    expect(pkg.dependencies).not.toHaveProperty("react");
    expect(pkg.devDependencies).toHaveProperty("vite-plugin-solid");
    expect(pkg.devDependencies).not.toHaveProperty("@vitejs/plugin-react");
    expect(cliPackage.dependencies).not.toHaveProperty("solid-js");
    expect(tsconfig.compilerOptions.jsx).toBe("preserve");
    expect(tsconfig.compilerOptions.jsxImportSource).toBe("solid-js");
    expect(readdirSync(join(solidPath, "src")).sort()).toEqual(["App.tsx", "main.tsx"]);
    expect(existsSync(join(solidPath, "vite.config.ts"))).toBe(false);
    expect(
      existsSync(
        join(
          projectRoot,
          ".tdk/.tdk-out/tdk-cli-ext/engine/topologies/tilt/generators/vite/frameworks/solid.star",
        ),
      ),
    ).toBe(true);
  }, 15000);

  it("scaffolds TanStack Router as a Vite SPA that shares the React toolchain", () => {
    const path = join(projectRoot, "apps", "router-web");
    runTdk(
      [
        "resource",
        "router-web",
        "--type",
        "frontend",
        "--framework",
        "tanstack-router",
        "--stack",
        "shop",
        "--path",
        "apps/router-web",
      ],
      projectRoot,
      "y\n",
    );

    const service = JSON.parse(readFileSync(join(path, "service.json"), "utf-8"));
    const pkg = JSON.parse(readFileSync(join(path, "package.json"), "utf-8"));
    const tsconfig = JSON.parse(readFileSync(join(path, "tsconfig.json"), "utf-8"));

    expect(service.framework).toBe("tanstack-router");
    expect(service.appType).toBe("frontend");
    expect(pkg.dependencies).toHaveProperty("@tanstack/react-router");
    expect(pkg.devDependencies).toHaveProperty("@vitejs/plugin-react");
    expect(tsconfig.compilerOptions.jsx).toBe("react-jsx");
    expect(readdirSync(join(path, "src")).sort()).toEqual(["main.tsx", "router.tsx"]);
    expect(existsSync(join(path, "vite.config.ts"))).toBe(false);
  }, 15000);

  it("scaffolds Qwik without a second Vite config owner or runtime fork", () => {
    const qwikPath = join(projectRoot, "apps", "qwik-web");
    runTdk(
      [
        "resource",
        "qwik-web",
        "--type",
        "frontend",
        "--framework",
        "qwik",
        "--stack",
        "shop",
        "--path",
        "apps/qwik-web",
      ],
      projectRoot,
      "y\n",
    );

    const service = JSON.parse(readFileSync(join(qwikPath, "service.json"), "utf-8"));
    const pkg = JSON.parse(readFileSync(join(qwikPath, "package.json"), "utf-8"));
    const tsconfig = JSON.parse(readFileSync(join(qwikPath, "tsconfig.json"), "utf-8"));
    const cliPackage = JSON.parse(readFileSync(join(repoRoot, "cli", "package.json"), "utf-8"));

    expect(service.framework).toBe("qwik");
    expect(service.appType).toBe("frontend");
    expect(pkg.dependencies).toHaveProperty("@builder.io/qwik");
    expect(pkg.dependencies).not.toHaveProperty("react");
    expect(pkg.devDependencies ?? {}).not.toHaveProperty("@vitejs/plugin-react");
    expect(cliPackage.dependencies).not.toHaveProperty("@builder.io/qwik");
    expect(tsconfig.compilerOptions.jsx).toBe("react-jsx");
    expect(tsconfig.compilerOptions.jsxImportSource).toBe("@builder.io/qwik");
    expect(readdirSync(join(qwikPath, "src")).sort()).toEqual(["App.tsx", "main.tsx"]);
    expect(existsSync(join(qwikPath, "vite.config.ts"))).toBe(false);
    expect(
      existsSync(
        join(
          projectRoot,
          ".tdk/.tdk-out/tdk-cli-ext/engine/topologies/tilt/generators/vite/frameworks/qwik.star",
        ),
      ),
    ).toBe(true);
  }, 15000);

  it("places a frontend where discovery finds it and says so", () => {
    const output = runTdk(
      ["resource", "landing", "--type", "frontend", "--stack", "shop"],
      projectRoot,
      "y\n",
    );

    // apps/landing would be outside the default services/*/* discovery glob, so Tilt would
    // never create a resource for it and `tdk up` would route to nothing.
    expect(existsSync(join(projectRoot, "services", "shop", "landing", "service.json"))).toBe(true);
    expect(existsSync(join(projectRoot, "apps", "landing"))).toBe(false);
    expect(output).toContain("Placed in services/shop/landing instead of the usual apps/landing");
    expect(output).toContain('["services/*/*"]');
    expect(existsSync(join(projectRoot, "services", "shop", "landing", "public"))).toBe(true);
  }, 15000);

  it("warns when an explicit --path is outside discovery", () => {
    const output = runTdk(
      [
        "resource",
        "marketing",
        "--type",
        "frontend",
        "--stack",
        "shop",
        "--path",
        "apps/marketing",
      ],
      projectRoot,
      "y\n",
    );

    expect(existsSync(join(projectRoot, "apps", "marketing", "service.json"))).toBe(true);
    expect(output).toContain("apps/marketing is outside discovery.paths");
    expect(output).toContain("tdk config regenerate");
  }, 15000);

  it("fails for an unknown framework before creating a resource directory", () => {
    const resourcePath = join(projectRoot, "apps", "invalid-web");

    expect(() =>
      runTdk(
        [
          "resource",
          "invalid-web",
          "--type",
          "frontend",
          "--framework",
          "nonesuch",
          "--stack",
          "shop",
          "--path",
          "apps/invalid-web",
        ],
        projectRoot,
      ),
    ).toThrow(
      /Unknown frontend framework "nonesuch"[\s\S]*Use one of: react, vue, svelte, preact, lit, solid, qwik, vanilla, tanstack-router/,
    );
    expect(existsSync(resourcePath)).toBe(false);
  }, 15000);

  it("rejects a frontend framework id on a backend before creating its directory", () => {
    const resourcePath = join(projectRoot, "services", "shop", "orders-api");

    expect(() =>
      runTdk(
        [
          "resource",
          "orders-api",
          "--type",
          "backend",
          "--framework",
          "react",
          "--stack",
          "shop",
          "--path",
          "services/shop/orders-api",
        ],
        projectRoot,
      ),
    ).toThrow(/Unknown backend framework "react"/);
    expect(existsSync(resourcePath)).toBe(false);
  }, 15000);
});
