import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolve(__dirname, "../../../..");
const cliBin = join(repoRoot, "cli", "bin", "tdk.js");

function runTdk(args: string[], cwd: string): string {
  return execFileSync("bun", [cliBin, ...args], {
    cwd,
    encoding: "utf-8",
    env: {
      ...process.env,
      TDK_EXTENSION_SOURCE: repoRoot,
    },
  });
}

describe("stack feature E2E", () => {
  let projectRoot = "";

  afterEach(() => {
    if (projectRoot && projectRoot.startsWith(tmpdir())) {
      rmSync(projectRoot, { recursive: true, force: true });
    }
  });

  it("generates database-management compose from pre_alpha services", () => {
    projectRoot = mkdtempSync(join(tmpdir(), "tdk-stack-feature-"));

    const output = runTdk(["project", "--yes"], projectRoot);
    expect(output).toContain("Generated: services/platform/database-management/docker-compose.yml");

    const projectJson = JSON.parse(readFileSync(join(projectRoot, ".tdk", "project.json"), "utf-8"));
    expect(projectJson.stack_features).toBeUndefined();
    expect(projectJson.phases.pre_alpha.enabledStacks).toContain("database-management");

    const composePath = join(
      projectRoot,
      "services",
      "platform",
      "database-management",
      "docker-compose.yml",
    );
    expect(existsSync(composePath)).toBe(true);

    const compose = readFileSync(composePath, "utf-8");
    expect(compose).toContain("Stack feature: database-management");
    expect(compose).toContain('Source: .tdk/project.json phases.*.enabledStacks includes "database-management"');
    expect(compose).toContain("container_name: tdk_stack_feature_");
    expect(compose).toContain("_postgres");
    expect(compose).toContain("_database");

    const spec = readFileSync(join(projectRoot, ".tdk", ".tdk-out", "spec.master"), "utf-8");
    expect(spec).toMatch(/"database-management":\s*True/);
    expect(spec).not.toContain("STACK_FEATURES");

    const tiltignore = readFileSync(join(projectRoot, ".tiltignore"), "utf-8");
    expect(tiltignore).toContain("**/.autogenerated/**");
  });

  it("does not keep database-management enabled after it leaves stack services", () => {
    projectRoot = mkdtempSync(join(tmpdir(), "tdk-stack-feature-off-"));
    runTdk(["project", "--yes"], projectRoot);

    const projectJsonPath = join(projectRoot, ".tdk", "project.json");
    const projectJson = JSON.parse(readFileSync(projectJsonPath, "utf-8"));
    projectJson.phases.pre_alpha.enabledStacks = projectJson.phases.pre_alpha.enabledStacks.filter(
      (service: string) => service !== "database-management",
    );
    writeFileSync(projectJsonPath, `${JSON.stringify(projectJson, null, 2)}\n`);

    runTdk(["project", "--yes"], projectRoot);

    const spec = readFileSync(join(projectRoot, ".tdk", ".tdk-out", "spec.master"), "utf-8");
    expect(spec).not.toMatch(/"database-management":\s*True/);
    expect(spec).not.toContain("STACK_FEATURES");
  });

  it("dedupes a duplicated service name in project.json instead of emitting a duplicate Starlark key", () => {
    projectRoot = mkdtempSync(join(tmpdir(), "tdk-stack-feature-dupe-"));
    runTdk(["project", "--yes"], projectRoot);

    const projectJsonPath = join(projectRoot, ".tdk", "project.json");
    const projectJson = JSON.parse(readFileSync(projectJsonPath, "utf-8"));
    projectJson.phases.pre_alpha.enabledStacks.push("database-management");
    writeFileSync(projectJsonPath, `${JSON.stringify(projectJson, null, 2)}\n`);

    runTdk(["project"], projectRoot);

    const spec = readFileSync(join(projectRoot, ".tdk", ".tdk-out", "spec.master"), "utf-8");
    const matches = spec.match(/"database-management":\s*True/g) ?? [];
    expect(matches.length).toBe(1);
  });

  it("adds newly discovered unassigned service stacks to pre_alpha on regeneration", () => {
    projectRoot = mkdtempSync(join(tmpdir(), "tdk-stack-discovery-sync-"));
    runTdk(["project", "--yes"], projectRoot);

    const serviceDir = join(projectRoot, "services", "billing", "checkout-app");
    mkdirSync(serviceDir, { recursive: true });
    writeFileSync(
      join(serviceDir, "service.json"),
      `${JSON.stringify(
        {
          appName: "checkout-app",
          appType: "frontend",
          stack: "billing",
          port: 3210,
        },
        null,
        2,
      )}\n`,
    );

    runTdk(["project", "--yes"], projectRoot);

    const projectJson = JSON.parse(readFileSync(join(projectRoot, ".tdk", "project.json"), "utf-8"));
    expect(projectJson.phases.pre_alpha.enabledStacks).toContain("billing");

    const spec = readFileSync(join(projectRoot, ".tdk", ".tdk-out", "spec.master"), "utf-8");
    expect(spec).toMatch(/"billing":\s*True/);
  });
});
