# =============================================================================
# 🐳 TILT SDK - DOCKERIGNORE GENERATORS (modular)
# =============================================================================
# Path: .tilt/topologies/platform/docker/dockerignore.star
# Purpose: .dockerignore generation helpers extracted from .tilt/providers/docker.star
# =============================================================================

# Import shared utilities for template headers
load('../../../tilt/common/utils.star', 'Utils')


def _get_common_dockerignore_rules():
    """Get common .dockerignore rules for all service types."""
    return """# Development files
node_modules
.git
.gitignore
.DS_Store
.env
.env.*
!.env.example

# IDE files
.vscode
.idea
*.swp
*~

# Build artifacts
coverage
*.log
npm-debug.log*
yarn-debug.log*

# Documentation
*.md
*.adoc
docs/
README*

# Configuration files not needed in production
.prettierrc
.eslintrc*
biome.json
tsconfig.tsbuildinfo
playwright.config.ts
playwright.config.autogenerated.ts
playwright.config.js
playwright.config.mjs
playwright.config.cjs
playwright.config.mts
playwright.config.cts
playwright.config.tsx

# Temporary files
tmp/
.cache/
.tmp/

# Shared packages source code (published to Verdaccio, installed via bun)
# These are not needed in Docker build context
shared-platform-engineering/
!shared-platform-engineering/docker-templates/
shared-product-engineering/
cli-platform-engineering/
shared-ddd-layers/
"""


def _get_backend_specific_rules():
    """Get backend-specific .dockerignore rules."""
    return """# Test files
**/__tests__
**/__mocks__
*.test.ts
*.spec.ts
test-results
playwright-report

# Config files
vitest.config.ts
"""


def _get_frontend_specific_rules():
    """Get frontend-specific .dockerignore rules."""
    return """# Test files
**/__tests__
**/__mocks__
*.test.ts
*.test.tsx
*.spec.ts
*.spec.tsx
**/*.stories.tsx
test-results
playwright-report
e2e/
cucumber/

# Config files
# vite.config.ts
# vite.config.autogenerated.ts
# vite.config.frontend.autogenerated.ts
# vite.config.backend.autogenerated.ts
vitest.config.ts

# Build artifacts (dist is included in final image)
.next
.nuxt
.output
"""


def _get_migrator_specific_rules():
    """Get migrator-specific .dockerignore rules."""
    return """# Test files (migrators typically don't have tests)
**/__tests__
**/__mocks__
*.test.ts
*.spec.ts

# Build artifacts
dist
"""


def generate_dockerignore(res_path, resource_type='backend'):
    """
    Generate .dockerignore file for a service.
    """
    # Generate header using shared utility
    header = Utils.get_template_header(
        'dockerignore',
        'Docker.generate_dockerignore()',
        res_path.split('/')[-1],
        resource_type.upper()
    )

    # Start with common rules
    content = header + _get_common_dockerignore_rules()

    # Add service-specific rules
    if resource_type == 'frontend':
        content += _get_frontend_specific_rules()
    elif resource_type == 'migrator':
        content += _get_migrator_specific_rules()
    else:  # backend
        content += _get_backend_specific_rules()

    return content
