# =============================================================================
# 🔐 TILT SDK - AUTH CONFIGURATION UTILITIES
# =============================================================================
# Path: .tilt/topologies/platform/docker/auth.star
# Purpose: Centralized authentication configuration helpers for docker-compose
#          and environment file generation across the platform.
# 
# Design Principle: This module is decoupled from manifest.json structure.
#          It accepts auth configuration as a dictionary parameter and does
#          not know where the config comes from. Callers (env.star, compose.star)
#          are responsible for extracting auth fields from manifest and passing
#          them as the auth_config dict.
# =============================================================================

# Default values for auth configuration
DEFAULT_AUTH_MODE = 'local-jwt'
DEFAULT_JWT_SECRET = 'local-development-secret-min-32-chars-long'
DEFAULT_IDENTITY_RESOURCE_URL = 'http://identity-service:3000'


def get_auth_mode(auth_config):
    """Get auth mode from auth config with default fallback.

    Args:
        auth_config: Auth configuration dictionary (may be None or empty)

    Returns:
        str: Auth mode ('local-jwt' or 'identity-service')
    """
    if not auth_config:
        return DEFAULT_AUTH_MODE
    return auth_config.get('authMode', DEFAULT_AUTH_MODE)


def get_jwt_secret(auth_config):
    """Get JWT secret from auth config with default fallback.

    Args:
        auth_config: Auth configuration dictionary (may be None or empty)

    Returns:
        str: JWT secret for local-jwt mode
    """
    if not auth_config:
        return DEFAULT_JWT_SECRET
    return auth_config.get('jwtSecret', DEFAULT_JWT_SECRET)


def get_identity_resource_url(auth_config):
    """Get identity service URL from auth config with default fallback.

    Args:
        auth_config: Auth configuration dictionary (may be None or empty)

    Returns:
        str: URL for identity service
    """
    if not auth_config:
        return DEFAULT_IDENTITY_RESOURCE_URL
    return auth_config.get('identityServiceUrl', DEFAULT_IDENTITY_RESOURCE_URL)


def get_auth_config(auth_config):
    """Get complete auth configuration from auth config dict.

    Args:
        auth_config: Auth configuration dictionary (may be None or empty)

    Returns:
        struct: Auth configuration with mode, jwt_secret, and identity_resource_url
    """
    return struct(
        mode = get_auth_mode(auth_config),
        jwt_secret = get_jwt_secret(auth_config),
        identity_resource_url = get_identity_resource_url(auth_config),
    )


def is_local_jwt_mode(auth_config):
    """Check if auth mode is local-jwt.

    Args:
        auth_config: Auth configuration dictionary (may be None or empty)

    Returns:
        bool: True if auth mode is 'local-jwt'
    """
    return get_auth_mode(auth_config) == 'local-jwt'


def is_identity_resource_mode(auth_config):
    """Check if auth mode is identity-service.

    Args:
        auth_config: Auth configuration dictionary (may be None or empty)

    Returns:
        bool: True if auth mode is 'identity-service'
    """
    return get_auth_mode(auth_config) == 'identity-service'


def generate_docker_compose_auth_env(auth_config):
    """Generate docker-compose environment variables for auth configuration.

    This function returns the properly formatted environment variable block
    for docker-compose.yml files based on the auth mode.

    Args:
        auth_config: Auth configuration dictionary (may be None or empty)

    Returns:
        str: Formatted auth environment variables for docker-compose
    """
    auth_mode = get_auth_mode(auth_config)
    jwt_secret = get_jwt_secret(auth_config)
    identity_resource_url = get_identity_resource_url(auth_config)

    if auth_mode == 'local-jwt':
        return """      - AUTH_MODE=local-jwt
      - JWT_SECRET=${JWT_SECRET:-%(jwt_secret)s}""" % {'jwt_secret': jwt_secret}
    else:
        return """      - AUTH_MODE=identity-service
      - IDENTITY_RESOURCE_URL=${IDENTITY_RESOURCE_URL:-%(identity_resource_url)s}""" % {'identity_resource_url': identity_resource_url}


def generate_env_file_auth_section(auth_config):
    """Generate .env file auth section content.

    This function returns the formatted authentication configuration section
    for .env.backend.autogenerated files.

    Args:
        auth_config: Auth configuration dictionary (may be None or empty)

    Returns:
        str: Formatted auth section for .env files
    """
    auth_mode = get_auth_mode(auth_config)
    jwt_secret = get_jwt_secret(auth_config)
    identity_resource_url = get_identity_resource_url(auth_config)

    content = """
# Authentication Configuration
# Mode: {auth_mode} (options: local-jwt, identity-service)
AUTH_MODE={auth_mode}
""".format(auth_mode=auth_mode)

    if auth_mode == 'local-jwt':
        content += "JWT_SECRET={jwt_secret}\n".format(jwt_secret=jwt_secret)
    else:
        content += "IDENTITY_RESOURCE_URL={identity_resource_url}\n".format(identity_resource_url=identity_resource_url)

    return content


# Export all functions as a struct for easy importing
AuthConfig = struct(
    get_auth_mode = get_auth_mode,
    get_jwt_secret = get_jwt_secret,
    get_identity_resource_url = get_identity_resource_url,
    get_auth_config = get_auth_config,
    is_local_jwt_mode = is_local_jwt_mode,
    is_identity_resource_mode = is_identity_resource_mode,
    generate_docker_compose_auth_env = generate_docker_compose_auth_env,
    generate_env_file_auth_section = generate_env_file_auth_section,
)
