#!/usr/bin/env bash
set -euo pipefail

project_dir="${1:?usage: cold-start.sh PROJECT_DIR}"
cd "$project_dir"

echo "::group::Scaffold deferred and deliberately slow backends"
tdk project --yes
printf 'y\n' | tdk resource cold-api --type backend --stack cold-start
printf 'y\n' | tdk resource slow-api --type backend --stack cold-start

python3 - <<'PY'
import json
from pathlib import Path

for service_name in ("cold-api", "slow-api"):
    matches = list(Path(".").glob(f"**/{service_name}/service.json"))
    if len(matches) != 1:
        raise SystemExit(f"expected one service.json for {service_name}; found {matches}")
    path = matches[0]
    service = json.loads(path.read_text())
    service["sablier"] = {"enable": True, "deferStart": service_name == "cold-api"}
    path.write_text(json.dumps(service, indent=2) + "\n")

# Keep an unrelated service unhealthy long enough to make the cold request
# overlap tdk up's normal bring-up, without depending on a large fixture.
slow_sources = list(Path(".").glob("**/slow-api/src/index.ts"))
if len(slow_sources) != 1:
    raise SystemExit(f"expected one slow-api source file; found {slow_sources}")
source = slow_sources[0]
source.write_text("await Bun.sleep(90000);\n" + source.read_text())
PY

# Re-vendor after setting the manifest so a configured premium CI key overlays
# the real Sablier implementation into this disposable project.
tdk project --yes
python3 - <<'PY'
import json
from pathlib import Path

manifest_path = next(Path(".").glob("**/cold-api/service.json"))
manifest = json.loads(manifest_path.read_text())
if manifest.get("sablier") != {"enable": True, "deferStart": True}:
    raise SystemExit(f"cold-api service manifest lost its deferred Sablier config: {manifest.get('sablier')!r}")

overlay = Path(".tdk/.tdk-out/tdk-cli-ext/engine/topologies/platform/docker/networking/sablier_container_cycle.star")
if not overlay.exists():
    raise SystemExit("Sablier overlay file was not applied; inspect the Premium entitlement probes, bundle contents, and Sablier entitlement check above to identify whether access or the published bundle is missing it")
if "No internal license check here" not in overlay.read_text():
    raise SystemExit("Sablier overlay file exists but does not contain the expected licensed implementation; inspect the published bundle/version")
print("Verified cold-api deferStart manifest and licensed Sablier overlay")
PY
echo "Running tdk doctor after resource generation and before tdk up"
tdk doctor
echo "::endgroup::"

cleanup() {
  tdk down >/dev/null 2>&1 || true
  if [ -n "${up_pid:-}" ]; then
    kill "$up_pid" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT
tdk up cold-start > up.log 2>&1 &
up_pid=$!
echo "tdk up pid=$up_pid"

echo "Waiting for Tilt to generate the deferred Compose file and prebuild its image"
compose_file=""
image=""
started_at="$(date +%s)"
for n in $(seq 1 300); do
  if [ -z "$compose_file" ] || [ -z "$image" ]; then
    compose_info="$(python3 <<'PY'
import re
from pathlib import Path

for path in Path(".").rglob("docker-compose.app.autogenerated.yml"):
    lines = path.read_text().splitlines()
    in_cold_api = False
    for line in lines:
        if re.match(r"^\s{2}cold-api:\s*$", line):
            in_cold_api = True
            continue
        if in_cold_api and re.match(r"^\s{2}\S", line):
            break
        if in_cold_api:
            match = re.match(r"^\s+image:\s*['\"]?([^\s'\"]+)", line)
            if match:
                print(f"{path}\t{match.group(1)}")
                raise SystemExit(0)
PY
)"
    if [ -n "$compose_info" ]; then
      IFS=$'\t' read -r compose_file image <<< "$compose_info"
    fi
  fi
  if [ -n "$image" ] && docker image inspect "$image" >/dev/null 2>&1; then
    break
  fi
  if ! kill -0 "$up_pid" 2>/dev/null; then
    cat up.log
    echo "::error::tdk up exited before the deferred image was built"
    exit 1
  fi
  if grep -Fq "requests sablier.deferStart but the licensed Sablier overlay is disabled; starting normally" up.log; then
    cat up.log
    echo "::error::cold-start E2E cannot continue: TDK_LICENSE_KEY did not activate the licensed Sablier overlay"
    exit 1
  fi
  if [ $((n % 15)) -eq 0 ]; then
    elapsed=$(( $(date +%s) - started_at ))
    echo "::group::cold-start setup progress (${elapsed}s)"
    if [ -n "$image" ]; then
      echo "Waiting for image build: $image"
    elif [ -n "$compose_file" ]; then
      echo "Compose file exists; waiting for its image declaration/build: $compose_file"
    else
      echo "Tilt has not generated the cold-api Compose file yet"
    fi
    echo "-- tdk up output (last 30 lines):"
    tail -30 up.log || true
    echo "-- Docker containers:"
    docker ps -a --format 'table {{.Names}}\t{{.Status}}' | head -20 || true
    echo "-- Docker images:"
    docker images --format '{{.Repository}}:{{.Tag}} {{.CreatedSince}}' | head -15 || true
    echo "-- Tilt resources:"
    timeout 5s tilt get uiresources -o json 2>/dev/null | python3 -c '
import json, sys
try:
    items = json.load(sys.stdin).get("items", [])
    for item in items:
        status = item.get("status", {})
        print("{}: update={} runtime={} waiting={}".format(item["metadata"]["name"], status.get("updateStatus", "-"), status.get("runtimeStatus", "-"), status.get("waiting", {})))
except Exception as error:
    print(f"Tilt status unavailable: {error}")
' | head -40 || echo "Tilt is not responding yet"
    echo "::endgroup::"
  fi
  sleep 2
done

if [ -z "$compose_file" ] || [ -z "$image" ] || ! docker image inspect "$image" >/dev/null 2>&1; then
  tail -200 up.log
  echo "::error::deferred Compose file/image was not generated and built within 10 minutes of tdk up"
  exit 1
fi
echo "Deferred image built: $image"
if grep -Fq "requests sablier.deferStart but the licensed Sablier overlay is disabled; starting normally" up.log; then
  cat up.log
  echo "::error::cold-start E2E cannot continue: TDK_LICENSE_KEY did not activate the licensed Sablier overlay"
  exit 1
fi

# Confirm Tilt registered the deferred service as intentionally disabled before
# any request can reach the wake gateway. A normal auto_init registration must
# never satisfy this scenario, even if its container has not started yet.
tilt get uiresources -o json | python3 -c '
import json, sys
items = json.load(sys.stdin)["items"]
cold = [x for x in items if x["metadata"]["name"] == "cold-api"]
if len(cold) != 1:
    raise SystemExit(f"expected one cold-api Tilt resource, found {len(cold)}")
status = cold[0].get("status", {})
runtime = status.get("runtimeStatus")
update = status.get("updateStatus")
if runtime not in (None, "none") or update not in (None, "none"):
    raise SystemExit(f"cold-api started before its first request: runtimeStatus={runtime!r}, updateStatus={update!r}")
print(f"Verified cold-api is deferred in Tilt: runtimeStatus={runtime!r}, updateStatus={update!r}")
'

# The generated static route must route through the wake gateway; otherwise an
# absent container could pass the pre-request assertion without a working wake path.
route_file="$(find . -path '*/.tdk-out/traefik-dynamic/cold-api.yml' -print -quit)"
if [ -z "$route_file" ] || ! grep -q 'wake-gateway' "$route_file"; then
  echo "::error::cold-api static Traefik wake route was not generated"
  exit 1
fi

# The container must not exist before its first request, including stopped
# containers. Names include the service name in the generated Compose project.
if docker ps -a --format '{{.Names}}' | grep -q 'cold-api'; then
  docker ps -a --format 'table {{.Names}}\t{{.Status}}'
  echo "::error::deferred cold-api container exists before its first request"
  exit 1
fi

health_url=""
for _ in $(seq 1 60); do
  health_url="$(grep -oE 'https?://[^ ]*/cold-api[^ ]*/health' up.log | head -1 || true)"
  [ -n "$health_url" ] && break
  sleep 2
done
if [ -z "$health_url" ]; then
  tail -200 up.log
  echo "::error::tdk up did not print cold-api health URL"
  exit 1
fi

# Verify doctor classifies the absent container as intentionally deferred.
if ! tdk doctor --no-ping > doctor.log 2>&1; then
  cat doctor.log
  echo "::error::tdk doctor failed while cold-api was intentionally deferred"
  exit 1
fi
cat doctor.log
grep -Eqi 'deferred|intentionally deferred' doctor.log || {
  echo "::error::tdk doctor did not report the deferred resource"
  exit 1
}

# Start the resource while slow-api is still inside its deliberate 90 second
# startup delay. The short hold override makes the 503/retry path deterministic.
tilt get uiresources -o json | python3 -c '
import json, sys
items = json.load(sys.stdin)["items"]
slow = [x for x in items if x["metadata"]["name"] == "slow-api"]
if not slow or slow[0].get("status", {}).get("runtimeStatus") == "healthy":
    raise SystemExit("slow-api is not still starting; cold wake did not overlap bring-up")
'

headers_file="$(mktemp)"
body_file="$(mktemp)"
code="$(curl -sS --max-time 20 -D "$headers_file" -o "$body_file" -w '%{http_code}' \
  -H 'X-Wake-Respond-Within-Ms: 1000' "$health_url" || true)"
echo "First cold request: HTTP $code"
cat "$body_file"
if [ "$code" = "503" ]; then
  grep -qi '^Retry-After:' "$headers_file" || {
    cat "$headers_file"
    echo "::error::cold wake 503 omitted Retry-After"
    exit 1
  }
elif [[ "$code" != 2* ]]; then
  cat "$headers_file" "$body_file"
  echo "::error::cold request returned HTTP $code"
  exit 1
fi

# A retry must join the in-flight startup (or reach the now-ready service) and
# eventually return the backend's real health response.
healthy=0
for _ in $(seq 1 90); do
  code="$(curl -sS --max-time 10 -o "$body_file" -w '%{http_code}' \
    -H 'X-Wake-Respond-Within-Ms: 1000' "$health_url" || true)"
  if [[ "$code" == 2* ]]; then
    healthy=1
    break
  fi
  [ "$code" = "503" ] || {
    cat "$body_file"
    echo "::error::retry returned unexpected HTTP $code"
    exit 1
  }
  sleep 2
done
if [ "$healthy" -ne 1 ]; then
  tail -200 up.log
  echo "::error::cold-api did not become healthy after its cold-start request"
  exit 1
fi
cat "$body_file"
grep -q 'cold-api' "$body_file" || {
  echo "::error::response was not cold-api's real health payload"
  exit 1
}
echo "Cold start passed: prebuilt image, no pre-request container, deferred doctor status, wake during unrelated startup, retry to HTTP 2xx."
