#!/usr/bin/env bash
# Run a native Go service with `dev.liveReload` through a real `tdk up` and check the development loop through Traefik (#369):
# an ordinary edit is served without an image rebuild, a broken edit puts the compiler error in Tilt's log while the last good build
# keeps serving, and the next valid edit recovers. Prints the first-start and warm edit-to-ready timings it observed.
#
# Needs Docker, Tilt, python3 and a built CLI (cli/dist). Uses an isolated throwaway project with a unique name and random alternate
# ports, and removes only the containers, networks and images carrying its own name (it never calls `tdk down`, which can touch other
# projects' containers).
#
# Usage: scripts/e2e/go-dev-loop.sh [edits]     (default 5)
#   VERIFY_WAIT_SECONDS   how long to wait for the first start (default 900)
#   GO_SERVICE_DIR        use this directory's go.mod, go.sum and main.go instead of the scaffold (a Gin service, for example);
#                         it must keep the scaffold's `"version"` response field on GET / and answer 200 on /health
set -euo pipefail

edits="${1:-5}"
root="$(cd "$(dirname "$0")/../.." && pwd)"
proj="golive$$"
work="$(mktemp -d)/$proj"
mkdir -p "$work"
http_port=$((30000 + RANDOM % 2000))
tilt_port=$((10400 + RANDOM % 500))
# Vendor and run this checkout's engine, not a published one (the backgrounded `tdk up` needs it too).
export TDK_EXTENSION_SOURCE="$root"
tdk() { node "$root/cli/bin/tdk.js" "$@"; }

cleanup() {
  # Anchored on the whole project name: golive123 must not match a concurrent run's golive1234.
  pkill -f "tilt up.*/${proj}/" >/dev/null 2>&1 || true
  docker rm -f $(docker ps -aq --filter "name=^${proj}[-_]") >/dev/null 2>&1 || true
  docker network ls --format '{{.Name}}' | grep -E "^${proj}_" | xargs -r docker network rm >/dev/null 2>&1 || true
  # Every tag of this run's own repositories: the service image, Tilt's app_<project> build tags, and the per-project golden layers.
  docker images --format '{{.Repository}}:{{.Tag}}' | grep -E "^(${proj}_api:|app_${proj}:|${proj}-l[0-9]+)" | xargs -r docker rmi -f >/dev/null 2>&1 || true
}
trap cleanup EXIT

cd "$work"
git init -q .
tdk project --yes >/dev/null 2>&1
printf '\nTDK_HTTP_PORT=%s\nTDK_HTTPS_PORT=%s\nTDK_POSTGRES_PORT=%s\n' \
  "$http_port" "$((32000 + RANDOM % 2000))" "$((34000 + RANDOM % 2000))" >> .env
tdk resource api --type backend --language go --stack "$proj" --yes >/dev/null
svc="services/$proj/api"
if [ -n "${GO_SERVICE_DIR:-}" ]; then
  cp "$GO_SERVICE_DIR"/go.mod "$GO_SERVICE_DIR"/main.go "$svc/"
  [ -f "$GO_SERVICE_DIR/go.sum" ] && cp "$GO_SERVICE_DIR/go.sum" "$svc/"
  rm -f "$svc/main_test.go"
fi
python3 - "$svc/service.json" <<'PY'
import json, sys
path = sys.argv[1]
manifest = json.load(open(path))
manifest.setdefault("dev", {})["liveReload"] = True
json.dump(manifest, open(path, "w"), indent=2)
open(path, "a").write("\n")
PY

started="$(date +%s)"
TILT_PORT="$tilt_port" nohup node "$root/cli/bin/tdk.js" up "$proj" >"$work/up.log" 2>&1 &

route="/api/api/"
health="/api/api/health"
host="api.$proj.localhost"
status=000
for _ in $(seq 1 "${VERIFY_WAIT_SECONDS:-900}"); do
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' -H "Host: $host" "http://127.0.0.1:$http_port$health" || true)"
  [ "$status" = "200" ] && break
  sleep 1
done
if [ "$status" != "200" ]; then
  echo "FAIL: GET $health -> $status after ${VERIFY_WAIT_SECONDS:-900}s" >&2
  tail -30 "$work/up.log" >&2 || true
  exit 1
fi
echo "first start: $(( $(date +%s) - started ))s from launching tdk up to the first 200 through Traefik (includes image builds; cache state is whatever this Docker host had)"

container="${proj}-autogenerated-api-1"
echo "image: $(docker inspect -f '{{.Config.Image}}' "$container"), process: $(docker top "$container" -o pid,args | sed -n 2p | cut -c1-70)"
echo "machine: $(uname -sm), load average $(uptime | sed 's/.*load averages*: //')"

python3 "$root/scripts/e2e/go-dev-loop-probe.py" "$work/$svc/main.go" "$http_port" "$host" "$route" "$container" "$tilt_port" "$edits"
