appName: identity-management-frontend
appType: frontend
stack: identity
port: 4000
backendName: identity-management-backend
basePath: /
federation:
  appName: identity-service
  appType: remote
  port: 4001
  framework: vite
  vite:
    exposes:
      ./PasswordReset: ./src/remote-entry.ts
      ./SignIn: ./src/remote-entry.ts
      ./SignUp: ./src/remote-entry.ts
    name: identity_service
    shared:
      - react
      - react-dom
      - @beauty-crm/introvertic-ui
healthCheck: True
path: identity-management-frontend
playwright: True
target_path: /app/dist
traefik:
  host: identity-management-frontend.localhost
  rootPath: True
  rootPriority: 101
