/**
 * Wake gateway: fronts every `sablier.deferStart` resource's Traefik static
 * route (see openspec/changes/prioritized-cold-start). On the first request
 * for a resource with no running container, it triggers the resource (and
 * its cold dependencies) via `tilt trigger`, and/or Sablier's own start for
 * an already-created container, then holds the request until the resource
 * answers its healthcheck or the configured timeout elapses.
 *
 * Config for each request comes from headers a Traefik `headers` middleware
 * injects (set by the file-provider entry generated in
 * traefik_static_routes.star) rather than the path, so the original request
 * path/query reach the real backend unchanged once it's ready:
 *   X-Wake-Resource        Tilt/Compose resource name (for `tilt trigger` and
 *                          `docker compose up <service>`).
 *   X-Wake-Container       The actual Docker container name (for `docker
 *                          inspect` state/health and the proxy target -- NOT the same string as
 *                          the resource name; Compose derives it as
 *                          <project>-<service>-<replica>, confirmed empirically
 *                          against a live TDK container, e.g.
 *                          "analytics-autogenerated-data-governance-api-1"
 *                          for the "data-governance-api" resource).
 *   X-Wake-Deps            Comma-separated "resourceName=containerName" pairs
 *                          for required dependencies (task 1.5: Tilt never
 *                          cascades a trigger to these on its own).
 *   X-Wake-Compose-Project The resource's Compose project (e.g. "analytics-autogenerated").
 *   X-Wake-Compose-Files   Comma-separated absolute compose file paths, the
 *                          same ones Tilt's `<resource>-run-only` resource
 *                          passes. The project root is mounted into this
 *                          container at the same absolute path, so relative
 *                          paths inside those files resolve exactly as for Tilt.
 *   X-Wake-Env-File        Absolute path of the project's .env (optional).
 *   X-Wake-Image           The image the compose service declares
 *                          (<service>_<resource>:dev).
 *   X-Wake-Timeout-Ms, X-Wake-Proxy-Port, X-Wake-Session-Duration
 */
import {
  decideWakeAction,
  evaluateReadiness,
  wakeTimeoutMs,
  type ContainerState,
} from "./decide";

const TILT_HOST = process.env.TILT_HOST || "host.docker.internal";
const TILT_PORT = process.env.TILT_PORT || "10350";
const SABLIER_URL = process.env.SABLIER_URL || "http://sablier:10000";
const POLL_INTERVAL_MS = 1000;

async function run(cmd: string[]): Promise<{ code: number; stdout: string; stderr: string }> {
  const proc = Bun.spawn(cmd, { stdout: "pipe", stderr: "pipe" });
  const [stdout, stderr, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  return { code, stdout, stderr };
}

async function containerState(name: string): Promise<ContainerState> {
  const { code, stdout } = await run([
    "docker", "inspect", "--format", "{{.State.Status}}", name,
  ]);
  if (code !== 0) return "absent";
  const status = stdout.trim();
  if (status === "running") return "running";
  if (status === "created") return "created";
  return "exited";
}

async function isHealthy(name: string): Promise<boolean> {
  const { code, stdout } = await run([
    "docker", "inspect",
    "--format", "{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}",
    name,
  ]);
  if (code !== 0) return false;
  const status = stdout.trim();
  return status === "healthy" || status === "running";
}

async function tiltTrigger(name: string): Promise<void> {
  const { code, stderr } = await run(["tilt", "trigger", name, "--host", TILT_HOST, "--port", TILT_PORT]);
  console.log(`tilt trigger ${name}: ${code === 0 ? "queued" : `failed (${stderr.trim()})`}`);
}

interface ComposeInvocation {
  project: string;
  files: string[];
  envFile: string;
  image: string;
}

/**
 * Make sure the compose service's declared image exists locally. Tilt tags its
 * own builds `<repo>:tilt-<hash>` and injects that tag when it runs compose, so
 * the declared `<repo>:dev` tag may be missing even though the resource was
 * built; retag Tilt's newest build in that case. False when nothing was ever
 * built -- only `tilt trigger` (which builds) can wake the resource then.
 */
async function ensureImage(image: string): Promise<boolean> {
  if ((await run(["docker", "image", "inspect", "--format", "{{.Id}}", image])).code === 0) return true;
  const repo = image.split(":")[0];
  // `docker images` lists newest first.
  const { code, stdout } = await run(["docker", "images", repo, "--format", "{{.Tag}}"]);
  if (code !== 0) return false;
  const tiltTag = stdout.split("\n").map((t) => t.trim()).find((t) => t.startsWith("tilt-"));
  if (!tiltTag) return false;
  return (await run(["docker", "tag", `${repo}:${tiltTag}`, image])).code === 0;
}

/**
 * Create and start the resource's container directly, with the same
 * `docker compose ... up -d --no-build` its Tilt `-run-only` resource runs,
 * bypassing Tilt's build queue (see decide.ts useComposeStart).
 */
async function composeStart(compose: ComposeInvocation, service: string): Promise<boolean> {
  if (!(await ensureImage(compose.image))) {
    console.log(`compose start ${service}: no local image for ${compose.image}, falling back to tilt trigger`);
    return false;
  }
  const args = ["docker", "compose", "-p", compose.project];
  for (const file of compose.files) args.push("-f", file);
  if (compose.envFile) args.push("--env-file", compose.envFile);
  args.push("up", "-d", "--no-build", "--no-deps", service);
  const { code, stderr } = await run(args);
  console.log(`compose start ${service}: ${code === 0 ? "started" : `failed (${stderr.trim()})`}`);
  return code === 0;
}

/**
 * Sablier's real blocking-strategy endpoint (GET /api/strategies/blocking,
 * per https://sablierapp.dev/openapi.json): starts the named instance and
 * holds until it's ready or `timeoutMs` elapses, returning that outcome via
 * the X-Sablier-Session-Status header. Only valid for an instance Sablier
 * already knows about (a container that exists with sablier.enable=true) --
 * see decide.ts's useSablierStart.
 */
async function sablierBlockingWait(resource: string, sessionDuration: string, timeoutMs: number): Promise<boolean> {
  const params = new URLSearchParams({
    names: resource,
    session_duration: sessionDuration,
    timeout: `${Math.max(1, Math.round(timeoutMs / 1000))}s`,
  });
  try {
    const res = await fetch(`${SABLIER_URL}/api/strategies/blocking?${params}`);
    return res.headers.get("X-Sablier-Session-Status") === "ready";
  } catch {
    return false;
  }
}

interface NamedDep {
  resourceName: string;
  containerName: string;
}

function parseDeps(raw: string): NamedDep[] {
  return raw
    .split(",")
    .filter(Boolean)
    .map((pair) => {
      const [resourceName, containerName] = pair.split("=");
      return { resourceName, containerName: containerName || resourceName };
    });
}

function parseRequest(req: Request) {
  const resource = req.headers.get("X-Wake-Resource") || "";
  const container = req.headers.get("X-Wake-Container") || resource;
  const deps = parseDeps(req.headers.get("X-Wake-Deps") || "");
  const timeoutOverrideMs = Number(req.headers.get("X-Wake-Timeout-Ms")) || undefined;
  const proxyPort = req.headers.get("X-Wake-Proxy-Port") || "80";
  const sessionDuration = req.headers.get("X-Wake-Session-Duration") || "10m";
  const composeFiles = (req.headers.get("X-Wake-Compose-Files") || "").split(",").filter(Boolean);
  const compose: ComposeInvocation = {
    project: req.headers.get("X-Wake-Compose-Project") || "",
    files: composeFiles,
    envFile: req.headers.get("X-Wake-Env-File") || "",
    image: req.headers.get("X-Wake-Image") || "",
  };
  const hasCompose = Boolean(compose.project && compose.files.length && compose.image);
  return { resource, container, deps, timeoutOverrideMs, proxyPort, sessionDuration, compose, hasCompose };
}

async function handleWake(req: Request): Promise<Response> {
  const { resource, container, deps, timeoutOverrideMs, proxyPort, sessionDuration, compose, hasCompose } =
    parseRequest(req);
  if (!resource) {
    return new Response("wake gateway: missing X-Wake-Resource header (set by the generated Traefik static route)", { status: 400 });
  }

  const resourceState = await containerState(container);
  const dependencies = await Promise.all(
    deps.map(async (dep) => ({ name: dep.resourceName, state: await containerState(dep.containerName) })),
  );

  const action = decideWakeAction({
    resourceContainerName: resource,
    resourceState,
    dependencies,
    hasComposeInvocation: hasCompose,
  });
  console.log(
    `wake ${resource}: state=${resourceState} compose=${action.useComposeStart} ` +
      `trigger=[${action.tiltTriggerNames.join(",")}] sablier=${action.useSablierStart}`,
  );

  // Dependencies (and the resource itself when it can't be started directly)
  // go through tilt trigger (task 1.5: Tilt never cascades this on its own).
  const tiltNames = [...action.tiltTriggerNames];
  let startedViaCompose = false;
  if (action.useComposeStart) {
    startedViaCompose = await composeStart(compose, resource);
    if (!startedViaCompose) tiltNames.unshift(resource);
  }
  const timeoutMs = wakeTimeoutMs(startedViaCompose, timeoutOverrideMs);
  const deadline = Date.now() + timeoutMs;

  // Sablier's blocking call, when applicable, both starts AND waits for the
  // resource itself in one round trip.
  const [, resourceReadyViaSablier] = await Promise.all([
    Promise.all(tiltNames.map(tiltTrigger)),
    action.useSablierStart
      ? sablierBlockingWait(resource, sessionDuration, timeoutMs)
      : Promise.resolve(false),
  ]);

  const requiredNames = [resource, ...deps.map((d) => d.resourceName)];
  const containerByName: Record<string, string> = { [resource]: container };
  for (const dep of deps) containerByName[dep.resourceName] = dep.containerName;

  while (Date.now() < deadline) {
    const healthy: Record<string, boolean> = {};
    // Sablier's blocking call already confirmed the resource itself; re-check
    // it too (cheap) so a false result from Sablier still gets a fair retry.
    healthy[resource] = resourceReadyViaSablier || (await isHealthy(container));
    for (const dep of deps) {
      healthy[dep.resourceName] = await isHealthy(dep.containerName);
    }
    const outcome = evaluateReadiness(requiredNames, healthy);
    if (outcome.ready) {
      return proxyThrough(req, container, proxyPort);
    }
    await Bun.sleep(POLL_INTERVAL_MS);
  }

  return new Response(
    `wake gateway: timed out after ${timeoutMs}ms waiting for ${resource} and its dependencies to become healthy`,
    { status: 504 },
  );
}

// Headers that must not be forwarded verbatim to the upstream fetch: Host
// would otherwise carry the gateway's own address, and the X-Wake-* control
// headers are gateway-internal, not part of the real app request.
const STRIPPED_REQUEST_HEADERS = new Set([
  "host",
  "x-wake-resource",
  "x-wake-container",
  "x-wake-deps",
  "x-wake-timeout-ms",
  "x-wake-proxy-port",
  "x-wake-session-duration",
  "x-wake-compose-project",
  "x-wake-compose-files",
  "x-wake-env-file",
  "x-wake-image",
]);

// Proxies to the container name rather than the Compose service name: every
// TDK project's resources share the traefik-public network, where a bare
// service name is only an alias and could collide across projects.
async function proxyThrough(req: Request, container: string, port: string): Promise<Response> {
  // The original path/query reach the gateway untouched (config travels via
  // X-Wake-* headers, not the path), so they're forwarded as-is.
  const target = new URL(req.url);
  target.protocol = "http:";
  // Set hostname/port separately, not via `.host` -- confirmed empirically
  // that `target.host = "name:port"` silently keeps the URL's original port
  // when one is already present instead of replacing it.
  target.hostname = container;
  target.port = port;

  const headers = new Headers();
  for (const [key, value] of req.headers) {
    if (!STRIPPED_REQUEST_HEADERS.has(key.toLowerCase())) headers.set(key, value);
  }

  const upstream = await fetch(target.toString(), {
    method: req.method,
    headers,
    body: req.method === "GET" || req.method === "HEAD" ? undefined : await req.arrayBuffer(),
  });
  return new Response(upstream.body, { status: upstream.status, headers: upstream.headers });
}

Bun.serve({
  port: Number(process.env.PORT) || 9999,
  // Bun's default idleTimeout (10s) is shorter than a real wake can take
  // (tilt trigger + healthcheck polling) -- confirmed empirically: a request
  // was killed mid-wait with "request timed out after 10 seconds" before this
  // was raised. 255s is Bun's own max for this setting.
  idleTimeout: 255,
  fetch(req) {
    return handleWake(req).catch((err) => {
      console.error("wake gateway error:", err);
      return new Response(`wake gateway error: ${String(err)}`, { status: 500 });
    });
  },
});

console.log(`wake gateway listening on :${Number(process.env.PORT) || 9999}`);
