// Copyright (c) 2026 TDK Landscape contributors
// SPDX-License-Identifier: MIT
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";

// Behaviour of the Starlark planners that `tdk up` runs at Tiltfile load: the frontend build plan and the
// Tilt build concurrency. They run under Tilt's own Starlark interpreter, so these tests spawn Tilt.
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../../..");
const framePlan = join(
  repoRoot,
  "engine/topologies/platform/docker/build/frontend_build_plan.star",
);
const concurrency = join(repoRoot, "engine/topologies/tilt/resources/build_concurrency.star");
const hasTilt = spawnSync("tilt", ["version"], { encoding: "utf-8" }).status === 0;

if (process.env.TDK_REQUIRE_TILT === "1" && !hasTilt) {
  throw new Error("Tilt is required for the build-performance Starlark tests in CI.");
}

const dirs: string[] = [];
afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

/** Runs a Tiltfile body in a scratch project and returns the JSON value it wrote to `out.json`. */
function evaluate(body: string, files: Record<string, string> = {}): unknown {
  const project = mkdtempSync(join(tmpdir(), "tdk-build-perf-"));
  dirs.push(project);
  for (const [path, content] of Object.entries(files)) {
    mkdirSync(dirname(join(project, path)), { recursive: true });
    writeFileSync(join(project, path), content);
  }
  const out = join(project, "out.json");
  writeFileSync(
    join(project, "Tiltfile"),
    `${body}
local('cat > ' + ${JSON.stringify(out)}, quiet = True, stdin = encode_json(RESULT))
`,
  );
  const result = spawnSync("tilt", ["alpha", "tiltfile-result", "-f", join(project, "Tiltfile")], {
    cwd: project,
    encoding: "utf-8",
    timeout: 60_000,
  });
  if (result.status !== 0) throw new Error(`tilt failed: ${result.stderr || result.stdout}`);
  return JSON.parse(readFileSync(out, "utf-8"));
}

const pkg = (scripts: Record<string, string>) => JSON.stringify({ name: "web", scripts });

describe.skipIf(!hasTilt)("frontend build plan", () => {
  const plan = (scripts: Record<string, string> | null) => {
    const files: Record<string, string> = scripts === null ? {} : { "web/package.json": pkg(scripts) };
    return evaluate(
      `load(${JSON.stringify(framePlan)}, "frontend_build_plan")
RESULT = frontend_build_plan("web/package.json")`,
      files,
    ) as { build_cmd: string; typecheck: boolean; typecheck_cmd: string };
  };

  it("moves a non-emitting type-check out of the image and runs vite directly", () => {
    expect(plan({ build: "tsc --noEmit && vite build" })).toEqual({
      build_cmd: "bunx vite build",
      typecheck: true,
      typecheck_cmd: "bunx tsc --noEmit",
    });
  });

  it("keeps extra vite flags and a generated config the image copies", () => {
    const result = plan({
      build:
        "tsc --noEmit && vite build --mode production --config .autogenerated/vite.config.build.autogenerated.ts",
    });
    expect(result.build_cmd).toBe(
      "bunx vite build --mode production --config .autogenerated/vite.config.build.autogenerated.ts",
    );
    expect(result.typecheck).toBe(true);
  });

  it("keeps a plain emitting tsc in the image (its output may be used)", () => {
    expect(
      plan({
        build: "tsc && vite build --config .autogenerated/vite.config.build.autogenerated.ts",
      }),
    ).toEqual({
      build_cmd: "bun run build",
      typecheck: false,
      typecheck_cmd: "",
    });
  });

  it("does not use a custom config the image does not copy", () => {
    expect(plan({ build: "tsc --noEmit && vite build --config vite.config.ts" }).typecheck).toBe(
      false,
    );
    expect(plan({ build: "tsc --noEmit && vite build --config=vite.config.ts" }).typecheck).toBe(
      false,
    );
  });

  it("leaves any other script unchanged", () => {
    expect(plan({ build: "vite build" }).typecheck).toBe(false);
    expect(plan({ build: "tsc --noEmit && vite build && node scripts/post.js" }).typecheck).toBe(
      false,
    );
    expect(plan({ build: "tsc -b && vite build" }).typecheck).toBe(false);
  });

  it("falls back to the default build when there is no build script or no package.json", () => {
    expect(plan({ start: "vite" })).toEqual({
      build_cmd: "bun run build",
      typecheck: false,
      typecheck_cmd: "",
    });
    expect(plan(null)).toEqual({ build_cmd: "bun run build", typecheck: false, typecheck_cmd: "" });
  });
});

describe.skipIf(!hasTilt)("Tilt build concurrency", () => {
  const max = (cpus: number, memoryBytes: number) =>
    evaluate(
      `load(${JSON.stringify(concurrency)}, "compute_max_parallel_builds")
RESULT = compute_max_parallel_builds(${cpus}, ${memoryBytes})`,
    ) as number;
  const GIB = 1024 ** 3;

  it("reserves two CPUs and about 1.5 GiB per build, clamped to 3..8", () => {
    expect(max(8, Math.round(8.3 * GIB))).toBe(5); // memory allows 5
    expect(max(4, 16 * GIB)).toBe(3); // 2 CPUs left, clamped up to the minimum
    expect(max(32, 64 * GIB)).toBe(8); // plenty of room, clamped down to the maximum
    expect(max(12, 8 * GIB)).toBe(5); // memory is the limit
  });
});

describe("Tilt build concurrency wiring", () => {
  // The override and the engine-unavailable branches run only inside a live Tilt load (they call update_settings),
  // so these checks pin the source they depend on.
  const source = readFileSync(concurrency, "utf-8");

  it("reads TDK_MAX_PARALLEL_BUILDS first and accepts only a positive integer", () => {
    expect(source).toContain("os.environ.get('TDK_MAX_PARALLEL_BUILDS'");
    expect(source).toContain("_is_positive_int(override)");
  });

  it("keeps Tilt's default and says why when docker info cannot be read", () => {
    expect(source).toContain("if resources == None:");
    expect(source).toContain("Tilt default (docker info unavailable");
  });

  it("calls update_settings exactly once", () => {
    expect(source.match(/update_settings\(/g)).toHaveLength(1);
  });
});
