import { mkdirSync, mkdtempSync, rmSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { assertTdkGeneratedPath, isTdkGeneratedPath } from "../generated-paths.js";

describe("TDK generated-file allowlist", () => {
  let tempRoot = "";

  afterEach(() => {
    if (tempRoot) rmSync(tempRoot, { recursive: true, force: true });
  });

  it("allows owned generated directories and project Tilt files", () => {
    for (const path of [
      "services/shop/api/.autogenerated/Dockerfile.app.autogenerated",
      ".tdk/.tdk-out/Tiltfile",
      "Tiltfile",
      "TILT_RESOURCE.star",
      "shared-platform-engineering/docker-templates/install-deps.sh",
    ]) {
      expect(isTdkGeneratedPath(path)).toBe(true);
    }
  });

  it("rejects project source and path traversal", () => {
    expect(isTdkGeneratedPath("services/shop/api/src/index.ts")).toBe(false);
    expect(isTdkGeneratedPath("../src/index.ts")).toBe(false);
    expect(isTdkGeneratedPath("/tmp/project/.autogenerated/file.ts")).toBe(false);
  });

  it("resolves an allowed path under the project root and rejects an unowned destination", () => {
    expect(assertTdkGeneratedPath("/tmp/project", ".autogenerated/file.ts")).toBe(
      "/tmp/project/.autogenerated/file.ts",
    );
    expect(() => assertTdkGeneratedPath("/tmp/project", "src/index.ts")).toThrow(
      /outside TDK's generated-file allowlist/,
    );
  });

  it("rejects an allowlisted path that traverses a project symlink", () => {
    tempRoot = mkdtempSync(join(tmpdir(), "tdk-generated-path-"));
    const outside = mkdtempSync(join(tmpdir(), "tdk-generated-outside-"));
    mkdirSync(join(tempRoot, "services"), { recursive: true });
    symlinkSync(outside, join(tempRoot, "services", "shop"));
    expect(() =>
      assertTdkGeneratedPath(tempRoot, "services/shop/api/.autogenerated/Dockerfile.app"),
    ).toThrow(/symbolic link/);
    rmSync(outside, { recursive: true, force: true });
  });
});
