import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

// Mock findProjectRoot to control project root detection
vi.mock("../paths.js", () => ({
  findProjectRoot: vi.fn(),
  getPackageVersion: vi.fn(() => "1.1.0"),
}));

import { AUTOGENERATED_FILE_PATTERNS, SKIP_DIRECTORIES } from "../constants.js";
import { findProjectRoot } from "../paths.js";
import { includes } from "../validation.js";

describe("SKIP_DIRECTORIES", () => {
  it("should skip node_modules", () => {
    expect(includes(SKIP_DIRECTORIES, "node_modules")).toBe(true);
  });

  it("should skip .git", () => {
    expect(includes(SKIP_DIRECTORIES, ".git")).toBe(true);
  });

  it("should skip dist", () => {
    expect(includes(SKIP_DIRECTORIES, "dist")).toBe(true);
  });

  it("should NOT skip regular project directories", () => {
    expect(includes(SKIP_DIRECTORIES, "services")).toBe(false);
    expect(includes(SKIP_DIRECTORIES, "shared")).toBe(false);
    expect(includes(SKIP_DIRECTORIES, "backend")).toBe(false);
    expect(includes(SKIP_DIRECTORIES, "frontend")).toBe(false);
  });

  it("should skip coverage", () => {
    expect(includes(SKIP_DIRECTORIES, "coverage")).toBe(true);
  });

  it("should skip test directories", () => {
    expect(includes(SKIP_DIRECTORIES, "__tests__")).toBe(true);
    expect(includes(SKIP_DIRECTORIES, "test")).toBe(true);
    expect(includes(SKIP_DIRECTORIES, "tests")).toBe(true);
  });

  it("should have consistent skip list", () => {
    // These directories should always be skipped
    const mandatorySkips = ["node_modules", ".git", "dist", "build", "coverage"];
    for (const dir of mandatorySkips) {
      expect(includes(SKIP_DIRECTORIES, dir)).toBe(true);
    }
  });
});

describe("AUTOGENERATED_FILE_PATTERNS", () => {
  it("should include standard generated files", () => {
    expect(AUTOGENERATED_FILE_PATTERNS).toContain("Dockerfile");
    expect(AUTOGENERATED_FILE_PATTERNS).toContain("vite.config.ts");
    expect(AUTOGENERATED_FILE_PATTERNS).toContain("tsconfig.json");
  });

  it("should include docker-compose patterns", () => {
    expect(AUTOGENERATED_FILE_PATTERNS).toContain("docker-compose.yml");
    expect(AUTOGENERATED_FILE_PATTERNS).toContain("docker-compose.yaml");
  });

  it("should include Tiltfile as autogenerated", () => {
    expect(AUTOGENERATED_FILE_PATTERNS).toContain("Tiltfile");
  });

  it("should include build configs", () => {
    expect(AUTOGENERATED_FILE_PATTERNS).toContain("tsconfig.build.json");
  });
});

describe("includes type guard", () => {
  it("should return true for values in readonly array", () => {
    const arr = ["a", "b", "c"] as const;
    expect(includes(arr, "a")).toBe(true);
    expect(includes(arr, "b")).toBe(true);
    expect(includes(arr, "c")).toBe(true);
  });

  it("should return false for values not in readonly array", () => {
    const arr = ["a", "b", "c"] as const;
    expect(includes(arr, "d")).toBe(false);
    expect(includes(arr, "")).toBe(false);
  });

  it("should narrow type correctly", () => {
    const arr = ["node_modules", ".git", "dist"] as const;
    const value: string = "node_modules";
    if (includes(arr, value)) {
      expect(value).toBe("node_modules");
    }
  });
});

describe("discoverResources", () => {
  beforeEach(() => {
    vi.mocked(findProjectRoot).mockReturnValue("/fake/project");
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it("should throw descriptive error when project root not found", async () => {
    vi.mocked(findProjectRoot).mockReturnValue(null);
    const { discoverResources } = await import("../services.js");
    expect(() => discoverResources()).toThrow("Could not find project root");
  });

  it("should error mention Tiltfile in message", async () => {
    vi.mocked(findProjectRoot).mockReturnValue(null);
    const { discoverResources } = await import("../services.js");
    try {
      discoverResources();
      expect.unreachable("Should have thrown");
    } catch (err) {
      expect((err as Error).message).toContain("project root");
      expect((err as Error).message).toContain("Tiltfile");
    }
  });
});

describe("getAllStacks", () => {
  it("should extract unique stack names from resources", async () => {
    const { getAllStacks } = await import("../services.js");
    const resources = [
      {
        name: "svc-a",
        stack: "alpha",
        path: "/tmp",
        configPath: "/tmp/svc-a/service.json",
        config: { appName: "svc-a", appType: "backend" as const },
      },
      {
        name: "svc-b",
        stack: "alpha",
        path: "/tmp",
        configPath: "/tmp/svc-b/service.json",
        config: { appName: "svc-b", appType: "backend" as const },
      },
      {
        name: "svc-c",
        stack: "beta",
        path: "/tmp",
        configPath: "/tmp/svc-c/service.json",
        config: { appName: "svc-c", appType: "frontend" as const },
      },
      { name: "svc-d", path: "/tmp", configPath: "/tmp/svc-d/service.json" },
    ];

    // biome-ignore lint: suspicious/noExplicitAny -- test resource fixture
    const stacks = getAllStacks(resources as any);
    expect(stacks).toEqual(["alpha", "beta"]);
  });

  it("should return empty array when no stacks", async () => {
    const { getAllStacks } = await import("../services.js");
    const stacks = getAllStacks([]);
    expect(stacks).toEqual([]);
  });

  it("should return sorted stack names", async () => {
    const { getAllStacks } = await import("../services.js");
    const resources = [
      {
        name: "svc-a",
        stack: "zeta",
        path: "/tmp",
        configPath: "/tmp/svc-a/service.json",
        config: { appName: "svc-a", appType: "backend" as const },
      },
      {
        name: "svc-b",
        stack: "alpha",
        path: "/tmp",
        configPath: "/tmp/svc-b/service.json",
        config: { appName: "svc-b", appType: "backend" as const },
      },
      {
        name: "svc-c",
        stack: "beta",
        path: "/tmp",
        configPath: "/tmp/svc-c/service.json",
        config: { appName: "svc-c", appType: "frontend" as const },
      },
    ];

    // biome-ignore lint: suspicious/noExplicitAny -- test resource fixture
    const stacks = getAllStacks(resources as any);
    expect(stacks).toEqual(["alpha", "beta", "zeta"]);
  });

  it("should handle resources without stack property", async () => {
    const { getAllStacks } = await import("../services.js");
    const resources = [
      {
        name: "svc-a",
        stack: "alpha",
        path: "/tmp",
        configPath: "/tmp/svc-a/service.json",
        config: { appName: "svc-a", appType: "backend" as const },
      },
      { name: "svc-b", path: "/tmp", configPath: "/tmp/svc-b/service.json" },
      {
        name: "svc-c",
        stack: undefined,
        path: "/tmp",
        configPath: "/tmp/svc-c/service.json",
        config: { appName: "svc-c", appType: "frontend" as const },
      },
    ];

    // biome-ignore lint: suspicious/noExplicitAny -- test resource fixture
    const stacks = getAllStacks(resources as any);
    expect(stacks).toEqual(["alpha"]);
  });
});

describe("discoverStacks with real temp dir", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "tdk-stacks-"));
    vi.mocked(findProjectRoot).mockReturnValue(tmpDir);
  });

  afterEach(() => {
    vi.clearAllMocks();
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("should return empty stacks when no resources", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    const { discoverStacks } = await import("../services.js");
    const stacks = discoverStacks();
    expect(stacks).toEqual([]);
  });

  it("should group resources by stack", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, "services", "product", "svc-a", "backend"), { recursive: true });
    mkdirSync(join(tmpDir, "services", "product", "svc-b", "backend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-a", "service.json"),
      JSON.stringify({ appName: "svc-a", runtime: "bun", stack: "alpha" }),
    );
    writeFileSync(
      join(tmpDir, "services", "product", "svc-b", "service.json"),
      JSON.stringify({ appName: "svc-b", runtime: "bun", stack: "alpha" }),
    );

    const { discoverStacks } = await import("../services.js");
    const stacks = discoverStacks();
    expect(stacks).toHaveLength(1);
    expect(stacks[0].name).toBe("alpha");
    expect(stacks[0].resourceCount).toBe(2);
  });
});

describe("getResourcesForStack with real temp dir", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "tdk-res-stack-"));
    vi.mocked(findProjectRoot).mockReturnValue(tmpDir);
  });

  afterEach(() => {
    vi.clearAllMocks();
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("should return empty array for nonexistent stack", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    const { getResourcesForStack } = await import("../services.js");
    const resources = getResourcesForStack("nonexistent");
    expect(resources).toEqual([]);
  });

  it("should return resources for existing stack", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, "services", "product", "svc-a", "backend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-a", "service.json"),
      JSON.stringify({ appName: "svc-a", runtime: "bun", stack: "alpha" }),
    );

    const { getResourcesForStack } = await import("../services.js");
    const resources = getResourcesForStack("alpha");
    expect(resources).toHaveLength(1);
    expect(resources[0].name).toBe("svc-a");
  });
});

describe("stackExists with real temp dir", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "tdk-exists-"));
    vi.mocked(findProjectRoot).mockReturnValue(tmpDir);
  });

  afterEach(() => {
    vi.clearAllMocks();
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("should return false for nonexistent stack", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    const { stackExists } = await import("../services.js");
    expect(stackExists("nonexistent")).toBe(false);
  });

  it("should return true for existing stack", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, "services", "product", "svc-a", "backend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-a", "service.json"),
      JSON.stringify({ appName: "svc-a", runtime: "bun", stack: "alpha" }),
    );

    const { stackExists } = await import("../services.js");
    expect(stackExists("alpha")).toBe(true);
  });
});

describe("clearMetadataCache", () => {
  beforeEach(() => {
    vi.mocked(findProjectRoot).mockReturnValue("/fake/project");
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it("should be callable without error", async () => {
    const { clearMetadataCache } = await import("../services.js");
    expect(() => clearMetadataCache()).not.toThrow();
  });
});

describe("error message consistency between services and tilt", () => {
  it("should have distinct error messages for missing project root", async () => {
    vi.mocked(findProjectRoot).mockReturnValue(null);
    const { discoverResources } = await import("../services.js");
    const { getTiltfilePath } = await import("../tilt.js");

    try {
      discoverResources();
    } catch (err) {
      expect((err as Error).message).toMatch(/project root/i);
    }

    try {
      getTiltfilePath();
    } catch (err) {
      expect((err as Error).message).toMatch(/TDK project/i);
    }
  });
});

describe("findServiceJsonFiles discovery (temp dir integration)", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), "tdk-svc-json-"));
    // Mock findProjectRoot to return our temp dir
    vi.mocked(findProjectRoot).mockReturnValue(tmpDir);
  });

  afterEach(() => {
    vi.clearAllMocks();
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it("should discover service.json files recursively", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, "services", "product", "svc-a", "backend"), { recursive: true });
    mkdirSync(join(tmpDir, "services", "product", "svc-b", "backend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-a", "service.json"),
      JSON.stringify({ appName: "svc-a", runtime: "bun" }),
    );
    writeFileSync(
      join(tmpDir, "services", "product", "svc-b", "service.json"),
      JSON.stringify({ appName: "svc-b", runtime: "bun" }),
    );

    const { discoverResources } = await import("../services.js");
    const resources = discoverResources();
    expect(resources).toHaveLength(2);
    const names = resources.map((r) => r.name).sort();
    expect(names).toEqual(["svc-a", "svc-b"]);
  });

  it("should skip node_modules directories", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, "node_modules", "some-pkg"), { recursive: true });
    writeFileSync(
      join(tmpDir, "node_modules", "some-pkg", "service.json"),
      JSON.stringify({ appName: "should-skip", runtime: "bun" }),
    );
    mkdirSync(join(tmpDir, "services", "product", "svc-a", "backend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-a", "service.json"),
      JSON.stringify({ appName: "svc-a", runtime: "bun" }),
    );

    const { discoverResources } = await import("../services.js");
    const resources = discoverResources();
    expect(resources).toHaveLength(1);
    expect(resources[0].name).toBe("svc-a");
  });

  it("should skip dot-directories", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, ".hidden"), { recursive: true });
    writeFileSync(
      join(tmpDir, ".hidden", "service.json"),
      JSON.stringify({ appName: "should-skip", runtime: "bun" }),
    );
    mkdirSync(join(tmpDir, "services", "product", "svc-a", "backend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-a", "service.json"),
      JSON.stringify({ appName: "svc-a", runtime: "bun" }),
    );

    const { discoverResources } = await import("../services.js");
    const resources = discoverResources();
    expect(resources).toHaveLength(1);
    expect(resources[0].name).toBe("svc-a");
  });

  it("should skip dist directories", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, "services", "product", "svc-a", "backend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-a", "service.json"),
      JSON.stringify({ appName: "svc-a", runtime: "bun" }),
    );
    mkdirSync(join(tmpDir, "dist"), { recursive: true });
    writeFileSync(
      join(tmpDir, "dist", "service.json"),
      JSON.stringify({ appName: "should-skip-dist", runtime: "bun" }),
    );

    const { discoverResources } = await import("../services.js");
    const resources = discoverResources();
    expect(resources).toHaveLength(1);
    expect(resources[0].name).toBe("svc-a");
  });

  it("should skip build directories", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, "services", "product", "svc-a", "backend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-a", "service.json"),
      JSON.stringify({ appName: "svc-a", runtime: "bun" }),
    );
    mkdirSync(join(tmpDir, "build"), { recursive: true });
    writeFileSync(
      join(tmpDir, "build", "service.json"),
      JSON.stringify({ appName: "should-skip-build", runtime: "bun" }),
    );

    const { discoverResources } = await import("../services.js");
    const resources = discoverResources();
    expect(resources).toHaveLength(1);
    expect(resources[0].name).toBe("svc-a");
  });

  it("should handle service.json with missing required fields", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, "services", "product", "svc-bad", "backend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-bad", "service.json"),
      JSON.stringify({ name: "svc-bad" }),
    );

    const { discoverResources } = await import("../services.js");
    expect(() => discoverResources()).toThrow("Invalid service.json");
  });

  it("should handle service.json with appType instead of runtime", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, "services", "product", "svc-front", "frontend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-front", "service.json"),
      JSON.stringify({ appName: "svc-front", appType: "frontend" }),
    );

    const { discoverResources } = await import("../services.js");
    const resources = discoverResources();
    expect(resources).toHaveLength(1);
    expect(resources[0].config?.appType).toBe("frontend");
  });

  it("should resolve resource paths relative to project root", async () => {
    mkdirSync(join(tmpDir, ".tdk"), { recursive: true });
    writeFileSync(join(tmpDir, ".tdk", "project.json"), JSON.stringify({ version: "2" }));
    mkdirSync(join(tmpDir, "services", "product", "svc-a", "backend"), { recursive: true });
    writeFileSync(
      join(tmpDir, "services", "product", "svc-a", "service.json"),
      JSON.stringify({ appName: "svc-a", runtime: "bun" }),
    );

    const { discoverResources } = await import("../services.js");
    const resources = discoverResources();
    expect(resources[0].path).toBe(join(tmpDir, "services", "product", "svc-a"));
    expect(resources[0].configPath).toBe(
      join(tmpDir, "services", "product", "svc-a", "service.json"),
    );
  });
});
