import { beforeEach, describe, expect, it, vi } from "vitest";
import type { DiscoveredResource, ResourceMetadata, StackMetadata } from "../../types/index.js";
import { applyServiceStates, fetchServiceStates } from "../ui-service-state.js";
import { tiltGetUiResources } from "../up-readiness.js";

vi.mock("../up-readiness.js", async (importOriginal) => ({
  ...(await importOriginal<typeof import("../up-readiness.js")>()),
  tiltGetUiResources: vi.fn(),
}));

function resource(name: string): ResourceMetadata {
  return {
    name,
    type: "backend",
    createdAt: "2026-10-07T00:00:00.000Z",
    lastModified: "2026-10-07T00:00:00.000Z",
    dependencies: [],
    hasDockerfile: true,
    hasTiltfile: false,
    hasDockerCompose: false,
    autogeneratedFiles: [],
    status: "unknown",
  };
}
const stack = (...names: string[]): StackMetadata => ({
  name: "app",
  resourceCount: names.length,
  createdAt: "2026-10-07T00:00:00.000Z",
  lastModified: "2026-10-07T00:00:00.000Z",
  resources: names.map(resource),
  overallStatus: "unknown",
});

describe("applyServiceStates", () => {
  it("puts each service's state, and the reason it is not ready, on the stack", () => {
    const result = applyServiceStates(stack("api", "web"), {
      api: { status: "error", reason: "db failed", blockedBy: ["db"] },
      web: { status: "ready" },
    });
    expect(result.resources.map((r) => [r.name, r.status, r.statusReason])).toEqual([
      ["api", "error", "db failed"],
      ["web", "ready", undefined],
    ]);
  });

  it("derives the stack status from the real service states", () => {
    const allReady = applyServiceStates(stack("api", "web"), {
      api: { status: "ready" },
      web: { status: "ready" },
    });
    expect(allReady.overallStatus).toBe("healthy");
    const oneDown = applyServiceStates(stack("api", "web"), {
      api: { status: "error", reason: "db failed" },
      web: { status: "ready" },
    });
    expect(oneDown.overallStatus).toBe("error");
  });

  it("leaves services Tilt does not list as unknown, and the stack unknown when none is", () => {
    const result = applyServiceStates(stack("api"), {});
    expect(result.resources[0]?.status).toBe("unknown");
    expect(result.overallStatus).toBe("unknown");
  });
});

describe("fetchServiceStates", () => {
  const services = [
    { name: "api", config: { dependsOn: ["db"] } },
    { name: "db", config: {} },
  ] as unknown as DiscoveredResource[];

  beforeEach(() => {
    vi.mocked(tiltGetUiResources).mockReset();
  });

  it("is empty when no Tilt answers", async () => {
    vi.mocked(tiltGetUiResources).mockResolvedValue(null);
    expect(await fetchServiceStates(services, 10350)).toEqual({});
  });

  it("is empty, not a rejection, when asking Tilt throws", async () => {
    vi.mocked(tiltGetUiResources).mockRejectedValue(new Error("spawn failed"));
    await expect(fetchServiceStates(services, 10350)).resolves.toEqual({});
  });

  it("is empty when Tilt's answer cannot be read", async () => {
    vi.mocked(tiltGetUiResources).mockResolvedValue("not json");
    expect(await fetchServiceStates(services, 10350)).toEqual({});
  });

  it("uses the dependsOn from service.json to block a running api on a failed db", async () => {
    vi.mocked(tiltGetUiResources).mockResolvedValue(
      JSON.stringify({
        items: [
          { metadata: { name: "db" }, status: { updateStatus: "error", runtimeStatus: "none" } },
          { metadata: { name: "api" }, status: { updateStatus: "ok", runtimeStatus: "ok" } },
        ],
      }),
    );
    const states = await fetchServiceStates(services, 10399);
    expect(vi.mocked(tiltGetUiResources)).toHaveBeenCalledWith(10399);
    expect(states.api).toMatchObject({ status: "error", blockedBy: ["db"] });
  });
});
