# =============================================================================
# Traefik static (file-provider) route for a deferred (`sablier.deferStart`)
# resource -- see openspec/changes/prioritized-cold-start.
# =============================================================================
# A never-created resource has no container and thus no Docker labels, so its
# route can't come from Traefik's Docker-label discovery the way every other
# resource's does. This generates the file-provider equivalent instead:
# same routing rule as the Docker-label `-project` router (traefik.star's
# get_backend_traefik_labels), but pointed at the wake gateway with a fixed
# LOW priority so the real, Docker-discovered router always wins once the
# container exists (verified empirically -- see design.md D4: at equal
# priority the file-provider router won even when the Docker-discovered
# backend was healthy).
#
# Config for a request travels to the gateway via headers (X-Wake-*), not
# the path/query, so the original request path reaches the real backend
# unchanged once the resource is ready (see wake-gateway/server.ts).

load("./traefik_helpers.star", "project_backend_rule", "build_entrypoints")
load("./traefik_constants.star",
    "TRAEFIK_BACKEND_ENABLE_HTTP",
    "TRAEFIK_BACKEND_ENABLE_HTTPS",
)

STATIC_ROUTE_PRIORITY = 1


def _container_name(compose_project_name, res_name):
    """Docker Compose's own naming convention: <project>-<service>-<replica>.

    Confirmed empirically against a live TDK container (analytics-autogenerated
    -data-governance-api-1) -- see design.md D2 Context. Always replica 1: a
    deferred resource's replica count is unrelated to which single instance
    the wake gateway needs to address."""
    return compose_project_name + "-" + res_name + "-1"


def generate_static_wake_route(
    resource_entry_name,
    compose_project_name,
    manifest,
    internal_port,
    gateway_host,
    gateway_port,
    dependencies=None,
):
    """YAML for one resource's Traefik file-provider dynamic-config entry.

    `dependencies` is a list of (res_name, compose_project_name) tuples for
    the resource's required startup dependencies (D5) -- each may live in a
    different compose project than the resource itself, so the project name
    travels alongside the resource name rather than being assumed shared.

    Written to the directory PlatformDockerConstants.TRAEFIK_DYNAMIC_DIR_REL
    mounts into the standalone Traefik container (traefik_standalone.star).
    """
    dependencies = dependencies or []

    rule = project_backend_rule(manifest, resource_entry_name)
    entrypoints = build_entrypoints(TRAEFIK_BACKEND_ENABLE_HTTP, TRAEFIK_BACKEND_ENABLE_HTTPS)
    router_name = resource_entry_name + "-wake"
    middleware_name = resource_entry_name + "-wake-headers"
    service_name = resource_entry_name + "-wake-gateway"
    container_name = _container_name(compose_project_name, resource_entry_name)
    deps_header = ",".join([
        dep_res_name + "=" + _container_name(dep_project_name, dep_res_name)
        for dep_res_name, dep_project_name in dependencies
    ])

    return """# SYSTEM-GENERATED - DO NOT EDIT (sablier.deferStart static wake route)
http:
  routers:
    {router_name}:
      rule: "{rule}"
      entryPoints:
        - {entrypoint}
      service: {service_name}
      middlewares:
        - {middleware_name}
      priority: {priority}
  middlewares:
    {middleware_name}:
      headers:
        customRequestHeaders:
          X-Wake-Resource: "{resource_entry_name}"
          X-Wake-Container: "{container_name}"
          X-Wake-Deps: "{deps_header}"
          X-Wake-Proxy-Port: "{internal_port}"
  services:
    {service_name}:
      loadBalancer:
        servers:
          - url: "http://{gateway_host}:{gateway_port}"
""".format(
        router_name=router_name,
        rule=rule,
        entrypoint=entrypoints.split(",")[0],
        service_name=service_name,
        middleware_name=middleware_name,
        priority=STATIC_ROUTE_PRIORITY,
        resource_entry_name=resource_entry_name,
        container_name=container_name,
        deps_header=deps_header,
        internal_port=internal_port,
        gateway_host=gateway_host,
        gateway_port=gateway_port,
    )
