# =============================================================================
# Traefik static (file-provider) route for a deferred (`sablier.deferStart`)
# resource -- see openspec/changes/prioritized-cold-start.
# =============================================================================
# A never-created resource has no container and thus no Docker labels, so its
# route can't come from Traefik's Docker-label discovery the way every other
# resource's does. This generates the file-provider equivalent instead:
# same routing rule as the Docker-label `-project` router (traefik.star's
# get_backend_traefik_labels), but pointed at the wake gateway with a fixed
# LOW priority so the real, Docker-discovered router always wins once the
# container exists (verified empirically -- see design.md D4: at equal
# priority the file-provider router won even when the Docker-discovered
# backend was healthy).
#
# Config for a request travels to the gateway via headers (X-Wake-*), not
# the path/query. The route still strips the same `apiPath` prefix the real
# Docker-label `-project` router strips (get_backend_traefik_labels) before
# forwarding -- confirmed live against tdk-erp-system (task 7.2) that a
# backend's app only serves its bare health path (e.g. `/health`), not the
# full `/api/{name}/health` the public route is matched on; without this, the
# gateway's own proxy-through would forward the unstripped path once healthy
# and the app would 404 on it, even though the wake itself succeeded.

load("./traefik_helpers.star", "project_backend_rule", "cli_api_path", "build_entrypoints")
load("./traefik_constants.star",
    "TRAEFIK_BACKEND_ENABLE_HTTP",
    "TRAEFIK_BACKEND_ENABLE_HTTPS",
)

STATIC_ROUTE_PRIORITY = 1


def normalize_abs_path(path):
    """Absolute path with `.`/`..` segments collapsed, or "" for "".

    Tilt's os.path.abspath does not collapse `..` (confirmed:
    abspath("/a/.tdk/.tdk-out/../..") comes back unchanged), and the
    generated Tiltfile's project root is exactly that shape
    (config.main_dir + "/../.."). The gateway's project mount and the compose
    paths in its route headers must match byte-for-byte, so both go through here.
    """
    if not path:
        return ""
    parts = []
    for segment in os.path.abspath(path).split("/"):
        if segment == "" or segment == ".":
            continue
        if segment == "..":
            if parts:
                parts.pop()
            continue
        parts.append(segment)
    return "/" + "/".join(parts)


def _container_name(compose_project_name, res_name):
    """Docker Compose's own naming convention: <project>-<service>-<replica>.

    Confirmed empirically against a live TDK container (analytics-autogenerated
    -data-governance-api-1) -- see design.md D2 Context. Always replica 1: a
    deferred resource's replica count is unrelated to which single instance
    the wake gateway needs to address."""
    return compose_project_name + "-" + res_name + "-1"


def generate_static_wake_route(
    resource_entry_name,
    compose_project_name,
    manifest,
    internal_port,
    gateway_host,
    gateway_port,
    dependencies=None,
    compose_files=None,
    env_file="",
    image="",
):
    """YAML for one resource's Traefik file-provider dynamic-config entry.

    `dependencies` is a list of (res_name, compose_project_name) tuples for
    the resource's required startup dependencies (D5) -- each may live in a
    different compose project than the resource itself, so the project name
    travels alongside the resource name rather than being assumed shared.

    `compose_files` (absolute paths), `env_file` and `image` let the gateway
    create the container itself with `docker compose up --no-build` when the
    image already exists, instead of waiting in Tilt's build queue behind
    `tilt trigger`. Omitted headers make the gateway use `tilt trigger` only.

    Written to the directory PlatformDockerConstants.TRAEFIK_DYNAMIC_DIR_REL
    mounts into the standalone Traefik container (traefik_standalone.star).
    """
    dependencies = dependencies or []

    rule = project_backend_rule(manifest, resource_entry_name)
    api_path = cli_api_path(resource_entry_name, manifest)
    entrypoints = build_entrypoints(TRAEFIK_BACKEND_ENABLE_HTTP, TRAEFIK_BACKEND_ENABLE_HTTPS)
    router_name = resource_entry_name + "-wake"
    headers_middleware_name = resource_entry_name + "-wake-headers"
    strip_middleware_name = resource_entry_name + "-wake-strip"
    service_name = resource_entry_name + "-wake-gateway"
    container_name = _container_name(compose_project_name, resource_entry_name)
    deps_header = ",".join([
        dep_res_name + "=" + _container_name(dep_project_name, dep_res_name)
        for dep_res_name, dep_project_name in dependencies
    ])
    compose_headers = ""
    if compose_files and image:
        compose_headers = (
            '\n          X-Wake-Compose-Project: "' + compose_project_name + '"'
            + '\n          X-Wake-Compose-Files: "' + ",".join(compose_files) + '"'
            + '\n          X-Wake-Env-File: "' + env_file + '"'
            + '\n          X-Wake-Image: "' + image + '"'
        )

    return """# SYSTEM-GENERATED - DO NOT EDIT (sablier.deferStart static wake route)
http:
  routers:
    {router_name}:
      rule: "{rule}"
      entryPoints:
        - {entrypoint}
      service: {service_name}
      middlewares:
        - {strip_middleware_name}
        - {headers_middleware_name}
      priority: {priority}
  middlewares:
    {strip_middleware_name}:
      stripPrefix:
        prefixes:
          - "{api_path}"
    {headers_middleware_name}:
      headers:
        customRequestHeaders:
          X-Wake-Resource: "{resource_entry_name}"
          X-Wake-Container: "{container_name}"
          X-Wake-Deps: "{deps_header}"
          X-Wake-Proxy-Port: "{internal_port}"{compose_headers}
  services:
    {service_name}:
      loadBalancer:
        servers:
          - url: "http://{gateway_host}:{gateway_port}"
""".format(
        router_name=router_name,
        rule=rule,
        entrypoint=entrypoints.split(",")[0],
        service_name=service_name,
        strip_middleware_name=strip_middleware_name,
        headers_middleware_name=headers_middleware_name,
        api_path=api_path,
        priority=STATIC_ROUTE_PRIORITY,
        resource_entry_name=resource_entry_name,
        container_name=container_name,
        deps_header=deps_header,
        internal_port=internal_port,
        compose_headers=compose_headers,
        gateway_host=gateway_host,
        gateway_port=gateway_port,
    )
