# =============================================================================
# 🗃️ ORCHESTRATOR APPLY - MIGRATOR ORCHESTRATION
# =============================================================================
# BLOCKER FIX #2: Sequential migration execution to prevent race conditions
# =============================================================================

# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load('../../../platform/docker/index.star', 'Docker')

load('../../../platform/docker/generators/golden_docker_generator_v2.star', 'L4_generate_orchestrator')


def _find_backend_resource_path(resource_config):
    resource_path = resource_config.get('path', '')
    if not resource_path:
        return None
    backend_resource_path = None

    for res in resource_config.get('resources', []):
        if res.get('frontend', False):
            continue

        candidate = resource_path + '/' + res['name']
        prisma_check = local("test -d " + candidate + "/prisma && echo yes || echo no", quiet=True)
        prisma_check_stdout = getattr(prisma_check, "stdout", prisma_check)
        has_prisma = str(prisma_check_stdout).strip() == 'yes'

        if has_prisma:
            return candidate

        if backend_resource_path == None:
            backend_resource_path = candidate

    return backend_resource_path


def register_migrators(resource_config, ctx, runtime_flags, compose_project_name):
    should_enable = ctx['should_enable']
    write_file = ctx['write_file']
    resource_name = resource_config.get('name', '')
    resource_path = resource_config.get('path', '')

    if not resource_name:
        print("⚠️  Skipping migrator registration for service without name")
        return

    if not resource_path:
        # Silently skip migrator registration for services without paths
        return

    if not resource_config.get('has_migrator', False):
        return
    if not should_enable('database-management'):
        return

    backend_resource_path = _find_backend_resource_path(resource_config)
    dockerfile_res_path = backend_resource_path if backend_resource_path else resource_path

    df_contents = L4_generate_orchestrator(
        dockerfile_res_path,
        res_type='migrator',
        resource_name=resource_name,
        use_nginx=False,
        port=3000,
        target_path='/app/dist',
        build_cmd='echo "No build needed for migrator"',
        cmd='bun run db:migrate',
        use_infisical=False,
        use_shared_libs=True,
        use_prisma=True,
        use_golden=should_enable('golden-image'),
    )
    write_file(dockerfile_res_path + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/Dockerfile.migrator.autogenerated", df_contents)

    migrator_dockerignore_content = Docker.generate_dockerignore(dockerfile_res_path, 'migrator')
    write_file(
        dockerfile_res_path + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/Dockerfile.migrator.autogenerated.dockerignore",
        migrator_dockerignore_content,
    )

    Docker.migrator_compose(
        resource_path=resource_path,
        resource_name=resource_name,
        dockerfile_path=dockerfile_res_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/Dockerfile.migrator.autogenerated',
        write_fn=write_file,
    )
    docker_compose(
        resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/docker-compose.migrator.autogenerated.yml',
        project_name=compose_project_name,
    )

    migrator_names = resource_config.get('migrator_names', [resource_name + '-db-migrator'])
    for migrator_name in migrator_names:
        # =============================================================================
        # BLOCKER FIX #2: Sequential migration dependencies prevent race conditions
        # =============================================================================
        # Each migrator depends on postgres, its own provisioned DB, golden image,
        # AND the previous migrator to ensure sequential execution
        migrator_db_deps = ['postgres', 'provision-db-' + resource_name]
        if should_enable('golden-image') and ctx.get('golden_image_resource'):
            migrator_db_deps.append(ctx['golden_image_resource'])
        
        # Add sequential dependency on previous migrator to prevent parallel execution
        # Use ctx to track sequence (mutable dict passed from caller)
        migrator_index = ctx.setdefault('migrator_sequence', {})
        previous_migrator = _get_previous_migrator(resource_name, migrator_index)
        if previous_migrator:
            migrator_db_deps.append(previous_migrator)
            print("🔗 Sequential migration: " + migrator_name + " will run after " + previous_migrator)

        dc_resource(
            migrator_name,
            labels=['app.' + resource_name, 'migrator'],
            resource_deps=migrator_db_deps,
            auto_init=runtime_flags['auto_init_migrators'],
        )


# =============================================================================
# BLOCKER FIX #2: Migration sequencing tracker
# =============================================================================
# Pass migrator sequence via ctx to avoid frozen module-level state
# The caller initializes ctx['migrator_sequence'] = {} before calling register_migrators

def _get_previous_migrator(current_service, migrator_index):
    """
    Get the previous migrator in sequence for dependency chaining.
    Returns the migrator name that should complete before this one starts.
    """
    if current_service not in migrator_index:
        migrator_index[current_service] = len(migrator_index)
    
    idx = migrator_index[current_service]
    if idx > 0:
        # Find the service with index idx - 1
        for svc, svc_idx in migrator_index.items():
            if svc_idx == idx - 1:
                return svc + '-db-migrator'
    return None


MigratorOrchestration = struct(
    register = register_migrators,
)
