#!/usr/bin/env bash
# =============================================================================
# Library Build & Publish with Caching
# =============================================================================
# Intelligently builds and publishes libraries only when needed
# =============================================================================

set -euo pipefail

LIB_PATH="${1:?Library path required}"
REGISTRY="${2:-http://localhost:4873}"
PACKAGE_NAME="${3:?Package name required}"
CONSUMER_PATHS="${4:-}"  # Optional: comma-separated list of consumer paths

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

if [[ "${LIB_PATH}" = /* ]]; then
  LIB_ABS_PATH="${LIB_PATH}"
else
  LIB_ABS_PATH="${WORKSPACE_ROOT}/${LIB_PATH}"
fi

CACHE_DIR="${LIB_ABS_PATH}/.tilt-cache"

# Check if rebuild/republish is needed
if ! "${SCRIPT_DIR}/check-lib-publish.sh" "${LIB_ABS_PATH}" "${REGISTRY}"; then
  # Script exited with 1 (skip rebuild)
  exit 0
fi

# Rebuild needed - run full pipeline
cd "${LIB_ABS_PATH}"

EFFECTIVE_REGISTRY="${REGISTRY%/}"
if ! curl -sf --max-time 3 "${EFFECTIVE_REGISTRY}/-/ping" >/dev/null 2>&1; then
  for fallback_registry in "http://localhost:4873" "http://verdaccio.localhost:4873"; do
    if curl -sf --max-time 3 "${fallback_registry}/-/ping" >/dev/null 2>&1; then
      echo "⚠️  Registry ${EFFECTIVE_REGISTRY} is unreachable, falling back to ${fallback_registry}"
      EFFECTIVE_REGISTRY="${fallback_registry}"
      break
    fi
  done
fi

echo "📦 Installing dependencies..."
NPMRC_FOR_INSTALL=""
if [[ "${EFFECTIVE_REGISTRY}" == *"host.docker.internal"* ]]; then
  if [[ -f "${LIB_ABS_PATH}/autogenerated/.npmrc.docker.autogenerated" ]]; then
    NPMRC_FOR_INSTALL="${LIB_ABS_PATH}/autogenerated/.npmrc.docker.autogenerated"
  elif [[ -f "${LIB_ABS_PATH}/.npmrc.docker" ]]; then
    NPMRC_FOR_INSTALL="${LIB_ABS_PATH}/.npmrc.docker"
  fi
fi

if [[ -z "${NPMRC_FOR_INSTALL}" ]]; then
  if [[ -f "${LIB_ABS_PATH}/autogenerated/.npmrc.autogenerated" ]]; then
    NPMRC_FOR_INSTALL="${LIB_ABS_PATH}/autogenerated/.npmrc.autogenerated"
  elif [[ -f "${LIB_ABS_PATH}/.npmrc" ]]; then
    NPMRC_FOR_INSTALL="${LIB_ABS_PATH}/.npmrc"
  elif [[ -f "${LIB_ABS_PATH}/.npmrc.docker" ]]; then
    NPMRC_FOR_INSTALL="${LIB_ABS_PATH}/.npmrc.docker"
  fi
fi

run_bun_install_with_retry() {
  local npmrc_path="${1:-}"
  local registry="${2:-}"
  local attempt=1
  local max_attempts=3
  local exit_code=1
  local install_env=()

  if [[ -n "${registry}" ]]; then
    install_env+=("npm_config_registry=${registry}")
    if [[ "${PACKAGE_NAME}" == @*/* ]]; then
      local package_scope="${PACKAGE_NAME%%/*}"
      install_env+=("npm_config_${package_scope}:registry=${registry}")
    fi
  fi

  while [[ ${attempt} -le ${max_attempts} ]]; do
    set +e
    if [[ -n "${npmrc_path}" ]]; then
      env "${install_env[@]}" NPM_CONFIG_USERCONFIG="${npmrc_path}" bun install
      exit_code=$?
    else
      env "${install_env[@]}" bun install
      exit_code=$?
    fi
    set -e

    if [[ ${exit_code} -eq 0 ]]; then
      return 0
    fi

    if [[ ${attempt} -lt ${max_attempts} ]]; then
      echo "⚠️  bun install failed (attempt ${attempt}/${max_attempts}), retrying..."
      sleep $((attempt * 2))
    fi

    attempt=$((attempt + 1))
  done

  return ${exit_code}
}

set +e
run_bun_install_with_retry "${NPMRC_FOR_INSTALL}" "${EFFECTIVE_REGISTRY}"
INSTALL_EXIT_CODE=$?
set -e

if [[ ${INSTALL_EXIT_CODE} -ne 0 ]]; then
  RETRY_REGISTRY=""
  RETRY_NPMRC=""
  for fallback_registry in "http://localhost:4873" "http://verdaccio.localhost:4873" "https://registry.npmjs.org"; do
    if [[ "${fallback_registry}" != "${EFFECTIVE_REGISTRY}" ]] && curl -sf --max-time 3 "${fallback_registry}/-/ping" >/dev/null 2>&1; then
      RETRY_REGISTRY="${fallback_registry}"
      break
    fi
  done

  if [[ -n "${RETRY_REGISTRY}" ]]; then
    if [[ "${RETRY_REGISTRY}" == *"host.docker.internal"* ]]; then
      if [[ -f "${LIB_ABS_PATH}/autogenerated/.npmrc.docker.autogenerated" ]]; then
        RETRY_NPMRC="${LIB_ABS_PATH}/autogenerated/.npmrc.docker.autogenerated"
      elif [[ -f "${LIB_ABS_PATH}/.npmrc.docker" ]]; then
        RETRY_NPMRC="${LIB_ABS_PATH}/.npmrc.docker"
      fi
    fi
    if [[ -z "${RETRY_NPMRC}" ]]; then
      if [[ -f "${LIB_ABS_PATH}/autogenerated/.npmrc.autogenerated" ]]; then
        RETRY_NPMRC="${LIB_ABS_PATH}/autogenerated/.npmrc.autogenerated"
      elif [[ -f "${LIB_ABS_PATH}/.npmrc" ]]; then
        RETRY_NPMRC="${LIB_ABS_PATH}/.npmrc"
      elif [[ -f "${LIB_ABS_PATH}/.npmrc.docker" ]]; then
        RETRY_NPMRC="${LIB_ABS_PATH}/.npmrc.docker"
      fi
    fi

    echo "⚠️  bun install failed, retrying with fallback registry ${RETRY_REGISTRY}"
    run_bun_install_with_retry "${RETRY_NPMRC}" "${RETRY_REGISTRY}"
    EFFECTIVE_REGISTRY="${RETRY_REGISTRY}"
  else
    exit ${INSTALL_EXIT_CODE}
  fi
fi

echo "🔨 Building package..."
if grep -q '"build":' package.json; then
  bun run build
else
  if [ -f ".autogenerated/tsconfig.autogenerated.json" ]; then
    bunx tsc -p .autogenerated/tsconfig.autogenerated.json --declaration --declarationMap --rootDir src --outDir dist
  else
    bunx tsc -p tsconfig.json --declaration --declarationMap --rootDir src --outDir dist
  fi
fi

echo "🔗 Linking package..."
bun link

echo "📤 Publishing to registry..."
# npm may prefer scoped registry config over --registry, so force both default
# and scope-specific registry to avoid publishing to a different host.
NPM_CONFIG_OVERRIDES=("npm_config_registry=${EFFECTIVE_REGISTRY}")
if [[ "${PACKAGE_NAME}" == @*/* ]]; then
  PACKAGE_SCOPE="${PACKAGE_NAME%%/*}"
  NPM_CONFIG_OVERRIDES+=("npm_config_${PACKAGE_SCOPE}:registry=${EFFECTIVE_REGISTRY}")
fi

# Try to unpublish first (ignore errors)
env "${NPM_CONFIG_OVERRIDES[@]}" npm unpublish --force --registry "${EFFECTIVE_REGISTRY}" >/dev/null 2>&1 || true
env "${NPM_CONFIG_OVERRIDES[@]}" npm publish --registry "${EFFECTIVE_REGISTRY}" --fetch-retries=1 --fetch-timeout=10000 --fetch-retry-mintimeout=1000 --fetch-retry-maxtimeout=5000

# Save source hash to mark successful build
mkdir -p "${CACHE_DIR}"
PACKAGE_JSON="${LIB_ABS_PATH}/package.json"
TSCONFIG_PATH="${LIB_ABS_PATH}/.autogenerated/tsconfig.autogenerated.json"
if [ -f "${TSCONFIG_PATH}" ]; then
  find "${LIB_ABS_PATH}/src" "${PACKAGE_JSON}" "${TSCONFIG_PATH}" -type f 2>/dev/null | \
    sort | \
    xargs cat 2>/dev/null | \
    shasum -a 256 | \
    awk '{print $1}' > "${CACHE_DIR}/source-hash.txt"
else
  find "${LIB_ABS_PATH}/src" "${PACKAGE_JSON}" "${LIB_ABS_PATH}/tsconfig.json" -type f 2>/dev/null | \
    sort | \
    xargs cat 2>/dev/null | \
    shasum -a 256 | \
    awk '{print $1}' > "${CACHE_DIR}/source-hash.txt"
fi

# Link to consumers if specified
if [[ -n "${CONSUMER_PATHS}" ]]; then
  IFS=',' read -ra CONSUMERS <<< "${CONSUMER_PATHS}"
  for consumer in "${CONSUMERS[@]}"; do
    if [[ -n "${consumer}" ]]; then
      echo "🔗 Linking to consumer: ${consumer}"
      (cd "${WORKSPACE_ROOT}/${consumer}" && bun link "${PACKAGE_NAME}") || true
    fi
  done
fi

echo "✅ ${PACKAGE_NAME} build and publish complete"
