#!/usr/bin/env bash
# =============================================================================
# Library Build/Publish Cache Checker
# =============================================================================
# Checks if a library needs to be rebuilt and republished to Verdaccio.
# The SOURCE HASH is the primary gate — if sources haven't changed since the
# last successful build+publish, skip entirely (regardless of registry state).
# Returns: 0 if rebuild needed, 1 if can skip
# =============================================================================

set -euo pipefail

LIB_PATH="${1:?Library path required}"
REGISTRY="${2:-http://localhost:4873}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

if [[ "${LIB_PATH}" = /* ]]; then
  LIB_ABS_PATH="${LIB_PATH}"
else
  LIB_ABS_PATH="${WORKSPACE_ROOT}/${LIB_PATH}"
fi

CACHE_DIR="${LIB_ABS_PATH}/.tilt-cache"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Ensure cache directory exists
mkdir -p "${CACHE_DIR}"

# Read package.json to get name and version
PACKAGE_JSON="${LIB_ABS_PATH}/package.json"
if [[ ! -f "${PACKAGE_JSON}" ]]; then
  echo -e "${YELLOW}⚠️  package.json not found at ${PACKAGE_JSON}${NC}"
  exit 0  # Needs rebuild
fi

PACKAGE_NAME=$(grep -o '"name"[[:space:]]*:[[:space:]]*"[^"]*"' "${PACKAGE_JSON}" | sed 's/"name"[[:space:]]*:[[:space:]]*"\([^"]*\)"/\1/')
PACKAGE_VERSION=$(grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' "${PACKAGE_JSON}" | sed 's/"version"[[:space:]]*:[[:space:]]*"\([^"]*\)"/\1/')

# ---------------------------------------------------------------------------
# PRIMARY CHECK: Source hash comparison (works offline, no registry needed)
# ---------------------------------------------------------------------------
SOURCE_HASH_FILE="${CACHE_DIR}/source-hash.txt"

# Calculate hash of source files (src/, package.json, tsconfig.json)
TSCONFIG_PATH="${LIB_ABS_PATH}/.autogenerated/tsconfig.autogenerated.json"
if [ -f "${TSCONFIG_PATH}" ]; then
  CURRENT_HASH=$(find "${LIB_ABS_PATH}/src" "${PACKAGE_JSON}" "${TSCONFIG_PATH}" -type f 2>/dev/null | \
    sort | \
    xargs cat 2>/dev/null | \
    shasum -a 256 | \
    awk '{print $1}')
else
  CURRENT_HASH=$(find "${LIB_ABS_PATH}/src" "${PACKAGE_JSON}" "${LIB_ABS_PATH}/tsconfig.json" -type f 2>/dev/null | \
    sort | \
    xargs cat 2>/dev/null | \
    shasum -a 256 | \
    awk '{print $1}')
fi

if [[ -f "${SOURCE_HASH_FILE}" ]]; then
  CACHED_HASH=$(cat "${SOURCE_HASH_FILE}")

  if [[ "${CURRENT_HASH}" == "${CACHED_HASH}" ]]; then
    # Source unchanged since last successful build+publish — skip
    echo -e "${GREEN}✓ ${PACKAGE_NAME}@${PACKAGE_VERSION} sources unchanged (hash match) - skipping build${NC}"
    exit 1  # Skip rebuild
  fi
fi

# ---------------------------------------------------------------------------
# Hash mismatch or no cached hash — rebuild needed
# ---------------------------------------------------------------------------
if [[ -f "${SOURCE_HASH_FILE}" ]]; then
  echo -e "${YELLOW}⚠️  ${PACKAGE_NAME}@${PACKAGE_VERSION} sources changed — rebuilding${NC}"
else
  echo -e "${YELLOW}⚠️  ${PACKAGE_NAME}@${PACKAGE_VERSION} no cached hash found — initial build${NC}"
fi

echo "🔨 Building ${PACKAGE_NAME}@${PACKAGE_VERSION}..."
exit 0  # Needs rebuild
