"""
Prisma Runtime Layers - L4 Prisma Runtime Copy and Resolution

Public API (preserved for backward compatibility with l4_runtime_layers.star):
  prisma_runtime_copy(res_path)       – copy .prisma artifacts from build stage
  prisma_cli_runtime_copy(res_path)   – copy the pinned Prisma CLI into the runtime
  prisma_bun_symlink_fix()            – fix Bun linker resolution for .prisma/client
  prisma_config_copy(res_path)        – copy prisma.config.ts (Prisma v7)
  L4_generate_migrator_runtime(...)   – full migrator stage (delegates to sub-modules)

Internal heavy-lifting is split across:
  filesystem_setup.star   – apk, dirs, permissions, engines symlink
  shared docker template  – generic migrate.sh entrypoint script
"""

load('../l1_base_layers.star', 'BUN_BASE')
load('../l2_dependency_layers.star', 'normalize_res_path')
load('../../../../../../discovery/config.star', 'GLOBAL_CONFIG')
load('../../../../tilt/manifest/constants.star', 'AUTOGENERATED_CONFIG_PATHS')
load('./filesystem_setup.star', 'migrator_filesystem_setup')
load(
    './constants.star',
    'APP_DIR',
    'BUN_USER',
    'L3_MIGRATION_BUILD_STAGE',
    'DEFAULT_GOLDEN_L4_MIGRATOR_IMAGE',
    'MIGRATE_SH_ABS_PATH',
    'PRISMA_CONFIG_WORKDIR_PATH',
    'PRISMA_DOT_DIR_REL_PATH',
    'PRISMA_DIR_NAME',
    'PRISMA_PACKAGE_REL_PATH',
    'ROOT_USER',
    'app_resource_dir',
    'resource_node_modules_dir',
)

_docker_cfg = GLOBAL_CONFIG['docker']
GOLDEN_L4_MIGRATOR_IMAGE = _docker_cfg.get('golden_l4_migrator_image', DEFAULT_GOLDEN_L4_MIGRATOR_IMAGE)
MIGRATE_SH_TEMPLATE_PATH = "shared-platform-engineering/docker-templates/migrate.sh"


# ---------------------------------------------------------------------------
# Small copy/fix helpers (used by l4_runtime_layers.star for backend runtime)
# ---------------------------------------------------------------------------

def prisma_runtime_copy(res_path):
    """
    Copy .prisma generated client and prisma schema from the build stage.

    Args:
        res_path: Service directory relative to /app (e.g. 'services/product/users/...')
    """
    base = app_resource_dir(res_path)
    return (
        "COPY --from=l3_backend_build " + base + "/" + PRISMA_DOT_DIR_REL_PATH + " ./" + PRISMA_DOT_DIR_REL_PATH + "\n"
        + "COPY --from=l3_backend_build " + base + "/" + PRISMA_DIR_NAME + " ./" + PRISMA_DIR_NAME + "\n"
    )


def prisma_cli_runtime_copy(res_path):
    """
    Copy the pinned Prisma CLI package into the backend runtime image.

    The runtime node_modules come from l3_production_purger, which runs
    `bun install --production` and then deletes every `.bin` directory, so the
    Prisma CLI (a devDependency) is absent.  The entrypoint's auto-migration
    would then fall back to `bunx prisma`, which downloads prisma@latest from
    npm on every container start – slow at best, and a boot hang that fails the
    healthcheck (and so blocks Traefik routing) on a slow network.

    l3_migration_build already installs the CLI at the exact version pinned in
    package.json, so reuse that instead of fetching at runtime.

    Args:
        res_path: Service directory relative to /app (e.g. 'services/app/dashboard-api')
    """
    base = resource_node_modules_dir(res_path)
    return (
        "# Prisma CLI at the version pinned in package.json - the entrypoint runs\n"
        + "# migrations with it instead of `bunx prisma`, which would fetch prisma@latest.\n"
        + "COPY --from=" + L3_MIGRATION_BUILD_STAGE + " " + base + "/" + PRISMA_DIR_NAME
        + " ./" + PRISMA_PACKAGE_REL_PATH + "\n"
    )


def prisma_bun_symlink_fix():
    """
    Symlink .prisma/client into every Bun linker path so runtime imports resolve.

    Bun hoists @prisma/client under node_modules/.bun/@prisma+client*/node_modules/
    and looks for .prisma relative to that path.  The loop below covers all versions
    that may be present.
    """
    return (
        "# Fix Bun module resolution: .prisma/client must be reachable from .bun/ linker paths\n"
        + "USER " + ROOT_USER + "\n"
        + "COPY shared-platform-engineering/docker-templates/prisma-bun-client-link-fix.sh /usr/local/bin/prisma-bun-client-link-fix.sh\n"
        + "RUN chmod +x /usr/local/bin/prisma-bun-client-link-fix.sh && /usr/local/bin/prisma-bun-client-link-fix.sh\n"
        + "USER " + BUN_USER + "\n"
    )


def prisma_config_copy(res_path):
    """
    Copy the auto-generated prisma.config.ts into the WORKDIR (required by Prisma v7).

    Args:
        res_path: Service directory relative to workspace root
    """
    # Normalize res_path for Docker COPY (must be relative to build context)
    res_path_rel = normalize_res_path(res_path)
    return "COPY " + res_path_rel + "/" + AUTOGENERATED_CONFIG_PATHS['prisma'] + " " + PRISMA_CONFIG_WORKDIR_PATH + "\n"


# ---------------------------------------------------------------------------
# Migrator stage builder
# ---------------------------------------------------------------------------

def _migrator_artifact_copies(res_path):
    """
    Runtime setup for migrator:
      1. Copy schema from l3 migration build stage
      2. Copy resolved node_modules from l3 migration build stage

    This avoids Bun lockfile/frozen-lockfile edge cases in the l4 runtime image
    while still keeping migrator logic simple (no pruner stage).
    """
    app_res_path = app_resource_dir(res_path)
    base = resource_node_modules_dir(res_path)
    return (
        "# Copy migration schema + resolved deps from l3 stage\n"
        + "COPY --from=l3_migration_build " + app_res_path + "/" + PRISMA_DIR_NAME + " ./" + PRISMA_DIR_NAME + "\n"
        + "COPY --from=l3_migration_build " + base + " ./node_modules\n"
    )


def _migrate_script_copy_block():
    """
    Keep Dockerfile concise by copying the shared migrate entrypoint script
    instead of inlining a long heredoc.
    """
    return (
        "# Provide the migrate entrypoint\n"
        + "COPY " + MIGRATE_SH_TEMPLATE_PATH + " " + MIGRATE_SH_ABS_PATH + "\n"
        + "RUN chmod +x " + MIGRATE_SH_ABS_PATH + "\n"
    )


def L4_generate_migrator_runtime(res_path, resource_name = 'migrator', use_golden = True):
    """
    Generate the complete l4_migrator_runtime Dockerfile stage.

    The stage:
      1. Copies Prisma artifacts from l3_migration_build
      2. Writes prisma.config.ts, fixes permissions, symlinks engines (filesystem_setup)
      3. Installs Alpine utilities (curl, jq, nc) needed at runtime
      4. Copies and chmod's /app/migrate.sh from shared docker templates
      5. Sets ENTRYPOINT to migrate.sh

    Args:
        res_path:     Service directory relative to /app
        resource_name: Used in RESOURCE_NAME env and Infisical secret path
        use_golden:   Always True – golden image is always preferred
    """
    # Golden image is mandatory – it ships Prisma + Infisical pre-built.
    base_image = GOLDEN_L4_MIGRATOR_IMAGE

    return (
        "# ---- L4: migrator_runtime ----\n"
        + "FROM " + base_image + " AS l4_migrator_runtime\n"
        + "WORKDIR " + APP_DIR + "\n"
        + "# Build argument to skip Infisical setup (for local dev / fast builds)\n"
        + "ARG SKIP_INFISICAL_SETUP=0\n"
        + "ENV NODE_ENV=production RESOURCE_NAME=" + resource_name + "\n"
        + _migrator_artifact_copies(res_path)
        + "USER " + ROOT_USER + "\n"
        + migrator_filesystem_setup()
        + "USER " + ROOT_USER + "\n"
        + _migrate_script_copy_block()
        # Migrators are one-shot jobs; they should not inherit long-running
        # service healthchecks (e.g. HTTP probes on localhost:3000) from base layers.
        + "HEALTHCHECK NONE\n"
        + "USER " + BUN_USER + "\n"
        + "ENTRYPOINT [\"" + MIGRATE_SH_ABS_PATH + "\"]\n"
        + "\nFROM l4_migrator_runtime AS migrator\n"
        + "FROM l4_migrator_runtime AS production\n"
        + "FROM l4_migrator_runtime AS development\n"
    )

GLOBAL_CONFIG = {}
