# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


"""
Prisma Build Layers - L3 Prisma Client Generation and Migration Engine

Encapsulates all Prisma-related Dockerfile instructions for the build stage:
- Client generation (`bunx prisma generate`)
- Output normalization (generated-client ↔ node_modules/.prisma/client)
- Default module shim for Prisma v7 / @prisma/client compatibility
- Migration engine stage for Prisma migrate deploy
"""

load('../l1_base_layers.star', 'BUN_BASE')
load('../l2_dependency_layers.star', 'normalize_res_path')
load('../../../../../../discovery/config.star', 'GLOBAL_CONFIG')
load('../../../../tilt/manifest/constants.star', 'AUTOGENERATED_CONFIG_PATHS')

load(
    './constants.star',
    'APP_BUN_STORE_DIR',
    'DEFAULT_GOLDEN_L3_MIGRATOR_IMAGE',
    'NODE_MODULES_DIR',
    'PRISMA_CONFIG_WORKDIR_PATH',
    'PRISMA_DIR_NAME',
    'PRISMA_GENERATE_RUN',
    'PRISMA_PACKAGE_NODE_MODULES_REL_PATH',
    'PRISMA_SCHEMA_PATH',
    'app_resource_dir',
    'prisma_normalize_output_block',
)

_docker_cfg = GLOBAL_CONFIG['docker']
GOLDEN_L3_MIGRATOR_IMAGE = _docker_cfg.get('golden_l3_migrator_image', DEFAULT_GOLDEN_L3_MIGRATOR_IMAGE)


def prisma_copy_instructions(res_path, has_prisma_config = False):
    """
    Generate Dockerfile COPY instructions for Prisma schema and config.

    Args:
        res_path: Resource path (service directory)
        has_prisma_config: Whether prisma.config.ts exists (Prisma v7)

    Returns:
        Dockerfile content string for copying Prisma files
    """
    # Normalize res_path for Docker COPY (must be relative to build context)
    res_path_rel = normalize_res_path(res_path)
    
    parts = "COPY " + res_path_rel + "/" + PRISMA_DIR_NAME + " ./" + PRISMA_DIR_NAME + "\n"
    if has_prisma_config:
        # Prisma v7 requires prisma.config.ts in CWD for correct client generation
        parts += "COPY " + res_path_rel + "/" + AUTOGENERATED_CONFIG_PATHS['prisma'] + " " + PRISMA_CONFIG_WORKDIR_PATH + "\n"
    return parts


def prisma_generate_instructions():
    """
    Generate Dockerfile RUN instruction for Prisma client generation.

    Returns:
        Dockerfile content string that runs `bunx prisma generate`
    """
    return PRISMA_GENERATE_RUN


def prisma_normalize_output():
    """
    Generate Dockerfile instructions to normalize Prisma output for both
    import styles: ../generated-client and node_modules/.prisma/client.

    Also creates a default.js shim required by @prisma/client v7 which
    resolves `.prisma/client/default` at runtime.

    Returns:
        Dockerfile content string for Prisma output normalization
    """
    return prisma_normalize_output_block(include_generated_client_export = True)


def L3_generate_migration_engine(res_path, use_golden = True):
    """
    Generate the migration engine layer for Prisma database migrations.

    Args:
        res_path: Resource path (service directory)
        use_golden: Whether to use golden L3-migrator image (default: True)

    Returns:
        Dockerfile content string for the l3_migration_build stage
    """
    # Normalize res_path for Docker COPY (must be relative to build context)
    res_path_rel = normalize_res_path(res_path)
    
    # Use golden L3-migrator image if enabled (Prisma pre-installed)
    base_image = GOLDEN_L3_MIGRATOR_IMAGE if use_golden else BUN_BASE
    app_res_path = app_resource_dir(res_path)

    return (
        "# ---- L3: migration_engine ----\n"
        + "FROM " + base_image + " AS l3_migration_build\n"
        + "WORKDIR " + app_res_path + "\n"
        + "# Copy manifest files for dependency installation\n"
        + "COPY " + res_path_rel + "/package.json ./package.json\n"
        + "COPY " + res_path_rel + "/" + PRISMA_DIR_NAME + " ./" + PRISMA_DIR_NAME + "\n"
        + "COPY " + res_path_rel + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/.npmrc.docker.autogenerated .npmrc\n"
        + "COPY " + res_path_rel + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/bunfig.docker.autogenerated.toml ./bunfig.toml\n"
        + "COPY bun.lock* ./\n"
        + "# Install runtime deps only for migrator image (skip test/dev toolchain)\n"
        + "# NOTE: keep bunfig.toml (it carries the @beauty-crm/@tdk-landscape registry\n"
        + "# scopes pointing at Verdaccio) - deleting it forces scoped packages to fall\n"
        + "# back to the public npm registry and fail with ConnectionRefused/404.\n"
        + "RUN --mount=type=cache,target=/cache/bun,sharing=shared rm -f bun.lock bun.lockb && env -u CI BUN_CONFIG_FROZEN_LOCKFILE=false BUN_TMPDIR=/tmp BUN_INSTALL=/tmp/bun-install bun install --production --no-frozen-lockfile --concurrent-scripts --cache-dir=/cache/bun\n"
        + "# Prisma CLI is often in devDependencies; install it explicitly without mutating manifest files\n"
        + "RUN --mount=type=cache,target=/cache/bun,sharing=shared PRISMA_VERSION=$(sed -n 's/.*\"prisma\"[[:space:]]*:[[:space:]]*\"[~^]*\\([^\"]*\\)\".*/\\1/p' package.json | head -n 1) && [ -n \"$PRISMA_VERSION\" ] && BUN_TMPDIR=/tmp BUN_INSTALL=/tmp/bun-install bun add --no-save --exact prisma@\"$PRISMA_VERSION\" --cache-dir=/cache/bun\n"
        + "# Generate Prisma client and normalize output location for runtime compatibility\n"
        + PRISMA_GENERATE_RUN
        + prisma_normalize_output_block(include_generated_client_export = False)
        + "RUN mkdir -p " + PRISMA_PACKAGE_NODE_MODULES_REL_PATH + "\n"
        + "RUN test -f " + PRISMA_SCHEMA_PATH + "\n"
    )

GLOBAL_CONFIG = {}
