import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import chalk from "chalk";
import { Command } from "commander";
import { confirmOrCancel } from "../utils/command-helpers.js";
import { runCommand } from "../utils/errors.js";
import { findProjectRoot } from "../utils/paths.js";

// Same location `tdk up` hands to Tilt (see getTiltfilePath in utils/tilt.ts), relative to the project root.
export const TILTFILE_RELATIVE_PATH = ".tdk/.tdk-out/Tiltfile";
export const TILT_UP_COMMAND = `tilt up -f ${TILTFILE_RELATIVE_PATH} -- --focus=<stack>`;

export const EJECTED_CONTENT = `# Ejected from TDK

\`tdk eject\` wrote this file and nothing else. It did not copy, move or generate anything, and it did
not remove TDK. What exists is what TDK had already generated, and that is still TDK-owned output.

## Where the generated files are

- \`.tdk/.tdk-out/\` holds the Tiltfile and the engine it loads (\`tdk-cli-ext/\`). It is git-ignored.
  \`tdk config regenerate\` rewrites the master files in it.
- The per-service Compose files (\`services/<stack>/<name>/.autogenerated/\`), the golden-layer
  Dockerfile and the Traefik file (\`.tdk/.tdk-out/\`) are written by Tilt when it runs, not by
  \`tdk eject\`. Until Tilt has run they do not exist. They are git-ignored too.
- Your own Dockerfiles, \`service.json\` files and source code are untouched.

## Running the stack without the tdk CLI

There is no Tiltfile at the project root, so a plain \`tilt up\` does not find one. TDK runs:

    ${TILT_UP_COMMAND}

from the project root (\`<stack>\` is a stack name under \`services/\`; without \`--focus\` the Tiltfile
falls back to its default phase). The Tiltfile still reads \`.tdk/project.json\` and the
\`service.json\` files, so those must stay. \`tdk up\` also does steps before Tilt starts (it chooses
host ports and exports them to Tilt); running Tilt by hand skips them.

## Cleaning up

Optional to delete later: this file, and \`.tdk/\` plus the \`service.json\` files if you stop using TDK.
Deleting them also removes what the Tiltfile needs.

To go back to TDK: install it and run \`tdk config regenerate\`.
`;

export const ejectCommand = new Command("eject")
  .description(
    "Write EJECTED.md describing the generated Tilt files (copies and generates nothing; they stay in .tdk/.tdk-out/)",
  )
  .option(
    "--dry-run",
    "List the generated files and what would be written, without changing the project",
    false,
  )
  .option("--yes", "Skip the confirmation prompt", false)
  .action(async (options) => {
    await runCommand(async () => {
      const projectRoot = findProjectRoot();
      if (!projectRoot) {
        throw new Error("tdk eject: no .tdk/project.json in this directory or parents");
      }
      const generatedPaths = [".tdk/.tdk-out"];
      const presentPaths = generatedPaths.filter((path) => existsSync(join(projectRoot, path)));
      const files = presentPaths.flatMap((path) => {
        const absolutePath = join(projectRoot, path);
        if (statSync(absolutePath).isFile()) return [path];
        try {
          return readdirSync(absolutePath, { recursive: true }).map((entry) =>
            join(path, entry.toString()),
          );
        } catch {
          return [path];
        }
      });
      if (!existsSync(join(projectRoot, ".tdk", ".tdk-out", "Tiltfile"))) {
        throw new Error(
          "Generated Tilt files are missing. Run `tdk project --yes` before ejecting.",
        );
      }
      const rootTiltfile = join(projectRoot, "Tiltfile");
      const userTiltfile = existsSync(rootTiltfile) ? ["Tiltfile"] : [];
      const ejectedPath = join(projectRoot, "EJECTED.md");
      const willCreate = existsSync(ejectedPath) ? [] : ["EJECTED.md"];

      if (options.dryRun) {
        console.log("Generated files, left where they are (git-ignored):");
        for (const path of files) console.log(`  ${path}`);
        if (userTiltfile.length > 0) {
          console.log("Root Tiltfile, left where it is (not generated, not git-ignored):");
          for (const path of userTiltfile) console.log(`  ${path}`);
        }
        console.log("Files written:");
        for (const path of willCreate) console.log(`  ${path}`);
        if (willCreate.length === 0) console.log("  (none)");
        return;
      }

      if (
        !options.yes &&
        !(await confirmOrCancel(
          "Write EJECTED.md? (Generated files stay in .tdk/.tdk-out/; nothing is copied or moved.)",
        ))
      ) {
        return;
      }

      if (existsSync(ejectedPath)) {
        console.log(
          chalk.green(
            "EJECTED.md already exists and was left unchanged. Nothing was copied, moved or generated.",
          ),
        );
      } else {
        writeFileSync(ejectedPath, EJECTED_CONTENT, { flag: "wx" });
        console.log(chalk.green("Wrote EJECTED.md. Nothing was copied, moved or generated."));
      }
      console.log(
        "Generated files stay in .tdk/.tdk-out/ (git-ignored) and still need TDK inputs.",
      );
      console.log(`Run from the project root: ${TILT_UP_COMMAND}`);
      console.log(
        "Replace <stack> with a stack name under services/, or omit --focus to use the Tiltfile's default phase.",
      );
      console.log("Read EJECTED.md");
    });
  });
