import { existsSync, mkdirSync } from "node:fs";
import { isAbsolute, relative, resolve } from "node:path";
import chalk from "chalk";
import { Command } from "commander";
import { resolveBackendFramework } from "../backend-frameworks/registry.js";
import { getBackendIndexTemplate } from "../backend-languages/bun.js";
import { resolveBackendLanguage } from "../backend-languages/registry.js";
import { resolveFrontendFramework } from "../frontend-frameworks/registry.js";
import { hasDddLicense } from "../generator/extension-fetch.js";
import type {
  CreatableResourceType,
  FileGenerationTask,
  PortAssignableResourceType,
  ResourceType,
} from "../types/index.js";
import { CREATABLE_RESOURCE_TYPES } from "../types/index.js";
import { assertValid, confirmOrCancel } from "../utils/command-helpers.js";
import {
  chooseResourcePath,
  isPathDiscovered,
  readDiscoveryPaths,
} from "../utils/discovery-paths.js";
import { errorFactories, requireProjectRoot, runCommand, TdkError } from "../utils/errors.js";
import { writeFilesWithProgress } from "../utils/file-helpers.js";
import { showCommandHeader } from "../utils/formatting.js";
import { assignPort } from "../utils/port-assignment.js";
import { promptSelect, promptText } from "../utils/prompt.js";
import { getDefaultFeaturesForResourceType } from "../utils/resource-features.js";
import {
  SERVICE_MANIFEST_SCHEMA_URL,
  SERVICE_MANIFEST_SCHEMA_VERSION,
} from "../utils/service-manifest.js";
import { discoverResources } from "../utils/services.js";
import { createKebabCaseValidator, isPathSafe, validateResourceName } from "../utils/validation.js";

export const BASE_TEMPLATE = {
  port: 0, // Will be assigned
  // `dependsOn` is the current name; `dependencies` is deprecated and `tdk doctor` warns about it, so a fresh scaffold must not write it.
  dependsOn: [],
  build: {
    dockerfile: "Dockerfile",
    context: ".",
  },
  dev: {
    command: "bun run dev",
    watch: ["src/**/*"],
  },
} as const;

interface TypeSpecificConfig {
  /** The route the engine probes. The engine reads `healthCheckPath` (default /health); a top-level `healthCheck` is read by nothing. */
  healthCheckPath?: string;
  dev?: {
    command: string;
    watch: string[];
  };
}

export const TYPE_SPECIFIC: Record<CreatableResourceType, TypeSpecificConfig> = {
  backend: {
    healthCheckPath: "/health",
  },
  frontend: {
    dev: {
      command: "bun run dev",
      watch: ["src/**/*", "public/**/*"],
    },
  },
  worker: {
    dev: {
      command: "bun run worker",
      watch: ["src/**/*"],
    },
  },
  mcp: {
    healthCheckPath: "/health",
  },
  "bring-your-own": {
    healthCheckPath: "/health",
  },
};

const BYO_RESTART_POLICIES = ["no", "on-failure", "unless-stopped", "always"];

export function resolveByoPort(
  value: string | undefined,
  assignedPort: number,
  resources: Array<{ config?: { port?: number } }>,
): number {
  if (!value) return assignedPort;
  if (!/^\d+$/.test(value)) {
    throw new TdkError("BYO --port must be an integer from 4000 through 5999.");
  }

  const port = Number(value);
  if (!Number.isInteger(port) || port < 4000 || port > 5999) {
    throw new TdkError("BYO --port must be an integer from 4000 through 5999.");
  }
  if (resources.some((resource) => resource.config?.port === port)) {
    throw new TdkError(`BYO port ${port} is already assigned to another resource.`);
  }
  return port;
}

export function createServiceJson(
  name: string,
  type: CreatableResourceType,
  stack: string,
  port: number,
  extraFeatures: string[] = [],
  frameworkId?: string,
  languageId?: string,
) {
  const framework = resolveFrontendFramework(type, frameworkId);
  // Only an explicit selection is persisted: a missing `language` has always meant Bun.
  const language = languageId === undefined ? undefined : resolveBackendLanguage(type, languageId);
  // Likewise a missing backend `framework` has always meant Hono.
  const backendFramework = resolveBackendFramework(type, frameworkId, language);
  const typeSpecific = TYPE_SPECIFIC[type];

  const base = JSON.parse(JSON.stringify(BASE_TEMPLATE));
  for (const [key, value] of Object.entries(typeSpecific)) {
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      base[key] = { ...base[key], ...value };
    } else {
      base[key] = value;
    }
  }

  if (language?.devCommand) {
    base.dev = { command: language.devCommand, watch: language.watch ?? base.dev.watch };
    // The engine generates the image (.autogenerated/Dockerfile.app.autogenerated); a build
    // block would point at a Dockerfile that does not exist.
    delete base.build;
  }

  return {
    ...base,
    $schema: SERVICE_MANIFEST_SCHEMA_URL,
    schemaVersion: SERVICE_MANIFEST_SCHEMA_VERSION,
    appName: name,
    appType: type as ResourceType,
    featuresEnabled: [
      ...getDefaultFeaturesForResourceType(type as ResourceType).filter(
        // Prisma wiring is Bun-only; the Python provider owns their data layer.
        (feature) => !(language?.createFiles && feature === "prisma"),
      ),
      ...extraFeatures,
    ],
    name,
    type,
    stack,
    port,
    ...(framework ? { framework: framework.id } : {}),
    ...(backendFramework && type !== "mcp" ? { framework: backendFramework.id } : {}),
    ...(language ? { language: language.id } : {}),
  };
}

export function createByoServiceJson(
  name: string,
  stack: string,
  port: number,
  options: {
    healthCheckPath: string;
    dockerfile: string;
    image?: string;
    exposeViaProxy?: boolean;
    restart?: string;
  },
) {
  return {
    $schema: SERVICE_MANIFEST_SCHEMA_URL,
    schemaVersion: SERVICE_MANIFEST_SCHEMA_VERSION,
    appName: name,
    appType: "bring-your-own",
    stack,
    port,
    healthCheckPath: options.healthCheckPath,
    ...(options.image ? { image: options.image } : { dockerfile: options.dockerfile }),
    ...(options.exposeViaProxy === false ? { exposeViaProxy: false } : {}),
    ...(options.restart ? { restart: options.restart } : {}),
  };
}

export function createPackageJson(name: string, type: string, frameworkId?: string) {
  const isFrontend = type === "frontend";
  const framework = resolveFrontendFramework(type, frameworkId);
  const backendFramework = resolveBackendFramework(type, frameworkId);

  return {
    name: `@project/${name}`,
    version: "0.0.1",
    type: "module",
    scripts: {
      dev: isFrontend
        ? "vite --config .autogenerated/vite.config.frontend.autogenerated.ts"
        : "bun run --watch src/index.ts",
      build: isFrontend
        ? "tsc && vite build --config .autogenerated/vite.config.build.autogenerated.ts"
        : "tsc",
      // Backends and workers run `start` in their production image; doctor checks for it.
      ...(isFrontend ? {} : { start: "bun run dist/index.js" }),
      test: "vitest",
      lint: "biome check .",
      "lint:fix": "biome check . --write",
    },
    dependencies: {
      ...(isFrontend ? {} : (backendFramework?.dependencies ?? { hono: "^4.0.0" })),
      ...(framework?.dependencies ?? {}),
    },
    devDependencies: {
      "@types/bun": "^1.4.2",
      // The generated Docker tsconfig sets "types": ["node"]; without this the
      // image's `bun run build` fails with TS2688. ^20 matches the services that build.
      "@types/node": "^20.0.0",
      typescript: "^7.0.2",
      vitest: "^5.0.0",
      "@biomejs/biome": "^2.5.13",

      ...(isFrontend ? { vite: "^5.0.0" } : {}),
      ...(framework?.devDependencies ?? {}),
      ...(backendFramework?.devDependencies ?? {}),
    },
  };
}

export function createResourceTsconfig(resourceType: CreatableResourceType, frameworkId?: string) {
  const framework = resolveFrontendFramework(resourceType, frameworkId);
  const backendFramework = resolveBackendFramework(resourceType, frameworkId);
  return {
    ...TSCONFIG_TEMPLATE,
    compilerOptions: {
      ...TSCONFIG_TEMPLATE.compilerOptions,
      ...(framework?.compilerOptions ?? {}),
      ...(backendFramework?.compilerOptions ?? {}),
    },
  };
}

export const TSCONFIG_TEMPLATE = {
  compilerOptions: {
    target: "ES2022",
    module: "ESNext",
    moduleResolution: "bundler",
    strict: true,
    esModuleInterop: true,
    skipLibCheck: true,
    forceConsistentCasingInFileNames: true,
    outDir: "./dist",
    rootDir: "./src",
    declaration: true,
    declarationMap: true,
    sourceMap: true,
  },
  include: ["src/**/*"],
  exclude: ["node_modules", "dist"],
};

export const DOCKERFILE_TEMPLATE = `FROM oven/bun:1.2

WORKDIR /app

# Copy package files
COPY package.json bun.lock ./

# Install dependencies
RUN bun install --frozen-lockfile

# Copy source
COPY . .

# Build if needed
RUN bun run build

# Health check
HEALTHCHECK --interval=10s --timeout=5s --retries=3 \\
  CMD curl -f http://localhost:3000/health || exit 1

EXPOSE 3000

CMD ["bun", "run", "start"]
`;

export { getBackendIndexTemplate };

function getShutdownHandlerTemplate(signal: string): string {
  return `process.on('${signal}', () => {
  console.log('[Worker] ${signal} received, shutting down gracefully...');
  process.exit(0);
});`;
}

export function getWorkerIndexTemplate(name: string) {
  return `console.log('🚀 ${name} worker started');

interface Job {
  id: string;
  type: string;
  payload: Record<string, JsonValue>;
  priority?: number;
  timestamp?: string;
}

const CONFIG = {
  pollIntervalMs: parseInt(process.env.WORKER_POLL_INTERVAL || '5000'),
  maxRetries: parseInt(process.env.WORKER_MAX_RETRIES || '3'),
  batchSize: parseInt(process.env.WORKER_BATCH_SIZE || '10'),
};

async function processJob(job: Job): Promise<void> {
  console.log('[Worker] Processing job:', job.id, 'type:', job.type);

  // Add job processing logic here using job.payload

  await new Promise(resolve => setTimeout(resolve, 1000));
  console.log('[Worker] Job completed:', job.id);
}

async function fetchJobs(): Promise<Job[]> {
  // Connect to your queue (Redis, RabbitMQ, etc.) and fetch jobs
  return [];
}

async function main() {
  console.log('[Worker] Configuration:', CONFIG);

  while (true) {
    try {
      const jobs = await fetchJobs();

      if (jobs.length === 0) {
        await new Promise(resolve => setTimeout(resolve, CONFIG.pollIntervalMs));
        continue;
      }

      console.log('[Worker] Fetched \${jobs.length} jobs');

      for (const job of jobs) {
        try {
          await processJob(job);
        } catch (error: unknown) {
          console.error('[Worker] Job failed:', error);
        }
      }
    } catch (error: unknown) {
      console.error('[Worker] Error in main loop:', error);
      // Wait before retrying to avoid tight error loops
      await new Promise(resolve => setTimeout(resolve, CONFIG.pollIntervalMs));
    }
  }
}

${getShutdownHandlerTemplate("SIGTERM")}

${getShutdownHandlerTemplate("SIGINT")}

main().catch((err) => {
  console.error('[Worker] Fatal error:', err);
  process.exit(1);
});
`;
}

function getTestTemplate(name: string) {
  return `import { describe, it, expect } from 'vitest';

describe('${name}', () => {
  it('should pass a basic test', () => {
    expect(true).toBe(true);
  });
});
`;
}

/** Resource types `tdk resource --type` accepts; `byo` is an alias of `bring-your-own`. */
export function parseResourceType(type: string): CreatableResourceType | "sdk" {
  const normalized = type === "byo" ? "bring-your-own" : type;
  const validTypes: readonly string[] = [...CREATABLE_RESOURCE_TYPES, "sdk"];
  if (!validTypes.includes(normalized)) {
    throw new TdkError(
      `Unknown resource type "${type}". Supported types: ${validTypes.join(", ")}.`,
      [`Use one of: ${validTypes.join(", ")}`, "Omit --type to create a backend"],
    );
  }
  return normalized as CreatableResourceType | "sdk";
}

export const resourceCommand = new Command("resource")
  .description("Create a new resource (service) from scratch, or register an existing one")
  .argument("[name]", "Resource name (kebab-case)")
  .option(
    "-t, --type <type>",
    "Resource type: backend, frontend, worker, mcp, bring-your-own, sdk",
    "backend",
  )
  .option(
    "--framework <id>",
    "Framework: frontend react (default), vue, svelte, preact, lit, solid, qwik, vanilla, tanstack-router; backend hono (default), express, elysia, fastify, nestjs, koa, h3",
  )
  .option("--language <id>", "Backend language: bun (default), python, go, rust")
  .option("-s, --stack <stack>", "Stack to assign resource to", "default")
  .option("-p, --path <path>", "Custom path for resource directory")
  .option("--resource-path <path>", "Alias for --path (for backward compatibility)")
  .option("--register-existing", "Register an existing resource without creating templates")
  .option("-y, --yes", "Skip confirmation prompt", false)
  .option(
    "--ddd",
    "Scaffold DDD (domain-driven design) folders + path aliases (Premium - requires TDK_LICENSE_KEY)",
  )
  .option("--dockerfile <path>", "Path to Dockerfile relative to resource dir (for bring-your-own)")
  .option("--health-path <path>", "HTTP health check path (for bring-your-own)", "/health")
  .option("--no-proxy", "Disable the Traefik route (bring-your-own only)")
  .option(
    "--restart <policy>",
    "Compose restart policy: no, on-failure, unless-stopped, always (bring-your-own only; use no for one-shot jobs)",
  )
  .option(
    "--image <name>",
    "Docker image name instead of building from Dockerfile (for bring-your-own)",
  )
  .option("--port <port>", "Port number (default: next free in 4000-5999)")
  .action(async (name, options) => {
    await runCommand(async () => {
      const projectRoot = requireProjectRoot();

      // Support --resource-path as alias for --path
      const resourcePath = options.resourcePath || options.path;

      showCommandHeader("Resource Creation");

      const allResources = discoverResources();

      let resourceName = name;
      if (!resourceName) {
        const inputName = await promptText({
          message: "Resource name (kebab-case):",
          validate: (input: string) => {
            const validation = createKebabCaseValidator("resource")(input);
            return validation === true || validation;
          },
        });
        resourceName = inputName;
      } else {
        assertValid(validateResourceName(resourceName));
      }

      const resourceType = parseResourceType(options.type);

      const frontendFramework = resolveFrontendFramework(resourceType, options.framework);
      const backendLanguage = resolveBackendLanguage(resourceType, options.language);
      const backendFramework = resolveBackendFramework(
        resourceType,
        options.framework,
        backendLanguage,
      );
      // The id passed on to the file generators. An mcp resource has one fixed scaffold and no `framework` setting, so it passes none
      // (its provider is selected by the resource type itself).
      const scaffoldFrameworkId =
        resourceType === "mcp" ? undefined : (frontendFramework?.id ?? backendFramework?.id);

      let dddEnabled = false;
      if (options.ddd) {
        if (resourceType !== "backend" && resourceType !== "worker") {
          console.log(
            chalk.yellow(
              `\n⚠️  --ddd only applies to backend/worker resources, ignoring for type "${resourceType}"`,
            ),
          );
        } else {
          const granted = await hasDddLicense(projectRoot);
          if (!granted) {
            throw new Error(
              "DDD scaffolding is a Premium feature and requires a license key that grants it. " +
                "Set export TDK_LICENSE_KEY=<key> (request a Premium license at https://tdk-landscape.github.io/tdk-website/#waitlist) and try again.",
            );
          }
          dddEnabled = true;
        }
      }

      let stackName = options.stack;
      if (stackName === "default") {
        const existingResources = allResources;
        const stackSet = new Set<string>();
        for (const r of existingResources) {
          if (r.stack) stackSet.add(r.stack);
        }
        const existingStacks = Array.from(stackSet);

        if (existingStacks.length > 0) {
          const selectedStack = await promptSelect({
            message: "Assign to stack:",
            choices: [
              ...existingStacks.map((s) => ({ title: s, value: s })),
              { title: "Create new stack", value: "__new__" },
            ],
          });

          if (selectedStack === "__new__") {
            const newStack = await promptText({
              message: "New stack name:",
              validate: (input: string) => {
                const validation = createKebabCaseValidator("stack")(input);
                return validation === true || validation;
              },
            });
            stackName = newStack;
          } else {
            stackName = selectedStack;
          }
        } else {
          const newStack = await promptText({
            message: "Stack name (first resource):",
            initial: "main",
            validate: (input: string) => {
              const validation = createKebabCaseValidator("stack")(input);
              return validation === true || validation;
            },
          });
          stackName = newStack;
        }
      }

      let finalResourcePath = resourcePath;
      let pathAdjustedFrom: string | undefined;
      if (!finalResourcePath) {
        const defaultPaths: Record<CreatableResourceType | "sdk", string> = {
          backend: `services/${stackName}/${resourceName}`,
          frontend: `apps/${resourceName}`,
          worker: `workers/${resourceName}`,
          mcp: `services/${stackName}/${resourceName}`,
          "bring-your-own": `services/${stackName}/${resourceName}`,
          sdk: `packages/${resourceName}`,
        };
        finalResourcePath = defaultPaths[resourceType];

        // An SDK is registered where it already lives, so its folder is never moved.
        if (resourceType !== "sdk") {
          const chosen = chooseResourcePath(
            projectRoot,
            finalResourcePath,
            stackName,
            resourceName,
          );
          finalResourcePath = chosen.path;
          pathAdjustedFrom = chosen.adjustedFrom;
        }
      }

      const fullPath = resolve(projectRoot, finalResourcePath);

      // Prevent path traversal attacks
      const relativePathResult = relative(projectRoot, fullPath);
      if (relativePathResult.startsWith("..") || isAbsolute(relativePathResult)) {
        errorFactories.invalidPath(fullPath).exit();
      }

      if (!isPathSafe(finalResourcePath)) {
        errorFactories.invalidPath(finalResourcePath).exit();
      }

      // Check if resource already exists
      const isExistingResource = existsSync(fullPath);
      const hasServiceJson = existsSync(resolve(fullPath, "service.json"));
      const shouldRegisterExisting =
        options.registerExisting ||
        resourceType === "sdk" ||
        (isExistingResource && hasServiceJson);

      if (isExistingResource && !shouldRegisterExisting && resourceType !== "bring-your-own") {
        errorFactories.directoryExists(fullPath).exit();
      }

      const nextPort =
        resourceType === "sdk"
          ? 0
          : assignPort(
              resourceType as CreatableResourceType as PortAssignableResourceType,
              allResources,
            );
      if (options.restart !== undefined) {
        if (resourceType !== "bring-your-own") {
          throw new TdkError("--restart can only be used with --type bring-your-own.", [
            "Add --type bring-your-own, or drop --restart",
          ]);
        }
        if (!BYO_RESTART_POLICIES.includes(options.restart)) {
          throw new TdkError(`Unknown --restart policy "${options.restart}".`, [
            `Use one of: ${BYO_RESTART_POLICIES.join(", ")}`,
          ]);
        }
      }
      const assignedPort =
        resourceType === "bring-your-own"
          ? resolveByoPort(options.port, nextPort, allResources)
          : nextPort;

      console.log(chalk.gray("\nResource details:"));
      console.log(chalk.gray(`  Name:  ${resourceName}`));
      console.log(chalk.gray(`  Type:  ${resourceType}`));
      console.log(chalk.gray(`  Stack: ${stackName}`));
      console.log(chalk.gray(`  Port: ${assignedPort || "N/A (SDK)"}`));
      console.log(chalk.gray(`  Path:  ${finalResourcePath}`));

      if (shouldRegisterExisting && hasServiceJson) {
        console.log(
          chalk.yellow("\n⚠️  Existing resource detected - will update service.json only"),
        );
      }

      const confirmed =
        options.yes ||
        (await confirmOrCancel(
          shouldRegisterExisting && hasServiceJson
            ? "\nRegister existing resource?"
            : "\nCreate resource?",
        ));
      if (!confirmed) return;

      // Handle existing resource registration
      if (shouldRegisterExisting && hasServiceJson) {
        // Read existing service.json
        const { readFileSync } = await import("node:fs");
        const existingServiceJsonPath = resolve(fullPath, "service.json");
        const existingContent = readFileSync(existingServiceJsonPath, "utf-8");
        const existingServiceJson = JSON.parse(existingContent);

        // Update with new values while preserving existing fields
        const updatedServiceJson = {
          ...existingServiceJson,
          $schema: existingServiceJson.$schema ?? SERVICE_MANIFEST_SCHEMA_URL,
          schemaVersion: existingServiceJson.schemaVersion ?? SERVICE_MANIFEST_SCHEMA_VERSION,
          appName: resourceName,
          appType: resourceType === "sdk" ? "sdk" : existingServiceJson.appType || resourceType,
          stack: stackName,
          ...(assignedPort > 0 && { port: assignedPort }),
        };

        // Write updated service.json
        const { writeFileSync } = await import("node:fs");
        writeFileSync(existingServiceJsonPath, JSON.stringify(updatedServiceJson, null, 2));

        console.log(chalk.green("\n✅ Existing resource registered successfully!"));
        console.log(chalk.gray(`\nLocation: ${fullPath}`));
        console.log(chalk.gray(`\nNext steps:`));
        console.log(chalk.gray(`  tdk up ${stackName}`));
        return;
      }

      // Handle bring-your-own type
      if (resourceType === "bring-your-own") {
        console.log(chalk.blue("\n📁 Creating bring-your-own resource..."));

        // Parse port option
        const port = assignedPort;

        const dockerfile = options.dockerfile || "./Dockerfile";
        const dockerfilePath = resolve(fullPath, dockerfile);
        const dockerfileRelativePath = relative(fullPath, dockerfilePath);
        if (
          isAbsolute(dockerfileRelativePath) ||
          dockerfileRelativePath === ".." ||
          dockerfileRelativePath.startsWith(`..${process.platform === "win32" ? "\\" : "/"}`)
        ) {
          errorFactories.invalidPath(dockerfile).exit();
        }

        mkdirSync(fullPath, { recursive: true });

        // Create service.json
        const byoServiceJson = createByoServiceJson(resourceName, stackName, port, {
          healthCheckPath: options.healthPath || "/health",
          dockerfile,
          ...(options.image ? { image: options.image } : {}),
          ...(options.proxy === false ? { exposeViaProxy: false } : {}),
          ...(options.restart ? { restart: options.restart } : {}),
        });

        const { writeFileSync } = await import("node:fs");
        writeFileSync(resolve(fullPath, "service.json"), JSON.stringify(byoServiceJson, null, 2));

        // Create Dockerfile stub if no image provided and dockerfile doesn't exist
        if (!options.image && !existsSync(dockerfilePath)) {
          mkdirSync(resolve(dockerfilePath, ".."), { recursive: true });
          const healthConfigPath = resolve(dockerfilePath, "..", "health.conf");
          const healthConfigRelativePath = relative(fullPath, healthConfigPath).replace(/\\/g, "/");
          const dockerfileContent = `FROM nginx:1.27-alpine
RUN apk add --no-cache curl
COPY ${healthConfigRelativePath} /etc/nginx/conf.d/default.conf
EXPOSE ${port}
`;
          writeFileSync(dockerfilePath, dockerfileContent);

          const healthConfContent = `server {
  listen ${port};
  location /health {
    default_type text/plain;
    return 200 'ok';
  }
  location / {
    default_type text/plain;
    return 200 'byo';
  }
}
`;
          writeFileSync(healthConfigPath, healthConfContent);
        }

        // Create AGENTS.md
        const agentsMdContent = `# AGENTS.md

DO NOT DELETE service.json

This file contains the resource configuration for TDK.
`;
        const agentsPath = resolve(fullPath, "AGENTS.md");
        if (!existsSync(agentsPath)) writeFileSync(agentsPath, agentsMdContent);

        console.log(chalk.green("\n✅ Bring-your-own resource created successfully!"));
        console.log(chalk.gray(`\nLocation: ${fullPath}`));
        console.log(chalk.gray(`\nNext steps:`));
        console.log(chalk.gray(`  tdk up ${stackName}`));
        return;
      }

      // Create directory structure for new resources
      console.log(chalk.blue("\n📁 Creating directory structure..."));
      mkdirSync(fullPath, { recursive: true });
      // A provider that owns its runtime files only gets the folders it writes into (Go keeps its files at the root).
      const ownedTopLevel = new Set(
        (backendLanguage?.createFiles?.(resourceName) ?? []).map(
          (file) => file.filename.split("/")[0],
        ),
      );
      for (const folder of ["src", "tests"]) {
        if (!backendLanguage?.createFiles || ownedTopLevel.has(folder)) {
          mkdirSync(resolve(fullPath, folder), { recursive: true });
        }
      }
      if (resourceType === "frontend") {
        mkdirSync(resolve(fullPath, "public"), { recursive: true });
      }
      if (dddEnabled) {
        for (const layer of ["domain", "application", "infrastructure", "presentation"]) {
          mkdirSync(resolve(fullPath, "src", layer), { recursive: true });
        }
      }

      // Prepare file generation tasks
      const serviceJson = createServiceJson(
        resourceName,
        resourceType as CreatableResourceType,
        stackName,
        assignedPort,
        dddEnabled ? ["ddd"] : [],
        scaffoldFrameworkId,
        options.language === undefined ? undefined : backendLanguage?.id,
      );
      const packageJson = createPackageJson(resourceName, resourceType, scaffoldFrameworkId);

      const tasks: FileGenerationTask[] = [
        {
          type: "json",
          filename: "service.json",
          content: serviceJson,
          description: "Generating service.json",
          emoji: "📝",
        },
        {
          type: "json",
          filename: "package.json",
          content: packageJson,
          description: "Generating package.json",
          emoji: "📦",
        },
        {
          type: "json",
          filename: "tsconfig.json",
          content: createResourceTsconfig(
            resourceType as CreatableResourceType,
            scaffoldFrameworkId,
          ),
          description: "Generating tsconfig.json",
          emoji: "⚙️",
        },
        {
          type: "text",
          filename: "Dockerfile",
          content: DOCKERFILE_TEMPLATE,
          description: "Generating Dockerfile",
          emoji: "🐳",
        },
      ];

      // Add source files based on resource type
      if (resourceType === "backend" || resourceType === "mcp") {
        tasks.push({
          type: "text",
          filename: "src/index.ts",
          content: (backendFramework?.createIndex ?? getBackendIndexTemplate)(resourceName),
          description:
            resourceType === "mcp" ? "Generating MCP server source" : "Generating backend source",
          emoji: "💻",
        });
      } else if (resourceType === "frontend") {
        tasks.push(
          ...(frontendFramework?.createFiles(resourceName).map((file) => ({
            ...file,
            type: "text" as const,
          })) ?? []),
        );
        // The shared frontend Docker builder unconditionally runs `COPY <resource>/public`
        // (the Vite static-assets folder), and an empty folder can't be committed, so
        // without a placeholder the image build fails for every framework.
        tasks.push({
          type: "text",
          filename: "public/.gitkeep",
          content: "",
          description: "Generating public/ assets folder",
          emoji: "📁",
        });
      } else if (resourceType === "worker") {
        tasks.push({
          type: "text",
          filename: "src/index.ts",
          content: getWorkerIndexTemplate(resourceName),
          description: "Generating worker source",
          emoji: "💻",
        });
      }

      // Add test file
      tasks.push({
        type: "text",
        filename: `tests/${resourceName}.test.ts`,
        content: getTestTemplate(resourceName),
        description: "Generating test file",
        emoji: "🧪",
      });

      // A language provider that owns its runtime files replaces the shared Bun/TypeScript
      // scaffold (package.json, tsconfig, source, test, and the Dockerfile, which the engine generates); service.json stays shared.
      const languageFiles = backendLanguage?.createFiles?.(resourceName);
      if (languageFiles) {
        const owned = new Set(languageFiles.map((file) => file.filename));
        const sharedTasks = tasks.filter(
          (task) =>
            task.filename === "service.json" ||
            !(
              owned.has(task.filename) ||
              task.filename === "Dockerfile" ||
              task.filename === "src/index.ts" ||
              task.filename === "package.json" ||
              task.filename === "tsconfig.json" ||
              task.filename.endsWith(".test.ts")
            ),
        );
        tasks.length = 0;
        tasks.push(
          ...sharedTasks,
          ...languageFiles.map((file) => ({ ...file, type: "text" as const })),
        );
      }

      // Execute all file writes with progress
      console.log(chalk.blue("💻 Generating source files..."));
      writeFilesWithProgress(fullPath, tasks);

      console.log(chalk.green("\n✅ Resource created successfully!"));
      console.log(chalk.gray(`\nLocation: ${fullPath}`));

      const discoveryPaths = readDiscoveryPaths(projectRoot);
      if (pathAdjustedFrom) {
        console.log(
          chalk.yellow(
            `\n📁 Placed in ${finalResourcePath} instead of the usual ${pathAdjustedFrom}: ` +
              `discovery.paths in .tdk/project.json is ${JSON.stringify(discoveryPaths)}, ` +
              `so ${pathAdjustedFrom} would never be started by \`tdk up\`.`,
          ),
        );
        console.log(chalk.gray("   Use --path to choose another folder."));
      } else if (!isPathDiscovered(projectRoot, finalResourcePath, discoveryPaths)) {
        console.log(
          chalk.yellow(
            `\n⚠️  ${finalResourcePath} is outside discovery.paths ${JSON.stringify(discoveryPaths)}, ` +
              "so `tdk up` will not start this resource.",
          ),
        );
        console.log(
          chalk.gray(
            "   Add a matching pattern to discovery.paths in .tdk/project.json and run `tdk config regenerate`.",
          ),
        );
      }
      console.log(chalk.gray(`\nNext steps:`));
      console.log(chalk.gray(`  cd ${finalResourcePath}`));
      console.log(chalk.gray(`  ${backendLanguage?.installHint ?? "bun install"}`));
      console.log(chalk.gray(`  tdk up ${stackName}`));
    });
  });
