appName: identity-management-backend
appType: backend
stack: identity
port: 4004
apiPath: /api/identity-management
features:
  - nats
  - prisma
healthCheck: True
healthCheckPath: /api/v1/health
params:
  BASE_URL: http://identity.backend.beauty.local
  EMAIL_FROM: noreply@beauty-crm.local
  UPSTASH_REDIS_REST_URL: http://redis:6379
path: identity-management-backend
playwright: True
prisma_client_path: ./node_modules/.prisma/client/client
replicas: 1
runtime: bun
secrets:
  optional:
  required:
    - JWT_REFRESH_SECRET
    - JWT_SECRET
    - PASSWORD_PEPPER
    - UPSTASH_REDIS_REST_TOKEN
