# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load("../../../../topologies/tilt/common/utils.star", "Utils")
load("../../../../topologies/tilt/manifest/constants.star", "GENERATED_CONFIG_FILENAMES")


# =============================================================================
# Backend TSConfig Generator
# =============================================================================

def generate_backend_tsconfig(resource_path, prisma_path, write_fn, internal_deps=None, is_docker=True, features=None):
    """
    Generate tsconfig for backend services.

    Args:
        resource_path: Path to the service directory
        prisma_path: Path to Prisma client
        write_fn: Write function for file output
        internal_deps: Optional internal dependencies map
        is_docker: Whether generating for Docker context
        features: Resource's service.json features: [] array (for the premium
            "ddd" feature - see generate_backend_path_aliases() in vite/helpers.star)
    """
    # When tsconfig is in .autogenerated/ folder, paths are relative to parent
    paths = {
        "@/*": ["../src/*"],
        "@prisma/client": [prisma_path]
    }
    # DDD is premium - same gate as generate_backend_path_aliases() in vite/helpers.star.
    ddd_enabled = features and 'ddd' in features and os.environ.get('TDK_LICENSE_KEY', '') != ''
    if ddd_enabled:
        paths["@application/*"] = ["../src/application/*"]
        paths["@domain/*"] = ["../src/domain/*"]
        paths["@infrastructure/*"] = ["../src/infrastructure/*"]
        paths["@presentation/*"] = ["../src/presentation/*"]
    root_dir = "../src"
    if internal_deps and not is_docker:
        sorted_deps = sorted(internal_deps.items())
        depth = len([segment for segment in resource_path.split('/') if segment])
        rel_to_root = "../" * depth
        for pkg_name, src_path in sorted_deps:
            paths[pkg_name] = [rel_to_root + src_path + "/src"]
            paths[pkg_name + "/*"] = [rel_to_root + src_path + "/src/*"]
    compiler_options = {
        "target": "ES2022",
        "module": "ES2022",
        "moduleResolution": "bundler",
        "paths": paths,
        "skipLibCheck": True,
        "strict": True,
        "experimentalDecorators": True,
        "emitDecoratorMetadata": True,
        "esModuleInterop": True,
        "forceConsistentCasingInFileNames": True,
        "resolveJsonModule": True,
        "allowSyntheticDefaultImports": True,
        "outDir": "../dist",
        "rootDir": root_dir,
        # "bun" (not "node"): @types/bun is a direct devDependency so it's always
        # linked at the top level under any linker mode (including Docker's
        # isolated linker), while @types/node is only a transitive dependency of
        # bun-types and isn't hoisted to the top level under the isolated linker -
        # "types": ["node"] fails to resolve there even though it works locally.
        "types": ["bun"],
    }
    content = {
        "compilerOptions": compiler_options,
        "exclude": [
            "node_modules",
            "dist",
            "../__tests__/**/*",
            "../**/*.test.ts",
            "../**/tests/**/*",
            "../src/legacy/**/*",
            "../**/*.steps.ts",
            "../**/*.spec.ts"
        ],
        "include": ["../src/**/*"]
    }
    if is_docker:
        # Docker tsconfig is copied to service root, so paths are relative to root
        docker_paths = {
            "@/*": ["./src/*"],
            "@application/*": ["./src/application/*"],
            "@domain/*": ["./src/domain/*"],
            "@infrastructure/*": ["./src/infrastructure/*"],
            "@presentation/*": ["./src/presentation/*"],
            "@prisma/client": [prisma_path]
        }
        docker_root_dir = "./src"
        if internal_deps:
            sorted_deps = sorted(internal_deps.items())
            depth = len([segment for segment in resource_path.split('/') if segment])
            rel_to_root = "../" * depth
            for pkg_name, src_path in sorted_deps:
                docker_paths[pkg_name] = [rel_to_root + src_path + "/src"]
                docker_paths[pkg_name + "/*"] = [rel_to_root + src_path + "/src/*"]
        docker_compiler_options = {
            "target": "ES2022",
            "module": "ES2022",
            "moduleResolution": "bundler",
            "paths": docker_paths,
            "skipLibCheck": True,
            "strict": True,
            "experimentalDecorators": True,
            "emitDecoratorMetadata": True,
            "esModuleInterop": True,
            "forceConsistentCasingInFileNames": True,
            "resolveJsonModule": True,
            "allowSyntheticDefaultImports": True,
            "outDir": "./dist",
            "rootDir": docker_root_dir,
            # See note above: "bun" resolves under the isolated linker, "node" doesn't.
            "types": ["bun"],
        }
        docker_content = {
            "compilerOptions": docker_compiler_options,
            "exclude": [
                "node_modules",
                "dist",
                "./__tests__/**/*",
                "./**/*.test.ts",
                "./**/tests/**/*",
                "./src/legacy/**/*",
                "./**/*.steps.ts",
                "./**/*.spec.ts"
            ],
            "include": ["./src/**/*"]
        }
        write_fn(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['tsconfig_docker'], Utils.encode_json(docker_content))
    else:
        write_fn(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['tsconfig_local'], Utils.encode_json(content))
