# =============================================================================
# 📝 FIXED TypeScript Config Generators
# =============================================================================
# These generators fix the Docker path alias issue that causes build failures
# =============================================================================

# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load("../../../../topologies/tilt/common/utils.star", "Utils")
load("../../../../topologies/tilt/manifest/constants.star", "GENERATED_CONFIG_FILENAMES")


# =============================================================================
# FIXED Frontend TSConfig Generator
# =============================================================================

def generate_frontend_tsconfig_fixed(resource_path, write_fn, internal_deps=None, is_docker=True):
    """
    Generate tsconfig for frontend services - FIXED VERSION

    CRITICAL FIX: When is_docker=True, we DO NOT include path aliases for
    internal dependencies (@{npm_scope}/* packages). This prevents the
    "Module not found" errors in Docker builds.

    In Docker builds:
      - Resolve @{npm_scope}/* from node_modules (published packages)
      - Only have @/* alias for local source

    In Local builds:
      - Can use path aliases to source for faster development
      - Maps @{npm_scope}/* to shared-*-engineering/*/src

    Args:
        resource_path: Path to the service (e.g., "services/product/order-planner/order-planner-frontend")
        write_fn: Function to write file if content changed
        internal_deps: Dict of {package_name: source_path} - ONLY used when NOT Docker
        is_docker: If True, generates Docker-safe config (no path aliases to source)

    Returns:
        Path to generated config file
    """
    # When tsconfig is in .autogenerated/ folder, paths are relative to parent
    paths = {
        "@/*": ["../src/*"]
    }
    include_paths = ["../src/**/*"]
    
    # =============================================================================
    # CRITICAL FIX: Only add path aliases for internal deps in LOCAL builds
    # =============================================================================
    # In Docker builds, these path aliases cause "Module not found" errors
    # because the source files aren't copied to the Docker context.
    # 
    # Docker builds should resolve from node_modules instead.
    # =============================================================================
    
    if internal_deps and not is_docker:
        # LOCAL BUILD: Can use path aliases to source for faster development
        sorted_deps = sorted(internal_deps.items())
        for pkg_name, src_path in sorted_deps:
            depth = len([segment for segment in resource_path.split('/') if segment])
            rel_to_root = "../" * depth
            paths[pkg_name] = [rel_to_root + src_path + "/src"]
            paths[pkg_name + "/*"] = [rel_to_root + src_path + "/src/*"]
    
    # If is_docker=True and internal_deps exist, warn about it
    if internal_deps and is_docker:
        print("📝 Note: Excluding {} path aliases from Docker tsconfig for {}".format(
            len(internal_deps),
            resource_path
        ))
        print("   Docker build will resolve @{npm_scope}/* from node_modules")
    
    content = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "ES2022",
            "moduleResolution": "node",
            "lib": ["dom", "dom.iterable", "esnext"],
            "jsx": "react-jsx",
            "paths": paths,
            "skipLibCheck": True,
            "strict": True,
            "types": ["node"],
        },
        "exclude": [
            "node_modules",
            "dist",
            "../__tests__/**/*",
            "../**/*.test.ts",
            "../**/tests/**/*",
            "../**/*.steps.ts",
            "../**/*.spec.ts"
        ],
        "include": include_paths
    }
    
    # Determine output filename based on context
    if is_docker:
        output_filename = GENERATED_CONFIG_FILENAMES['tsconfig_docker']
    else:
        output_filename = GENERATED_CONFIG_FILENAMES['tsconfig_local']
    
    output_path = resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + output_filename
    write_fn(output_path, Utils.encode_json(content))

    return output_path

def generate_frontend_tsconfig_docker_only(resource_path, write_fn):
    """
    Generate Docker-specific tsconfig with NO path aliases to internal deps.

    This is a simplified version that always excludes internal_deps,
    ensuring Docker builds work correctly.
    """
    paths = {
        "@/*": ["../src/*"]
        # NO @{npm_scope}/* aliases - resolve from node_modules
    }
    
    content = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "ES2022",
            "moduleResolution": "node",
            "lib": ["dom", "dom.iterable", "esnext"],
            "jsx": "react-jsx",
            "paths": paths,
            "skipLibCheck": True,
            "strict": True,
            "types": ["node"],
        },
        "exclude": [
            "node_modules",
            "dist",
            "../__tests__/**/*",
            "../**/*.test.ts",
            "../**/tests/**/*",
            "../**/*.steps.ts",
            "../**/*.spec.ts"
        ],
        "include": ["../src/**/*"]
    }
    
    output_path = resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['tsconfig_docker']
    write_fn(output_path, Utils.encode_json(content))

    return output_path

def generate_frontend_tsconfig_local_only(resource_path, internal_deps, write_fn):
    """
    Generate local development tsconfig WITH path aliases to internal deps.

    This provides faster builds during development by resolving from source
    rather than node_modules.
    """
    paths = {
        "@/*": ["../src/*"]
    }
    
    if internal_deps:
        sorted_deps = sorted(internal_deps.items())
        for pkg_name, src_path in sorted_deps:
            depth = len([segment for segment in resource_path.split('/') if segment])
            rel_to_root = "../" * depth
            paths[pkg_name] = [rel_to_root + src_path + "/src"]
            paths[pkg_name + "/*"] = [rel_to_root + src_path + "/src/*"]
    
    content = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "ES2022",
            "moduleResolution": "node",
            "lib": ["dom", "dom.iterable", "esnext"],
            "jsx": "react-jsx",
            "paths": paths,
            "skipLibCheck": True,
            "strict": True,
            "types": ["node"],
        },
        "exclude": [
            "node_modules",
            "dist",
            "../__tests__/**/*",
            "../**/*.test.ts",
            "../**/tests/**/*",
            "../**/*.steps.ts",
            "../**/*.spec.ts"
        ],
        "include": ["../src/**/*"]
    }
    
    output_path = resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['tsconfig_local']
    write_fn(output_path, Utils.encode_json(content))

    return output_path

# =============================================================================
# FIXED Library TSConfig Generator
# =============================================================================

def generate_frontend_library_tsconfig_fixed(resource_path, write_fn, internal_deps=None, is_docker=True):
    """
    Generate tsconfig for frontend libraries - FIXED VERSION

    Libraries have simpler requirements but same Docker path alias issue.
    """
    paths = {
        "./*": ["./*"]
    }
    
    # Only add internal dep paths for local builds
    if internal_deps and not is_docker:
        sorted_deps = sorted(internal_deps.items())
        for pkg_name, src_path in sorted_deps:
            paths[pkg_name] = [src_path + "/src"]
            paths[pkg_name + "/*"] = [src_path + "/src/*"]
    
    content = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "ESNext",
            "moduleResolution": "bundler",
            "lib": ["dom", "dom.iterable", "esnext"],
            "jsx": "react-jsx",
            "paths": paths,
            "skipLibCheck": True,
            "strict": True,
            "types": ["node"],
        },
        "exclude": [
            "node_modules",
            "dist",
            "**/__tests__/**/*",
            "**/*.test.ts",
            "**/tests/**/*",
            "**/*.steps.ts",
            "**/*.spec.ts"
        ],
        "include": ["src/**/*"]
    }
    
    if is_docker:
        output_filename = GENERATED_CONFIG_FILENAMES['tsconfig_docker']
    else:
        output_filename = GENERATED_CONFIG_FILENAMES['tsconfig_local']
    
    output_path = resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + output_filename
    write_fn(output_path, Utils.encode_json(content))

    return output_path

# =============================================================================
# Exports
# =============================================================================

FixedTSConfig = struct(
    # Main entry points with Docker-safe behavior
    generate_frontend_tsconfig=generate_frontend_tsconfig_fixed,
    generate_frontend_library_tsconfig=generate_frontend_library_tsconfig_fixed,
    
    # Explicit Docker/Local variants
    generate_frontend_tsconfig_docker_only=generate_frontend_tsconfig_docker_only,
    generate_frontend_tsconfig_local_only=generate_frontend_tsconfig_local_only,
)
