# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load("../../../../topologies/tilt/common/utils.star", "Utils")
load("../../../../topologies/tilt/manifest/constants.star", "GENERATED_CONFIG_FILENAMES")


# =============================================================================
# Frontend Library TSConfig Generator (with JSX)
# =============================================================================

def generate_frontend_library_tsconfig(resource_path, write_fn, internal_deps=None, is_docker=True):
    """
    Generate tsconfig for frontend shared libraries (with JSX support).

    Args:
        resource_path: Path to the resource directory
        write_fn: Write function for file output
        internal_deps: Optional internal dependencies map
        is_docker: Whether generating for Docker context

    Returns:
        dict: Generated tsconfig content
    """
    base_url = "." if is_docker else ".."
    out_dir = "./dist" if is_docker else "../dist"
    include_src = "src" if is_docker else "../src"
    exclude_prefix = "" if is_docker else "../"
    paths = {
        "@/*": ["./src/*"],
        "@application/*": ["./src/application/*"],
        "@domain/*": ["./src/domain/*"],
        "@infrastructure/*": ["./src/infrastructure/*"],
        "@presentation/*": ["./src/presentation/*"],
    }
    # NOTE: Do not add internal workspace path mappings for libraries.
    # These mappings pull external sources into the program and break
    # library builds that compile with `--rootDir src`.
    content = {
        "compilerOptions": {
            "target": "ES2022",
            "module": "ESNext",
            "moduleResolution": "bundler",
            "lib": ["DOM", "DOM.Iterable", "ESNext"],
            "baseUrl": base_url,
            "outDir": out_dir,
            "rootDir": "src" if is_docker else "../src",
            "paths": paths,
            "skipLibCheck": True,
            "strict": True,
            "emitDecoratorMetadata": True,
            "experimentalDecorators": True,
            "esModuleInterop": True,
            "forceConsistentCasingInFileNames": True,
            "jsx": "react-jsx",
            "allowSyntheticDefaultImports": True,
            "resolveJsonModule": True
        },
        "exclude": [
            exclude_prefix + "node_modules",
            exclude_prefix + "dist",
            exclude_prefix + "__tests__/**/*",
            exclude_prefix + "**/*.test.ts",
            exclude_prefix + "**/*.test.tsx",
            exclude_prefix + "**/tests/**",
            exclude_prefix + "**/*.stories.ts",
            exclude_prefix + "**/*.stories.tsx",
        ],
        "include": [include_src + "/**/*", include_src + "/**/*.tsx"]
    }
    if is_docker:
        write_fn(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['tsconfig_docker'], Utils.encode_json(content))
    else:
        write_fn(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['tsconfig_local'], Utils.encode_json(content))
