# =============================================================================
# 🎭 TILT SDK - PLAYWRIGHT CONFIG GENERATOR (free-tier stub)
# =============================================================================
# Path: .tilt/providers/typescript/playwright_config.star
# =============================================================================
# The real generator is part of a paid TDK license. When a valid license
# grants the "playwright" resource, cli/src/generator/template-engine.ts
# (vendorTdkExtension) overwrites this file with the licensed version
# fetched via extension-fetch.ts before Tilt loads it. Same function
# signature either way, so nothing else in the generator pipeline changes.
# =============================================================================

load('../../../../topologies/tilt/common/utils.star', 'Utils')
load('../../../../topologies/tilt/manifest/constants.star', 'GENERATED_CONFIG_FILENAMES')

OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")

_STUB_NOTICE = """// Playwright e2e config generation is a paid TDK feature.
// Run `tdk upgrade` to enable generated Playwright configs for this service.
"""


def generate_playwright_config(resource_path, resource_type='backend', write_fn=None):
    """
    Free-tier stub - see module header. Signature matches the licensed
    implementation so callers never need to know which one is active.
    """
    resource_name = resource_path.split('/')[-1]
    header = Utils.get_template_header(
        GENERATED_CONFIG_FILENAMES['playwright'],
        'TypeScript.generate_playwright_config() [unlicensed stub]',
        resource_name,
        resource_type.upper()
    )
    content = header + _STUB_NOTICE

    if write_fn:
        write_fn(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['playwright'], content)

    return content
