# React-specific Vite templates for frontend resources.

REACT_VITE_FRONTEND = """{header}
import {{ resolve }} from 'node:path';
import react from '@vitejs/plugin-react';
import {{ defineConfig }} from 'vite';

export default defineConfig({{
  base: '{base_path}',
  build: {{
    cssCodeSplit: false,
    minify: false,
    modulePreload: false,
    rollupOptions: {{
      output: {{
        entryFileNames: '[name].js',
        format: 'esm',
      }},
    }},
    target: 'esnext',
  }},
  define: {{
    global: 'globalThis',
  }},
  optimizeDeps: {{
    include: [{optimize_deps_include}],
  }},
  plugins: [react()],
  preview: {{
    host: '0.0.0.0',
    port: {port},
  }},
  resolve: {{
    alias: {{
      // 🎯 IMPORTANT: Order matters! More specific aliases must come FIRST
      '@/autogenerated': resolve(__dirname),
      '@': resolve(__dirname, '../src'),
      'set-cookie-parser': resolve(__dirname, '../src/utils/empty-module.js'),
{internal_aliases}
    }},
  }},
  server: {{
    host: '0.0.0.0',
    port: {port},
    hmr: {{
      port: {hmr_port},
    }},
{proxy_config}
  }},
}});
"""

REACT_VITE_FRONTEND_BUILD = """{header}
import {{ resolve }} from 'node:path';
import react from '@vitejs/plugin-react';
import {{ defineConfig }} from 'vite';

export default defineConfig({{
  mode: 'production',
  base: '{base_path}',
  build: {{
    cssCodeSplit: false,
    minify: true,
    modulePreload: false,
    rollupOptions: {{
      output: {{
        entryFileNames: '[name].js',
        format: 'esm',
        // Inline all node_modules to prevent lazy dynamic imports for CJS modules
        manualChunks: undefined,
      }},
    }},
    target: 'esnext',
  }},
  define: {{
    global: 'globalThis',
    __DEV__: 'false',
    'process.env.NODE_ENV': '"production"',
  }},
  esbuild: {{
    // Force production JSX runtime
    jsx: 'automatic',
    jsxImportSource: 'react',
    // CRITICAL: Disable development JSX (jsxDEV) for Vite 8 + Rolldown compatibility
    jsxDev: false,
  }},
  optimizeDeps: {{
    include: [
      'react',
      'react-dom',
      'react-dom/client',
      'react/jsx-runtime',
      '@tanstack/react-query',
      // Internal packages (auto-generated)
      {optimize_deps_include}
    ],
    esbuildOptions: {{
      format: 'esm',
      target: 'esnext',
      // Use production JSX runtime
      jsx: 'automatic',
      jsxImportSource: 'react',
      jsxDev: false,
    }},
  }},
  plugins: [
    react({{
      // Force automatic JSX runtime in production mode
      jsxRuntime: 'automatic',
      jsxImportSource: 'react',
    }}),
  ],
  resolve: {{
    alias: {{
      // 🎯 IMPORTANT: Order matters! More specific aliases must come FIRST
      '@/autogenerated': resolve(__dirname),
      '@': resolve(__dirname, '../src'),
      'set-cookie-parser': resolve(__dirname, '../src/utils/empty-module.js'),
      // Force production JSX runtime - alias dev runtime to production runtime
      'react/jsx-dev-runtime': 'react/jsx-runtime',
    }},
    conditions: ['browser', 'import', 'module', 'es2020', 'default'],
    mainFields: ['browser', 'module', 'jsnext:main', 'jsnext', 'main'],
  }},
}});
"""
