# =============================================================================
# 🧱 TILT SDK - TYPESCRIPT BUILDERS
# =============================================================================
# Path: .tilt/provisioner/orchestrator/builders/typescript.star
# Purpose: TypeScript build helpers for orchestrator
# =============================================================================


# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
DEFAULTS = {}

# === END INLINED CONSTANTS ===


load('../../../common/utils.star', 'Utils')
# Import filewatch ignore patterns from master config (replaces hardcoded values)


def _with_resource_prefix(pattern, resource_path):
    """Prefix dockerignore pattern so it applies to the service subtree in root context."""
    normalized = pattern
    if normalized.startswith('/'):
        normalized = normalized[1:]

    # Patterns in autogenerated dockerignore are service-relative.
    # When context is project root, scope patterns under resource_path.
    return resource_path + '/' + normalized


def get_filewatch_ignore_patterns(resource_path):
    """Return filewatch ignore patterns to prevent fsnotify buffer overflow."""
    return [
        resource_path + "/node_modules",
        resource_path + "/dist",
        resource_path + "/build",
        resource_path + "/.git",
        resource_path + "/.prisma",
        resource_path + "/.turbo",
        resource_path + "/coverage",
        resource_path + "/tmp",
        resource_path + "/temp",
    ]

def _load_autogenerated_dockerignore_patterns(dockerfile_path, resource_path):
    """
    Read Dockerfile-specific autogenerated dockerignore and convert to Tilt ignore rules.
    Note: Tilt ignore does not support negate patterns ('!'), so those are skipped.
    """
    dockerignore_path = dockerfile_path + '.dockerignore'
    content = read_file(dockerignore_path, default='')

    if not content:
        return []

    ignore_patterns = []
    for raw_line in str(content).split('\n'):
        line = raw_line.strip()
        if not line or line.startswith('#') or line.startswith('!'):
            continue
        ignore_patterns.append(_with_resource_prefix(line, resource_path))

    return ignore_patterns

def _get_resource_only_paths(resource_path):
    """
    Generate minimal file paths for docker_build 'only' parameter.
    This dramatically reduces build context from 7.4GB to just the necessary files.
    
    Args:
        resource_path: Path to service (e.g., 'services/product/{domain}/{service-name}')
    
    Returns:
        List of paths to include in build context
    """
    only_paths = [
        # Root level dependencies
        'bun.lock',
        'bun.lockb',
        'package.json',
        
        # Service-specific files
        resource_path,
        
        # Shared runtime scripts copied in generated Dockerfiles.
        'shared-platform-engineering/docker-templates',
    ]

    # Include only internal libraries referenced by this service package.json
    # (covers shared-ddd-layers/<lib> too, via resolve_lib_path's 'ddd' root -
    # no Dockerfile ever COPYs a bare shared-ddd-layers/domain or /infrastructure
    # path, so hardcoding those two here was pure dead weight: every one of a
    # large landscape's docker_build resources got its own Tilt watch
    # registration on paths most projects don't even have on disk. At 107
    # resources that's 107 duplicate watchers on the same couple of
    # nonexistent paths - real amplification if anything ever touches them,
    # and a plausible contributor to "fsnotify: queue or buffer overflow" at
    # this scale, on top of being wasted watch overhead regardless).
    # This also prevents unrelated library changes from triggering rebuilds
    # of services that don't use them.
    deps_map = Utils.build_deps_mapping(resource_path)
    for dep_path in deps_map.values():
        if dep_path not in only_paths:
            only_paths.append(dep_path)

    return only_paths

def _build_typescript_service(name, context, dockerfile, live_update_rules, deps, env=None):
    """Build a TypeScript service with Docker.
    
    Args:
        name: Resource name
        context: Docker build context
        dockerfile: Path to Dockerfile
        live_update_rules: Live update configuration
        deps: Resource dependencies
        env: Dict of environment variables to pass to container (optional)
    """
    # Extract service path from dockerfile path (e.g., 'services/product/{domain}/{service-name}')
    # The dockerfile parameter looks like: 'services/product/{domain}/{service-name}/autogenerated/Dockerfile.autogenerated'
    resource_path = '/'.join(dockerfile.split('/')[:-1])
    
    # Handle both 'autogenerated' (without dot) and '.autogenerated' (with dot)
    # Some services use 'autogenerated', others use '.autogenerated' folder
    autogenerated_folders = ['autogenerated', '.autogenerated']
    for folder in autogenerated_folders:
        suffix = '/' + folder
        if resource_path.endswith(suffix):
            resource_path = resource_path[:-len(suffix)]
            break
    
    # Also check OUTPUT.AUTOGENERATED_FOLDER for consistency
    if resource_path.endswith('/' + OUTPUT.AUTOGENERATED_FOLDER):
        resource_path = resource_path[:-(len('/' + OUTPUT.AUTOGENERATED_FOLDER))]

    ignore_patterns = _load_autogenerated_dockerignore_patterns(dockerfile, resource_path)
    
    # CRITICAL FIX: Add filewatch ignore patterns from master config
    # These prevent fsnotify buffer overflow by excluding high-churn directories
    # Previously hardcoded; now imported from TILT_RESOURCE_DEFAULTS.star
    additional_ignores = get_filewatch_ignore_patterns(resource_path)
    
    # Merge patterns, avoiding duplicates
    for pattern in additional_ignores:
        if pattern not in ignore_patterns:
            ignore_patterns.append(pattern)
    
    only_paths = _get_resource_only_paths(resource_path)

    # Build context must be the project root (.) so that COPY commands can reference
    # shared-platform-engineering/, shared-ddd-layers/, and services/ directories
    # BUT we use 'only' to dramatically reduce the context size (from 7.4GB to ~100MB)
    docker_build(
        name,
        context,
        dockerfile=dockerfile,
        target='production',
        live_update=live_update_rules,
        only=_get_resource_only_paths(resource_path),
        ignore=ignore_patterns,
        network='host',
    )


TypescriptBuilders = struct(
    build_typescript_service = _build_typescript_service,
    load_dockerignore_patterns = _load_autogenerated_dockerignore_patterns,
)

DEBUG = {}
