# Copyright (c) 2026 TDK Landscape contributors
# SPDX-License-Identifier: MIT
"""
Compose project, container and image names carry the TDK project name.

Two projects that both have a stack called `people` can run under separate Tilt
instances on one Docker daemon. Before the names were scoped, both generated the
Compose project `people-autogenerated` and the image `people_person-api:dev`, so
the second `tdk up` ran `--remove-orphans` against the first project's containers
and overwrote its image.

Runs the real generators through Tilt's interpreter (`tilt alpha tiltfile-result`).
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

pytestmark = [pytest.mark.generator]
TILT_REQUIRED = pytest.mark.skipif(shutil.which("tilt") is None, reason="tilt CLI not installed")

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCKER_DIR = REPO_ROOT / "engine" / "topologies" / "platform" / "docker"
RESULT_MARKER = "Error in fail: RESULT"

# The generated compose YAML is what Compose and Tilt actually run, so the image refs come from it.
IMAGES_BODY = """
load('@DOCKER/compose/compose.star', 'generate_backend_compose_entry', 'generate_app_compose_from_entries', 'generate_migrator_compose')

stack = 'people'
res = {'name': 'person-api', 'port': 4001}
manifest = {'appType': 'backend', 'stack': stack, 'port': 4001}
entry = generate_backend_compose_entry('services/people', stack, res, manifest)
r = {
    'app_yaml': generate_app_compose_from_entries('services/people', [entry]),
    'migrator_yaml': generate_migrator_compose('services/people', stack),
}
"""

# The Compose project name is not in the generated YAML; it comes from the shared helper the orchestrator uses.
PROJECT_BODY = """
load('@DOCKER/constants.star', 'PlatformDockerConstants')

r = {'compose_project': PlatformDockerConstants.compose_project_name('people')}
"""


def run_project(tmp_path: Path, project_name: str, body: str) -> dict:
    """Evaluate `body` as one TDK project named `project_name`; the body must assign a dict to `r`."""
    project_root = tmp_path / project_name
    (project_root / ".tdk").mkdir(parents=True)
    (project_root / ".tdk" / "project.json").write_text(json.dumps({"project": {"name": project_name}}))
    tiltfile = project_root / "Tiltfile"
    tiltfile.write_text(body.replace("@DOCKER", str(DOCKER_DIR)) + "\nfail('RESULT' + encode_json(r))\n")
    proc = subprocess.run(
        ["tilt", "alpha", "tiltfile-result", "-f", str(tiltfile)],
        capture_output=True,
        text=True,
        timeout=180,
        cwd=project_root,
        env={**os.environ, "TDK_PROJECT_ROOT": str(project_root)},
    )
    output = proc.stdout + proc.stderr
    assert RESULT_MARKER in output, output[-3000:]
    return json.loads(output.split(RESULT_MARKER, 1)[1].strip())


def image_refs(yaml_text: str) -> list[str]:
    return [line.split("image:", 1)[1].strip() for line in yaml_text.splitlines() if line.strip().startswith("image:")]


@TILT_REQUIRED
def test_two_projects_with_the_same_stack_declare_distinct_images(tmp_path):
    first = run_project(tmp_path, "tdk-person-crud-example", IMAGES_BODY)
    second = run_project(tmp_path, "acme-shop", IMAGES_BODY)

    assert image_refs(first["app_yaml"]) == ["tdk_person_crud_example_people_person-api:dev"]
    assert image_refs(second["app_yaml"]) == ["acme_shop_people_person-api:dev"]
    assert image_refs(first["migrator_yaml"]) == ["tdk_person_crud_example_people-db-migrator:dev"]
    assert image_refs(second["migrator_yaml"]) == ["acme_shop_people-db-migrator:dev"]


@TILT_REQUIRED
def test_two_projects_with_the_same_stack_get_distinct_compose_projects(tmp_path):
    first = run_project(tmp_path, "tdk-person-crud-example", PROJECT_BODY)
    second = run_project(tmp_path, "acme-shop", PROJECT_BODY)

    assert first["compose_project"] == "tdk-person-crud-example-people-autogenerated"
    assert second["compose_project"] == "acme-shop-people-autogenerated"
    # Compose names containers <project>-<service>-<replica>, so distinct projects give distinct containers.
    assert first["compose_project"] + "-person-api-1" != second["compose_project"] + "-person-api-1"


INFRA_BODY = """
load('@DOCKER/constants.star', 'PlatformDockerConstants')

r = {'database': PlatformDockerConstants.infra_compose_project_name('database-management')}
"""


@TILT_REQUIRED
def test_two_projects_get_distinct_infra_compose_projects(tmp_path):
    """Shared platform stacks (postgres, traefik, ...) must not share a Compose project either."""
    first = run_project(tmp_path, "tdk-person-crud-example", INFRA_BODY)
    second = run_project(tmp_path, "acme-shop", INFRA_BODY)

    assert first["database"] == "tdk-person-crud-example-database-management"
    assert second["database"] == "acme-shop-database-management"


def test_every_infra_docker_compose_call_names_its_project():
    """Each infra docker_compose() call passes an infra name; a two-argument call falls back to the directory-named project."""
    source = (REPO_ROOT / "engine" / "topologies" / "tilt" / "resources" / "infra-loader.star").read_text()
    calls = [line.strip() for line in source.splitlines() if "_docker_compose(" in line and "def _docker_compose" not in line]
    assert calls, "no infra _docker_compose calls found; update this guard"
    for call in calls:
        assert call.rstrip(")").rsplit(",", 1)[-1].strip().startswith("'"), call
