"""
Regression test for the sibling-service dockerignore collision bug.

manifest_resource.star computed the .dockerignore path for a resource's
Dockerfile by taking `resource_path.rsplit('/', 1)[0]` (stripping the last
path segment) before appending the resource's relative `dockerfile` field.
`resource_path` is already the resource's own directory (e.g.
"services/app/dashboard-api"), so stripping a segment lands one level up, at
the shared STACK directory (e.g. "services/app") instead.

Two sibling services in the same stack (e.g. dashboard-api and dashboard-app
under services/app) then both write to the same shared path
("services/app/.autogenerated/Dockerfile.app.autogenerated.dockerignore")
with different content (backend vs frontend dockerignore rules). Since the
two writers keep overwriting each other every Tiltfile load, the file is
never stable, Tilt sees it change on every run, and reloads the Tiltfile
forever - an infinite restart loop.

The fix drops the `.rsplit('/', 1)[0]` so the dockerignore path always sits
next to its own Dockerfile, matching how the Dockerfile path itself (and how
_register_docker_build in apply_compose_resource_registration.star resolves
a resource's `dockerfile` field) is computed.
"""

import re
from pathlib import Path

import pytest

pytestmark = [pytest.mark.fast, pytest.mark.generator]


@pytest.fixture
def manifest_resource_path() -> Path:
    return (
        Path(__file__).parent.parent.parent
        / "engine"
        / "topologies"
        / "tilt"
        / "resources"
        / "orchestrator"
        / "generators"
        / "manifest_resource.star"
    )


def test_file_exists(manifest_resource_path: Path):
    assert manifest_resource_path.exists(), f"Not found: {manifest_resource_path}"


def test_dockerignore_path_is_not_stripped_to_parent_directory(manifest_resource_path: Path):
    """The buggy `resource_path.rsplit('/', 1)[0]` pattern must not reappear in code."""
    code_lines = [
        line
        for line in manifest_resource_path.read_text().splitlines()
        if not line.strip().startswith("#")
    ]
    code = "\n".join(code_lines)
    assert "resource_path.rsplit(" not in code, (
        "dockerignore path must be resolved relative to the resource's own "
        "directory (resource_path), not a parent stripped via rsplit"
    )


def test_dockerignore_path_matches_dockerfile_path(manifest_resource_path: Path):
    """Both the logged file-list builder and the actual writer must use the
    same resource_path-relative join for the dockerignore path."""
    content = manifest_resource_path.read_text()

    matches = re.findall(
        r'dockerfile_path = ([^\n]+)',
        content,
    )
    assert matches, "Expected at least one dockerfile_path assignment"
    for expr in matches:
        assert expr.strip() == 'resource_path + "/" + dockerfile_rel_path', (
            f"dockerfile_path must join resource_path directly, got: {expr}"
        )


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
