"""
Traefik static (file-provider) wake route for `sablier.deferStart` resources.

Executes the real Starlark generators through Tilt's interpreter
(`tilt alpha tiltfile-result`) instead of inspecting source text.
Spec: openspec/changes/prioritized-cold-start/specs/on-demand-resource-startup/spec.md
Design: openspec/changes/prioritized-cold-start/design.md (D4)
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

import pytest

pytestmark = [
    pytest.mark.generator,
    pytest.mark.skipif(shutil.which("tilt") is None, reason="tilt CLI not installed"),
]

NETWORKING_DIR = Path(__file__).resolve().parents[2] / "engine" / "topologies" / "platform" / "docker" / "networking"
RESULT_MARKER = "Error in fail: RESULT"


def run_starlark(tmp_path: Path, body: str) -> dict:
    tiltfile = tmp_path / "Tiltfile"
    tiltfile.write_text(body.replace("@NETWORKING", str(NETWORKING_DIR)) + "\nfail('RESULT' + encode_json(r))\n")
    proc = subprocess.run(
        ["tilt", "alpha", "tiltfile-result", "-f", str(tiltfile)],
        capture_output=True,
        text=True,
        timeout=180,
    )
    output = proc.stdout + proc.stderr
    assert RESULT_MARKER in output, output[-3000:]
    return json.loads(output.split(RESULT_MARKER, 1)[1].strip())


MANIFEST = {
    "appType": "backend",
    "stack": "analytics",
    "sablier": {"enable": True, "deferStart": True},
}


def test_static_route_rule_matches_docker_label_project_router(tmp_path):
    r = run_starlark(
        tmp_path,
        "load('@NETWORKING/traefik.star', 'get_backend_traefik_labels')\n"
        "load('@NETWORKING/traefik_static_routes.star', 'generate_static_wake_route')\n"
        f"manifest = {MANIFEST!r}\n"
        "docker_labels = get_backend_traefik_labels(\n"
        "    'data-governance-api', 'analytics.backend.tdk_erp_system.local', '',\n"
        "    'data-governance-api', 4604, '/health', manifest=manifest,\n"
        ")\n"
        "static_yaml = generate_static_wake_route(\n"
        "    'data-governance-api', 'analytics-autogenerated', manifest, 4604,\n"
        "    'tdk-wake-gateway', 9999,\n"
        "    dependencies=[('postgres', 'analytics-autogenerated')],\n"
        ")\n"
        "r = {'docker_labels': docker_labels, 'static_yaml': static_yaml}\n",
    )

    docker_rule_match = re.search(
        r'traefik\.http\.routers\.data-governance-api-project\.rule=(.+?)"', r["docker_labels"]
    )
    docker_priority_match = re.search(
        r'traefik\.http\.routers\.data-governance-api-project\.priority=(\d+)"', r["docker_labels"]
    )
    assert docker_rule_match and docker_priority_match

    static_rule_match = re.search(r'rule:\s*"(.+?)"', r["static_yaml"])
    static_priority_match = re.search(r"priority:\s*(\d+)", r["static_yaml"])
    assert static_rule_match and static_priority_match

    # Same routing rule as the Docker-label path (task 4.2)...
    assert static_rule_match.group(1) == docker_rule_match.group(1)
    # ...but a fixed low priority, not the computed one (task 1.4's finding:
    # at equal priority the file-provider router won even over a healthy
    # Docker-discovered backend).
    assert int(static_priority_match.group(1)) == 1
    assert int(static_priority_match.group(1)) < int(docker_priority_match.group(1))


def test_static_route_headers_carry_container_names_not_just_resource_names(tmp_path):
    r = run_starlark(
        tmp_path,
        "load('@NETWORKING/traefik_static_routes.star', 'generate_static_wake_route')\n"
        f"manifest = {MANIFEST!r}\n"
        "r = {'yaml': generate_static_wake_route(\n"
        "    'data-governance-api', 'analytics-autogenerated', manifest, 4604,\n"
        "    'tdk-wake-gateway', 9999,\n"
        "    dependencies=[('postgres', 'analytics-autogenerated')],\n"
        ")}\n",
    )
    yaml = r["yaml"]
    assert 'X-Wake-Resource: "data-governance-api"' in yaml
    # Container name follows Compose's own <project>-<service>-<replica>
    # convention, confirmed empirically against a live TDK container.
    assert 'X-Wake-Container: "analytics-autogenerated-data-governance-api-1"' in yaml
    assert 'X-Wake-Deps: "postgres=analytics-autogenerated-postgres-1"' in yaml
    assert 'X-Wake-Proxy-Port: "4604"' in yaml


def test_static_route_with_no_dependencies_omits_deps_header_value(tmp_path):
    r = run_starlark(
        tmp_path,
        "load('@NETWORKING/traefik_static_routes.star', 'generate_static_wake_route')\n"
        f"manifest = {MANIFEST!r}\n"
        "r = {'yaml': generate_static_wake_route(\n"
        "    'data-governance-api', 'analytics-autogenerated', manifest, 4604,\n"
        "    'tdk-wake-gateway', 9999,\n"
        ")}\n",
    )
    assert 'X-Wake-Deps: ""' in r["yaml"]
