# Dockerfiles for backends whose `language` is not the Bun default.
#
# Bun backends use the golden-image generator. Python backends are a small
# standalone image: language-specific base image and reload command, while the build
# context (project root), `production` target, health check, and PORT contract stay the
# same as every other backend.

BASE_PORT_BACKEND = 4000

# Languages whose runtime files are owned by the provider (no Vite/tsconfig/Bun config).
PROVIDER_OWNED_LANGUAGES = ["python", "go", "rust"]

# Files a provider-owned language must scaffold; checked before generating anything.
LANGUAGE_REQUIRED_FILES = {
    "python": ["pyproject.toml", "src/main.py"],
    "go": ["go.mod", "main.go"],
    "rust": ["Cargo.toml", "src/main.rs"],
}

_CURL = """RUN apt-get update && apt-get install -y --no-install-recommends curl \\
  && rm -rf /var/lib/apt/lists/*
"""

_HEALTHCHECK = """HEALTHCHECK --interval=10s --timeout=5s --retries=3 \\
  CMD curl -f http://localhost:${{PORT:-{port}}}/health || exit 1
"""

_PYTHON = """# Generated by TDK for a Python backend. Do not edit; change service.json instead.
FROM python:3.12-slim AS base

WORKDIR /app/{res_path}

{curl}
COPY {res_path}/pyproject.toml ./
RUN pip install --no-cache-dir .

COPY {res_path}/src ./src

FROM base AS test
RUN pip install --no-cache-dir ".[dev]"
COPY {res_path}/tests ./tests
RUN pytest

FROM base AS production

{healthcheck}
EXPOSE {port}

CMD ["sh", "-c", "uvicorn main:app --app-dir src --host 0.0.0.0 --port ${{PORT:-{port}}} --reload --reload-dir src"]
"""

_GO = """# Generated by TDK for a Go backend. Do not edit; change service.json instead.
FROM golang:1.23-bookworm AS build
# The official image pins GOTOOLCHAIN=local, so a go.mod that needs a newer Go (Gin 1.12 needs 1.25) stops with "requires go >= 1.25".
# `auto` lets Go fetch the toolchain go.mod asks for; a go.mod at or below the image's Go downloads nothing.
ENV GOTOOLCHAIN=auto

WORKDIR /app/{res_path}

COPY {res_path}/go.* ./
RUN go mod download

COPY {res_path}/ ./
RUN CGO_ENABLED=0 go build -o /out/app .

FROM build AS test
RUN go test ./...
{go_development}
FROM debian:bookworm-slim AS production

{curl}
COPY --from=build /out/app /usr/local/bin/app

{healthcheck}
EXPOSE {port}

CMD ["app"]
"""

_RUST = """# Generated by TDK for a Rust backend. Do not edit; change service.json instead.
# BuildKit cache mounts keep the registry and the target directory between builds, so a rebuild after a
# source change recompiles only the crate itself, not every dependency.
FROM rust:1-slim-bookworm AS build

WORKDIR /app/{res_path}

COPY {res_path}/ ./
RUN --mount=type=cache,target=/usr/local/cargo/registry \\
    --mount=type=cache,target=/app/{res_path}/target \\
    cargo build --release && mkdir -p /out && cp target/release/app /out/app

FROM build AS test
RUN --mount=type=cache,target=/usr/local/cargo/registry \\
    --mount=type=cache,target=/app/{res_path}/target \\
    cargo test

FROM debian:bookworm-slim AS production

{curl}
COPY --from=build /out/app /usr/local/bin/app

{healthcheck}
EXPOSE {port}

CMD ["app"]
"""

# The watcher the Go development target runs. It compiles a change into a staging binary while the running app keeps serving, and stops
# and swaps the app only when that build succeeds. Air was tried first and stops the app as soon as it sees a change (engine.go `start`
# calls stopBin before buildRun), so the service stayed down for the whole compile; a Traefik health check landing in that gap kept the
# route at 503 for up to 10s. A compile error is printed to the log and the last good build keeps serving.
# `-s -w` drops debug info, which shortens the link step; delve cannot attach to a binary built this way.
# `\\n` in find's -printf format is written with a doubled backslash so the shell receives a backslash and an n.
_GO_DEV_WATCH = """#!/bin/sh
app=/tmp/app
next=/tmp/app.next
pid=

# Path, mtime and size of every file a Go build can read. Dot-directories (.git, .autogenerated), tmp/, tests and docs are ignored.
signature() {
  find . -type f -not -path '*/.*' -not -path './tmp/*' -not -name '*_test.go' -not -name '*.md' -printf '%p %T@ %s\\n' | sort | cksum
}

# The app runs in its own session so a signal reaches everything it forked and no child keeps the listen socket.
start_app() {
  setsid "$app" &
  pid=$!
}

# Succeeds only when the app is really gone; a swap on top of a live process would fail (ETXTBSY) or hit address-in-use.
stop_app() {
  [ -n "$pid" ] || return 0
  kill -TERM -- "-$pid" 2>/dev/null || kill "$pid" 2>/dev/null
  waited=0
  while kill -0 "$pid" 2>/dev/null && [ "$waited" -lt 50 ]; do
    sleep 0.1
    waited=$((waited + 1))
  done
  kill -KILL -- "-$pid" 2>/dev/null || kill -9 "$pid" 2>/dev/null
  wait "$pid" 2>/dev/null
  if kill -0 "$pid" 2>/dev/null; then
    return 1
  fi
  pid=
}

trap 'stop_app; exit 0' TERM INT

last=$(signature)
echo "[tdk] watching for Go changes; the running app keeps serving while a rebuild compiles"
start_app

while true; do
  sleep 0.2 &
  wait $!
  if [ -n "$pid" ] && ! kill -0 "$pid" 2>/dev/null; then
    wait "$pid"
    echo "[tdk] the app exited with status $?; waiting for a change to rebuild"
    pid=
  fi
  now=$(signature)
  [ "$now" = "$last" ] && continue
  last=$now
  echo "[tdk] change detected, rebuilding..."
  if go build -ldflags='-s -w' -o "$next" . ; then
    if stop_app && mv "$next" "$app"; then
      start_app
      echo "[tdk] rebuilt and restarted"
    else
      echo "[tdk] could not stop the running app or install the new build; save again to retry"
      last=
    fi
  else
    echo "[tdk] build failed; the last good build keeps running. Fix the error and save again."
  fi
done
"""

# Opt-in Go development target (`dev.liveReload`): the toolchain image plus the watcher above, which rebuilds and restarts the app when a
# source file changes. Dependencies are downloaded in their own layer and the Go module cache is a BuildKit cache mount, so an ordinary
# source edit recompiles incrementally. `go.mod`, `go.sum` and the Dockerfile still rebuild the image. The heredoc needs BuildKit's
# Dockerfile frontend 1.4 (Docker Engine 23+), which is also what makes the cache mount available.
_GO_DEVELOPMENT = """
FROM golang:1.23-bookworm AS development
ENV GOTOOLCHAIN=auto
WORKDIR /app/{res_path}
COPY {res_path}/go.* ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY {res_path}/ ./
ENV GOFLAGS=-buildvcs=false CGO_ENABLED=0
# Prime the build cache inside the image (a cache mount would not be kept), so the first edit recompiles only what changed.
# Same flags as the watcher's builds (and CGO off like the production stage), so the primed binary and cache match every later one.
RUN go build -ldflags='-s -w' -o /tmp/app .
COPY --chmod=755 <<'TDK_GO_DEV_WATCH' /usr/local/bin/tdk-go-watch
{watch_script}TDK_GO_DEV_WATCH
EXPOSE {port}
CMD ["tdk-go-watch"]
"""

def generate_language_dockerfile(res_path, language, port = BASE_PORT_BACKEND, dev = False):
    """Dockerfile text for a provider-owned backend language, or fail for an unknown one."""
    template = {"python": _PYTHON, "go": _GO, "rust": _RUST}.get(language)
    if template == None:
        fail("No Dockerfile generator for backend language '{}'".format(language))
    go_development = ""
    if dev and language == "go":
        go_development = _GO_DEVELOPMENT.format(res_path = res_path, port = port, watch_script = _GO_DEV_WATCH)
    return template.format(
        res_path = res_path,
        port = port,
        go_development = go_development,
        curl = _CURL,
        healthcheck = _HEALTHCHECK.format(port = port),
    )


def is_provider_owned_language(manifest):
    """True when the manifest selects a provider-owned language (a missing language means Bun)."""
    if not manifest:
        return False
    return manifest.get("appType", "backend") == "backend" and manifest.get("language", "bun") in PROVIDER_OWNED_LANGUAGES


def go_live_reload_enabled(manifest):
    """True for a Go service that opted in with `dev.liveReload: true` (see _GO_DEVELOPMENT); anything else stays off."""
    if not manifest or manifest.get("language", "bun") != "go":
        return False
    dev = manifest.get("dev")
    if type(dev) != "dict":
        return False
    return dev.get("liveReload") == True
