# Dockerfiles for backends whose `language` is not the Bun default.
#
# Bun backends use the golden-image generator. Python backends are a small
# standalone image: language-specific base image and reload command, while the build
# context (project root), `production` target, health check, and PORT contract stay the
# same as every other backend.

BASE_PORT_BACKEND = 4000

# Languages whose runtime files are owned by the provider (no Vite/tsconfig/Bun config).
PROVIDER_OWNED_LANGUAGES = ["python", "go", "rust"]

# Files a provider-owned language must scaffold; checked before generating anything.
LANGUAGE_REQUIRED_FILES = {
    "python": ["pyproject.toml", "src/main.py"],
    "go": ["go.mod", "main.go"],
    "rust": ["Cargo.toml", "src/main.rs"],
}

_CURL = """RUN apt-get update && apt-get install -y --no-install-recommends curl \\
  && rm -rf /var/lib/apt/lists/*
"""

_HEALTHCHECK = """HEALTHCHECK --interval=10s --timeout=5s --retries=3 \\
  CMD curl -f http://localhost:${{PORT:-{port}}}/health || exit 1
"""

_PYTHON = """# Generated by TDK for a Python backend. Do not edit; change service.json instead.
FROM python:3.12-slim AS base

WORKDIR /app/{res_path}

{curl}
COPY {res_path}/pyproject.toml ./
RUN pip install --no-cache-dir .

COPY {res_path}/src ./src

FROM base AS test
RUN pip install --no-cache-dir ".[dev]"
COPY {res_path}/tests ./tests
RUN pytest

FROM base AS production

{healthcheck}
EXPOSE {port}

CMD ["sh", "-c", "uvicorn main:app --app-dir src --host 0.0.0.0 --port ${{PORT:-{port}}} --reload --reload-dir src"]
"""

_GO = """# Generated by TDK for a Go backend. Do not edit; change service.json instead.
FROM golang:1.23-bookworm AS build

WORKDIR /app/{res_path}

COPY {res_path}/go.* ./
RUN go mod download

COPY {res_path}/ ./
RUN CGO_ENABLED=0 go build -o /out/app .

FROM build AS test
RUN go test ./...

FROM debian:bookworm-slim AS production

{curl}
COPY --from=build /out/app /usr/local/bin/app

{healthcheck}
EXPOSE {port}

CMD ["app"]
"""

_RUST = """# Generated by TDK for a Rust backend. Do not edit; change service.json instead.
# BuildKit cache mounts keep the registry and the target directory between builds, so a rebuild after a
# source change recompiles only the crate itself, not every dependency.
FROM rust:1-slim-bookworm AS build

WORKDIR /app/{res_path}

COPY {res_path}/ ./
RUN --mount=type=cache,target=/usr/local/cargo/registry \\
    --mount=type=cache,target=/app/{res_path}/target \\
    cargo build --release && mkdir -p /out && cp target/release/app /out/app

FROM build AS test
RUN --mount=type=cache,target=/usr/local/cargo/registry \\
    --mount=type=cache,target=/app/{res_path}/target \\
    cargo test

FROM debian:bookworm-slim AS production

{curl}
COPY --from=build /out/app /usr/local/bin/app

{healthcheck}
EXPOSE {port}

CMD ["app"]
"""

def generate_language_dockerfile(res_path, language, port = BASE_PORT_BACKEND):
    """Dockerfile text for a provider-owned backend language, or fail for an unknown one."""
    template = {"python": _PYTHON, "go": _GO, "rust": _RUST}.get(language)
    if template == None:
        fail("No Dockerfile generator for backend language '{}'".format(language))
    return template.format(
        res_path = res_path,
        port = port,
        curl = _CURL,
        healthcheck = _HEALTHCHECK.format(port = port),
    )


def is_provider_owned_language(manifest):
    """True when the manifest selects a provider-owned language (a missing language means Bun)."""
    if not manifest:
        return False
    return manifest.get("appType", "backend") == "backend" and manifest.get("language", "bun") in PROVIDER_OWNED_LANGUAGES
