import { renderToString } from "ink";
import { createElement } from "react";
import { describe, expect, it } from "vitest";
import type { ResourceMetadata } from "../types/index.js";
import { ResourceTable } from "./ResourceTable.js";

const resources: ResourceMetadata[] = [
  {
    name: "orders-api-with-a-long-name",
    stack: "shop",
    type: "backend",
    createdAt: "2026-10-06T12:34:56.000Z",
    lastModified: "2026-10-06T12:34:56.000Z",
    dependencies: [],
    hasDockerfile: true,
    hasTiltfile: false,
    hasDockerCompose: false,
    autogeneratedFiles: [],
    status: "ready",
  },
  {
    name: "worker",
    type: "worker",
    createdAt: "2026-10-05T12:34:56.000Z",
    lastModified: "2026-10-05T12:34:56.000Z",
    dependencies: [],
    hasDockerfile: true,
    hasTiltfile: false,
    hasDockerCompose: false,
    autogeneratedFiles: [],
    status: "pending",
  },
];

function renderTable(maxWidth: number): string {
  return renderToString(createElement(ResourceTable, { resources, maxWidth }), {
    columns: maxWidth,
  });
}

function expectLinesToFit(output: string, maxWidth: number): void {
  const lineWidths = output.split("\n").map((line) => Array.from(line).length);
  expect(Math.max(...lineWidths)).toBeLessThanOrEqual(maxWidth);
}

describe("ResourceTable", () => {
  it("uses the resource names and keeps the four core columns within a narrow width", () => {
    const output = renderTable(50);

    expect(output).toContain("Name");
    expect(output).toContain("Stack");
    expect(output).toContain("Type");
    expect(output).toContain("Status");
    expect(output).not.toContain("Created");
    expect(output).not.toContain("Logical ID");
    expect(output).not.toContain("Physical ID");
    expect(output).toContain("shop");
    expect(output).toContain("orders");
    expect(output).toContain("...");
    expect(output).toContain("-");
    expect(output).not.toContain("shop/orders-api");
    expect(output).not.toContain("orders-api-with-a-long-name");
    expectLinesToFit(output, 50);
  });

  it("adds the Created column at the wide-mode boundary without overflowing", () => {
    const output = renderTable(80);

    expect(output).toContain("Name");
    expect(output).toContain("Stack");
    expect(output).toContain("Type");
    expect(output).toContain("Status");
    expect(output).toContain("Created");
    expect(output).toContain("shop");
    expect(output).not.toContain("shop/orders-api");
    expectLinesToFit(output, 80);
  });
});
