import * as fs from "node:fs";
import * as path from "node:path";
import Handlebars from "handlebars";
import { PLATFORM_STANDARDS } from "../config/platform-standards.js";
import type { JsonValue, ProjectConfig } from "../types/index.js";
import { writeTextFile } from "../utils/file-helpers.js";
import { isStackFeatureEnabledInStacks } from "../utils/stack-features.js";
import tiltResourceDefaultsTemplate from "../../templates/TILT_RESOURCE_DEFAULTS.star.hbs" with { type: "text" };
import tiltTechStackTemplate from "../../templates/TILT_TECH_STACK.star.hbs" with { type: "text" };
import tiltfileTemplate from "../../templates/Tiltfile.hbs" with { type: "text" };
import tiltignoreTemplate from "../../templates/.tiltignore.hbs" with { type: "text" };
import specMasterTemplate from "../../templates/spec.master.hbs" with { type: "text" };

interface GeneratorContext {
  version: string;
  timestamp: string;
  tech: typeof PLATFORM_STANDARDS.tech;
  ports: typeof PLATFORM_STANDARDS.ports;
  health: typeof PLATFORM_STANDARDS.health;
  naming: typeof PLATFORM_STANDARDS.naming;
  traefik: typeof PLATFORM_STANDARDS.traefik;
  filewatchIgnores: string[];
  serviceTypes: typeof PLATFORM_STANDARDS.serviceTypes;
  paths: typeof PLATFORM_STANDARDS.paths;
  discovery: { scanIntervalSeconds: number; maxManifestsPerRoot: number; paths: string[] };
  docker: typeof PLATFORM_STANDARDS.docker;
  runtime: typeof PLATFORM_STANDARDS.runtime;
  project: ProjectConfig["project"];
  stacks: ProjectConfig["stacks"];
  alwaysEnabledInfra: string[];
  optionalInfra: ProjectConfig["optional_infra"];
  serviceDescriptions: Record<string, string>;
  infraDescriptions: Record<string, string>;
}

// Generic resource descriptions - no hardcoded service names
// Users define their own service descriptions in project.json
const RESOURCE_DESCRIPTIONS: Record<string, string> = {
  proxy: "Traefik reverse proxy",
  verdaccio: "Private npm registry",
  "database-management": "PostgreSQL database",
};

const INFRA_DESCRIPTIONS: Record<string, string> = {
  monitoring: "Signoz, SkyWalking (RAM intensive)",
  elk: "Elasticsearch/Logstash/Kibana",
  debezium: "CDC with Kafka/Zookeeper",
  golden_image: "Golden image rebuild (one-time)",
  verdaccio: "Premium local npm registry",
};

/**
 * List of all files generated by the template engine.
 * Used for iteration and type-safe access to generated content.
 */
const ALL_GENERATED_FILES = [
  "TILT_TECH_STACK.star",
  "TILT_RESOURCE_DEFAULTS.star",
  "spec.master",
  "Tiltfile",
  ".tiltignore",
] as const;

/**
 * Type representing valid generated file names.
 * Derived from ALL_GENERATED_FILES const array for type safety.
 */
type GeneratedFileName = (typeof ALL_GENERATED_FILES)[number];

const EMBEDDED_TEMPLATES: Record<string, string> = {
  ".tiltignore": tiltignoreTemplate,
  "TILT_RESOURCE_DEFAULTS.star": tiltResourceDefaultsTemplate,
  "TILT_TECH_STACK.star": tiltTechStackTemplate,
  Tiltfile: tiltfileTemplate,
  "spec.master": specMasterTemplate,
};

export class TemplateEngine {
  private templatesDir: string;

  constructor(templatesDir?: string) {
    const currentDir = import.meta.dirname || path.dirname(new URL(import.meta.url).pathname);
    this.templatesDir = templatesDir || path.join(currentDir, "..", "..", "templates");
    this.registerHelpers();
  }

  private formatStarlarkValue(val: JsonValue): string {
    if (val === null || val === undefined) {
      return "None";
    }
    if (typeof val === "string") {
      return `"${val.replace(/"/g, '\\"')}"`;
    }
    if (typeof val === "boolean") {
      return val ? "True" : "False";
    }
    if (typeof val === "number") {
      return String(val);
    }
    if (Array.isArray(val)) {
      const items = val.map((item) => this.formatStarlarkValue(item));
      return `[${items.join(", ")}]`;
    }
    if (typeof val === "object") {
      const entries = Object.entries(val).map(([key, v]) => {
        return `"${key}": ${this.formatStarlarkValue(v)}`;
      });
      return `{${entries.join(", ")}}`;
    }
    return String(val);
  }

  private registerHelpers(): void {
    Handlebars.registerHelper("starlark", (value: JsonValue): Handlebars.SafeString => {
      return new Handlebars.SafeString(this.formatStarlarkValue(value));
    });

    Handlebars.registerHelper("starlarkArray", (value: JsonValue[]): Handlebars.SafeString => {
      if (!Array.isArray(value)) return new Handlebars.SafeString("[]");
      const items = value.map((item) => this.formatStarlarkValue(item));
      return new Handlebars.SafeString(`[${items.join(", ")}]`);
    });

    Handlebars.registerHelper("json", (value: JsonValue): string => {
      return JSON.stringify(value);
    });
  }

  buildContext(projectConfig: ProjectConfig): GeneratorContext {
    return {
      version: PLATFORM_STANDARDS.version,
      timestamp: new Date().toISOString(),
      tech: PLATFORM_STANDARDS.tech,
      ports: PLATFORM_STANDARDS.ports,
      health: PLATFORM_STANDARDS.health,
      naming: PLATFORM_STANDARDS.naming,
      traefik: PLATFORM_STANDARDS.traefik,
      filewatchIgnores: [...PLATFORM_STANDARDS.filewatchIgnores],
      serviceTypes: PLATFORM_STANDARDS.serviceTypes,
      paths: PLATFORM_STANDARDS.paths,
      discovery: {
        scanIntervalSeconds: PLATFORM_STANDARDS.discovery.scanIntervalSeconds,
        maxManifestsPerRoot: PLATFORM_STANDARDS.discovery.maxManifestsPerRoot,
        paths: projectConfig.discovery.paths,
      },
      docker: PLATFORM_STANDARDS.docker,
      runtime: PLATFORM_STANDARDS.runtime,
      project: projectConfig.project,
      stacks: projectConfig.stacks,
      alwaysEnabledInfra: projectConfig.always_enabled_infra ?? [
        "database-management",
        "proxy",
        "infisical",
      ],
      optionalInfra: projectConfig.optional_infra,
      serviceDescriptions: RESOURCE_DESCRIPTIONS,
      infraDescriptions: INFRA_DESCRIPTIONS,
    };
  }

  private loadTemplate(templateName: string): HandlebarsTemplateDelegate {
    const templatePath = path.join(this.templatesDir, `${templateName}.hbs`);
    const templateSource = fs.existsSync(templatePath)
      ? fs.readFileSync(templatePath, "utf-8")
      : EMBEDDED_TEMPLATES[templateName];
    if (!templateSource) {
      throw new Error(`Template not found: ${templatePath}`);
    }
    return Handlebars.compile(templateSource);
  }

  generateTechStack(context: GeneratorContext): string {
    const template = this.loadTemplate("TILT_TECH_STACK.star");
    return template(context);
  }

  generateServiceDefaults(context: GeneratorContext): string {
    const template = this.loadTemplate("TILT_RESOURCE_DEFAULTS.star");
    return template(context);
  }

  generateSpecMaster(context: GeneratorContext): string {
    const template = this.loadTemplate("spec.master");
    return template(context);
  }

  generateTiltfile(context: GeneratorContext): string {
    const template = this.loadTemplate("Tiltfile");
    return template(context);
  }

  generateTiltIgnore(context: GeneratorContext): string {
    const template = this.loadTemplate(".tiltignore");
    return template(context);
  }

  generateAll(projectConfig: ProjectConfig): Record<GeneratedFileName, string> {
    const context = this.buildContext(projectConfig);

    return {
      "TILT_TECH_STACK.star": this.generateTechStack(context),
      "TILT_RESOURCE_DEFAULTS.star": this.generateServiceDefaults(context),
      "spec.master": this.generateSpecMaster(context),
      Tiltfile: this.generateTiltfile(context),
      ".tiltignore": this.generateTiltIgnore(context),
    };
  }
}

function toComposeProjectName(projectName: string): string {
  return projectName.replace(/-/g, "_");
}

export function generateDatabaseManagementCompose(projectConfig: ProjectConfig): string {
  const name = toComposeProjectName(projectConfig.project.name || "tdk_project");
  return `###############################################################################
# SYSTEM-GENERATED - DO NOT EDIT
# Stack feature: database-management
# Source: .tdk/project.json stacks.*.services includes "database-management"
###############################################################################

services:
  postgres:
    image: postgres:16-alpine
    container_name: ${name}_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${name}
      POSTGRES_PASSWORD: \${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ${name}_postgres_data:/var/lib/postgresql/data
    networks:
      - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${name} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  database:
    name: ${name}_database
    external: true

volumes:
  ${name}_postgres_data:
`;
}

/**
 * Type guard to validate if an unknown value is a valid ProjectConfig.
 *
 * NOTE: The `as` assertions below are INTENTIONAL and SAFE:
 * - We've already verified `typeof value === 'object'` and `value !== null`
 * - TypeScript doesn't automatically narrow `{}` to `Record<string, unknown>`
 * - Each assertion is immediately followed by property type checks
 * - This pattern is standard for deep object validation in type guards
 */
function isProjectConfig(value: unknown): value is ProjectConfig {
  if (!value || typeof value !== "object") {
    return false;
  }

  // Safe to assert as Record after null and object type checks
  const config = value as Record<string, unknown>;

  if (typeof config.version !== "string") {
    return false;
  }

  if (!config.project || typeof config.project !== "object") {
    return false;
  }
  const project = config.project as Record<string, unknown>;
  if (typeof project.name !== "string" || typeof project.version !== "string") {
    return false;
  }

  if (!config.stacks || typeof config.stacks !== "object") {
    return false;
  }
  const stacks = config.stacks as Record<string, unknown>;
  if (
    typeof stacks.pre_alpha !== "object" ||
    typeof stacks.alpha !== "object" ||
    typeof stacks.beta !== "object" ||
    typeof stacks.out_of_scope !== "object"
  ) {
    return false;
  }

  if (!config.optional_infra || typeof config.optional_infra !== "object") {
    return false;
  }
  const optionalInfra = config.optional_infra as Record<string, unknown>;
  if (
    typeof optionalInfra.monitoring !== "boolean" ||
    typeof optionalInfra.elk !== "boolean" ||
    typeof optionalInfra.debezium !== "boolean" ||
    typeof optionalInfra.golden_image !== "boolean" ||
    typeof optionalInfra.verdaccio !== "boolean"
  ) {
    return false;
  }

  if (!config.discovery || typeof config.discovery !== "object") {
    return false;
  }
  const discovery = config.discovery as Record<string, unknown>;
  if (!Array.isArray(discovery.paths)) {
    return false;
  }

  return true;
}

export function readProjectConfig(projectRoot: string): ProjectConfig {
  const projectJsonPath = path.join(projectRoot, ".tdk", "project.json");

  if (!fs.existsSync(projectJsonPath)) {
    throw new Error(`Project config not found: ${projectJsonPath}. Run 'tdk project init' first.`);
  }

  const jsonContent = fs.readFileSync(projectJsonPath, "utf-8");
  const parsed: unknown = JSON.parse(jsonContent);

  if (!isProjectConfig(parsed)) {
    throw new Error(
      "Invalid project.json: missing or invalid required fields. " +
        "Expected: version (string), project (object with name/version), " +
        "stacks (object with pre_alpha/alpha/beta/out_of_scope), " +
        "optional_infra (object with boolean flags), " +
        "discovery (object with paths array)",
    );
  }

  return parsed;
}

export async function generateMasterConfigs(projectRoot: string): Promise<void> {
  const projectConfig = readProjectConfig(projectRoot);

  const outputDir = path.join(projectRoot, ".tdk", ".tdk-out");
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const engine = new TemplateEngine();
  const files = engine.generateAll(projectConfig);

  for (const filename of ALL_GENERATED_FILES) {
    const content = files[filename];
    const filePath = path.join(outputDir, filename);
    writeTextFile(filePath, content);
    console.log(`✓ Generated: .tdk/.tdk-out/${filename}`);
  }

  if (isStackFeatureEnabledInStacks(projectConfig.stacks, "database-management")) {
    const composeDir = path.join(projectRoot, "services", "platform", "database-management");
    fs.mkdirSync(composeDir, { recursive: true });
    const composePath = path.join(
      composeDir,
      "docker-compose.yml",
    );
    writeTextFile(composePath, generateDatabaseManagementCompose(projectConfig));
    console.log("✓ Generated: services/platform/database-management/docker-compose.yml");
  }

  // Copy .tiltignore to project root so Tilt uses it
  const tiltignoreSource = path.join(outputDir, ".tiltignore");
  const tiltignoreTarget = path.join(projectRoot, ".tiltignore");
  if (fs.existsSync(tiltignoreSource)) {
    fs.copyFileSync(tiltignoreSource, tiltignoreTarget);
    console.log(`✓ Copied: .tiltignore → project root`);
  }

  await vendorTdkExtension(projectRoot);

  console.log("");
  console.log("💡 To start Tilt: tdk up");
}

// The generated Tiltfile loads the TDK Tilt extension (engine, discovery,
// specs, ext starlark modules). The extension repo may stay private, so we
// vendor a working copy into .tdk/.tdk-out/tdk-cli-ext/ at generation time.
// This makes `tdk up` work offline and on any machine - no hardcoded paths,
// no dependency on a private GitHub repo.
const TDK_EXTENSION_DIRS = ["engine", "discovery", "specs", "ext"] as string[];

// Walk up from this module's own location looking for a directory that has
// both Tiltfile and engine/ next to it - true when cli/ and engine/ ship
// together in the same repo (the public tdk-cli-core layout, where a plain
// `git clone` + `bun run` needs zero extra config to find the engine).
function findSelfContainedEngineRoot(): string | null {
  let dir = import.meta.dirname || process.cwd();
  for (let i = 0; i < 6; i++) {
    if (fs.existsSync(path.join(dir, "Tiltfile")) && fs.existsSync(path.join(dir, "engine"))) {
      return dir;
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

async function vendorTdkExtension(projectRoot: string): Promise<void> {
  const outputDir = path.join(projectRoot, ".tdk", ".tdk-out");
  const vendoredDir = path.join(outputDir, "tdk-cli-ext");

  // Source resolution order:
  //   1. $TDK_EXTENSION_SOURCE (explicit override)
  //   2. Self-contained repo (engine/ ships next to cli/ - public tdk-cli-core)
  //   3. Executable-adjacent checkout (bundled installs)
  //   4. Relative ../tdk-cli sibling (monorepo maintainer layout)
  let sources: string[] = [];
  if (process.env.TDK_EXTENSION_SOURCE) {
    sources.push(process.env.TDK_EXTENSION_SOURCE);
  }
  const selfContainedRoot = findSelfContainedEngineRoot();
  if (selfContainedRoot) {
    sources.push(selfContainedRoot);
  }
  // process.execPath is the compiled binary's own path when running as a
  // standalone executable (what we actually need here). In dev mode it's
  // the bun CLI's own path instead (e.g. ~/.bun/bin/bun) - harmless, that
  // candidate just won't match anything and falls through to the next
  // one. Note: process.executablePath is not a real property on Node or
  // Bun's process object - it was always undefined, silently falling
  // back to cwd() instead of the binary's real location.
  const exeDir = path.dirname(process.execPath);
  sources.push(path.join(exeDir, "tdk-cli"));
  sources.push(path.join(projectRoot, "..", "tdk-cli"));

  let sourceRoot = "";
  for (const candidate of sources) {
    if (
      candidate &&
      fs.existsSync(path.join(candidate, "Tiltfile")) &&
      fs.existsSync(path.join(candidate, "engine"))
    ) {
      sourceRoot = candidate;
      break;
    }
  }

  if (!sourceRoot) {
    console.warn(
      "⚠️  TDK extension not found - set TDK_EXTENSION_SOURCE to its checkout path " +
        "and re-run `tdk project` (or `tdk config regenerate`) to vendor it before `tdk up`.",
    );
    return;
  }

  if (!fs.existsSync(vendoredDir)) {
    fs.mkdirSync(vendoredDir, { recursive: true });
  }
  fs.copyFileSync(path.join(sourceRoot, "Tiltfile"), path.join(vendoredDir, "Tiltfile"));
  for (const dir of TDK_EXTENSION_DIRS) {
    fs.cpSync(path.join(sourceRoot, dir), path.join(vendoredDir, dir), {
      recursive: true,
    });
  }
  console.log(`✓ Vendored TDK extension → .tdk/.tdk-out/tdk-cli-ext/`);

  // Best-effort: if TDK_LICENSE_KEY is set and grants any paid resource,
  // overlay the premium bundle over the stub files just vendored above.
  // No-ops silently (beyond a warning) if there's no key, the fetch
  // fails, or nothing's granted - the free engine already works fine on
  // its own.
  try {
    const { applyPremiumOverlay } = await import("./extension-fetch.js");
    await applyPremiumOverlay(projectRoot, vendoredDir);
  } catch (err) {
    console.warn(`⚠️  Premium overlay skipped: ${(err as Error).message}`);
  }
}

export function verifyMasterConfigs(projectRoot: string): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  const projectConfig = readProjectConfig(projectRoot);
  const engine = new TemplateEngine();
  const expectedFiles = engine.generateAll(projectConfig);

  const outputDir = path.join(projectRoot, ".tdk", ".tdk-out");

  for (const filename of ALL_GENERATED_FILES) {
    const expectedContent = expectedFiles[filename];
    const filePath = path.join(outputDir, filename);

    if (!fs.existsSync(filePath)) {
      errors.push(`Missing file: .tdk/.tdk-out/${filename}`);
      continue;
    }

    const actualContent = fs.readFileSync(filePath, "utf-8");
    if (actualContent !== expectedContent) {
      errors.push(`Out of sync: .tdk/.tdk-out/${filename} (run 'tdk config regenerate')`);
    }
  }

  return { valid: errors.length === 0, errors };
}
