#!/usr/bin/env bash
# Copyright (c) 2026 TDK Landscape contributors
# SPDX-License-Identifier: MIT
# Scaffold one frontend per framework provider in ONE isolated throwaway project, run them through a single real `tdk up` and Traefik,
# and check each one: its route answers 200, the HTML carries the app's module script, and that script is served under the base path
# with a JavaScript content type. This is stronger than a `vite build`: it proves the generated Dockerfile, nginx and Traefik route.
# Needs Docker, Tilt and a built CLI (cli/dist). Uses unique names and random alternate ports, and removes only the containers,
# networks and images carrying its own unique project name (it never calls `tdk down`).
#
# Usage: scripts/verify-frontend-frameworks.sh [framework ...]     (default: every framework provider)
#        VERIFY_WAIT_SECONDS bounds the wait for all routes to answer (default 900).
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
if [ "$#" -gt 0 ]; then
  frameworks=("$@")
else
  frameworks=(react vue svelte preact lit solid qwik vanilla tanstack-router)
fi

proj="fe$$"
work="$(mktemp -d)/$proj"
mkdir -p "$work"
http_port=$((30000 + RANDOM % 2000))
tdk() { TDK_EXTENSION_SOURCE="$root" node "$root/cli/bin/tdk.js" "$@"; }

cleanup() {
  pkill -f "tilt up.*$proj" >/dev/null 2>&1 || true
  docker rm -f $(docker ps -aq --filter "name=$proj") >/dev/null 2>&1 || true
  docker network ls --format '{{.Name}}' | grep "^${proj}" | xargs -r docker network rm >/dev/null 2>&1 || true
  # Every tag of this run's own images (Tilt adds a tilt-<hash> tag next to :dev), and its golden-layer base images.
  docker images --format '{{.Repository}}:{{.Tag}}' | grep -E "^app_${proj}[-_:]|^${proj}-l[0-9]+" | xargs -r docker rmi -f >/dev/null 2>&1 || true
}
trap cleanup EXIT

cd "$work"
git init -q .
tdk project --yes >/dev/null 2>&1
printf '\nTDK_HTTP_PORT=%s\nTDK_HTTPS_PORT=%s\nTDK_POSTGRES_PORT=%s\n' \
  "$http_port" "$((32000 + RANDOM % 2000))" "$((34000 + RANDOM % 2000))" >> .env
for fw in "${frameworks[@]}"; do
  tdk resource "$proj-$fw" --type frontend --framework "$fw" --stack app --yes >/dev/null
done
nohup node "$root/cli/bin/tdk.js" up app >"$work/up.log" 2>&1 &

route() { echo "http://127.0.0.1:$http_port/$proj-$1/"; }
code() { curl -s -o /dev/null -m 4 -w '%{http_code}' -H "Host: app.$proj.localhost" "$1" || true; }

deadline=$((SECONDS + ${VERIFY_WAIT_SECONDS:-900}))
while [ "$SECONDS" -lt "$deadline" ]; do
  pending=0
  for fw in "${frameworks[@]}"; do
    [ "$(code "$(route "$fw")")" = "200" ] || pending=1
  done
  [ "$pending" = 0 ] && break
  sleep 5
done

failed=()
for fw in "${frameworks[@]}"; do
  url="$(route "$fw")"
  html="$(curl -s -m 5 -H "Host: app.$proj.localhost" "$url" || true)"
  asset="$(printf '%s' "$html" | grep -oE 'src="[^"]*\.js"' | head -1 | sed 's/^src="//; s/"$//' || true)"
  status="$(code "$url")"
  asset_info="no module script in the HTML"
  asset_ok=1
  if [ -n "$asset" ]; then
    case "$asset" in /*) asset_path="$asset" ;; *) asset_path="/$proj-$fw/$asset" ;; esac
    asset_info="$(curl -s -o /dev/null -m 5 -w '%{http_code} %{content_type}' -H "Host: app.$proj.localhost" "http://127.0.0.1:$http_port$asset_path" || true)"
    case "$asset_info" in "200 "*javascript*) asset_ok=0 ;; esac
  fi
  if [ "$status" = "200" ] && [ "$asset_ok" = 0 ]; then
    echo "PASS $fw: through tdk up and Traefik, GET /$proj-$fw/ -> 200, $asset -> $asset_info"
  else
    echo "FAIL $fw: GET /$proj-$fw/ -> $status, asset ${asset:-none} -> $asset_info" >&2
    docker logs "${proj}-app-autogenerated-$proj-$fw-1" 2>&1 | tail -8 >&2 || true
    failed+=("$fw")
  fi
done

if [ "${#failed[@]}" -gt 0 ]; then
  echo "FAIL frontend frameworks: ${failed[*]}" >&2
  exit 1
fi
echo "PASS all ${#frameworks[@]} frontend frameworks: ${frameworks[*]}"
