#!/usr/bin/env bash
# Run one examples/byo/<name> service through a real `tdk up` and check it answers through Traefik.
# Needs Docker, Tilt, and a built CLI (cli/dist). Uses an isolated throwaway project with unique
# names and random alternate ports, and removes only the containers and networks carrying its own
# unique project name (it never calls `tdk down`, which can touch other projects' containers).
#
# Unlike verify-byo-example.sh, which runs the image alone, this gives the service TDK's DATABASE_URL
# and Postgres, so it is the check for apps that need a database.
#
# Usage: scripts/verify-byo-tdk.sh <name> [health-path]     (default health path /health)
set -euo pipefail

name="${1:?usage: verify-byo-tdk.sh <name> [health-path]}"
health="${2:-/health}"
root="$(cd "$(dirname "$0")/.." && pwd)"
src="$root/examples/byo/$name"
[ -d "$src" ] || { echo "no such example: $src" >&2; exit 2; }

proj="svc${name//[^a-z0-9]/}$$"
proj="${proj:0:24}"
work="$(mktemp -d)/$proj"
mkdir -p "$work"
http_port=$((30000 + RANDOM % 2000))
tdk() { TDK_EXTENSION_SOURCE="$root" node "$root/cli/bin/tdk.js" "$@"; }

cleanup() {
  pkill -f "tilt up.*$proj" >/dev/null 2>&1 || true
  docker rm -f $(docker ps -aq --filter "name=$proj") >/dev/null 2>&1 || true
  docker network ls --format '{{.Name}}' | grep "^${proj}" | xargs -r docker network rm >/dev/null 2>&1 || true
}
trap cleanup EXIT

cd "$work"
git init -q .
tdk project --yes >/dev/null 2>&1
printf '\nTDK_HTTP_PORT=%s\nTDK_HTTPS_PORT=%s\nTDK_POSTGRES_PORT=%s\n' \
  "$http_port" "$((32000 + RANDOM % 2000))" "$((34000 + RANDOM % 2000))" >> .env
mkdir -p "services/app/$proj"
cp -R "$src/." "services/app/$proj/"
rm -f "services/app/$proj/README.md"
(cd "services/app/$proj" && tdk resource "$proj" --type bring-your-own --stack app \
  --register-existing --dockerfile ./Dockerfile --health-path "$health" --yes >/dev/null)
nohup node "$root/cli/bin/tdk.js" up app >"$work/up.log" 2>&1 &

url="http://127.0.0.1:$http_port/api/$proj$health"
status=000
for _ in $(seq 1 "${VERIFY_WAIT_SECONDS:-600}"); do
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' -H "Host: api.$proj.localhost" "$url" || true)"
  [ "$status" = "200" ] && break
  sleep 1
done

if [ "$status" = "200" ]; then
  echo "PASS $name: through tdk up and Traefik, GET /api/$proj$health -> 200 ($(curl -s -m 3 -H "Host: api.$proj.localhost" "$url" | head -c 80))"
else
  echo "FAIL $name: GET /api/$proj$health -> $status" >&2
  docker logs "app-autogenerated-$proj-1" 2>&1 | tail -20 >&2 || true
  exit 1
fi
