#!/usr/bin/env bash
# Scaffold an `mcp` resource in an isolated throwaway project, run it through a real `tdk up` and Traefik, and talk to it with the
# official MCP TypeScript SDK client (not just curl): connect, list the tools, call the `echo` tool. The client uses the real host
# name `api.<project>.localhost`, so this also shows that a client resolves it.
# Needs Docker, Tilt, Node 18+ with npm and network access (it installs @modelcontextprotocol/sdk into a temp directory), and a built
# CLI (cli/dist). Uses unique names and random alternate ports, and removes only the containers, networks and images carrying its own
# unique project name (it never calls `tdk down`, which can touch other projects' containers).
#
# Usage: scripts/verify-mcp.sh        (VERIFY_WAIT_SECONDS bounds the wait for the resource to become healthy, default 600)
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
proj="mcp$$"
work="$(mktemp -d)/$proj"
clientdir="$(mktemp -d)"
mkdir -p "$work"
http_port=$((30000 + RANDOM % 2000))
tdk() { TDK_EXTENSION_SOURCE="$root" node "$root/cli/bin/tdk.js" "$@"; }

cleanup() {
  pkill -f "tilt up.*$proj" >/dev/null 2>&1 || true
  docker rm -f $(docker ps -aq --filter "name=$proj") >/dev/null 2>&1 || true
  docker network ls --format '{{.Name}}' | grep "^${proj}" | xargs -r docker network rm >/dev/null 2>&1 || true
  # Tilt also tags the build as app_<project>:tilt-<hash>, so remove every tag of this run's own repository, not just :dev.
  docker images --format '{{.Repository}}:{{.Tag}}' | grep -E "^app_${proj}:" | xargs -r docker rmi -f >/dev/null 2>&1 || true
  docker images --format '{{.Repository}}:{{.Tag}}' | grep -E "^${proj}-l[0-9]+" | xargs -r docker rmi -f >/dev/null 2>&1 || true
  rm -rf "$clientdir"
}
trap cleanup EXIT

cd "$work"
git init -q .
tdk project --yes >/dev/null 2>&1
printf '\nTDK_HTTP_PORT=%s\nTDK_HTTPS_PORT=%s\nTDK_POSTGRES_PORT=%s\n' \
  "$http_port" "$((32000 + RANDOM % 2000))" "$((34000 + RANDOM % 2000))" >> .env
tdk resource "$proj" --type mcp --stack app --yes >/dev/null
nohup node "$root/cli/bin/tdk.js" up app >"$work/up.log" 2>&1 &

status=000
for _ in $(seq 1 "${VERIFY_WAIT_SECONDS:-600}"); do
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' -H "Host: api.$proj.localhost" "http://127.0.0.1:$http_port/api/$proj/health" || true)"
  [ "$status" = "200" ] && break
  sleep 1
done
if [ "$status" != "200" ]; then
  echo "FAIL mcp: the resource did not become healthy (GET /api/$proj/health -> $status)" >&2
  docker logs "app-autogenerated-$proj-1" 2>&1 | tail -20 >&2 || true
  exit 1
fi

cd "$clientdir"
npm init -y >/dev/null 2>&1
npm install --no-audit --no-fund @modelcontextprotocol/sdk@1 >/dev/null 2>&1
cat > client.mjs <<'JS'
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

const client = new Client({ name: "tdk-verify-mcp", version: "0.0.0" });
await client.connect(new StreamableHTTPClientTransport(new URL(process.argv[2])));
const { tools } = await client.listTools();
const result = await client.callTool({ name: "echo", arguments: { message: "hello from the MCP client" } });
console.log(JSON.stringify({ server: client.getServerVersion()?.name, tools: tools.map((t) => t.name), echo: result.content?.[0]?.text, isError: !!result.isError }));
await client.close();
JS

url="http://api.$proj.localhost:$http_port/api/$proj/mcp"
if out="$(node client.mjs "$url" 2>&1)" && echo "$out" | grep -q '"echo":"hello from the MCP client"' && echo "$out" | grep -q '"isError":false'; then
  echo "PASS mcp: the MCP SDK client connected through tdk up and Traefik at $url -> $out"
else
  echo "FAIL mcp: the MCP SDK client could not use $url" >&2
  echo "$out" >&2
  exit 1
fi
