#!/usr/bin/env bash
# Run one examples/byo-jobs/<name> one-shot job through a real `tdk up` and check the result.
# Needs Docker, Tilt, and a built CLI (cli/dist). Uses an isolated throwaway project with unique
# names and alternate ports, and removes only the containers and networks carrying its own
# unique project name (it never calls `tdk down`, which can touch other projects' containers).
#
# Checks, in order: the container exits 0, it was not restarted (restart policy "no"), and the
# query in verify.sql returns the text in verify.expect against TDK's Postgres.
#
# Usage: scripts/verify-byo-job.sh <name>
set -euo pipefail

name="${1:?usage: verify-byo-job.sh <name>}"
root="$(cd "$(dirname "$0")/.." && pwd)"
src="$root/examples/byo-jobs/$name"
[ -d "$src" ] || { echo "no such example: $src" >&2; exit 2; }

proj="job${name//[^a-z0-9]/}$$"
work="$(mktemp -d)/$proj"
mkdir -p "$work"
tdk() { TDK_EXTENSION_SOURCE="$root" node "$root/cli/bin/tdk.js" "$@"; }
res="$proj"          # resource name; unique because Traefik watches every container on the daemon
until_exit=${VERIFY_WAIT_SECONDS:-240}

cleanup() {
  pkill -f "tilt up.*$proj" >/dev/null 2>&1 || true
  docker rm -f $(docker ps -aq --filter "name=$proj") >/dev/null 2>&1 || true
  docker network ls --format '{{.Name}}' | grep "^${proj}" | xargs -r docker network rm >/dev/null 2>&1 || true
}
trap cleanup EXIT

cd "$work"
git init -q .
tdk project --yes >/dev/null 2>&1
printf '\nTDK_HTTP_PORT=%s\nTDK_HTTPS_PORT=%s\nTDK_POSTGRES_PORT=%s\n' \
  "$((30000 + RANDOM % 2000))" "$((32000 + RANDOM % 2000))" "$((34000 + RANDOM % 2000))" >> .env
mkdir -p "services/app/$res"
cp -R "$src/." "services/app/$res/"
rm -f "services/app/$res/verify.sql" "services/app/$res/verify.expect"
(cd "services/app/$res" && tdk resource "$res" --type bring-your-own --stack app \
  --register-existing --dockerfile ./Dockerfile --restart no --yes >/dev/null)
nohup node "$root/cli/bin/tdk.js" up app >"$work/up.log" 2>&1 &

container="app-autogenerated-$res-1"
state=""
for _ in $(seq 1 "$until_exit"); do
  state="$(docker inspect -f '{{.State.Status}} {{.State.ExitCode}} {{.RestartCount}}' "$container" 2>/dev/null || true)"
  case "$state" in exited*) break ;; esac
  sleep 1
done
sleep 8   # a restart-looping container would show a higher count by now
state="$(docker inspect -f '{{.State.Status}} {{.State.ExitCode}} {{.RestartCount}} {{.HostConfig.RestartPolicy.Name}}' "$container" 2>/dev/null || echo missing)"
echo "container: $state"
set -- $state
if [ "${1:-}" != "exited" ] || [ "${2:-}" != "0" ] || [ "${3:-}" != "0" ]; then
  echo "FAIL $name: expected 'exited 0 0'" >&2
  docker logs "$container" 2>&1 | tail -15 >&2 || true
  exit 1
fi

pw="$(grep -E '^DB_PASSWORD=' .env | head -1 | cut -d= -f2-)"
got="$(docker exec -e PGPASSWORD="$pw" "${proj}_postgres" psql -U "$proj" -d "${proj}_app" -tA -c "$(cat "$src/verify.sql")" 2>&1 || true)"
want="$(cat "$src/verify.expect")"
if [ "$got" = "$want" ]; then
  echo "PASS $name: job exited 0 with 0 restarts, and verify.sql -> $got"
else
  echo "FAIL $name: verify.sql returned '$got', wanted '$want'" >&2
  exit 1
fi
