#!/usr/bin/env bash
# Run two examples/byo services in ONE throwaway project through a real `tdk up`: a dependency (for example a database server)
# and an app that connects to it over the landscape's Docker network. The check is the app's health route, so write that route
# to need the dependency (a real round trip), and a 200 means the two actually talk.
# Needs Docker, Tilt, and a built CLI (cli/dist). Uses unique names and random alternate ports, and removes only containers,
# networks and images carrying its own unique project name (it never calls `tdk down`).
#
# The app's Dockerfile must contain an `ENV <VAR>=http://<dep-name>:<dep-port>` line; this script rewrites the host name in
# its scratch copy to the dependency's unique run name (resource names must be unique across projects sharing one Docker daemon).
#
# Usage: scripts/verify-byo-pair.sh <dep-example> <dep-port> <dep-health> <app-example> <env-var> [app-health]
#   e.g. scripts/verify-byo-pair.sh turso 4500 /health turso-app LIBSQL_URL /health
set -euo pipefail

dep="${1:?usage: verify-byo-pair.sh <dep-example> <dep-port> <dep-health> <app-example> <env-var> [app-health]}"
dep_port="${2:?dep port}"
dep_health="${3:?dep health path}"
app="${4:?app example}"
envvar="${5:?env var holding the dependency URL}"
app_health="${6:-/health}"
root="$(cd "$(dirname "$0")/.." && pwd)"
for e in "$dep" "$app"; do [ -d "$root/examples/byo/$e" ] || { echo "no such example: $e" >&2; exit 2; }; done

proj="pair${app//[^a-z0-9]/}$$"
proj="${proj:0:20}"
dep_name="dep${dep//[^a-z0-9]/}$$"
dep_name="${dep_name:0:20}"
app_name="app${app//[^a-z0-9]/}$$"
app_name="${app_name:0:20}"
work="$(mktemp -d)/$proj"
mkdir -p "$work"
http_port=$((30000 + RANDOM % 2000))
tdk() { TDK_EXTENSION_SOURCE="$root" node "$root/cli/bin/tdk.js" "$@"; }

cleanup() {
  pkill -f "tilt up.*$proj" >/dev/null 2>&1 || true
  docker rm -f $(docker ps -aq --filter "name=$proj") >/dev/null 2>&1 || true
  docker network ls --format '{{.Name}}' | grep "^${proj}" | xargs -r docker network rm >/dev/null 2>&1 || true
  docker images --format '{{.Repository}}:{{.Tag}}' | grep -E "^app_${proj}|^${proj}-l[0-9]+" | xargs -r docker rmi -f >/dev/null 2>&1 || true
}
trap cleanup EXIT

cd "$work"
git init -q .
tdk project --yes >/dev/null 2>&1
printf '\nTDK_HTTP_PORT=%s\nTDK_HTTPS_PORT=%s\nTDK_POSTGRES_PORT=%s\n' \
  "$http_port" "$((32000 + RANDOM % 2000))" "$((34000 + RANDOM % 2000))" >> .env

add_resource() { # <example> <name> <health> [port]
  local ex="$1" nm="$2" hp="$3" port="${4:-}"
  mkdir -p "services/app/$nm"
  cp -R "$root/examples/byo/$ex/." "services/app/$nm/"
  rm -f "services/app/$nm/README.md"
  # macOS ships bash 3.2, where expanding an empty array under `set -u` fails, so branch instead of using an array.
  if [ -n "$port" ]; then
    (cd "services/app/$nm" && tdk resource "$nm" --type bring-your-own --stack app --register-existing \
      --dockerfile ./Dockerfile --health-path "$hp" --port "$port" --yes >/dev/null)
  else
    (cd "services/app/$nm" && tdk resource "$nm" --type bring-your-own --stack app --register-existing \
      --dockerfile ./Dockerfile --health-path "$hp" --yes >/dev/null)
  fi
}
add_resource "$dep" "$dep_name" "$dep_health" "$dep_port"
add_resource "$app" "$app_name" "$app_health"
# Point the app at this run's dependency by its unique name.
sed -i.bak -E "s#^(ENV ${envvar}=http://)[^:]+(:[0-9]+)#\1${dep_name}\2#" "services/app/$app_name/Dockerfile" && rm -f "services/app/$app_name/Dockerfile.bak"
grep -q "^ENV ${envvar}=http://${dep_name}:" "services/app/$app_name/Dockerfile" \
  || { echo "the app Dockerfile has no 'ENV ${envvar}=http://<host>:<port>' line to rewrite" >&2; exit 2; }

nohup node "$root/cli/bin/tdk.js" up app >"$work/up.log" 2>&1 &

url="http://127.0.0.1:$http_port/api/$app_name$app_health"
status=000
for _ in $(seq 1 "${VERIFY_WAIT_SECONDS:-600}"); do
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' -H "Host: api.$proj.localhost" "$url" || true)"
  [ "$status" = "200" ] && break
  sleep 1
done

if [ "$status" = "200" ]; then
  echo "PASS $app + $dep: through tdk up and Traefik, GET /api/$app_name$app_health -> 200 ($(curl -s -m 3 -H "Host: api.$proj.localhost" "$url" | head -c 120))"
else
  echo "FAIL $app + $dep: GET /api/$app_name$app_health -> $status" >&2
  curl -s -m 3 -H "Host: api.$proj.localhost" "$url" | head -c 300 >&2 || true
  echo >&2
  docker logs "app-autogenerated-$app_name-1" 2>&1 | tail -15 >&2 || true
  exit 1
fi
