# =============================================================================
# ⚡ TILT SDK - VITE BACKEND GENERATOR

# === INLINED CONSTANTS for pure extension loading ===
BASE_PORT_BACKEND = 4000
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load('../../../../topologies/tilt/manifest/constants.star', 'GENERATED_CONFIG_FILENAMES')
# =============================================================================
# Path: .tilt/providers/vite/backend.star
# Purpose: Vite config generator for Backend services
# =============================================================================


load('./templates.star', 'TEMPLATE_VITE_BACKEND_WITH_NODE', 'TEMPLATE_VITE_BACKEND_VITEST_ONLY')
load('./helpers.star', 
    'build_header', 
    'generate_backend_path_aliases', 
    'generate_externals_config', 
    'generate_vitest_inline_deps'
)

# Constants for output paths
VITE_BACKEND_CONFIG_PATH = '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['vite_backend']

def generate_backend(manifest, write_fn=None):
    """
    Generate vite.config.ts for BACKEND services.
    
    Why backends use Vite:
    1. Vitest: Fastest test runner for TypeScript
    2. vite-plugin-node: Instant HMR for Node.js (no restart) - OPTIONAL
    3. Fast TypeScript transpilation via SWC/esbuild
    4. Unified config with frontend teams
    """
    app_type = manifest.get('appType', 'backend')
    if app_type not in ['backend', 'migrator']:
        fail("Vite.backend() requires a backend manifest, got: " + app_type)
    
    resource_path = manifest.get('_resource_path', '')
    app_name = manifest.get('appName', 'unknown')
    port = manifest.get('port', BASE_PORT_BACKEND)
    
    # 🔥 SMART DETECTION: Check if service uses vite-plugin-node for HMR
    use_vite_node = manifest.get('useViteNode', False)
    features = manifest.get('features', [])
    if 'vite-node' in features or 'vite-plugin-node' in features or 'hmr' in features:
        use_vite_node = True
    
    entry_point = manifest.get('entryPoint', './src/index.ts')
    path_aliases = generate_backend_path_aliases(resource_path, manifest)
    vitest_inline_deps = generate_vitest_inline_deps(manifest)
    
    if use_vite_node:
        header = build_header('Vite.backend()', app_name, 'Backend (SSR + HMR + Vitest)')
        externals_config = generate_externals_config(manifest)
        config = TEMPLATE_VITE_BACKEND_WITH_NODE.format(
            header=header,
            entry_point=entry_point,
            port=port,
            path_aliases=path_aliases,
            externals_config=externals_config,
            vitest_inline_deps=vitest_inline_deps,
        )
    else:
        header = build_header('Vite.backend()', app_name, 'Backend (Vitest)')
        config = TEMPLATE_VITE_BACKEND_VITEST_ONLY.format(
            header=header,
            path_aliases=path_aliases,
            vitest_inline_deps=vitest_inline_deps,
        )
    
    if write_fn:
        write_fn(resource_path + VITE_BACKEND_CONFIG_PATH, config)
    
    return config
