# =============================================================================
# ⚡ TILT SDK - VITE FRONTEND GENERATOR

# === INLINED CONSTANTS for pure extension loading ===
BASE_PORT_FRONTEND = 3000
BASE_PORT_BACKEND = 4000
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load('../../../../topologies/tilt/manifest/constants.star', 'GENERATED_CONFIG_FILENAMES')
# =============================================================================
# Path: .tilt/providers/vite/frontend.star
# Purpose: Vite config generator for Frontend services
# =============================================================================


load('./templates.star', 'TEMPLATE_VITE_FRONTEND', 'TEMPLATE_VITE_FRONTEND_BUILD')
load('./helpers.star', 
    'build_header', 
    'generate_frontend_internal_aliases', 
    'generate_frontend_optimize_deps', 
    'generate_proxy_block'
)

# Constants for output paths
VITE_FRONTEND_CONFIG_PATH = '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['vite_frontend']
VITE_FRONTEND_BUILD_CONFIG_PATH = '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['vite_build']

def _normalize_vite_base_path(base_path):
    """Vite subpath deploys are more reliable with a trailing slash."""
    if not base_path:
        return '/'
    if not base_path.startswith('/'):
        base_path = '/' + base_path
    if base_path != '/' and not base_path.endswith('/'):
        base_path = base_path + '/'
    return base_path

def generate_frontend(manifest, backend_manifest=None, write_fn=None):
    """
    Generate vite.config.ts for FRONTEND services.
    
    Features:
    - Auto-proxy to backend based on backend manifest port
    - HMR configuration with correct ports
    - Base path configuration
    - TypeScript path aliases
    - 🔥 Auto-generated internal dependency aliases from package.json
    - 🔥 optimizeDeps.include for faster dev startup
    """
    if manifest.get('appType') != 'frontend':
        fail("Vite.frontend() requires a frontend manifest, got: " + manifest.get('appType', 'unknown'))
    
    resource_path = manifest.get('_resource_path', '')
    stack = manifest.get('stack', 'app')
    port = manifest.get('port', BASE_PORT_FRONTEND)
    hmr_port = port + 1000  # HMR port is always port + 1000
    base_path = manifest.get('basePath', '/' + stack + 's')
    vite_base_path = _normalize_vite_base_path(base_path)
    app_name = manifest.get('appName', 'unknown')

    backend_port = BASE_PORT_BACKEND
    if backend_manifest:
        backend_port = backend_manifest.get('port', BASE_PORT_BACKEND)

    # Use traefik pathPrefix for API base path (modern pattern)
    traefik_config = manifest.get('traefik', {})
    api_base_path = traefik_config.get('pathPrefix', '/api')

    proxy_config = generate_proxy_block(api_base_path, backend_port, [], stack)
    header = build_header('Vite.frontend()', app_name)
    # Config is written under .autogenerated/, so aliases need one extra ".." level.
    internal_aliases = generate_frontend_internal_aliases(resource_path, manifest, 1)
    optimize_deps_include = generate_frontend_optimize_deps(manifest)
    
    config = TEMPLATE_VITE_FRONTEND.format(
        header=header,
        base_path=vite_base_path,
        port=port,
        hmr_port=hmr_port,
        proxy_config=proxy_config,
        internal_aliases=internal_aliases,
        optimize_deps_include=optimize_deps_include,
    )

    build_cfg_header = build_header('Vite.frontend()', app_name, 'Build-only Vite config')
    build_config = TEMPLATE_VITE_FRONTEND_BUILD.format(
        header=build_cfg_header,
        base_path=vite_base_path,
        optimize_deps_include=optimize_deps_include,
    )
    
    if write_fn:
        write_fn(resource_path + VITE_FRONTEND_CONFIG_PATH, config)
        write_fn(resource_path + VITE_FRONTEND_BUILD_CONFIG_PATH, build_config)
    
    return config
