# =============================================================================
# ⚡ TILT SDK - VITE SDK GENERATOR

# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load('../../../../topologies/tilt/manifest/constants.star', 'GENERATED_CONFIG_FILENAMES')
# =============================================================================
# Path: .tilt/providers/vite/sdk.star
# Purpose: Vite config generator for SDK packages (Module Federation)
# =============================================================================

load('./templates.star', 'TEMPLATE_VITE_SDK')
load('./helpers.star', 'build_header')

# Constants for output paths
VITE_SDK_CONFIG_PATH = '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['vite_sdk']

def generate_sdk(manifest, write_fn=None):
    """
    Generate vite.config.ts for SDK packages with Module Federation.
    
    SDK features:
    1. @module-federation/vite for runtime module sharing
    2. Exposes configured modules
    3. Shared React/React-DOM as singletons
    4. Remote entry generation
    """
    resource_path = manifest.get('_resource_path', '')
    app_name = manifest.get('appName', 'unknown')
    port = manifest.get('port', 3001)
    
    federation_name = app_name.replace('-', '_')
    
    exposes = manifest.get('federationExposes', {
        './App': './src/App.tsx',
        './client': './src/clients/main-client.ts',
    })
    
    exposes_lines = []
    for key, value in exposes.items():
        exposes_lines.append("        '" + key + "': '" + value + "',")
    exposes_str = '\n'.join(exposes_lines)
    
    shared_deps = manifest.get('federationShared', [
        'react',
        'react-dom',
        'react-router-dom',
        '@tanstack/react-query',
        'zod',
    ])
    
    shared_lines = []
    for dep in shared_deps:
        shared_lines.append("        '" + dep + "': { singleton: true },")
    shared_str = '\n'.join(shared_lines)
    
    header = build_header('Vite.sdk()', app_name, 'SDK (Module Federation)')
    
    config = TEMPLATE_VITE_SDK.format(
        header=header,
        federation_name=federation_name,
        port=port,
        exposes_str=exposes_str,
        shared_str=shared_str,
    )
    
    if write_fn:
        write_fn(resource_path + VITE_SDK_CONFIG_PATH, config)
    
    return config
