import type { ResourceType } from "../types/index.js";

export const MASTER_CONFIG_FILES = [
  "TILT_TECH_STACK.star",
  "TILT_RESOURCE_DEFAULTS.star",
  "spec.master",
] as const;

export const VALID_RESOURCE_TYPES: ResourceType[] = [
  "backend",
  "frontend",
  "library",
  "sdk",
  "worker",
  "migrator",
] as const;

export const OPTIONAL_INFRA_SERVICES = ["monitoring", "elk", "debezium", "golden_image"] as const;

export const PORT_RANGES = {
  frontend: { base: 3000, min: 3000, max: 3999, range: "3000-3999" as const },
  backend: { base: 4000, min: 4000, max: 4999, range: "4000-4999" as const },
  worker: { base: 6000, min: 6000, max: 6999, range: "6000-6999" as const },
  health: { base: 5000, min: 5000, max: 5999, range: "5000-5999" as const },
  migrator: { base: 7000, min: 7000, max: 7999, range: "7000-7999" as const },
} as const;

export const STANDARD_PORTS = {
  tiltUi: 10350,
  traefik: 8080,
} as const;

export const BASE_DOMAIN_DEFAULT = "beauty-crm.localhost";
export const APP_SUBDOMAIN_PREFIX = "app";
export const API_SUBDOMAIN_PREFIX = "api";

export function getBaseDomain(): string {
  const override = process.env.TDK_SERVICE_BASE_URL ?? process.env.TDK_PUBLIC_HOST;
  if (override) {
    try {
      const u = new URL(override.includes("://") ? override : `http://${override}`);
      return u.hostname;
    } catch {
      return override.replace(/^https?:\/\//, "").split("/")[0];
    }
  }
  return BASE_DOMAIN_DEFAULT;
}

export function frontendBaseUrl(protocol = "http"): string {
  return `${protocol}://${APP_SUBDOMAIN_PREFIX}.${getBaseDomain()}`;
}

export function apiBaseUrl(protocol = "http"): string {
  return `${protocol}://${API_SUBDOMAIN_PREFIX}.${getBaseDomain()}`;
}

export const SKIP_DIRECTORIES = [
  "node_modules",
  ".git",
  ".tilt",
  ".tilt-engine",
  "dist",
  "build",
  ".prisma",
  ".turbo",
  "coverage",
  "tmp",
  "temp",
  "__tests__",
  "test",
  "tests",
  ".github",
  ".vscode",
  "docs",
] as const;

export const AUTOGENERATED_FILE_PATTERNS = [
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.yaml",
  "Tiltfile",
  "vite.config.ts",
  "tsconfig.json",
  "tsconfig.build.json",
] as const;

// Stack emojis - generic, no hardcoded service names
// Users can add their own stack emojis via project config
const STACK_EMOJIS: Record<string, string> = {
  infra: "🏗️",
  core: "🔧",
  api: "⚡",
  app: "🎨",
  orchestrator: "⚙️",
} as const;

export function getStackEmoji(stackName: string): string {
  const lowerName = stackName.toLowerCase();
  for (const [key, emoji] of Object.entries(STACK_EMOJIS)) {
    if (lowerName.includes(key)) {
      return emoji;
    }
  }
  return "📦";
}
