import { existsSync, lstatSync } from "node:fs";
import { isAbsolute, normalize, relative, sep } from "node:path";

/** Reviewed TDK-owned destinations written by `tdk config regenerate` or Tilt generation. */
export const TDK_GENERATED_PATH_ALLOWLIST = [
  ".autogenerated/**",
  ".tdk/.tdk-out/**",
  "Tiltfile",
  "TILT_*.star",
  ".tiltignore",
  "package.json (create only)",
  "shared-platform-engineering/docker-templates/**",
  "services/platform/database-management/docker-compose.yml",
  "product_autogenerated_resource_manifests/**",
  "product_autogenerated_services_list/**",
] as const;

export function isTdkGeneratedPath(path: string): boolean {
  const normalized = normalize(path).split(sep).join("/");
  if (isAbsolute(path) || normalized === ".." || normalized.startsWith("../")) return false;
  if (
    normalized.split("/").includes(".autogenerated") ||
    normalized.startsWith(".tdk/.tdk-out/") ||
    normalized === "shared-platform-engineering/docker-templates" ||
    normalized.startsWith("shared-platform-engineering/docker-templates/") ||
    normalized.startsWith("product_autogenerated_resource_manifests/") ||
    normalized.startsWith("product_autogenerated_services_list/")
  ) {
    return true;
  }
  return (
    normalized === "Tiltfile" ||
    /^TILT_[^/]+\.star$/.test(normalized) ||
    normalized === ".tiltignore" ||
    normalized === "package.json" ||
    normalized === "services/platform/database-management/docker-compose.yml"
  );
}

export function assertTdkGeneratedPath(projectRoot: string, path: string): string {
  const absolute = isAbsolute(path) ? normalize(path) : normalize(`${projectRoot}/${path}`);
  const projectRelative = relative(projectRoot, absolute).split(sep).join("/");
  if (!isTdkGeneratedPath(projectRelative)) {
    throw new Error(`Refusing to write outside TDK's generated-file allowlist: ${projectRelative}`);
  }
  let cursor = projectRoot;
  for (const segment of projectRelative.split("/")) {
    cursor = normalize(`${cursor}/${segment}`);
    if (existsSync(cursor) && lstatSync(cursor).isSymbolicLink()) {
      throw new Error(
        `Refusing to write through a symbolic link in generated path: ${projectRelative}`,
      );
    }
  }
  return absolute;
}
