import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import type {
  AutogeneratedFile,
  DiscoveredResource,
  DiscoveredStack,
  FileType,
  ResourceConfig,
  ResourceMetadata,
  ResourceType,
  StackMetadata,
} from "../types/index.js";
import { Cache, createCacheValidator } from "./cache.js";
import { AUTOGENERATED_FILE_PATTERNS, SKIP_DIRECTORIES } from "./constants.js";
import { formatCount } from "./formatting.js";
import { findProjectRoot } from "./paths.js";
import { includes } from "./validation.js";

const RESOURCE_JSON_FILENAME = "service.json";

function findServiceJsonFiles(
  dir: string,
  maxDepth: number = 5,
  currentDepth: number = 0,
): string[] {
  const results: string[] = [];

  if (currentDepth > maxDepth) {
    return results;
  }

  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      if (shouldSkipDirectory(entry.name)) continue;
      results.push(...findServiceJsonFiles(fullPath, maxDepth, currentDepth + 1));
    } else if (entry.isFile() && entry.name === RESOURCE_JSON_FILENAME) {
      results.push(fullPath);
    }
  }

  return results;
}

function shouldSkipDirectory(name: string): boolean {
  return includes(SKIP_DIRECTORIES, name) || name.startsWith(".");
}

function isValidResourceConfig(value: unknown): value is ResourceConfig {
  if (!value || typeof value !== "object") return false;
  const config = value as Record<string, unknown>;
  // Accept runtime, appType, or type (for backward compatibility with existing service.json files)
  const hasRuntimeOrAppType =
    typeof config.runtime === "string" ||
    typeof config.appType === "string" ||
    typeof config.type === "string";
  return typeof config.appName === "string" && hasRuntimeOrAppType;
}

function parseResource(serviceJsonPath: string): DiscoveredResource {
  const content = readFileSync(serviceJsonPath, "utf-8");
  const parsed: unknown = JSON.parse(content);

  if (!isValidResourceConfig(parsed)) {
    throw new Error(
      `Invalid service.json at ${serviceJsonPath}: missing required fields (appName, runtime or appType)`,
    );
  }

  const rawConfig = parsed as Record<string, unknown>;
  const config: ResourceConfig = {
    ...(parsed as ResourceConfig),
    appType: (rawConfig.appType || rawConfig.type) as ResourceConfig["appType"],
  };
  const resourceDir = dirname(serviceJsonPath);

  return {
    name: config.appName,
    path: resourceDir,
    configPath: serviceJsonPath,
    config,
    stack: config.stack,
  };
}

export function discoverResources(): DiscoveredResource[] {
  const projectRoot = findProjectRoot();

  if (!projectRoot) {
    throw new Error(
      "Could not find project root (no Tiltfile found). Make sure you're in a root project.",
    );
  }

  const serviceJsonPaths = findServiceJsonFiles(projectRoot);
  const resources: DiscoveredResource[] = [];

  for (const path of serviceJsonPaths) {
    resources.push(parseResource(path));
  }

  return resources;
}

export function getAllStacks(resources?: DiscoveredResource[]): string[] {
  const resourcesToScan = resources || discoverResources();
  const stacks = new Set<string>();

  for (const resource of resourcesToScan) {
    if (resource.stack) {
      stacks.add(resource.stack);
    }
  }

  return Array.from(stacks).sort();
}

export function discoverStacks(): DiscoveredStack[] {
  const resources = discoverResources();
  const stackMap = new Map<string, DiscoveredResource[]>();

  for (const resource of resources) {
    if (resource.stack) {
      const stackResources = stackMap.get(resource.stack);
      if (stackResources) {
        stackResources.push(resource);
      } else {
        stackMap.set(resource.stack, [resource]);
      }
    }
  }

  const stacks: DiscoveredStack[] = [];
  for (const [name, stackResources] of stackMap) {
    stacks.push({
      name,
      description: formatCount(stackResources.length, "resource"),
      resources: stackResources,
      resourceCount: stackResources.length,
    });
  }

  return stacks.sort((a, b) => a.name.localeCompare(b.name));
}

export function getResourcesForStack(stackName: string): DiscoveredResource[] {
  const allResources = discoverResources();
  return allResources.filter((r) => r.stack === stackName);
}

export function stackExists(stackName: string): boolean {
  const resources = getResourcesForStack(stackName);
  return resources.length > 0;
}

/**
 * Cache TTL in milliseconds
 */
const CACHE_TTL_MS = 5000;

const resourcesCache = new Cache<ResourceMetadata>({ ttlMs: CACHE_TTL_MS });
const stacksCache = new Cache<StackMetadata>({ ttlMs: CACHE_TTL_MS });
const cacheValidator = createCacheValidator(CACHE_TTL_MS);

export function clearMetadataCache(): void {
  resourcesCache.clear();
  stacksCache.clear();
  cacheValidator.reset();
}

function detectFileType(filename: string, content?: string): FileType {
  if (filename === "Dockerfile" || filename.startsWith("docker-compose")) {
    return "docker";
  }
  if (filename === "Tiltfile" || filename.endsWith(".star")) {
    return "tilt";
  }
  if (
    filename === "vite.config.ts" ||
    filename === "tsconfig.json" ||
    filename === "package.json"
  ) {
    return "config";
  }
  if (filename === "schema.prisma" || filename.includes("migration")) {
    return "prisma";
  }
  if (content) {
    const firstLines = content.split("\n").slice(0, 10).join("\n");
    if (firstLines.includes("GENERATED BY TDK") || firstLines.includes("AUTOGENERATED")) {
      return "generated";
    }
  }
  return "unknown";
}

export function getResourceMetadata(resource: DiscoveredResource): ResourceMetadata {
  const cacheKey = resource.configPath;

  if (cacheValidator.isValid()) {
    const cached = resourcesCache.get(cacheKey);
    if (cached) {
      return cached;
    }
  }

  const resourceDir = resource.path;

  const stats = statSync(resource.configPath);
  const createdAt = stats.mtime.toISOString();
  const lastModified = stats.mtime.toISOString();

  const autogeneratedFiles = discoverAutogeneratedFiles(resourceDir);
  const hasDockerfile = existsSync(join(resourceDir, "Dockerfile"));
  const hasTiltfile = existsSync(join(resourceDir, "Tiltfile"));
  const hasDockerCompose =
    existsSync(join(resourceDir, "docker-compose.yml")) ||
    existsSync(join(resourceDir, "docker-compose.yaml"));

  const configType = resource.config?.appType;
  let type: ResourceType = configType || "backend";
  if (!configType) {
    if (resource.name.includes("frontend")) {
      type = "frontend";
    } else if (
      resource.name.includes("sdk") ||
      resource.name.includes("lib") ||
      resource.name.includes("infra")
    ) {
      type = "library";
    }
  }

  const metadata: ResourceMetadata = {
    name: resource.name,
    stack: resource.stack,
    type,
    port: resource.config?.port,
    createdAt,
    lastModified,
    dependencies: resource.config?.dependsOn ?? [],
    hasDockerfile,
    hasTiltfile,
    hasDockerCompose,
    autogeneratedFiles,
    status: "unknown",
  };

  resourcesCache.set(cacheKey, metadata);
  cacheValidator.markUpdated();

  return metadata;
}

function discoverAutogeneratedFiles(resourceDir: string): AutogeneratedFile[] {
  const files: AutogeneratedFile[] = [];

  for (const pattern of AUTOGENERATED_FILE_PATTERNS) {
    const filePath = join(resourceDir, pattern);
    if (existsSync(filePath)) {
      const stats = statSync(filePath);
      const content = readFileSync(filePath, "utf-8");

      files.push({
        name: pattern,
        path: filePath,
        type: detectFileType(pattern, content),
        size: stats.size,
        lastModified: stats.mtime.toISOString(),
      });
    }
  }

  const prismaDir = join(resourceDir, "prisma");
  if (existsSync(prismaDir)) {
    const entries = readdirSync(prismaDir);
    for (const entry of entries) {
      if (entry === "schema.prisma" || entry.includes("migration")) {
        const filePath = join(prismaDir, entry);
        const stats = statSync(filePath);
        files.push({
          name: `prisma/${entry}`,
          path: filePath,
          type: "prisma",
          size: stats.size,
          lastModified: stats.mtime.toISOString(),
        });
      }
    }
  }

  return files.sort((a, b) => a.name.localeCompare(b.name));
}

export function getStackMetadata(stack: DiscoveredStack): StackMetadata {
  const cacheKey = stack.name;

  if (cacheValidator.isValid()) {
    const cached = stacksCache.get(cacheKey);
    if (cached) {
      return cached;
    }
  }

  const resourcesMetadata = stack.resources.map((r) => getResourceMetadata(r));
  const timestamps = resourcesMetadata.map((r) => new Date(r.createdAt).getTime());
  const earliestTimestamp = Math.min(...timestamps);
  const latestTimestamp = Math.max(...timestamps);
  const totalResources = resourcesMetadata.length;

  let overallStatus: StackMetadata["overallStatus"] = "unknown";
  if (totalResources > 0) {
    const readyCount = resourcesMetadata.filter((r) => r.status === "ready").length;
    const ratio = readyCount / totalResources;
    if (ratio > 0.9) {
      overallStatus = "healthy";
    } else if (ratio > 0.5) {
      overallStatus = "degraded";
    } else {
      overallStatus = "error";
    }
  }

  const metadata: StackMetadata = {
    name: stack.name,
    resourceCount: resourcesMetadata.length,
    createdAt: new Date(earliestTimestamp).toISOString(),
    lastModified: new Date(latestTimestamp).toISOString(),
    resources: resourcesMetadata,
    overallStatus,
  };

  stacksCache.set(cacheKey, metadata);
  cacheValidator.markUpdated();

  return metadata;
}
