# =============================================================================
# 🎨 TILT SDK - FRONTEND API CLIENT GENERATORS
# =============================================================================
# Purpose: Generate api-client.ts, env.ts, and index.ts for frontend services
#          These files import from @{npm_scope}/platform-api-client package
# =============================================================================

# Load npm scope from project.json
# Use TDK_PROJECT_ROOT env var set by Tilt, fallback to current directory
def _load_npm_scope():
    project_root = os.environ.get('TDK_PROJECT_ROOT', '')
    project_json_path = '.tdk/project.json'
    if project_root:
        project_json_path = project_root + '/' + project_json_path
    
    if os.path.exists(project_json_path):
        _project_json = read_json(project_json_path)
        return _project_json.get('project', {}).get('name', 'tdk-project')
    return 'tdk-project'

_NPM_SCOPE = _load_npm_scope()

load("../../../../platform/docker/networking/traefik_helpers.star", "get_api_path")
load("../../../../platform/docker/constants.star", "PlatformDockerConstants")
load("./dependencies/resolver.star", "resolve_backend_api_path")

def generate_frontend_api_client(manifest, write_fn=None):
    """Generate .autogenerated/api-client.ts for a frontend resource.

    Args:
        manifest: Resource manifest with stack field
        write_fn: Optional function to write file (for Tilt)

    Returns:
        str: Generated file content
    """
    stack = manifest.get("stack", "app")

    # Auto-resolve apiPath from backend manifest if backendName is specified
    backend_api_path = resolve_backend_api_path(manifest)
    if backend_api_path:
        api_path = backend_api_path
    else:
        api_path = get_api_path(stack, manifest)

    content = '''// 🛑 GENERATED BY TILT SDK - DO NOT EDIT
// Source: engine/topologies/tilt/resources/orchestrator/generators/frontend.star
// Purpose: Pre-configured API client for {stack} resource

import {{ createApiClient }} from '@" + _NPM_SCOPE + "'/platform-api-client';

/**
 * Pre-configured API client for {stack} resource
 *
 * Usage:
 * ```typescript
 * import {{ apiClient }} from '../.autogenerated/api-client';
 * const data = await apiClient.get('/');
 * ```
 */
export const apiClient = createApiClient({{
  baseURL: import.meta.env.VITE_API_URL || 'http://{local_domain}{api_path}',
  withAuth: true,
}});

export default apiClient;
'''.format(
        stack=stack,
        api_path=api_path,
        local_domain=PlatformDockerConstants.API_LOCAL_DOMAIN,
    )
    
    if write_fn:
        resource_path = manifest.get('_resource_path', '')
        write_fn(resource_path + '/.autogenerated/api-client.ts', content)

    return content


def generate_frontend_env_ts(manifest, write_fn=None):
    """Generate .autogenerated/env.ts for a frontend resource.

    Args:
        manifest: Resource manifest with stack field
        write_fn: Optional function to write file (for Tilt)

    Returns:
        str: Generated file content
    """
    stack = manifest.get("stack", "app")

    # Auto-resolve apiPath from backend manifest if backendName is specified
    backend_api_path = resolve_backend_api_path(manifest)
    if backend_api_path:
        api_path = backend_api_path
    else:
        api_path = get_api_path(stack, manifest)

    content = '''// 🛑 GENERATED BY TILT SDK - DO NOT EDIT
// Source: .tilt/topologies/tilt/resources/orchestrator/generators/frontend.star
// Purpose: Environment constants for {stack} resource

/**
 * Base API URL for {stack} resource
 * Uses VITE_API_URL env var with fallback to local dev URL
 */
export const API_URL = import.meta.env.VITE_API_URL || 'http://{local_domain}{api_path}';
'''.format(
        stack=stack,
        api_path=api_path,
        local_domain=PlatformDockerConstants.API_LOCAL_DOMAIN,
    )
    
    if write_fn:
        resource_path = manifest.get('_resource_path', '')
        write_fn(resource_path + '/.autogenerated/env.ts', content)

    return content


def generate_frontend_api_index(manifest, write_fn=None):
    """Generate .autogenerated/api-index.ts for clean imports.

    Args:
        manifest: Service manifest
        write_fn: Optional function to write file (for Tilt)

    Returns:
        str: Generated file content
    """
    content = '''// 🛑 GENERATED BY TILT SDK - DO NOT EDIT
// Source: .tilt/topologies/tilt/resources/orchestrator/generators/frontend.star
// Purpose: Clean barrel exports for API client

export { apiClient } from './api-client';
export { API_URL } from './env';
'''
    
    if write_fn:
        resource_path = manifest.get('_resource_path', '')
        write_fn(resource_path + '/.autogenerated/api-index.ts', content)

    return content


def generate_all_frontend_api_files(manifest, write_fn=None):
    """Generate all frontend API files for a service.

    Args:
        manifest: Service manifest
        write_fn: Function to write files

    Returns:
        dict: Generated content for each file
    """
    return {
        'api-client.ts': generate_frontend_api_client(manifest, write_fn),
        'env.ts': generate_frontend_env_ts(manifest, write_fn),
        'api-index.ts': generate_frontend_api_index(manifest, write_fn),
    }


# Export struct for easy importing
FrontendGenerators = struct(
    generate_api_client = generate_frontend_api_client,
    generate_env_ts = generate_frontend_env_ts,
    generate_api_index = generate_frontend_api_index,
    generate_all = generate_all_frontend_api_files,
)
