# =============================================================================
# 🎯 TILT SDK - MANIFEST-DRIVEN CONFIG GENERATOR
# =============================================================================
# Path: .tilt/provisioner/orchestrator/generators/manifest_resource.star
# Purpose: Per-manifest config generation as Tilt resources
# =============================================================================
#
# Creates individual Tilt resources for each manifest that trigger all
# config generators (tsconfig, dockerfile, vite, npmrc, etc.) for that
# specific service.
#
# Benefits:
# - Granular tracking (see "my-service-config-gen" in Tilt UI)
# - Efficient updates (only regenerate changed manifests)
# - Better dependency management (explicit resource deps)
# - Cleaner architecture (manifest → resource → 10 generators)
# =============================================================================

# === INLINED CONSTANTS for pure extension loading ===
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


load('../../../../../topologies/tilt/common/utils.star', 'Utils')
load('../../../../../../discovery/loading.star', 'Manifest')
load('../../../../../topologies/tilt/manifest/constants.star', 'AUTOGENERATED_CONFIG_PATHS', 'PACKAGE_CONFIG_FILENAMES', 'GENERATED_CONFIG_FILENAMES', 'MANIFEST_FILENAME', 'MANIFEST_FILENAME_YAML', 'BASE_PORT_FRONTEND')
  # Load OUTPUT for AUTOGENERATED_FOLDER
load('../../../generators/vite_config.star', 'Vite')
load('../../../generators/nginx_conf.star', 'Nginx')
load('../../../generators/api_gateway.star', 'ApiGateway')
load('../../../generators/tsconfig.star', 'TSConfig')
load('../../../../platform/docker/index.star', 'Docker')
load('../../../generators/npmrc.star', 'PackageConfig')
load('../../libs.star', 'Libs')
load('./env.star', 'EnvGenerators')
load('./frontend.star', 'FrontendGenerators')
load('../helpers.star', 'OrchestratorHelpers')

# =============================================================================
# NEW: Pre-Flight Validation Generators (v2.0)
# These generators prevent vibe-coding failures by validating before build
# =============================================================================
load('../../../generators/index.star', 'Generators')

_generate_env_file = EnvGenerators.generate_env_file
_generate_frontend_api_files = FrontendGenerators.generate_all
_get_db_name_for_resource = OrchestratorHelpers.get_db_name
_get_resource_display_name = OrchestratorHelpers.get_display_name


def _run_pre_flight_validations(resource_name, resource_path, manifest, ctx):
    """
    Run pre-flight validations before generating configs.
    
    This catches issues BEFORE they cause build failures:
    - Docker path alias issues
    - Missing dependencies  
    - Database config problems
    - Package publishing gaps
    
    Returns validation report for logging.
    """
    global_config = ctx.get('global_config', {})
    all_services = ctx.get('all_services', [])
    
    # Only run validations if Generators module loaded successfully
    if not Generators:
        return {"status": "SKIPPED", "reason": "Generators module not loaded"}
    
    # Run all validations
    report = Generators.run_pre_flight_validations(
        resource_path,
        manifest,
        all_services,
        global_config,
    )
    
    # Log summary to Tilt UI
    if report.get("overall_status") == "FAILED":
        print("⚠️  {}: Validation failures detected - check " + OUTPUT.AUTOGENERATED_FOLDER + "/validation-*.json".format(resource_name))
    elif report.get("summary", {}).get("warnings", 0) > 0:
        print("⚡ {}: Validations passed with warnings".format(resource_name))
    else:
        print("✅ {}: All validations passed".format(resource_name))
    
    return report


def _escape_for_double_quoted_shell(value):
    escaped = str(value)
    escaped = escaped.replace("\\", "\\\\")
    escaped = escaped.replace('"', '\\"')
    escaped = escaped.replace("$", "\\$")
    escaped = escaped.replace("`", "\\`")
    return escaped


def _get_file_emoji(filename):
    """Return an emoji based on the file type."""
    if 'Dockerfile' in filename:
        return '🐳'
    elif filename.endswith('.ts'):
        return '📜'
    elif filename.endswith('.json'):
        return '📋'
    elif filename.endswith('.toml'):
        return '⚙️'
    elif filename.endswith('.conf'):
        return '🔧'
    elif filename.endswith('.env') or '.env.' in filename:
        return '🔐'
    elif '.npmrc' in filename:
        return '📦'
    elif '.dockerignore' in filename:
        return '🚫'
    elif filename.endswith('.md'):
        return '🤖'
    else:
        return '📄'


def _build_generated_file_list(resource_config, resource_path, manifest):
    """
    Build the expected generated file list for logging in config-gen resources.
    Mirrors _generate_all_configs_for_resource() behavior.
    """
    files = []
    app_type = manifest.get('appType', 'backend')
    is_frontend = resource_config.get('frontend', False) or app_type == 'frontend'

    # Vite
    if is_frontend:
        files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['vite_frontend'])
        files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['vite_build'])
    elif app_type == 'backend':
        files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['vite_backend'])
    elif app_type == 'sdk':
        files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['vite_sdk'])

    # Nginx (frontends)
    if is_frontend:
        files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['nginx'])

    # Env
    if is_frontend:
        files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['env_frontend'])
    else:
        files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['env_backend'])

    # Dockerfile + dockerignore
    files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['dockerfile_app'])
    dockerfile_rel_path = resource_config.get('dockerfile', '')
    if dockerfile_rel_path:
        dockerfile_path = resource_path + "/" + dockerfile_rel_path
        files.append(dockerfile_path + '.dockerignore')

    # TS config(s)
    files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['tsconfig_docker'])
    files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['tsconfig_local'])

    # Prisma config (non-frontends)
    if not is_frontend:
        files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['prisma'])

    # Playwright config (optional)
    if manifest.get('playwright', False):
        files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['playwright'])

    # Package configs
    files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + PACKAGE_CONFIG_FILENAMES['npmrc_docker_autogenerated'])
    files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + PACKAGE_CONFIG_FILENAMES['bunfig_docker_autogenerated'])
    files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + PACKAGE_CONFIG_FILENAMES['npmrc'])
    files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + PACKAGE_CONFIG_FILENAMES['bunfig'])

    # AGENTS.md (AI agent guard rail)
    files.append(resource_path + '/' + OUTPUT.AUTOGENERATED_FOLDER + '/' + GENERATED_CONFIG_FILENAMES['agents_md'])

    return files


def _build_config_log_cmd(resource_name, generated_files, config_gen_resource_name):
    """Build a tree-structured log command with emojis for generated files.
    
    Includes auto-removal of the config-gen resource after logging since
    it's only needed for initial generation and watching for changes.
    """
    cmd_parts = [
        'echo ""',
        'echo "╔══════════════════════════════════════════════════════════════════════╗"',
        'echo "║  ⚡ ' + _escape_for_double_quoted_shell(resource_name) + ' configs generated by Starlark"',
        'echo "╚══════════════════════════════════════════════════════════════════════╝"',
        'echo ""',
    ]

    # Group files by directory
    dirs = {}
    for file_path in generated_files:
        parts = file_path.rsplit('/', 1)
        if len(parts) == 2:
            dir_path, filename = parts
        else:
            dir_path = '.'
            filename = file_path
        if dir_path not in dirs:
            dirs[dir_path] = []
        dirs[dir_path].append(filename)

    # Sort directories for consistent output
    sorted_dirs = sorted(dirs.keys())
    total_files = len(generated_files)
    
    cmd_parts.append('echo "📦 Generated ' + str(total_files) + ' files:"')
    cmd_parts.append('echo ""')

    for dir_idx, dir_path in enumerate(sorted_dirs):
        is_last_dir = (dir_idx == len(sorted_dirs) - 1)
        dir_prefix = '└── ' if is_last_dir else '├── '
        
        cmd_parts.append('echo "' + dir_prefix + '📁 ' + _escape_for_double_quoted_shell(dir_path) + '/"')
        
        files_in_dir = sorted(dirs[dir_path])
        for file_idx, filename in enumerate(files_in_dir):
            is_last_file = (file_idx == len(files_in_dir) - 1)
            file_prefix = '    └── ' if is_last_file else '    ├── '
            if not is_last_dir:
                file_prefix = '│   └── ' if is_last_file else '│   ├── '
            
            emoji = _get_file_emoji(filename)
            cmd_parts.append('echo "' + file_prefix + emoji + ' ' + _escape_for_double_quoted_shell(filename) + '"')

    cmd_parts.append('echo ""')
    cmd_parts.append('echo "✅ All configs ready!"')
    cmd_parts.append('echo ""')
    
    # Auto-remove this config-gen resource after logging
    # This prevents clutter in the Tilt UI since config-gen is only needed for initial generation
    cmd_parts.append('echo "🧹 Auto-removing config-gen resource..."')
    cmd_parts.append('tilt delete uiresource ' + config_gen_resource_name + ' 2>/dev/null || true')
    cmd_parts.append('echo "✅ Config-gen resource auto-removed"')
    cmd_parts.append('echo ""')

    return " && ".join(cmd_parts)


def _generate_all_configs_for_resource(
    resource_name,
    resource_config,
    resource_path,
    manifest,
    backend_manifest,
    ctx
):
    """
    Generate ALL configuration files for a single resource.
    
    This function is the core of the manifest-driven architecture.
    It generates 10+ config files for one service based on its manifest.
    
    Args:
        resource_name: Parent service name (e.g., 'my-service')
        resource_config: Resource dict from registry
        resource_path: Full path to resource (e.g., 'services/product/users/user-backend')
        manifest: Loaded manifest for this resource
        backend_manifest: Backend manifest (for frontends only)
        ctx: Tilt context with write_file, should_enable, etc.
    """
    write_file = ctx['write_file']
    should_enable = ctx['should_enable']
    global_config = ctx['global_config']
    
    # WORKAROUND: Prevent infinite recursion by checking recursion depth
    # Use a unique key per resource to track depth, avoiding interference between different resources
    recursion_key = '_recursion_depth_' + resource_name
    recursion_depth = ctx.get(recursion_key, 0)
    if recursion_depth > 5:
        print("⚠️  Recursion depth exceeded for {}, skipping config generation".format(resource_name))
        return
    # Create a new context copy to avoid mutating shared state for other resources
    ctx = dict(ctx)
    ctx[recursion_key] = recursion_depth + 1
    
    # Add resource_path to manifest so generators can access it
    manifest['_resource_path'] = resource_path
    
    # ==========================================================================
    # NEW: PRE-FLIGHT VALIDATIONS (v2.0)
    # Run validations BEFORE generating configs to catch issues early
    # ==========================================================================
    validation_report = _run_pre_flight_validations(
        resource_name,
        resource_path,
        manifest,
        ctx
    )
    
    # Store validation report for later reference
    write_file(
        resource_path + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/validation-report.autogenerated.json",
        Utils.encode_json(validation_report)
    )
    
    app_type = manifest.get('appType', 'backend')
    is_frontend = resource_config.get('frontend', False) or app_type == 'frontend'
    
    # ==========================================================================
    # 1. VITE CONFIG
    # ==========================================================================
    if is_frontend:
        if backend_manifest:
            Vite.for_manifest(manifest, backend_manifest, write_file)
        else:
            Vite.for_manifest(manifest, None, write_file)
    elif app_type == 'backend':
        Vite.for_manifest(manifest, None, write_file)
    elif app_type == 'sdk':
        Vite.for_manifest(manifest, None, write_file)
    
    # ==========================================================================
    # 2. NGINX CONFIG (for frontends)
    # ==========================================================================
    if is_frontend:
        # Generate referer map using ApiGateway and pass to Nginx
        referer_map_block = ApiGateway.build_referer_map_block(manifest)
        Nginx.frontend(manifest, write_file, referer_map_block)
    
    # ==========================================================================
    # 3. ENV FILE
    # ==========================================================================
    _generate_env_file(manifest, backend_manifest, write_file)
    
    # ==========================================================================
    # 3.5 FRONTEND API CLIENT FILES (for frontends only)
    # ==========================================================================
    if is_frontend:
        FrontendGenerators.generate_all(manifest, write_file)
    
    # ==========================================================================
    # 4. PLAYWRIGHT CONFIG (if enabled)
    # ==========================================================================
    if manifest.get('playwright', False):
        resource_type = 'frontend' if is_frontend else 'backend'
        TSConfig.playwright(resource_path, resource_type, write_file)
    
    # ==========================================================================
    # 5. DOCKERFILE
    # ==========================================================================
    if is_frontend:
        target_path = resource_config.get('target_path', '/usr/share/nginx/html')
        use_nginx = 'nginx' in target_path or target_path == '/usr/share/nginx/html'
        port = resource_config.get('port', manifest.get('port', BASE_PORT_FRONTEND))
        dockerfile_content = Docker.frontend(
            res_path=resource_path,
            resource_name=resource_config['name'],
            port=port,
            target_path=target_path,
            use_nginx=use_nginx,
            use_golden=should_enable('golden-image')
        )
    else:
        dockerfile_content = Docker.backend(
            res_path=resource_path,
            resource_name=resource_name,
            use_golden=should_enable('golden-image')
        )
    
    write_file(resource_path + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/" + GENERATED_CONFIG_FILENAMES['dockerfile_app'], dockerfile_content)
    
    # ==========================================================================
    # 6. DOCKERIGNORE
    # ==========================================================================
    dockerfile_rel_path = resource_config.get('dockerfile', '')
    if dockerfile_rel_path:
        resource_type = 'frontend' if is_frontend else ('migrator' if 'migrator' in resource_config['name'] else 'backend')
        dockerignore_content = Docker.generate_dockerignore(resource_path, resource_type)
        # dockerfile_rel_path (e.g. ".autogenerated/Dockerfile.app.autogenerated") is relative
        # to this resource's OWN directory - same convention _register_docker_build uses in
        # apply_compose_resource_registration.star. Stripping a path segment here (previously
        # resource_path.rsplit('/', 1)[0]) pointed at the parent STACK directory instead, so
        # every sibling service in a stack (e.g. dashboard-api and dashboard-app under
        # services/app) collided on one shared dockerignore file, each overwriting it with a
        # different (backend vs frontend) ruleset on every Tiltfile load - a real diff every
        # single run, which Tilt saw as a file change and used to trigger an infinite reload loop.
        dockerfile_path = resource_path + "/" + dockerfile_rel_path
        dockerignore_path = dockerfile_path + ".dockerignore"
        write_file(dockerignore_path, dockerignore_content)
    
    # ==========================================================================
    # 7. TYPESCRIPT CONFIGS
    # ==========================================================================
    internal_deps_map = Libs.get_deps_mapping(ctx, resource_path)
    
    if is_frontend:
        # CRITICAL FIX (v2.0): For Docker builds, we MUST NOT pass internal_deps
        # This prevents "Module not found" errors when path aliases point to
        # source files outside the Docker context.
        # 
        # Local builds: Use path aliases to source for faster development
        # Docker builds: Resolve from node_modules (packages must be published)
        
        # Docker tsconfig: NO path aliases to internal deps
        TSConfig.frontend(resource_path, write_file, internal_deps=None, is_docker=True)
        
        # Local tsconfig: CAN use path aliases to internal deps
        TSConfig.frontend(resource_path, write_file, internal_deps=internal_deps_map, is_docker=False)
    else:
        prisma_path = resource_config.get('prisma_client_path', './node_modules/.prisma/client')
        resource_features = manifest.get('features', [])
        TSConfig.backend(resource_path, prisma_path, write_file, internal_deps=internal_deps_map, is_docker=True, features=resource_features)
        TSConfig.backend(resource_path, prisma_path, write_file, internal_deps=internal_deps_map, is_docker=False, features=resource_features)
        
        # Prisma config
        db_name = _get_db_name_for_resource(resource_name, resource_config['name'])
        resource_display_name = _get_resource_display_name(resource_name, resource_config['name'])
        TSConfig.prisma(resource_path=resource_path, resource_name=resource_display_name, db_name=db_name, write_fn=write_file)
    
    # ==========================================================================
    # 8. PACKAGE CONFIGS (npmrc, bunfig)
    # ==========================================================================
    verdaccio_enabled = global_config.get('verdaccio_enabled', True)
    PackageConfig.npmrc(resource_path=resource_path, registry_url=global_config['verdaccio_url_docker'], is_docker=True, write_fn=write_file, verdaccio_enabled=verdaccio_enabled)
    PackageConfig.bunfig(resource_path=resource_path, registry_url=global_config['verdaccio_url_docker'], is_docker=True, write_fn=write_file, verdaccio_enabled=verdaccio_enabled)
    PackageConfig.npmrc(resource_path=resource_path, registry_url=global_config['verdaccio_url_local'], is_docker=False, write_fn=write_file, verdaccio_enabled=verdaccio_enabled)
    PackageConfig.bunfig(resource_path=resource_path, registry_url=global_config['verdaccio_url_local'], is_docker=False, write_fn=write_file, verdaccio_enabled=verdaccio_enabled)
    
    # ==========================================================================
    # 9. YAML MANIFEST (for verification)
    # ==========================================================================
    _generate_yaml_manifest(resource_path, manifest, write_file)

    # ==========================================================================
    # 10. AGENTS.MD (AI agent guard rail for .autogenerated/ folder)
    # ==========================================================================
    # Generates AGENTS.md in .autogenerated/ to warn AI agents not to modify
    # machine-generated files. Explains single source of truth principle.
    Generators.AgentsMd.generate(manifest, write_file)


def _generate_yaml_manifest(resource_path, manifest, write_file):
    """Generate YAML version of manifest for verification (idempotent)."""
    yaml_path = resource_path + "/" + MANIFEST_FILENAME_YAML
    
    # Check if YAML already exists and is up-to-date by comparing with JSON
    json_path = resource_path + "/" + MANIFEST_FILENAME
    json_mtime = local("stat -f %m " + json_path + " 2>/dev/null || stat -c %Y " + json_path + " 2>/dev/null || echo 0", quiet=True)
    yaml_mtime = local("stat -f %m " + yaml_path + " 2>/dev/null || stat -c %Y " + yaml_path + " 2>/dev/null || echo 0", quiet=True)
    
    if str(json_mtime).strip() <= str(yaml_mtime).strip() and yaml_mtime != "0":
        # YAML is up-to-date, skip generation
        return
    
    # Generate YAML using the json_to_yaml.py converter
    # NOTE: Path relative to TDK CLI installation root (where this file is located)
    # json_to_yaml.py is in engine/topologies/tilt/manifest/ relative to tdk-cli root
    converter_path = "engine/topologies/tilt/manifest/json_to_yaml.py"
    yaml_content = str(local("python3 " + converter_path + " " + json_path, quiet=True)).strip()
    write_file(yaml_path, yaml_content)


# =============================================================================
# 📦 EXPORTED STRUCT
# =============================================================================

def create_manifest_config_resource(
    resource_name,
    resource_config,
    resource_path,
    manifest,
    backend_manifest,
    ctx
):
    """
    Create a Tilt local_resource for manifest-driven config generation.
    
    This creates a visible Tilt resource (e.g., "my-service-config-gen")
    that watches the manifest and package.json, regenerating all configs
    when they change.
    
    Args:
        resource_name: Parent service name
        resource_config: Resource dict from registry
        resource_path: Base service path
        manifest: Loaded manifest
        backend_manifest: Backend manifest (for frontends)
        ctx: Tilt context
        
    Returns:
        Resource name (e.g., "my-service-config-gen")
    """
    resource_name = resource_config['name']
    # resource_path is now correctly passed from apply_manifest_orchestration.star
    # which uses resource.get('_resource_path', ...) to get the actual path
    resource_path = resource_path
    config_gen_resource_name = resource_name + '-config-gen'
    auto_init_config_gen = ctx.get('auto_init_config_gen', True)
    
    # Dependencies to watch
    manifest_path = resource_path + "/" + MANIFEST_FILENAME
    package_json_path = resource_path + "/package.json"
    
    # Generate configs immediately (synchronously)
    _generate_all_configs_for_resource(
        resource_name,
        resource_config,
        resource_path,
        manifest,
        backend_manifest,
        ctx
    )
    generated_files = _build_generated_file_list(resource_config, resource_path, manifest)
    log_cmd = _build_config_log_cmd(resource_name, generated_files, config_gen_resource_name)
    
    # Create a Tilt resource to watch for changes
    # Note: Generation happens in Starlark before this resource runs.
    # We log the expected generated file set for quick visibility in Tilt logs.
    # The real value is in the deps watching and labels.
    # The command auto-removes this resource after completion via tilt delete.
    local_resource(
        name=config_gen_resource_name,
        cmd=log_cmd,
        deps=[manifest_path, package_json_path],
        labels=['config-gen', resource_name],
        allow_parallel=True,
        auto_init=auto_init_config_gen
    )
    
    return config_gen_resource_name


ManifestResource = struct(
    generate_all_configs = _generate_all_configs_for_resource,
    create_config_resource = create_manifest_config_resource,
)

VALIDATION = {}
