# === INLINED CONSTANTS for pure extension loading ===
WEB_FRAMEWORK = "hono"
RUNTIME_CONFIG = {"bun": {"image_base": "oven/bun:latest", "package_manager": "bun", "lockfile": "bun.lock", "backend_start_command": "bun run start", "frontend_start_command": "bun run dev"}, "node": {"image_base": "node:20-alpine", "package_manager": "npm", "lockfile": "package-lock.json", "backend_start_command": "node dist/index.js"}}
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


"""
L3 Builder Layers - Compilation and Build Stages

Handles the build stages for different application types:
- l3_backend_compiler: TypeScript backend compilation
- l3_frontend_builder: Frontend application building
- l3_migration_engine: Prisma migration preparation
- l3_production_purger: Production dependency stripping
"""

load('./l1_base_layers.star', 'BUN_BASE')
load('./l2_dependency_layers.star', 'GOLDEN_L2_IMAGE', 'normalize_res_path')
load('../../../../../discovery/config.star', 'GLOBAL_CONFIG')
load('../../../tilt/manifest/constants.star', 'AUTOGENERATED_CONFIG_PATHS')



load('./prisma/prisma_build.star',
    'prisma_copy_instructions',
    'prisma_generate_instructions',
    'prisma_normalize_output',
    'L3_generate_migration_engine',
)
load('./infisical/infisical_docker.star', 'InfisicalDocker')

# Load project name for dynamic golden image naming
# Use TDK_PROJECT_ROOT env var set by Tilt, fallback to current directory
def _load_golden_prefix():
    project_root = os.environ.get('TDK_PROJECT_ROOT', '')
    project_json_path = '.tdk/project.json'
    if project_root:
        project_json_path = project_root + '/' + project_json_path
    
    if os.path.exists(project_json_path):
        _project_json = read_json(project_json_path)
        return _project_json.get('project', {}).get('name', 'tdk-project')
    return 'tdk-project'

_GOLDEN_PREFIX = _load_golden_prefix()

_docker_cfg = GLOBAL_CONFIG['docker']
GOLDEN_L3_BACKEND_IMAGE = _docker_cfg.get('golden_l3_backend_image', _GOLDEN_PREFIX + '-l3-backend:latest')
GOLDEN_L3_FRONTEND_IMAGE = _docker_cfg.get('golden_l3_frontend_image', _GOLDEN_PREFIX + '-l3-frontend:latest')


def L3_generate_backend_compiler(res_path, build_cmd = RUNTIME_CONFIG["bun"]["backend_start_command"], use_prisma = True, use_shared_libs = True, use_infisical = True, use_golden = True, has_prisma_config = False):
    """
    Generate the backend compiler layer for TypeScript services.

    Args:
        res_path: Resource path (service directory)
        build_cmd: Build command to run (default: from RUNTIME_CONFIG)
        use_prisma: Include Prisma setup (default: True)
        use_shared_libs: Include shared library copies (default: True)
        use_infisical: Include Infisical CLI installation (default: True)
        use_golden: Whether to use golden L3-backend image (default: True)
        has_prisma_config: Whether the service has Prisma config (default: False)

    Returns:
        Dockerfile content string for the l3_backend_build stage
    """
    # Normalize res_path for Docker COPY (must be relative to build context)
    res_path_rel = normalize_res_path(res_path)
    
    base_image = GOLDEN_L3_BACKEND_IMAGE if use_golden else BUN_BASE
    prisma_copy = prisma_copy_instructions(res_path) if use_prisma else ""
    prisma_generate = prisma_generate_instructions() if use_prisma else ""
    prisma_compat = prisma_normalize_output() if use_prisma else ""
    parts = [
        "# ---- L3: backend_compiler ----\n",
        "FROM " + base_image + " AS l3_backend_build\n",
        "WORKDIR /app/" + res_path + "\n",
        "# Build argument to skip Infisical setup (for local dev / fast builds)\n",
        "ARG SKIP_INFISICAL_SETUP=0\n",
        "# Reuse resolved dependencies from l2_deps_manifest to avoid reinstalling in L3\n",
        "COPY --link --from=l2_deps_manifest /app/" + res_path + "/node_modules ./node_modules\n",
        "# Bun isolated linker symlinks may resolve through /app/node_modules/.bun\n",
        "COPY --link --from=l2_deps_manifest /app/node_modules/.bun /app/node_modules/.bun\n",
        "# Copy manifest files for dependency installation (in case L2 is stale)\n",
        "COPY " + res_path_rel + "/package.json ./package.json\n",
        "COPY " + res_path_rel + "/" + AUTOGENERATED_CONFIG_PATHS['bunfig_docker'] + " ./bunfig.toml\n",
        "COPY " + res_path_rel + "/" + AUTOGENERATED_CONFIG_PATHS['npmrc_docker'] + " ./.npmrc\n",
        "COPY " + res_path_rel + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/tsconfig.docker.autogenerated.json ./tsconfig.json\n",
        "COPY " + res_path_rel + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/tsconfig.autogenerated.json ./" + OUTPUT.AUTOGENERATED_FOLDER + "/tsconfig.autogenerated.json\n",
        "COPY " + res_path_rel + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/*.ts ./" + OUTPUT.AUTOGENERATED_FOLDER + "/\n",
        "COPY " + res_path_rel + "/src ./src\n",
        prisma_copy,
        prisma_generate,
        prisma_compat,
    ]
    # shared libs (@{npm_scope}/*) are resolved from Verdaccio by l2_deps_manifest
    # and already present in node_modules — no COPY of shared-* source dirs needed.
    # Use InfisicalDocker generator for CLI setup (if not using golden image)
    if use_infisical and not use_golden:
        parts.append(InfisicalDocker.builder_setup(
            use_infisical=use_infisical,
            use_golden=use_golden,
        ))
    parts.append("ENV NODE_ENV=production\n")
    parts.append("RUN " + build_cmd + "\n")
    parts.append("# Fix " + WEB_FRAMEWORK + "/cors subpath import for Bun runtime compatibility\n")
    parts.append("RUN find ./dist -type f -name \"*.js\" -exec sed -i \"s|from '" + WEB_FRAMEWORK + "/cors'|from '../node_modules/" + WEB_FRAMEWORK + "/dist/middleware/cors/index.js'|g\" {} + || true\n")
    return "".join(parts)


def L3_generate_frontend_builder(res_path, build_cmd = RUNTIME_CONFIG["bun"]["backend_start_command"], use_infisical = False, use_shared_libs = True, use_golden = True):
    """
    Generate the frontend builder layer for Vue/React applications.

    Args:
        res_path: Resource path (service directory)
        build_cmd: Build command to run (default: from RUNTIME_CONFIG)
        use_infisical: Include Infisical CLI installation (default: False)
        use_shared_libs: Include shared library copies (default: True)
        use_golden: Whether to use golden L3-frontend image (default: True)

    Returns:
        Dockerfile content string for the l3_frontend_build stage
    """
    # Normalize res_path for Docker COPY (must be relative to build context)
    res_path_rel = normalize_res_path(res_path)
    
    # Use golden L3-frontend image if enabled (no Prisma)
    base_image = GOLDEN_L3_FRONTEND_IMAGE if use_golden else BUN_BASE

    parts = [
        "# ---- L3: frontend_builder ----\n",
        "FROM " + base_image + " AS l3_frontend_build\n",
        "WORKDIR /app/" + res_path + "\n",
        "# Build argument to skip Infisical setup (for local dev / fast builds)\n",
        "ARG SKIP_INFISICAL_SETUP=1\n",
        "# Reuse resolved dependencies from l2_deps_manifest to avoid reinstalling in L3\n",
        "COPY --link --from=l2_deps_manifest /app/" + res_path + "/node_modules ./node_modules\n",
        # Bun isolated linker symlinks may resolve through /app/node_modules/.bun.
        "COPY --link --from=l2_deps_manifest /app/node_modules/.bun /app/node_modules/.bun\n",
        "# Copy manifest files required by the build\n",
        "COPY " + res_path_rel + "/package.json ./package.json\n",
        "COPY " + res_path_rel + "/" + AUTOGENERATED_CONFIG_PATHS['bunfig_docker'] + " ./bunfig.toml\n",
        "COPY " + res_path_rel + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/tsconfig.docker.autogenerated.json ./tsconfig.json\n",
        "COPY " + res_path_rel + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/tsconfig.autogenerated.json ./" + OUTPUT.AUTOGENERATED_FOLDER + "/tsconfig.autogenerated.json\n",
        # Copy ALL TypeScript files from autogenerated directory (env.ts, api-client.ts, vite configs, etc.)
        "COPY " + res_path_rel + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/*.ts ./" + OUTPUT.AUTOGENERATED_FOLDER + "/\n",
        "COPY " + res_path_rel + "/src ./src\n",
        "COPY " + res_path_rel + "/public ./public\n",
        "COPY " + res_path_rel + "/index.html ./index.html\n",
    ]
    # shared libs (@{npm_scope}/*) are resolved from Verdaccio by l2_deps_manifest
    # and already present in node_modules — no COPY of shared-* source dirs needed.
    # Use InfisicalDocker generator for CLI setup (if not using golden image)
    if use_infisical and not use_golden:
        parts.append(InfisicalDocker.builder_setup(
            use_infisical=use_infisical,
            use_golden=use_golden,
        ))
    parts.append("ENV NODE_ENV=production\n")
    parts.append("RUN " + build_cmd + "\n")
    return "".join(parts)


# L3_generate_migration_engine is now loaded from prisma/prisma_build.star


def L3_generate_production_purger(res_path, use_golden = True):
    """
    Generate the production purger layer that removes development dependencies.

    Implements Option 2: Reduce node_modules size by:
    1. Installing only production dependencies (--production flag)
    2. Removing unnecessary files (.md, .ts, .map, test files, etc.)
    3. Pruning package.json files from node_modules
    4. Removing optional dependencies not needed at runtime

    Args:
        res_path: Resource path (service directory)
        use_golden: Whether to use golden L2 image (default: True)

    Returns:
        Dockerfile content string for the l3_production_purger stage
    """
    # Normalize res_path for Docker COPY (must be relative to build context)
    res_path_rel = normalize_res_path(res_path)
    
    # Use golden L2 image if enabled (Bun + system deps pre-installed)
    base_image = GOLDEN_L2_IMAGE if use_golden else BUN_BASE

    return (
        "# ---- L3: production_purger ----\n"
        + "FROM " + base_image + " AS l3_production_purger\n"
        + "WORKDIR /app/" + res_path + "\n"
        + "COPY " + res_path_rel + "/package.json ./package.json\n"
        + "COPY " + res_path_rel + "/" + AUTOGENERATED_CONFIG_PATHS['bunfig_docker'] + " ./bunfig.toml\n"
        + "COPY " + res_path_rel + "/" + AUTOGENERATED_CONFIG_PATHS['npmrc_docker'] + " ./.npmrc\n"
        + "COPY --link --from=l2_deps_manifest /cache/bun /cache/bun\n"
        # sharing=shared allows parallel builds without lock contention (Bun cache is atomic)
        + "RUN --mount=type=cache,target=/cache/bun,sharing=shared bun install --production --cache-dir=/cache/bun\n"
        + "# Option 2: Aggressive node_modules pruning to reduce size\n"
        + "# NOTE: Keep .d.ts files - they are needed for Bun module resolution with subpath exports\n"
        + "RUN find node_modules -type f \\( -name '*.md' -o -name '*.ts' ! -name '*.d.ts' -o -name '*.map' -o -name '*.test.js' -o -name '*.spec.js' -o -name 'README*' -o -name 'CHANGELOG*' -o -name 'LICENSE*' \\) -delete\n"
        + "RUN find node_modules -type d \\( -name '.bin' -o -name 'test' -o -name 'tests' -o -name '__tests__' -o -name 'spec' -o -name 'specs' -o -name '.github' -o -name 'docs' -o -name 'examples' \\) -exec rm -rf {} + 2>/dev/null || true\n"
    )

GLOBAL_CONFIG = {}
