# === INLINED CONSTANTS for pure extension loading ===
BASE_PORT_FRONTEND = 3000
BASE_PORT_BACKEND = 4000
OUTPUT = struct(AUTOGENERATED_FOLDER = ".autogenerated")
# === END INLINED CONSTANTS ===


"""
L4 Runtime Layers - Final Application Runtime Stages

Handles the final runtime stages for deployed applications:
- l4_backend_runtime: Backend service runtime with Bun
- l4_frontend_runtime: Frontend runtime with Nginx or Bun static
- l4_migrator_runtime: Database migration runner with Infisical integration
"""

load('./l1_base_layers.star', 'BUN_BASE')
load('./l2_dependency_layers.star', 'normalize_res_path')
load('../../../../../discovery/config.star', 'GLOBAL_CONFIG')
load('../../../tilt/common/utils_debug.star', 'DEBUG_MODE')
load('../../../tilt/manifest/constants.star', 'AUTOGENERATED_CONFIG_PATHS')
load('./prisma/prisma_runtime.star',
    'prisma_runtime_copy',
    'prisma_cli_runtime_copy',
    'prisma_bun_symlink_fix',
    'prisma_config_copy',
    'L4_generate_migrator_runtime',
)

load('./bun_helpers.star', 'bun_hoisted_packages_symlink_fix')
load('../config/healthcheck.star', 'DOCKER_HEALTHCHECK', 'dockerfile_healthcheck_flags')
load('./infisical/infisical_docker.star', 'InfisicalDocker')


# Load project name for dynamic golden image naming
# Use TDK_PROJECT_ROOT env var set by Tilt, fallback to current directory
def _load_golden_prefix():
    project_root = os.environ.get('TDK_PROJECT_ROOT', '')
    project_json_path = '.tdk/project.json'
    if project_root:
        project_json_path = project_root + '/' + project_json_path
    
    if os.path.exists(project_json_path):
        _project_json = read_json(project_json_path)
        return _project_json.get('project', {}).get('name', 'tdk-project')
    return 'tdk-project'

_GOLDEN_PREFIX = _load_golden_prefix()

_docker_cfg = GLOBAL_CONFIG['docker']
GOLDEN_L4_BACKEND_IMAGE = _docker_cfg.get('golden_l4_backend_image', _GOLDEN_PREFIX + '-l4-backend:latest')
GOLDEN_L4_FRONTEND_IMAGE = _docker_cfg.get('golden_l4_frontend_image', _GOLDEN_PREFIX + '-l4-frontend:latest')

DEFAULT_BUN_START_COMMAND = 'bun run start'

_ENTRY_FILE_EXTENSIONS = ['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsx', '.tsx']
_SHELL_CHARS = ['=', '&', '|', ';', '$', '`', '<', '>', '(', ')', '"', "'", '*', '\\']


def _is_entry_file(token):
    if token.startswith('-'):
        return False
    for ch in _SHELL_CHARS:
        if ch in token:
            return False
    for ext in _ENTRY_FILE_EXTENSIONS:
        if token.endswith(ext):
            return True
    return False


def start_command_from_script(start_script):
    """
    `bun run start` starts a Bun wrapper that spawns a second Bun runtime for the
    real server. When the start script only runs one entry file, run that file
    directly so each container holds a single Bun process. Anything else keeps
    `bun run start` so custom start scripts behave exactly as before.
    """
    tokens = (start_script or '').split()
    if len(tokens) == 3 and tokens[0] == 'bun' and tokens[1] == 'run' and _is_entry_file(tokens[2]):
        return 'bun ' + tokens[2]
    if len(tokens) == 2 and tokens[0] == 'bun' and _is_entry_file(tokens[1]):
        return 'bun ' + tokens[1]
    return DEFAULT_BUN_START_COMMAND


def resolve_bun_start_command(res_path, cmd = DEFAULT_BUN_START_COMMAND):
    """Resolve the runtime command from the service's package.json `start` script."""
    if cmd != DEFAULT_BUN_START_COMMAND:
        return cmd
    package_json_path = res_path + '/package.json'
    if not res_path.startswith('/'):
        package_json_path = os.environ.get('TDK_PROJECT_ROOT', '.') + '/' + package_json_path
    if not os.path.exists(package_json_path):
        return cmd
    package_json = read_json(package_json_path, default = {}) or {}
    scripts = package_json.get('scripts', {}) or {}
    return start_command_from_script(scripts.get('start', ''))


def _cmd_instruction(command):
    return "CMD [" + ", ".join(["\"" + part + "\"" for part in command.split()]) + "]\n"


def L4_generate_backend_runtime(res_path, port = BASE_PORT_BACKEND, cmd = 'bun run start', use_infisical = False, resource_name = 'service', use_golden = True, use_prisma = True, has_prisma_config = False, manifest = None):
    """
    Generate the backend runtime layer for deployed services.

    Args:
        res_path: Resource path (service directory)
        port: Port to expose (default: BASE_PORT_BACKEND from master config)
        cmd: Command to run (default: 'bun run start')
        use_infisical: Enable Infisical secret management (default: True)
        resource_name: Service name for logging and configuration (default: 'service')
        use_golden: Whether to use golden L4-backend image (default: True)
        use_prisma: Whether the service has the "prisma" feature enabled - gates copying
            the .prisma/prisma dirs from the L3 build stage, which only exist there when
            L3 itself ran prisma generate, plus the pinned Prisma CLI from the L3
            migration stage that the entrypoint needs to run migrations (default: True)
        has_prisma_config: Whether service has a generated prisma.config.ts to copy in
            (default: False)
        manifest: Service manifest dict for feature detection (default: None)
    
    Returns:
        Dockerfile content string for the l4_backend_runtime stage
    """
    # Normalize res_path for Docker COPY (must be relative to build context)
    res_path_rel = normalize_res_path(res_path)
    cmd = resolve_bun_start_command(res_path, cmd)
    
    # Use golden L4-backend image if enabled (production-optimized backend runtime)
    base_image = GOLDEN_L4_BACKEND_IMAGE if use_golden else BUN_BASE
    
    parts = [
        "# ---- L4: backend_runtime ----\n",
        "FROM " + base_image + " AS l4_backend_runtime\n",
        "WORKDIR /app/" + res_path + "\n",
        "# Build argument to skip Infisical setup (for local dev / fast builds)\n",
        "ARG SKIP_INFISICAL_SETUP=0\n",
        "ENV NODE_ENV=production\n",
        "COPY --from=l3_production_purger /app/" + res_path + "/node_modules ./node_modules\n",
        prisma_runtime_copy(res_path) if use_prisma else "",
        prisma_cli_runtime_copy(res_path) if use_prisma else "",
        "COPY --from=l3_backend_build /app/" + res_path + "/dist ./dist\n",
        "COPY " + res_path_rel + "/package.json ./package.json\n",
        prisma_bun_symlink_fix() if use_prisma else "",
        bun_hoisted_packages_symlink_fix(),
    ]
    
    # Check for special tooling requirements from manifest features
    # Services requiring Hugo (or other tools) should specify in manifest features array
    manifest_features = manifest.get('featuresEnabled', []) if manifest else []
    if "hugo" in manifest_features:
        parts.append("USER root\n")
        parts.append("RUN apk add --no-cache hugo\n")
        parts.append("USER bun\n")

    if has_prisma_config:
        # Prisma v7 migrate deploy reads datasource.url from prisma.config.ts in CWD
        parts.append(prisma_config_copy(res_path))
    
    # Only set USER if not using golden image (already set in golden L4)
    if not use_golden:
        parts.append("USER bun\n")
    
    parts.extend([
        "EXPOSE " + str(port) + "\n",
    ])
    
    # Only add healthcheck if not using golden image (already in golden L4)
    if not use_golden:
        parts.append("HEALTHCHECK " + dockerfile_healthcheck_flags() + " CMD bun --version || exit 1\n")
    
    if use_infisical:
        # Use InfisicalDocker generator for proper secret injection setup
        # This uses Starlark generators instead of hardcoded values
        infisical_setup = InfisicalDocker.runtime_setup(
            resource_name=resource_name,
            secret_path=None,  # Auto-generate from resource_name
            resource_type="backend",
            command=cmd,
            use_entrypoint=True,
        )
        parts.append(infisical_setup)
    else:
        parts.append(_cmd_instruction(cmd))

    # Provide build targets that match external tooling (e.g. --target production/ development)
    parts.append("\nFROM l4_backend_runtime AS production\nFROM l4_backend_runtime AS development\n")

    return "".join(parts)


def L4_generate_frontend_runtime(res_path, target_path = '/usr/share/nginx/html', use_nginx = True, use_golden = True, port = None):
    """
    Generate the frontend runtime layer for static site serving.
    
    Args:
        res_path: Resource path (service directory)
        target_path: Target path for static files (default: Nginx html directory)
        use_nginx: Use Nginx for serving (default: True, uses Bun static if False)
        use_golden: Whether to use golden L4-frontend image (default: True)
        port: Port to expose (default: None, uses BASE_PORT_FRONTEND or 80 for nginx)
    
    Returns:
        Dockerfile content string for the l4_frontend_runtime stage
    """
    # Use provided port or fall back to base port constant
    expose_port = port if port else BASE_PORT_FRONTEND
    # Normalize res_path for Docker COPY (must be relative to build context)
    res_path_rel = normalize_res_path(res_path)
    
    if use_nginx:
        # Use golden L4-frontend image if enabled (Nginx pre-configured)
        base_image = GOLDEN_L4_FRONTEND_IMAGE if use_golden else "nginx:alpine"
        
        # If using golden image, skip curl installation (already there)
        healthcheck_setup = "" if use_golden else "RUN apk add --no-cache curl\n"
        
        return (
            "# ---- L4: frontend_runtime (nginx) ----\n"
            + "FROM " + base_image + " AS l4_frontend_runtime\n"
            + healthcheck_setup
            + "COPY --from=l3_frontend_build /app/" + res_path + "/dist " + target_path + "\n"
            + "COPY " + res_path_rel + "/" + OUTPUT.AUTOGENERATED_FOLDER + "/nginx.autogenerated.conf /etc/nginx/conf.d/default.conf\n"
            + "EXPOSE 80\n"
            + ("" if use_golden else "HEALTHCHECK " + dockerfile_healthcheck_flags(DOCKER_HEALTHCHECK["frontend_start_period_seconds"]) + " CMD curl -f http://localhost/ || exit 1\n")
            + "CMD [\"nginx\", \"-g\", \"daemon off;\"]\n"
            + "FROM l4_frontend_runtime AS production\n"
            + "FROM l4_frontend_runtime AS development\n"
        )
    # Use golden L4-frontend image even for Bun static serving (or BUN_BASE as fallback)
    # NOTE: When use_nginx=False, we MUST use BUN_BASE because the golden L4 frontend
    # image is nginx-based and doesn't have Bun installed
    base_image = GOLDEN_L4_FRONTEND_IMAGE if (use_golden and use_nginx) else BUN_BASE
    
    return (
        "# ---- L4: frontend_runtime (bun static) ----\n"
        + "FROM " + base_image + " AS l4_frontend_runtime\n"
        + "WORKDIR /app/" + res_path + "\n"
        + "COPY --from=l3_frontend_build /app/" + res_path + "/dist ./dist\n"
        + "COPY --from=l3_frontend_build /app/" + res_path + "/node_modules ./node_modules\n"
        + "COPY --from=l3_frontend_build /app/" + res_path + "/" + OUTPUT.AUTOGENERATED_FOLDER + " ./" + OUTPUT.AUTOGENERATED_FOLDER + "\n"
        + "COPY " + res_path_rel + "/package.json ./package.json\n"
        + "EXPOSE " + str(expose_port) + "\n"
        + _cmd_instruction(resolve_bun_start_command(res_path))
        + "FROM l4_frontend_runtime AS production\n"
        + "FROM l4_frontend_runtime AS development\n"
    )


# L4_generate_migrator_runtime is now loaded from prisma/prisma_runtime.star

DEBUG = {}

GLOBAL_CONFIG = {}
